# yaml-language-server: $schema=../../json_schema/terraformer_validate.json
provider_name: "Aci"
name: "Tenant"
imports:
  - "fmt"
  - "strconv"
  - "github.com/GoogleCloudPlatform/terraformer/terraformutils"
getURL: "/api/node/class/fvTenant.json"
resource_allowed_empty_attributes: 
  - name_alias
  - relation_fv_rs_tn_deny_rule
  - relation_fv_rs_tenant_mon_pol
  - annotation
  - description
