imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: application_profile
provider_name: Aci
schemas:
- attribute: tenant_dn
  depends_on:
    attribute_name:
    - id
    resource_name: tenant
  description: Dn of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - yugu7l3jfu
    - zowgyheoy6
    - 36vkxeewby
    - 3nf74l795b
    - qsp62g45fk
    - wi9xve4iza
    - tg51jfy6xd
    - k7joyf4oha
    - x04ysxuvp7
    - maycjscksu
    - m37pmsccfs
    - 9v9en784hv
    - hv2apoj8c7
    - c0duw93q5o
    - wz6vjto5j7
    valid:
    - 2mb25goyec
    - nqdiqfp4uh
    - 2608jc304f
    - veivfdbgu7
  type: string
- attribute: name
  computed: true
  description: Name of Application Profile
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 60pu2o0wg4
    - vp8jutz8my
    - mu4ezwqpzw
    - utrjs5e07z
    - ygvhpr8vzg
    - 352vp3n61l
    - 7klisnrimw
    - 6xzbf57mpo
    - 9pwfwt3nrf
    - fd26v5gzr9
    - 6fqov3c0q0
    - 5o4rz9ln66
    - r7y3p19qdy
    - xkboq5omzd
    - beoacoa1i7
    valid:
    - 57i2vt4wio
    - hpdbwf0hly
    - bip0mz06sa
    - mxm9rir89j
  type: string
- attribute: name_alias
  computed: true
  description: Name Alias for Application Profile
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - io10asopr3
    - w35zd2tk1l
    - rqfsm3yfb4
    - a96r0q06mq
    - 4gqs1rxyvv
    - fouav2ess4
    - dlqqic3k66
    - agrv7p8719
    - xz129ncnln
    - inxm9la635
    - m2j52seq45
    - vpk2vaufug
    - 85uikv1haw
    - ihv8hfwnwp
    - klmfbr5mq9
    valid:
    - w3sk931mmo
    - mnncemgmr7
    - jcr5g4s6hg
    - xs91d7hheu
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 2vsr0azk77
    - 8gcsm4i786
    - cznoeed6qe
    - l3fk8eczjv
    - bql1qphxus
    - axtinrc5io
    - 13c3xubtxj
    - 09c5esqdcx
    - co82r3xt6o
    - ky58zi032u
    - ck7ujmad2p
    - 97x4vqszf7
    - 2mch4x3ciu
    - 6bjqechssp
    - ecxhwvxr97
    valid:
    - jgfgtfaj5j
    - d0tcx3lfz7
    - rkdbh05umk
    - cto0xni4j3
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 0nd20zwc9m
    - 4wjt57xmzq
    - x05npwzgzu
    - i6b40yqe6a
    - a6hscukh7c
    - 7qy5sc1md9
    - ya1nm9b5xk
    - umuayiec5i
    - w9kxsjluye
    - lnbxfpg4bv
    - icpq3x1ol9
    - h6e8a1mu1j
    - fttz045bsy
    - 7lew26oeq0
    - t8j85dsqie
    valid:
    - 2ce46uj976
    - g0evz5rojr
    - c25pbyw5hw
    - 03hzjy6909
  type: string
- attribute: prio
  computed: true
  default: unspecified
  optional: true
  subtype: string
  test_params:
    invalid:
    - 6bkb76p2dy
    multiple_valids:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
    valid:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: 'false'
    params:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - bXRiZXNvZnJzcw==
    - N3JldXFzbGkxYw==
    - cXp5Z2N6Znd4eA==
    - NWJsc3FkODFkcg==
    - ODB5YWxobm81ZQ==
    - NXA2cWtsbHA3OA==
    - b3FqbWsyeXpuYw==
    - OXQwc3BwbXhucQ==
    - a2kzdmFtMHZzOA==
    - dzMwZG5memJieQ==
    - bnByMWFtNm80ZQ==
    - anU0djVic3h5Mg==
    - ajJ2OW40c2w5ZA==
    - NDk0Y3VqZ2QzcA==
    - NGtjanljdGZjcw==
    valid:
    - MHZzZHhueHJyZw==
    - dTAxNjliOXo4aw==
    - M3lhN3lnbm5jbQ==
    - cWRhbWo3bGFzbw==
  cidr:
    invalid:
    - 298.299.283.283/12
    multiple_valids:
    - 217.56.224.0/20
    - 217.56.112.0/20
    - 217.56.48.0/20
    - 217.56.64.0/20
    - 217.56.192.0/20
    - 217.56.16.0/20
    - 217.56.128.0/20
    - 217.56.240.0/20
    - 217.56.176.0/20
    - 217.56.32.0/20
    - 217.56.96.0/20
    - 217.56.80.0/20
    - 217.56.160.0/20
    - 217.56.208.0/20
    - 217.56.0.0/20
    valid:
    - 217.56.224.0/20
    - 217.56.112.0/20
    - 217.56.48.0/20
    - 217.56.64.0/20
  ipv4:
    invalid:
    - 270.265.264.285
    multiple_valids:
    - 217.56.224.44
    - 217.56.68.4
    - 217.56.115.179
    - 217.56.193.163
    - 217.56.217.189
    - 217.56.96.229
    - 217.56.42.244
    - 217.56.240.250
    - 217.56.30.221
    - 217.56.152.12
    - 217.56.54.20
    - 217.56.242.237
    - 217.56.157.242
    - 217.56.8.235
    - 217.56.108.155
    valid:
    - 217.56.224.44
    - 217.56.68.4
    - 217.56.115.179
    - 217.56.193.163
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f303
    - 2001:db8::34f4:0:0:f3e2
    - 2001:db8::34f4:0:0:f330
    - 2001:db8::34f4:0:0:f383
    - 2001:db8::34f4:0:0:f32c
    - 2001:db8::34f4:0:0:f3b3
    - 2001:db8::34f4:0:0:f3b1
    - 2001:db8::34f4:0:0:f3d4
    - 2001:db8::34f4:0:0:f317
    - 2001:db8::34f4:0:0:f323
    - 2001:db8::34f4:0:0:f3e4
    - 2001:db8::34f4:0:0:f395
    - 2001:db8::34f4:0:0:f3d9
    - 2001:db8::34f4:0:0:f3db
    - 2001:db8::34f4:0:0:f37e
    valid:
    - 2001:db8::34f4:0:0:f303
    - 2001:db8::34f4:0:0:f3e2
    - 2001:db8::34f4:0:0:f330
    - 2001:db8::34f4:0:0:f383
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 05:d5:fa:da:2b:02
    - 97:94:f8:c2:5d:ac
    - a8:bb:eb:2f:37:25
    - b1:da:7d:00:ce:e8
    - 95:a8:29:a7:a5:bb
    - 37:1f:ea:9d:4b:aa
    - 4f:cd:6b:37:bb:fe
    - 1f:9e:75:48:7e:b9
    - d2:00:c5:b1:a9:ef
    - f6:e1:33:c9:94:76
    - 0d:14:53:a3:e5:e6
    - 75:75:9a:68:c3:81
    - 1d:7a:84:f8:5b:67
    - 0d:30:0c:a7:32:fb
    - cb:86:f4:d0:98:1a
    valid:
    - 5c:2d:95:2e:6b:99
    - 34:b1:e0:52:97:c3
    - 9f:9c:96:93:5e:a8
    - dd:2d:dc:9b:7c:b6
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - pv04whh97n
    - 4wawiuxrie
    - w9vvox32s3
    - b0a2o7z4ml
    - t8351n0nhx
    - c3ynzs1pnv
    - abtoj0haoj
    - ngruiy1bv3
    - mn2sjc8i4x
    - cfm5gfxsjk
    - 2baf9uhulk
    - rjrvruzz3y
    - qcu046l2wn
    - trktqb7hqh
    - af1i8tykuk
    valid:
    - b0rx9vps5o
    - ngjddxo75v
    - pulggmmh4k
    - div613n1yx
  time:
    invalid:
    - '2022-08-01 17:50:38.956022'
    multiple_valids:
    - '2022-08-01T12:20:38.971663+00:00'
    - '2022-08-24T12:20:38.972252+00:00'
    - '2022-09-16T12:20:38.972252+00:00'
    - '2022-10-09T12:20:38.972252+00:00'
    - '2022-11-01T12:20:38.972252+00:00'
    - '2022-11-24T12:20:38.972252+00:00'
    - '2022-12-17T12:20:38.972252+00:00'
    - '2023-01-09T12:20:38.972252+00:00'
    - '2023-02-01T12:20:38.972252+00:00'
    - '2023-02-24T12:20:38.972252+00:00'
    - '2023-03-19T12:20:38.972252+00:00'
    - '2023-04-11T12:20:38.972252+00:00'
    - '2023-05-04T12:20:38.972252+00:00'
    - '2023-05-27T12:20:38.972252+00:00'
    - '2023-06-19T12:20:38.972252+00:00'
    valid:
    - '2022-08-01T12:20:38.956022+00:00'
    - '2022-08-24T12:20:38.956022+00:00'
    - '2022-09-16T12:20:38.956022+00:00'
    - '2022-10-09T12:20:38.956022+00:00'
  url-http:
    invalid:
    - ht:/5ocp5txj2w6tu0k.com
    multiple_valids:
    - http://gfaithkmrh7ynmb.com
    - http://eqchxs1u3mqekmf.com
    - http://0a2zg73d3i2d4zd.com
    - http://r7unymqv7rsgz35.com
    - http://t8q7t12cjd39jhn.com
    - http://zpgjqovbr24s1ut.com
    - http://7dhn7rv1as0uuqn.com
    - http://i3k3dukq8zqc4zk.com
    - http://silliiiwnhn2d0a.com
    - http://91zreq7akfk00z6.com
    - http://3nysoj80ammagrh.com
    - http://ymd9lw1tx4pgbbm.com
    - http://z2g7tpfk1awhbql.com
    - http://axtnl7ngxfvnauh.com
    - http://20aljobqyg2kqez.com
    valid:
    - http://d3k7jg4orpp49np.com
    - http://4kafw6jkb4yel4l.com
    - http://l8zcleebutylkxm.com
    - http://1xlqved618jvrsi.com
  url-https:
    invalid:
    - hts:/i3vi1kazk25bw07.com
    multiple_valids:
    - https://o5ilg9ik6ld3gsn.com
    - https://71x5d874kz5kl5l.com
    - https://4odu772ovpvje7n.com
    - https://xtzb9adt6akufn1.com
    - https://xl9mvqsxlt0w0t2.com
    - https://11ayckvvjqqt6s5.com
    - https://qf18mfbjt0ejr8h.com
    - https://lbojgvo03dvmxm3.com
    - https://whdzaicyotobgm4.com
    - https://u1jj4ifdffhzxa4.com
    - https://wo7f9xpnhe1xikz.com
    - https://j2sr7oxcnplb59h.com
    - https://yny9wtctejbvt19.com
    - https://ydllelcpnrund14.com
    - https://d4s3imx3treev4b.com
    valid:
    - https://gxai13tpnidk5bf.com
    - https://85ydtsjk9pl0y99.com
    - https://2dk0kxs40y3fem1.com
    - https://c68mw08pslozxmk.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 5a8309a0-1194-11ed-8b21-dc214861057a
    - 5a8309a1-1194-11ed-b312-dc214861057a
    - 5a8309a2-1194-11ed-ad51-dc214861057a
    - 5a8309a3-1194-11ed-80a3-dc214861057a
    - 5a8309a4-1194-11ed-9a5a-dc214861057a
    - 5a8309a5-1194-11ed-ba83-dc214861057a
    - 5a8309a6-1194-11ed-8e9b-dc214861057a
    - 5a8309a7-1194-11ed-8fc7-dc214861057a
    - 5a8309a8-1194-11ed-8b52-dc214861057a
    - 5a8309a9-1194-11ed-ada0-dc214861057a
    - 5a8309aa-1194-11ed-a6e4-dc214861057a
    - 5a8309ab-1194-11ed-8a10-dc214861057a
    - 5a8309ac-1194-11ed-98b2-dc214861057a
    - 5a8309ad-1194-11ed-b4a6-dc214861057a
    - 5a8309ae-1194-11ed-a27e-dc214861057a
    valid:
    - 5a83099c-1194-11ed-8db2-dc214861057a
    - 5a83099d-1194-11ed-a687-dc214861057a
    - 5a83099e-1194-11ed-a025-dc214861057a
    - 5a83099f-1194-11ed-856a-dc214861057a
unique_attribute:
- name
