imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: application_profile
provider_name: Aci
schemas:
- attribute: tenant_dn
  depends_on:
    attribute_name:
    - id
    resource_name: tenant
  description: Dn of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - pyfqq2v07r
    - 9n7l3vjmec
    - x6sg2gckc7
    - ave18t9cmq
    - qi0gvm26oq
    - ywasq0v90l
    - u2a6c6tdr4
    - r5pthnrq9v
    - 0v02yktq50
    - 2jwwjht5ki
    - t8j0152abw
    - xi16a8eal6
    - zb4pblj543
    - movjlk7ocy
    - pmkigysagu
    valid:
    - h041mclis8
    - xejjs922qd
    - hptqxirp63
    - 5ncxl5z329
  type: string
- attribute: name
  computed: true
  description: Name of Application Profile
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ohya7g3fuc
    - hvhov79w2w
    - 2yci0o8yc4
    - 9xwtrrulxn
    - qjp3qeb16c
    - wc6td99apf
    - 5dsjc8twdr
    - m4n6ncpb9z
    - pvuzuabftk
    - zdwg0hemhd
    - uolr2eyrwl
    - 1god820ncy
    - s2ojac7w7e
    - s59vqdcrwp
    - h8ab7k9l56
    valid:
    - kgt5zu0ce2
    - r13jlxpwgm
    - vbfqi08vuc
    - t1tm2ohmi0
  type: string
- attribute: name_alias
  computed: true
  description: Name Alias for Application Profile
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - kpsx0a6sy9
    - ztje351a1a
    - 5r0q9chlno
    - fwjbbypvbh
    - olcvcttr3y
    - eiqz849tmh
    - rce266275c
    - 9lta8sr3mh
    - sth0vu0why
    - wb0tpqjzke
    - hfcy55c1iz
    - f6gllx3zwc
    - tzzzrsacjx
    - c8q7i7zw9o
    - wgojtybwyq
    valid:
    - h22p7ycmpj
    - 4dzy2c2tao
    - c609oncjc4
    - doexon7j46
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - p4ezwpj34e
    - vqirtqmi2t
    - 7gt2dtc73h
    - g3zwpe1elz
    - xgzifgtxcf
    - 2fc9sdvnzn
    - f2ghtqidsi
    - 1hsu9088bj
    - o8xvchf0po
    - 75pulfb7hz
    - d2e0d90udu
    - war0tk73mn
    - p405ko6qjn
    - 9z8u1y3lgd
    - 8xindoxx4h
    valid:
    - m66gey0wn5
    - qg10oe0an8
    - mt8g9bfsk2
    - 52lcla15fc
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - vy71sto2g1
    - 5ay4j3c26q
    - wk7reh9lpt
    - ehnky39o3m
    - q7a1x1vfc0
    - 6k82n5nf7v
    - 9b5y44nhnl
    - camhrgb51f
    - yaparu64li
    - 2e7rh17w9f
    - z2t3te4veq
    - 3a1vlmhci0
    - pepbnmuz4b
    - bvmb83x7l5
    - cjgnku54qc
    valid:
    - kbm2a7n2m1
    - vdkffohqzg
    - 50he4a6fgn
    - x90pbgo6im
  type: string
- attribute: prio
  computed: true
  default: unspecified
  optional: true
  subtype: string
  test_params:
    invalid:
    - t6ywle047f
    multiple_valids:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
    valid:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: 'false'
    params:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - aWswcG83dXgzaA==
    - OWtka3ZodjN4dA==
    - M3I3dXZtZjFzdQ==
    - MjBxaTB1bjNueg==
    - cjJ0M3czeDZ0MQ==
    - ZjZxMjM5OXR6ag==
    - ZzZweWh3YzBiZA==
    - NmwwdGNmcnIxbg==
    - N3M3czZiMXlmMw==
    - bzY2djY3d255bg==
    - a2doNm9lMm5uYw==
    - ZGw1dGVuYmM5Zw==
    - M2gwNmxzY3Rwcg==
    - cW01cXAxb3Fsaw==
    - azZ5NXFicWYwdA==
    valid:
    - enpudnlhcnU3Zw==
    - dWJ4ZXJ3OHdkeA==
    - cmYxZWVkbHNrNA==
    - dzAwcXNwdzl3Yg==
  cidr:
    invalid:
    - 300.289.281.287/25
    multiple_valids:
    - 11.72.176.0/20
    - 11.72.32.0/20
    - 11.72.64.0/20
    - 11.72.160.0/20
    - 11.72.240.0/20
    - 11.72.144.0/20
    - 11.72.80.0/20
    - 11.72.0.0/20
    - 11.72.208.0/20
    - 11.72.128.0/20
    - 11.72.112.0/20
    - 11.72.96.0/20
    - 11.72.48.0/20
    - 11.72.16.0/20
    - 11.72.192.0/20
    valid:
    - 11.72.176.0/20
    - 11.72.32.0/20
    - 11.72.64.0/20
    - 11.72.160.0/20
  ipv4:
    invalid:
    - 277.278.281.284
    multiple_valids:
    - 11.72.219.170
    - 11.72.126.70
    - 11.72.162.207
    - 11.72.204.124
    - 11.72.250.180
    - 11.72.93.131
    - 11.72.205.148
    - 11.72.0.144
    - 11.72.69.134
    - 11.72.180.166
    - 11.72.166.197
    - 11.72.193.11
    - 11.72.25.35
    - 11.72.132.153
    - 11.72.102.108
    valid:
    - 11.72.219.170
    - 11.72.126.70
    - 11.72.162.207
    - 11.72.204.124
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f35e
    - 2001:db8::34f4:0:0:f3de
    - 2001:db8::34f4:0:0:f359
    - 2001:db8::34f4:0:0:f3da
    - 2001:db8::34f4:0:0:f31d
    - 2001:db8::34f4:0:0:f3c3
    - 2001:db8::34f4:0:0:f328
    - 2001:db8::34f4:0:0:f301
    - 2001:db8::34f4:0:0:f377
    - 2001:db8::34f4:0:0:f35f
    - 2001:db8::34f4:0:0:f3fb
    - 2001:db8::34f4:0:0:f3be
    - 2001:db8::34f4:0:0:f3a1
    - 2001:db8::34f4:0:0:f3f6
    - 2001:db8::34f4:0:0:f3a9
    valid:
    - 2001:db8::34f4:0:0:f35e
    - 2001:db8::34f4:0:0:f3de
    - 2001:db8::34f4:0:0:f359
    - 2001:db8::34f4:0:0:f3da
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 12:dc:f6:76:af:56
    - 36:58:27:24:3c:02
    - d5:8a:26:4e:aa:65
    - 39:ec:98:7f:74:79
    - b1:21:48:df:e8:e8
    - 75:0c:8e:42:45:49
    - 69:3f:59:e4:7c:0f
    - c2:36:fa:ca:ba:3e
    - 90:55:86:c9:24:f8
    - c9:c0:70:d7:5c:a3
    - 1c:d4:60:94:38:3f
    - 25:1b:2a:bd:f7:f8
    - d8:de:e9:2d:ff:ca
    - 92:e5:48:da:a9:a3
    - c5:a7:9a:85:ba:a5
    valid:
    - 49:05:c3:d9:5f:48
    - af:1d:2b:1b:9e:b5
    - 02:ca:ab:4a:ff:06
    - 0d:de:30:79:52:10
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - gbriynh4rf
    - 3a3shgdfmj
    - irhruayrgk
    - e6eoe0c6pk
    - n4n8b77vfx
    - ve35x2dcw5
    - vrozefbitj
    - plt7ad3g2t
    - qzf4b1jjw9
    - oy1zyazq5b
    - r8oyzfhrk1
    - c4tkammcy9
    - zueke2oakq
    - tltrrxn228
    - 562qr5ylej
    valid:
    - akfywbgcv5
    - 1q6ybsmwpp
    - dytmxdpfcr
    - m8kwbb3ou4
  time:
    invalid:
    - '2022-08-02 10:47:49.148686'
    multiple_valids:
    - '2022-08-02T05:17:49.148686+00:00'
    - '2022-08-25T05:17:49.148686+00:00'
    - '2022-09-17T05:17:49.148686+00:00'
    - '2022-10-10T05:17:49.148686+00:00'
    - '2022-11-02T05:17:49.148686+00:00'
    - '2022-11-25T05:17:49.148686+00:00'
    - '2022-12-18T05:17:49.148686+00:00'
    - '2023-01-10T05:17:49.148686+00:00'
    - '2023-02-02T05:17:49.148686+00:00'
    - '2023-02-25T05:17:49.148686+00:00'
    - '2023-03-20T05:17:49.148686+00:00'
    - '2023-04-12T05:17:49.148686+00:00'
    - '2023-05-05T05:17:49.148686+00:00'
    - '2023-05-28T05:17:49.148686+00:00'
    - '2023-06-20T05:17:49.148686+00:00'
    valid:
    - '2022-08-02T05:17:49.148686+00:00'
    - '2022-08-25T05:17:49.148686+00:00'
    - '2022-09-17T05:17:49.148686+00:00'
    - '2022-10-10T05:17:49.148686+00:00'
  url-http:
    invalid:
    - ht:/k9v47p92550okrp.com
    multiple_valids:
    - http://4pgiv9ioslxt85l.com
    - http://b27ndc3tra7uyrg.com
    - http://tc3eqbc23v6spjf.com
    - http://qe6ed6y5nj8x9gj.com
    - http://ycw4zr6mhordgld.com
    - http://6bw9tp7nhid4wn5.com
    - http://t2xw75hrdfn74r8.com
    - http://1tot9s35xjwwgks.com
    - http://0l8f89jfd1l4ut8.com
    - http://k4lq16hhxnl03ru.com
    - http://f9aw65svju4nb3s.com
    - http://mlv3hwca9jh7jb9.com
    - http://y7vwopv0062pfgp.com
    - http://buibtryyb8x3nko.com
    - http://ysfi05r1gfwq1ei.com
    valid:
    - http://8r7cc4o50ewyorz.com
    - http://e59vulmp7w6802l.com
    - http://hpy49vs2supo15z.com
    - http://zcknyg71isrskph.com
  url-https:
    invalid:
    - hts:/2dqqsbcgp7astbo.com
    multiple_valids:
    - https://347s52qkvbw5nfn.com
    - https://z3s7zvqxu4t0qwn.com
    - https://giu0drwa2ovy9tw.com
    - https://o73eipubhvubtrv.com
    - https://hggy5b9h94taerd.com
    - https://0pa0nd7hjvsxktb.com
    - https://gvy8jrbqyr3iuub.com
    - https://1zx0d2jcdfieme0.com
    - https://rp3vmmxyt0gvewr.com
    - https://ojt0omkrlq2kzk7.com
    - https://14uphz2biu44jcv.com
    - https://uo8swnok2zoyyt0.com
    - https://tih3mmm7tecu1pe.com
    - https://yk679tfgooovhvz.com
    - https://7dmzj7xwuxd0xyl.com
    valid:
    - https://pfef1u09pqom4xc.com
    - https://g5cvattkw8y0lj0.com
    - https://j91apqvrny7t4u8.com
    - https://7rftr86wbn7goj9.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 7354ec92-1222-11ed-9782-dc214861057a
    - 7354ec93-1222-11ed-b4fd-dc214861057a
    - 7354ec94-1222-11ed-b1ab-dc214861057a
    - 7354ec95-1222-11ed-920f-dc214861057a
    - 7354ec96-1222-11ed-afdc-dc214861057a
    - 7354ec97-1222-11ed-9820-dc214861057a
    - 7354ec98-1222-11ed-8946-dc214861057a
    - 7354ec99-1222-11ed-847e-dc214861057a
    - 7354ec9a-1222-11ed-b57f-dc214861057a
    - 7354ec9b-1222-11ed-9544-dc214861057a
    - 7354ec9c-1222-11ed-92cd-dc214861057a
    - 7354ec9d-1222-11ed-8959-dc214861057a
    - 7354ec9e-1222-11ed-b051-dc214861057a
    - 7354ec9f-1222-11ed-a6b8-dc214861057a
    - 7354eca0-1222-11ed-aff5-dc214861057a
    valid:
    - 7354ec8e-1222-11ed-90c8-dc214861057a
    - 7354ec8f-1222-11ed-9572-dc214861057a
    - 7354ec90-1222-11ed-8bf9-dc214861057a
    - 7354ec91-1222-11ed-9ca2-dc214861057a
unique_attribute:
- name
