imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: application_profile
provider_name: Aci
schemas:
- attribute: tenant_dn
  depends_on:
    attribute_name:
    - id
    resource_name: tenant
  description: Dn of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - o0r8m1hy6c
    - a2so1kguug
    - jjgirx82ee
    - 4raxywu6o9
    - a1l55yh4i5
    - 3wdfgeji51
    - 83ncgsz9bp
    - ofb1i0m15j
    - h3sj1wf5ry
    - kql369azhr
    - iealu51k3h
    - 9gro7iyfgg
    - 1agqy5xf1q
    - jqw5m283e1
    - 9po5qd3u0m
    valid:
    - qvoo7jp7zg
    - p3jgqxuqv4
    - vw9x5g0iau
    - pe7g5fd9rz
  type: string
- attribute: name
  description: Name of Application Profile
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - i4atrf6wbr
    - vbu704nfjq
    - 0r6ng7dm0p
    - qgzbrjggb4
    - 2klfx2b55a
    - 9djndt52m4
    - 4lohhdo5zt
    - ds93bz61eu
    - 5qvng5iqbv
    - 6rjzcm2j4e
    - v4xnpvyg1h
    - nafkic8ftg
    - ja8yzvbo99
    - 41pucov8mi
    - 0r2vjrc6jj
    valid:
    - enw5p4v9he
    - fu3fwtsc17
    - p70sdyyqe3
    - ayaacutj9p
  type: string
- attribute: name_alias
  computed: true
  description: Name Alias for Application Profile
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - wb8xst3gm3
    - 95ociyp30h
    - udr63juxmw
    - 06mezjjpbq
    - wnuflhf57k
    - v4io6a4dho
    - yerzo8f3l0
    - xa04igzkt2
    - ls3957eztz
    - dz61lw4jwd
    - sdkqqgtyb1
    - wjpqt1zrzc
    - 8j4tqcqv6l
    - u0v8bn5rgs
    - cf45h3syer
    valid:
    - ael8v75q43
    - bvlypkls2x
    - egmrh8gok2
    - fqoj7gcxu9
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - mtji48wu2v
    - ez57n8lqkm
    - j84lmu9oh7
    - rl4nllxs7u
    - mgnqlmd53t
    - 0ph2p113sf
    - 7wouga5k5k
    - eadyrut1wb
    - ptcbjl1q5l
    - qq59ko8w75
    - 3cyaqdcctr
    - w1a2zvjlxf
    - cw0rrxho1s
    - kobb5za9fi
    - 8rxar50agi
    valid:
    - 4irnr5dyn3
    - 764my4pu0p
    - 1ukf765g9s
    - elq7w22ejx
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 81htddy0x0
    - cd8quswgqp
    - hie0b7hgqp
    - f28whsjul0
    - ijvvvppszy
    - t9th4awmh4
    - r0bc1h6ptr
    - 88agzco225
    - j8p83lkd4t
    - hol8c09n7w
    - ap8d9itbf4
    - 9dpmkkhzni
    - zwoloe6v1z
    - d12sg5rxvj
    - rlgozd5v2m
    valid:
    - 6fw9n6ltkf
    - nkuyv309of
    - uzz146mxtn
    - x9r7cfe8ty
  type: string
- attribute: prio
  computed: true
  default: unspecified
  optional: true
  subtype: string
  test_params:
    invalid:
    - s2e0n74vv9
    multiple_valids:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
    valid:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: 'false'
    params:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - dXhmZjV6b2RudA==
    - M2wwNnJsdWw5cw==
    - cnoweTNvem93Mg==
    - NHU5Y2NvdDAzdw==
    - azRsMGt1a3djZQ==
    - ZTF0Nzh1OXAzMA==
    - YmJycWt0NnF3YQ==
    - aTN4anZqdG4wZw==
    - OGpta2FpYmY0Yg==
    - eW50dTlmaWc1Ng==
    - bGdzcWZ2cjN3Nw==
    - dTg0N2ZhY3F0NA==
    - dWZxZmRvaWVrZQ==
    - aXVnOGcxeTNvNw==
    - cGw1M2h6aGFtYw==
    valid:
    - YnlodG93aWRkeg==
    - cmRwNTdscm94Ng==
    - ZDJ5anRvbGgwYQ==
    - NHkyeXRuYTF4NQ==
  cidr:
    invalid:
    - 268.281.264.287/21
    multiple_valids:
    - 135.110.64.0/20
    - 135.110.176.0/20
    - 135.110.48.0/20
    - 135.110.144.0/20
    - 135.110.32.0/20
    - 135.110.224.0/20
    - 135.110.208.0/20
    - 135.110.96.0/20
    - 135.110.128.0/20
    - 135.110.80.0/20
    - 135.110.192.0/20
    - 135.110.16.0/20
    - 135.110.240.0/20
    - 135.110.0.0/20
    - 135.110.112.0/20
    valid:
    - 135.110.64.0/20
    - 135.110.176.0/20
    - 135.110.48.0/20
    - 135.110.144.0/20
  ipv4:
    invalid:
    - 282.256.288.282
    multiple_valids:
    - 135.110.235.20
    - 135.110.177.132
    - 135.110.167.220
    - 135.110.59.58
    - 135.110.66.54
    - 135.110.26.90
    - 135.110.252.126
    - 135.110.203.59
    - 135.110.43.10
    - 135.110.98.129
    - 135.110.162.40
    - 135.110.33.102
    - 135.110.185.193
    - 135.110.2.202
    - 135.110.94.207
    valid:
    - 135.110.235.20
    - 135.110.177.132
    - 135.110.167.220
    - 135.110.59.58
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f37f
    - 2001:db8::34f4:0:0:f3c7
    - 2001:db8::34f4:0:0:f37d
    - 2001:db8::34f4:0:0:f349
    - 2001:db8::34f4:0:0:f332
    - 2001:db8::34f4:0:0:f3b6
    - 2001:db8::34f4:0:0:f33c
    - 2001:db8::34f4:0:0:f357
    - 2001:db8::34f4:0:0:f3f8
    - 2001:db8::34f4:0:0:f353
    - 2001:db8::34f4:0:0:f3e1
    - 2001:db8::34f4:0:0:f30f
    - 2001:db8::34f4:0:0:f33f
    - 2001:db8::34f4:0:0:f3ee
    - 2001:db8::34f4:0:0:f38d
    valid:
    - 2001:db8::34f4:0:0:f37f
    - 2001:db8::34f4:0:0:f3c7
    - 2001:db8::34f4:0:0:f37d
    - 2001:db8::34f4:0:0:f349
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 68:5d:3d:04:30:c1
    - 43:b1:29:f4:64:bd
    - 37:e7:34:ce:6c:b8
    - 20:73:de:1d:6d:cb
    - 3a:30:82:32:91:a8
    - f0:de:59:29:72:10
    - ee:24:63:97:bb:03
    - 76:e0:90:b0:f7:25
    - 5f:a3:e4:91:b6:2f
    - 50:2e:f9:f2:25:cb
    - 6b:de:81:4a:05:a3
    - 80:86:04:1d:15:22
    - 34:21:c2:ac:a5:4c
    - f0:cf:03:95:fc:d0
    - 8c:80:0f:0c:14:32
    valid:
    - 65:e5:0b:a9:a2:15
    - 4e:29:96:53:23:97
    - 9e:69:d5:59:ad:75
    - 55:35:85:6a:f5:42
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - bg3855x6q6
    - 2decmgl7yp
    - ybdo3yqhrn
    - ta10l4h3fi
    - mba9hynbme
    - yij5qh4bik
    - ydec6h6ztp
    - rffca871oz
    - 5qc3l3vs1c
    - x8pb8lm9ha
    - wxjmnpzzxm
    - 2577l7ui5r
    - xdw1urx4d3
    - e20d56r4ir
    - w332702v9c
    valid:
    - temb076tbc
    - 32i7bygtyh
    - 8pwew02det
    - xmvmafrkee
  time:
    invalid:
    - '2022-07-29 11:13:56.286875'
    multiple_valids:
    - '2022-07-29T05:43:56.286875+00:00'
    - '2022-08-21T05:43:56.286875+00:00'
    - '2022-09-13T05:43:56.286875+00:00'
    - '2022-10-06T05:43:56.286875+00:00'
    - '2022-10-29T05:43:56.286875+00:00'
    - '2022-11-21T05:43:56.286875+00:00'
    - '2022-12-14T05:43:56.286875+00:00'
    - '2023-01-06T05:43:56.286875+00:00'
    - '2023-01-29T05:43:56.286875+00:00'
    - '2023-02-21T05:43:56.286875+00:00'
    - '2023-03-16T05:43:56.286875+00:00'
    - '2023-04-08T05:43:56.286875+00:00'
    - '2023-05-01T05:43:56.286875+00:00'
    - '2023-05-24T05:43:56.286875+00:00'
    - '2023-06-16T05:43:56.286875+00:00'
    valid:
    - '2022-07-29T05:43:56.286875+00:00'
    - '2022-08-21T05:43:56.286875+00:00'
    - '2022-09-13T05:43:56.286875+00:00'
    - '2022-10-06T05:43:56.286875+00:00'
  url-http:
    invalid:
    - ht:/sh3n3gnil9rx256.com
    multiple_valids:
    - http://51dneu1pabbw20r.com
    - http://antleffmuhtz4p9.com
    - http://b5pbxtzsuzxixnb.com
    - http://c6le5nilliu4ue2.com
    - http://7pm517po4ncd83a.com
    - http://br1ge8a2inbr185.com
    - http://rd086dcd3qjcn3z.com
    - http://r4bl076uoo0nr7z.com
    - http://k9optzceqfk4nvm.com
    - http://r1tevw0dwc2bt8y.com
    - http://niikojrm97548kf.com
    - http://umw2te1esicb83l.com
    - http://4e3z9e0dlwzsvjg.com
    - http://cegj5cyfyq6dyt1.com
    - http://s3k6eseask3akaa.com
    valid:
    - http://beoa50d2gmt2fub.com
    - http://3csf7sia1gcr9s4.com
    - http://rfn7648vc3b5mxx.com
    - http://fyxht84zcp990im.com
  url-https:
    invalid:
    - hts:/j7q9rdf190h0o02.com
    multiple_valids:
    - https://tp57q8kgompysdj.com
    - https://xh9dt1fvcyp06bt.com
    - https://hrjh47aj41w7697.com
    - https://p9wxi9ddycdq45d.com
    - https://ue7env5ilhnlg39.com
    - https://dncsi6nffaoqspw.com
    - https://b7visghgloj4dwo.com
    - https://uuxmd4j5ecgv5uf.com
    - https://mw2bvndsp0x723p.com
    - https://sg7ragi49cxpafw.com
    - https://jqpl6emwmbhkeqb.com
    - https://wv8wj7d6f9rel5u.com
    - https://uywlzb2rztm96si.com
    - https://phk3jwlj8qje5ol.com
    - https://bl9t0rrlg28mkru.com
    valid:
    - https://x4rkma3loyhtlmg.com
    - https://gpi4jhpd1vjskro.com
    - https://lakvry005baj0wm.com
    - https://5y6pqp6wi5zv1h7.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 6fc43c12-0f01-11ed-9e45-7c8ae1979a87
    - 6fc43c13-0f01-11ed-8fec-7c8ae1979a87
    - 6fc43c14-0f01-11ed-a76c-7c8ae1979a87
    - 6fc43c15-0f01-11ed-be78-7c8ae1979a87
    - 6fc43c16-0f01-11ed-9373-7c8ae1979a87
    - 6fc43c17-0f01-11ed-92ca-7c8ae1979a87
    - 6fc43c18-0f01-11ed-b762-7c8ae1979a87
    - 6fc43c19-0f01-11ed-b6f0-7c8ae1979a87
    - 6fc43c1a-0f01-11ed-9c59-7c8ae1979a87
    - 6fc43c1b-0f01-11ed-ae29-7c8ae1979a87
    - 6fc43c1c-0f01-11ed-a86d-7c8ae1979a87
    - 6fc43c1d-0f01-11ed-9819-7c8ae1979a87
    - 6fc43c1e-0f01-11ed-b52f-7c8ae1979a87
    - 6fc43c1f-0f01-11ed-bf7c-7c8ae1979a87
    - 6fc43c20-0f01-11ed-bad3-7c8ae1979a87
    valid:
    - 6fc43c0e-0f01-11ed-a242-7c8ae1979a87
    - 6fc43c0f-0f01-11ed-9cd0-7c8ae1979a87
    - 6fc43c10-0f01-11ed-82ea-7c8ae1979a87
    - 6fc43c11-0f01-11ed-bdd9-7c8ae1979a87
unique_attribute:
- name
