imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: application_profile
provider_name: Aci
schemas:
- attribute: tenant_dn
  depends_on:
    attribute_name:
    - id
    resource_name: tenant
  description: Dn of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 659qr5d951
    - o040vbmqvv
    - 71mn7yddag
    - 2ab4q54gkk
    - 18zp1phmle
    - gp7sooeigr
    - lodx6su4e0
    - 4ymbhwx2ci
    - mabfatgsl8
    - yutn9pezv1
    - wvl6ovjdu6
    - nd3rxhix8q
    - d70cnnfxmn
    - sfaei34ktp
    - lw3v85j771
    valid:
    - 78axutsotu
    - 3uur1le788
    - bnuz2q58sx
    - 6c8h931iwt
  type: string
- attribute: name
  description: Name of Application Profile
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - g2efcqsbar
    - wk7dhdjyyn
    - bucmb2bex4
    - ggsh9a1q5q
    - 8r9q89pzz4
    - 2pt820ouqh
    - mepr1bxeb8
    - 6zllm0jsuj
    - et9751arph
    - 6co7df6yue
    - z703iqj2gn
    - z062efh2q1
    - 768baevgrc
    - tyedbmufyt
    - q0dm2kst4f
    valid:
    - qwo71kur5o
    - wzg409k6l7
    - 7k9a075ueg
    - tk9zk6oocm
  type: string
- attribute: name_alias
  computed: true
  description: Name Alias for Application Profile
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 82gnt3w06d
    - jx72bmi467
    - zy4nb3lem7
    - c7g2z5qmbd
    - 7uk29viinc
    - ong5kmnv65
    - i9z35mpcyk
    - es7wr7dooo
    - r0i882j947
    - t8ryk15yqi
    - cgmbnvyzul
    - hqerun6bk4
    - 4gjd2b8fkw
    - wm6ynvz8y8
    - twofiz5a6s
    valid:
    - fs6pbrm6hn
    - cslfktwqrr
    - c1gw34d88v
    - 2vrr86oe90
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ycwuyc0ifl
    - 2ie4bkklqz
    - utwn4t6bzc
    - 2p2zigsz9e
    - tcovteafhn
    - zj9v8zljsh
    - 35v9xa1lao
    - uwfytllru1
    - r8jrz0fvig
    - x9t8upipgo
    - 6o27onl8gc
    - 2eaj3xe923
    - oap4bk9k23
    - 3etbst6uir
    - 94q1epx9sv
    valid:
    - opa7y597f4
    - 3o79qbiiyc
    - js8x6mpkg5
    - iidzor93xa
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - mp6jj51jmb
    - epaihq1sxw
    - lmqe99910q
    - e9ogcafwit
    - 81uhvkp5op
    - jxdrcr24cv
    - rkoa167pet
    - xy1d1opzji
    - tpczrwgzdw
    - prl4f6a9vw
    - pmneftizaq
    - mlavkb2w3v
    - rrteg331xs
    - qfj8kjtx75
    - e4txaov22y
    valid:
    - ea9gx0ac2l
    - 2br6heels3
    - 8drll6a3f4
    - j97e5ocs1i
  type: string
- attribute: prio
  computed: true
  default: unspecified
  optional: true
  subtype: string
  test_params:
    invalid:
    - v11ub9kj2q
    multiple_valids:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
    valid:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: 'false'
    params:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - dHhsdzg0dGQ1dA==
    - cTdnaGg3ajgyYQ==
    - eXo0M3JqYzM0cw==
    - YnQxbDZuM240MQ==
    - MGk3OHkxdTVveQ==
    - cndmMzVidDlmYQ==
    - bmJkZ20zazRlcA==
    - Mmh3NnQ4dWRzdg==
    - OXlnbDJlZ3oyaw==
    - ZDM5NzBoOTN5ZQ==
    - Z2NhZTcwcHF4eQ==
    - bjF2dG5reW56cw==
    - ZW5qbWJ6NHgzNg==
    - aXF3NWpsOGcyag==
    - ZmhpZTl2djV6Yw==
    valid:
    - YTdxazRsc3UwZA==
    - aHFzNzMyNjlnYQ==
    - ODRqbnp2ajM2MQ==
    - aW9panZhZTVjMg==
  cidr:
    invalid:
    - 280.269.268.273/22
    multiple_valids:
    - 86.180.192.0/20
    - 86.180.208.0/20
    - 86.180.32.0/20
    - 86.180.224.0/20
    - 86.180.16.0/20
    - 86.180.144.0/20
    - 86.180.128.0/20
    - 86.180.112.0/20
    - 86.180.48.0/20
    - 86.180.64.0/20
    - 86.180.0.0/20
    - 86.180.240.0/20
    - 86.180.176.0/20
    - 86.180.160.0/20
    - 86.180.96.0/20
    valid:
    - 86.180.192.0/20
    - 86.180.208.0/20
    - 86.180.32.0/20
    - 86.180.224.0/20
  ipv4:
    invalid:
    - 296.300.290.289
    multiple_valids:
    - 86.180.197.123
    - 86.180.8.9
    - 86.180.39.35
    - 86.180.222.156
    - 86.180.108.47
    - 86.180.253.94
    - 86.180.227.107
    - 86.180.60.66
    - 86.180.247.106
    - 86.180.167.155
    - 86.180.36.151
    - 86.180.25.89
    - 86.180.130.235
    - 86.180.206.255
    - 86.180.82.227
    valid:
    - 86.180.197.123
    - 86.180.8.9
    - 86.180.39.35
    - 86.180.222.156
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f372
    - 2001:db8::34f4:0:0:f33b
    - 2001:db8::34f4:0:0:f331
    - 2001:db8::34f4:0:0:f365
    - 2001:db8::34f4:0:0:f3c1
    - 2001:db8::34f4:0:0:f3f0
    - 2001:db8::34f4:0:0:f376
    - 2001:db8::34f4:0:0:f310
    - 2001:db8::34f4:0:0:f314
    - 2001:db8::34f4:0:0:f3eb
    - 2001:db8::34f4:0:0:f31f
    - 2001:db8::34f4:0:0:f321
    - 2001:db8::34f4:0:0:f38c
    - 2001:db8::34f4:0:0:f3f3
    - 2001:db8::34f4:0:0:f3dc
    valid:
    - 2001:db8::34f4:0:0:f372
    - 2001:db8::34f4:0:0:f33b
    - 2001:db8::34f4:0:0:f331
    - 2001:db8::34f4:0:0:f365
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - f2:24:2d:1a:63:7b
    - e5:78:40:66:8f:ee
    - 02:1b:e0:af:61:87
    - 7b:6c:21:6b:b9:cf
    - 78:17:c0:c9:55:b9
    - 39:7d:cd:cc:46:03
    - 3c:10:45:2d:bd:34
    - 1c:c3:72:0c:13:45
    - 6a:6f:cc:c4:27:0b
    - 4f:be:eb:b5:e6:58
    - 46:fa:7e:34:6e:45
    - 7a:0c:3b:40:3a:98
    - c4:af:00:cc:2d:d4
    - 89:97:d0:da:80:2e
    - 5c:e5:42:9d:41:8d
    valid:
    - 44:13:b8:41:d6:2d
    - c3:ae:75:8e:e0:d1
    - 22:6f:8c:58:02:e4
    - 55:2f:46:80:59:45
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - jg7uw6v6ek
    - egoxytukvg
    - 4my2xmqm4g
    - xgsm7zdowg
    - jm2vd73ghq
    - y0rgnhuju2
    - tj46enho0f
    - 5epl1scws9
    - l3ojlayxup
    - rue5fm56p8
    - dj0f5hhabl
    - y26dkhd7gt
    - lu05nln6gg
    - rkpqmaqcxn
    - psmma67lrx
    valid:
    - ljl7iz3qe2
    - 6l3idb49nn
    - 6yaucrhtoo
    - 1nb4q1wjkz
  time:
    invalid:
    - '2022-07-26 11:01:28.535488'
    multiple_valids:
    - '2022-07-26T05:31:28.535488+00:00'
    - '2022-08-18T05:31:28.535488+00:00'
    - '2022-09-10T05:31:28.535488+00:00'
    - '2022-10-03T05:31:28.535488+00:00'
    - '2022-10-26T05:31:28.535488+00:00'
    - '2022-11-18T05:31:28.535488+00:00'
    - '2022-12-11T05:31:28.535488+00:00'
    - '2023-01-03T05:31:28.535488+00:00'
    - '2023-01-26T05:31:28.535488+00:00'
    - '2023-02-18T05:31:28.535488+00:00'
    - '2023-03-13T05:31:28.535488+00:00'
    - '2023-04-05T05:31:28.535488+00:00'
    - '2023-04-28T05:31:28.535488+00:00'
    - '2023-05-21T05:31:28.535488+00:00'
    - '2023-06-13T05:31:28.535488+00:00'
    valid:
    - '2022-07-26T05:31:28.535488+00:00'
    - '2022-08-18T05:31:28.535488+00:00'
    - '2022-09-10T05:31:28.535488+00:00'
    - '2022-10-03T05:31:28.535488+00:00'
  url-http:
    invalid:
    - ht:/25ay91ohi2x080c.com
    multiple_valids:
    - http://zwklmcxffuo0hdk.com
    - http://9lmsuajemf02a0v.com
    - http://kyrvhxg98s6rwj7.com
    - http://ypsyasbsop3zsht.com
    - http://8p0414x3kqrazi2.com
    - http://si8ybm0s3zcjtb3.com
    - http://gapl3ng1nwbl5bs.com
    - http://eep56w0srktwfgk.com
    - http://1hx06u04st631um.com
    - http://xj8tb8x9hp9lrk4.com
    - http://jzjuqswowb7lu1z.com
    - http://hjvq1kqt7wxtzea.com
    - http://ux8x9nseup1o5f8.com
    - http://dv90cmvduq22xpq.com
    - http://82r0gyeif96m1l7.com
    valid:
    - http://jwpen2uy3rmos70.com
    - http://cob2yf21vq9agud.com
    - http://gbax8wh59kw3e6m.com
    - http://5xh539i5kngap8t.com
  url-https:
    invalid:
    - hts:/gc6zgxprdliior1.com
    multiple_valids:
    - https://8f8h694kiijdi63.com
    - https://flw357yjtkntgbw.com
    - https://zdoexbywcb8ueu2.com
    - https://errfvbeh8w3ejyn.com
    - https://qv4c7ngnegeeic9.com
    - https://jg4xeolkl9l1btl.com
    - https://r7su4wxxhua1o0x.com
    - https://gtjr4vpo8hcowj8.com
    - https://0swy9uo6r5nsyqg.com
    - https://y64g3ryray20n2j.com
    - https://hi9z5n40suq93q8.com
    - https://7thwgzc98a5pnyh.com
    - https://1ujojszvywl4h4u.com
    - https://lx6txuho77801xv.com
    - https://1gzec0cp9t9y91n.com
    valid:
    - https://ck682awcz0vfkjt.com
    - https://aiobi09lf0ough0.com
    - https://vxbrlzas8af7y24.com
    - https://grg3ar4rkyzabmv.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 32d52d86-0ca4-11ed-b4e3-7c8ae1979a87
    - 32d52d87-0ca4-11ed-82fe-7c8ae1979a87
    - 32d52d88-0ca4-11ed-9ef8-7c8ae1979a87
    - 32d52d89-0ca4-11ed-839f-7c8ae1979a87
    - 32d52d8a-0ca4-11ed-85d8-7c8ae1979a87
    - 32d52d8b-0ca4-11ed-9a65-7c8ae1979a87
    - 32d52d8c-0ca4-11ed-9769-7c8ae1979a87
    - 32d52d8d-0ca4-11ed-bf75-7c8ae1979a87
    - 32d52d8e-0ca4-11ed-b996-7c8ae1979a87
    - 32d52d8f-0ca4-11ed-a084-7c8ae1979a87
    - 32d52d90-0ca4-11ed-815e-7c8ae1979a87
    - 32d52d91-0ca4-11ed-99e3-7c8ae1979a87
    - 32d52d92-0ca4-11ed-8053-7c8ae1979a87
    - 32d52d93-0ca4-11ed-bd09-7c8ae1979a87
    - 32d52d94-0ca4-11ed-be2d-7c8ae1979a87
    valid:
    - 32d52d82-0ca4-11ed-9970-7c8ae1979a87
    - 32d52d83-0ca4-11ed-96fb-7c8ae1979a87
    - 32d52d84-0ca4-11ed-9123-7c8ae1979a87
    - 32d52d85-0ca4-11ed-9820-7c8ae1979a87
unique_attribute:
- name
