imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: application_profile
provider_name: Aci
schemas:
- attribute: tenant_dn
  depends_on:
    attribute_name:
    - id
    resource_name: tenant
  description: Dn of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - fgvn4v84p7
    - jdc3ry5rtk
    - 3k3tkt72vg
    - f5cy3t649p
    - 84wqv65j2v
    - d5il5mi8um
    - en332dif0n
    - 5mjtt7xn5z
    - rrhkgbwql8
    - mdaqdprclo
    - 5uhax3mcz6
    - rnhnihx44e
    - k0363qzslw
    - qpiwbvjqs1
    - n6xmbyv70g
    valid:
    - 2yvew1m1k1
    - c64eh30l8c
    - dhj92ne5mt
    - oorctal5jp
  type: string
- attribute: name
  description: Name of Application Profile
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 2m03u1qy17
    - 1ydpu0wmcy
    - e1ggh0v18x
    - uwica6s5sq
    - n7dd9kgs4v
    - sdwqk1f1td
    - 70im0fzq18
    - 9h3fty4hvt
    - lp8v4s7sdc
    - zeql2w3fgq
    - noq77mrgeb
    - l32mixm5x8
    - 0rcs7hiqa7
    - 5s9krf00dn
    - 3jpv6uk603
    valid:
    - sinmab83w8
    - wkqi1av7gv
    - evqyn4j05p
    - yivhblwhnt
  type: string
- attribute: name_alias
  computed: true
  description: Name Alias for Application Profile
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ao2uj6b91g
    - 6s5oxzjevp
    - g6xv430crr
    - tixxjf2qqd
    - zwjh48cg45
    - x3e5p2ac8l
    - w6lsrimozy
    - 43gxmwq73c
    - rw40hblfq1
    - cp9x4cf38d
    - 3hq0d5tqio
    - acu0az2mi3
    - 3hr1h8kyjp
    - 2pvb0ngii2
    - f6xf2uf9p7
    valid:
    - 81owp5de30
    - bho0gk25dk
    - ld7an4bg1p
    - d92clflvm8
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 4t1179i71g
    - fvaaio5crj
    - sjbpz1s324
    - 1ugl9nm5s3
    - 2foga790o2
    - 738hl0o7nl
    - 3grnfgwxnt
    - p5s2cl4l4g
    - 2yz7jyqg19
    - 8qz4jvsvrz
    - qbx164954d
    - g74x9g6h89
    - yxyt1cm023
    - 7hch6la7n8
    - kjyuis8y2h
    valid:
    - 0cfpo7vpsr
    - wekiiov50g
    - 2m73t4tr2d
    - rwkk4bymn7
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - dm5f5znnh2
    - soc9mq7439
    - h58lalme5x
    - a3lliyu5a8
    - 6ttw7gtsn9
    - scys8aaryx
    - 4iiqzq2v9g
    - lgcrzqe3m3
    - dcki0og06d
    - v0cizxd7s3
    - atn07nit1s
    - wrm7i57rlf
    - vg26jueclu
    - xlde9w9xib
    - 477mz3k54o
    valid:
    - tp4ec8ai8p
    - ozdeutvesi
    - 3orucuphpr
    - oyygo2w2dq
  type: string
- attribute: prio
  computed: true
  default: unspecified
  optional: true
  subtype: string
  test_params:
    invalid:
    - ycmlrhftvg
    multiple_valids:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
    valid:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: 'false'
    params:
    - unspecified
    - level3
    - level2
    - level1
    - level4
    - level5
    - level6
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - a3lkMDVycWh3bw==
    - NGtpZGgxOW40ZQ==
    - YWR1azZ3Nmc1Mg==
    - d3ZtNnd5Njd0bA==
    - c3lkZXpudnFiaA==
    - czdwMnJ3dTcyaw==
    - YTkzbjF2a3oxbw==
    - ZWVoaTJrYzh1bw==
    - aGFnNmRmd3hsbQ==
    - d3ZwaW1rdHJmdw==
    - dDBmbTVvZTliZw==
    - dDdvYmp1dzg4dA==
    - bG5yZnM1c3I4Mg==
    - aXNza3BiODlyMw==
    - bHc2M2FjZWFiNA==
    valid:
    - N2g3dTNiMXRuag==
    - YWU1MGkxa2d5dA==
    - YzZxbXFpNTYzcQ==
    - NjY1YW9qcWYyaA==
  cidr:
    invalid:
    - 293.282.259.285/9
    multiple_valids:
    - 152.38.144.0/20
    - 152.38.160.0/20
    - 152.38.112.0/20
    - 152.38.128.0/20
    - 152.38.48.0/20
    - 152.38.64.0/20
    - 152.38.0.0/20
    - 152.38.176.0/20
    - 152.38.208.0/20
    - 152.38.80.0/20
    - 152.38.192.0/20
    - 152.38.32.0/20
    - 152.38.240.0/20
    - 152.38.224.0/20
    - 152.38.96.0/20
    valid:
    - 152.38.144.0/20
    - 152.38.160.0/20
    - 152.38.112.0/20
    - 152.38.128.0/20
  ipv4:
    invalid:
    - 285.288.300.297
    multiple_valids:
    - 152.38.86.126
    - 152.38.67.171
    - 152.38.89.205
    - 152.38.66.116
    - 152.38.105.76
    - 152.38.44.186
    - 152.38.186.172
    - 152.38.16.29
    - 152.38.73.13
    - 152.38.144.195
    - 152.38.224.226
    - 152.38.174.98
    - 152.38.188.180
    - 152.38.81.184
    - 152.38.179.121
    valid:
    - 152.38.86.126
    - 152.38.67.171
    - 152.38.89.205
    - 152.38.66.116
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f319
    - 2001:db8::34f4:0:0:f360
    - 2001:db8::34f4:0:0:f301
    - 2001:db8::34f4:0:0:f35a
    - 2001:db8::34f4:0:0:f372
    - 2001:db8::34f4:0:0:f341
    - 2001:db8::34f4:0:0:f333
    - 2001:db8::34f4:0:0:f34a
    - 2001:db8::34f4:0:0:f3ab
    - 2001:db8::34f4:0:0:f3df
    - 2001:db8::34f4:0:0:f332
    - 2001:db8::34f4:0:0:f393
    - 2001:db8::34f4:0:0:f374
    - 2001:db8::34f4:0:0:f338
    - 2001:db8::34f4:0:0:f386
    valid:
    - 2001:db8::34f4:0:0:f319
    - 2001:db8::34f4:0:0:f360
    - 2001:db8::34f4:0:0:f301
    - 2001:db8::34f4:0:0:f35a
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - be:ff:e7:85:09:fc
    - fa:90:74:07:14:e9
    - 22:e0:b3:ee:47:11
    - b4:2c:e1:b3:e8:40
    - ef:3d:2d:f5:ae:56
    - 34:b3:59:66:bf:19
    - 4d:27:54:52:b7:04
    - d8:c3:a7:38:e8:e9
    - 4e:06:63:a4:1a:0e
    - 41:fd:3d:62:64:5b
    - a3:7d:bd:af:a4:ec
    - a0:90:43:6f:3e:1b
    - c5:1c:5e:da:33:af
    - 89:da:4b:75:5e:50
    - 17:0c:6c:0c:a6:36
    valid:
    - 9c:7c:db:c8:8f:a3
    - 46:cd:6c:13:5b:6b
    - b0:97:f6:a8:34:26
    - f5:26:a6:e9:d2:92
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 83jk82x3cb
    - 1umbdzfa0x
    - lkb0a8zki7
    - ygdiycblas
    - tlzupy3mck
    - kuwozkzqdf
    - g9wex9pu0n
    - c1lzcykkzx
    - 1kmddz3jqq
    - jntzokpzli
    - gs19k8929k
    - kypx0yh3ep
    - lfolsymlxj
    - s25ao95pep
    - clcf7dea0i
    valid:
    - 11tc5osda2
    - fa0m5osw1y
    - o0mh3yaqj6
    - ayybcca3za
  time:
    invalid:
    - '2022-07-25 12:40:46.710454'
    multiple_valids:
    - '2022-07-25T07:10:46.710454+00:00'
    - '2022-08-17T07:10:46.710454+00:00'
    - '2022-09-09T07:10:46.710454+00:00'
    - '2022-10-02T07:10:46.710454+00:00'
    - '2022-10-25T07:10:46.710454+00:00'
    - '2022-11-17T07:10:46.710454+00:00'
    - '2022-12-10T07:10:46.710454+00:00'
    - '2023-01-02T07:10:46.710454+00:00'
    - '2023-01-25T07:10:46.710454+00:00'
    - '2023-02-17T07:10:46.710454+00:00'
    - '2023-03-12T07:10:46.710454+00:00'
    - '2023-04-04T07:10:46.710454+00:00'
    - '2023-04-27T07:10:46.710454+00:00'
    - '2023-05-20T07:10:46.710454+00:00'
    - '2023-06-12T07:10:46.710454+00:00'
    valid:
    - '2022-07-25T07:10:46.710454+00:00'
    - '2022-08-17T07:10:46.710454+00:00'
    - '2022-09-09T07:10:46.710454+00:00'
    - '2022-10-02T07:10:46.710454+00:00'
  url-http:
    invalid:
    - ht:/un5d3i2b9ypxn8a.com
    multiple_valids:
    - http://89cs5rvq6ydxtly.com
    - http://0mgkmmqcc7s0i2b.com
    - http://ifi7v3to476rfzh.com
    - http://7heaqhhkb7u9g9f.com
    - http://pi1tspklp82e5dm.com
    - http://lpjlgeyxx0d990v.com
    - http://9x6pptut049m5ff.com
    - http://gjuwlrl4a0xjsg7.com
    - http://himd8nangwx1fgh.com
    - http://m9rzznzst4lfzfz.com
    - http://uabdg9mvr7s8vxn.com
    - http://jj5degjyhoaj68q.com
    - http://wmo0efquiz96luf.com
    - http://3gghz9t0rkvzsug.com
    - http://5b3b04g1fzuxvbv.com
    valid:
    - http://rwehdrf8t8vy44v.com
    - http://0weytby38cqgthm.com
    - http://2h5otpcnr3iwhm5.com
    - http://hs7xm6u675iaeja.com
  url-https:
    invalid:
    - hts:/f4rfu1yc1t0h33j.com
    multiple_valids:
    - https://kngiamegk0xizw1.com
    - https://xf1oymsjopi6hpv.com
    - https://bs8lq1hu4vvs7g0.com
    - https://6sj9eyunjwxzhx5.com
    - https://w5z9k0hkp9db46v.com
    - https://26xtdj1tamtze6y.com
    - https://pe9jaqayz7cr8zj.com
    - https://zhbbadxtx0hkp6o.com
    - https://puw2rf0r8kikn08.com
    - https://nfhzgwzvgbs0tqp.com
    - https://gir6gxuf0q2ofer.com
    - https://70chviode6tcl4i.com
    - https://3fbzbnuz4j2a38c.com
    - https://qtwjf5mfw45mf7e.com
    - https://lrji707jz8cwdk0.com
    valid:
    - https://8sqahpgrdzs5kfs.com
    - https://osakokar7g85hye.com
    - https://ut63h8ezlii50xy.com
    - https://ekzagw6xx246khe.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - e7c4c724-0be8-11ed-8ca9-7c8ae1979a87
    - e7c4c725-0be8-11ed-a221-7c8ae1979a87
    - e7c4c726-0be8-11ed-9b6c-7c8ae1979a87
    - e7c4c727-0be8-11ed-a915-7c8ae1979a87
    - e7c4c728-0be8-11ed-b3e0-7c8ae1979a87
    - e7c4c729-0be8-11ed-b8af-7c8ae1979a87
    - e7c4c72a-0be8-11ed-8a24-7c8ae1979a87
    - e7c4c72b-0be8-11ed-a8c3-7c8ae1979a87
    - e7c4c72c-0be8-11ed-a096-7c8ae1979a87
    - e7c4c72d-0be8-11ed-a233-7c8ae1979a87
    - e7c4c72e-0be8-11ed-b696-7c8ae1979a87
    - e7c4c72f-0be8-11ed-aa62-7c8ae1979a87
    - e7c4c730-0be8-11ed-9a6a-7c8ae1979a87
    - e7c4c731-0be8-11ed-a5b0-7c8ae1979a87
    - e7c4c732-0be8-11ed-9ebf-7c8ae1979a87
    valid:
    - e7c4c720-0be8-11ed-8a22-7c8ae1979a87
    - e7c4c721-0be8-11ed-952a-7c8ae1979a87
    - e7c4c722-0be8-11ed-aa52-7c8ae1979a87
    - e7c4c723-0be8-11ed-a220-7c8ae1979a87
unique_attribute:
- name
