imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ywcixn7etw
    - 77v851co6g
    - f40bsossx6
    - vaez93vmge
    - mtcbc8h6xk
    - 51w0is15cq
    - hacyuc7o9w
    - bs4p1wjcth
    - trt5vv0qtw
    - qk8ik4hso7
    - i0zwcasoks
    - pb6ta74gow
    - mkeadoo98g
    - 03ouhk6354
    - ogmzgpy2oh
    valid:
    - 1hncbct2fm
    - rqmh5lib09
    - n8qn3ddm3n
    - lbxp5sd8da
  type: string
- attribute: temp
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -863
    - -476
    - -520
    - -550
    - 478
    - 949
    - 174
    - 439
    - -727
    - 420
    - 775
    - 918
    - 698
    - -292
    - 815
    valid:
    - -671
    - 750
    - -354
    - -404
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - 871.6997018048248
    - 747.1050029456238
    - 406.14202351332676
    - -565.6510611742249
    - -845.8074324357609
    - -855.663876707127
    - -731.1007899676537
    - 578.9800895298391
    - 705.2981555903509
    - 1.5399913418599809
    - 787.036191844461
    - 122.14192809782719
    - -739.1218674456527
    - 628.167222464692
    - 838.3362821249619
    valid:
    - 793.6325457759696
    - -754.1377416306135
    - -390.22839720124637
    - 556.4698719829979
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 289.300.286.269
    multiple_valids: &id002
    - 130.217.180.12
    - 130.217.183.234
    - 130.217.156.129
    - 130.217.83.84
    - 130.217.165.186
    - 130.217.140.166
    - 130.217.252.185
    - 130.217.223.53
    - 130.217.53.180
    - 130.217.173.9
    - 130.217.40.17
    - 130.217.134.79
    - 130.217.63.163
    - 130.217.212.162
    - 130.217.119.36
    valid: &id003
    - 130.217.180.12
    - 130.217.183.234
    - 130.217.156.129
    - 130.217.83.84
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 59035
    - 62558
    - 2780
    - 26775
    - 30808
    - 51376
    - 10884
    - 28251
    - 13604
    - 55678
    - 143
    - 58411
    - 57650
    valid:
    - 1
    - 65535
    - 29853
    - 10262
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      type: string
    type: schema
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 0hpxbc76s6
    - 1vb8usqr7i
    - ls5u3yi06w
    - 9yekotdqv4
    - wd3pvnic6q
    - 9tzialg6d9
    - d1e6lbv8dm
    - lz0qkl4gfy
    - c9l4tm252k
    - 00gmrpm658
    - n7dixcvjf3
    - yv06v5zmne
    - p3rn41j2i8
    - o78p7wdfh9
    - atfolv0lzq
    valid:
    - b6lopmlc5i
    - riwy9yxb9w
    - zr3zvlcss0
    - znzc493r9c
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 28
    - 64
    - 97
    - 87
    - 81
    - 51
    - 15
    - 75
    - 96
    - 38
    - 52
    - 96
    valid:
    - 1
    - 100
    - 50
    - 37
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - 97xky3h318
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 22
    - 8
    - 2
    - 24
    - 18
    - 5
    - 18
    - 3
    - 16
    - 23
    - 3
    - 19
    valid:
    - 0
    - 32
    - 16
    - 28
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 35.43753930922524
    - 4.987468860668278
    - 60.31852474589726
    - 22.190748775963456
    - 37.51117636283956
    - 44.15679306778197
    - 5.259391267195609
    - 51.881805894597605
    - 27.94522162710477
    - 73.42481741401544
    - 91.98704862656518
    - 21.11681458422678
    valid:
    - 0
    - 100
    - 50.0
    - 0.16315715392874452
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 405
    - 704
    - -368
    - -229
    - -480
    - 322
    - -530
    - 110
    - -276
    - 246
    - -724
    - -795
    - 509
    - -977
    - -245
    valid:
    - -799
    - 176
    - 82
    - -583
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - ted770iev5
        - rslo6jpycz
        - b9ouldfsgp
        - nbo95dpnnp
        - p62yn8eun9
        - 9y4zw4lb8n
        - ehtfeywn8b
        - epdfe2zdv2
        - ftg5vrc537
        - um6p0tel3u
        - grpk3ddkdu
        - 44wx61ml9o
        - p3436gbs2f
        - chezs48501
        - m7a56li57p
        valid:
        - o7k6pxud0i
        - vhuqkzy7l4
        - u2a46z17x0
        - g6ljek69ml
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - ji1hw6e5m7
        - wefd2n5uvh
        - h6jt5sfdcb
        - ixhvsgbs58
        - 514a1ji4dw
        - 92vcy23tyo
        - w37hvshifu
        - hs50fax9lk
        - 4xllvb21h6
        - xy1c59mq92
        - pnv1punhnz
        - 5m8ncn8dmz
        - l5wvpdzva4
        - tpzgf7vepy
        - 1e0irgxr92
        valid:
        - w7kck95k3w
        - otrzzr2bdn
        - s4edwthq3j
        - jp0pilbjxk
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - h2ovni3csj
        - rfsfb760l2
        - 38d449kohz
        - pvgpxec9ni
        - 3lx2zg4pdr
        - d84wcex3fl
        - p9w5l3nm30
        - xi4stljz6s
        - f2uc5pw1r4
        - s2tpwnu5dp
        - shkw83nac7
        - qd7qz2jnn1
        - x2cfr7hf3v
        - qf7xvskwzw
        - hofdgnzexx
        valid:
        - rmize137za
        - 1a9zipf4kg
        - qaxwmohxe1
        - 5ic7jyqp0g
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - vejyxa80pd
            - 8yp474x1fu
            - awqxdj5oan
            - b92eamb7n8
            - lddz62e9j5
            - bcuaxjc52q
            - g1rjtc1n7f
            - 6pi8fpgu18
            - sffbd6mo0l
            - tbsv2oli3l
            - 4b6cmvxkjo
            - jynsvno2rw
            - xqzvefweo3
            - zo85tp296v
            - nro1iphbze
            valid:
            - gyiujw2cj8
            - e79yg0j8ia
            - z9weu8oct5
            - 1hp7v4v4qg
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - opevo5kb60
            - 78pybaco6g
            - uxsuhdv2i2
            - z2raoovbzy
            - fd2gnltaaf
            - kjf22q13b8
            - suay05ki1x
            - d1sqpyk7un
            - ujc4bg7sqc
            - svkhsox6cb
            - 12gooat18g
            - x6zqqob2p8
            - l2oc42yhkm
            - 0xafuvprqz
            - p84bcn51hz
            valid:
            - r8y3dy61us
            - 6yuovcp9u2
            - 63mjxpbd7s
            - 9a8iexg0ip
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f3b5
            - 2001:db8::34f4:0:0:f395
            - 2001:db8::34f4:0:0:f37e
            - 2001:db8::34f4:0:0:f39b
            - 2001:db8::34f4:0:0:f347
            - 2001:db8::34f4:0:0:f338
            - 2001:db8::34f4:0:0:f33b
            - 2001:db8::34f4:0:0:f30e
            - 2001:db8::34f4:0:0:f327
            - 2001:db8::34f4:0:0:f317
            - 2001:db8::34f4:0:0:f368
            - 2001:db8::34f4:0:0:f3af
            - 2001:db8::34f4:0:0:f3f9
            - 2001:db8::34f4:0:0:f3f2
            - 2001:db8::34f4:0:0:f343
            valid: &id006
            - 2001:db8::34f4:0:0:f3b5
            - 2001:db8::34f4:0:0:f395
            - 2001:db8::34f4:0:0:f37e
            - 2001:db8::34f4:0:0:f39b
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - o8gbo6czqe
            - 1vcdbcops7
            - duei7ov2cd
            - ub1wf6l1j8
            - 6irg65fioe
            - 2d245isqkr
            - 32yns7uy69
            - t4h5uatu8t
            - xtpjirojsi
            - nqxtg13iut
            - 8zy6mji82t
            - l1tsx9sx21
            - q3h3r66zzl
            - hjccppxkx8
            - uv4ew00uzv
            valid:
            - ypts86s9ki
            - zpkv9rlkfb
            - x7e8kho91g
            - wu64ya9zta
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - Nm1oaTJ0NHBnZw==
    - ZHllZWI2NXZ0cg==
    - NGx6cTJ3NmNkaw==
    - OXFhOWZ5a3M2Nw==
    - aGkwM3hneWQ3ag==
    - cDNibGFrYTBnYw==
    - ajdmc2JtMGo3bw==
    - MWtjeGJ5MmUxbA==
    - em4xNXNsMDQ3Mw==
    - MGMzbTYxNTVzcQ==
    - ajlwd3NkdTMwaw==
    - NTk5anJ1c2RwNw==
    - d3ViM2tpeWFzZg==
    - bWR6OWRyeG5oYQ==
    - NHN3MTByYWZrMA==
    valid:
    - ZXBlcDNhMTJmMg==
    - amhoMGRkaGZwcw==
    - MHd2NnNvMHg2NQ==
    - eGw0Nzg0MGFxaQ==
  cidr:
    invalid:
    - 256.282.259.275/3
    multiple_valids:
    - 130.217.16.0/20
    - 130.217.48.0/20
    - 130.217.80.0/20
    - 130.217.0.0/20
    - 130.217.96.0/20
    - 130.217.128.0/20
    - 130.217.192.0/20
    - 130.217.208.0/20
    - 130.217.144.0/20
    - 130.217.64.0/20
    - 130.217.160.0/20
    - 130.217.176.0/20
    - 130.217.224.0/20
    - 130.217.240.0/20
    - 130.217.32.0/20
    valid:
    - 130.217.16.0/20
    - 130.217.48.0/20
    - 130.217.80.0/20
    - 130.217.0.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 24:a2:cb:e6:ec:be
    - fc:7a:24:c8:1c:9e
    - 57:04:d4:1f:ce:6f
    - 5d:a8:cf:07:b3:6f
    - 35:d4:0f:35:cd:7b
    - d7:d2:60:70:cd:a6
    - 8a:98:b4:ab:48:8d
    - dc:39:46:03:8b:7a
    - 46:ef:8d:9e:40:27
    - c8:60:9d:7b:9d:01
    - 3c:1a:be:a5:7e:5b
    - 6a:19:cf:06:33:37
    - 40:e7:61:86:d1:a1
    - da:ef:d8:19:83:c1
    - 15:44:f2:37:9a:19
    valid:
    - b8:78:95:42:8e:57
    - 2d:82:88:61:82:f1
    - 48:79:5e:22:33:c8
    - a9:a6:8c:92:b2:08
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 2yhu1co7tn
    - nrhpcbbfv7
    - bbqld9s6og
    - u1k02w5n7c
    - g9xuhwq7k9
    - 2ltjkmsbx6
    - y3l431heqm
    - tyf5po8c5i
    - 3eyugud3me
    - 0w0jiuzdlr
    - recwrgq9fe
    - su92pu38fx
    - n7p2u52840
    - y4z5gd8i9x
    - 8wlieort3v
    valid:
    - al97sjrc65
    - m11eykyr95
    - lv9wesur0k
    - sip75zu7qv
  time:
    invalid:
    - '2022-07-26 11:01:28.892147'
    multiple_valids:
    - '2022-07-26T05:31:28.892147+00:00'
    - '2022-08-18T05:31:28.892147+00:00'
    - '2022-09-10T05:31:28.892147+00:00'
    - '2022-10-03T05:31:28.892147+00:00'
    - '2022-10-26T05:31:28.892147+00:00'
    - '2022-11-18T05:31:28.892147+00:00'
    - '2022-12-11T05:31:28.892147+00:00'
    - '2023-01-03T05:31:28.892147+00:00'
    - '2023-01-26T05:31:28.892147+00:00'
    - '2023-02-18T05:31:28.892147+00:00'
    - '2023-03-13T05:31:28.892147+00:00'
    - '2023-04-05T05:31:28.892147+00:00'
    - '2023-04-28T05:31:28.892147+00:00'
    - '2023-05-21T05:31:28.892147+00:00'
    - '2023-06-13T05:31:28.892147+00:00'
    valid:
    - '2022-07-26T05:31:28.892147+00:00'
    - '2022-08-18T05:31:28.892147+00:00'
    - '2022-09-10T05:31:28.892147+00:00'
    - '2022-10-03T05:31:28.892147+00:00'
  url-http:
    invalid:
    - ht:/oafhd6bta8dp0g7.com
    multiple_valids:
    - http://hkibntmrm91poj7.com
    - http://rkp275w9af13yhd.com
    - http://qyu3zf9fz5thxc8.com
    - http://4c70rjcewq9myr1.com
    - http://1rcegj86azsg4ij.com
    - http://d8apgifp5ynbpvz.com
    - http://bvwh64wx8ho7hvh.com
    - http://8ns2pqbdlzlhg8y.com
    - http://mv3ax0n3ez2rd9n.com
    - http://mxp5k1s44kl4pro.com
    - http://mh6crjnkv22s8mu.com
    - http://kv8xxw4qpbmk6wp.com
    - http://dym5y11v6d8mamz.com
    - http://0v4lgfymnys7icj.com
    - http://na0i4cx54fenrqv.com
    valid:
    - http://3ou71ke6nt2khx8.com
    - http://qxbjoqd2rlpw77r.com
    - http://rgjf0qp2dyb248a.com
    - http://m5ruqiqdw6csbbd.com
  url-https:
    invalid:
    - hts:/i766cwqmheq949s.com
    multiple_valids:
    - https://tmug1wto16ctd9h.com
    - https://t3makx6wjwiz443.com
    - https://32qgrmwj1pqymb7.com
    - https://2byu04nq40c1xrc.com
    - https://75ijy9kv9t1idi1.com
    - https://lckxd6456f58w7u.com
    - https://wrh4f70x8fqcbgm.com
    - https://ojjg4ptepo18kr5.com
    - https://n7130hwv7qkrxa7.com
    - https://e1tuogax143vzgg.com
    - https://4l3zgub04fjgckk.com
    - https://pf9yth0gsho8ke2.com
    - https://n1yur8ie8mexzvy.com
    - https://bs6unbshq2hwkta.com
    - https://3dsc2s6xdbu78vx.com
    valid:
    - https://6yanqlnpug4pkki.com
    - https://21zarkgj7ugp36r.com
    - https://dfpyzuu2f9wpeui.com
    - https://aycyn3qj7isyc4u.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 330b9983-0ca4-11ed-8c8d-7c8ae1979a87
    - 330b9984-0ca4-11ed-a30c-7c8ae1979a87
    - 330b9985-0ca4-11ed-bd5a-7c8ae1979a87
    - 330b9986-0ca4-11ed-af7f-7c8ae1979a87
    - 330b9987-0ca4-11ed-85d3-7c8ae1979a87
    - 330b9988-0ca4-11ed-b2c8-7c8ae1979a87
    - 330b9989-0ca4-11ed-821e-7c8ae1979a87
    - 330b998a-0ca4-11ed-92dc-7c8ae1979a87
    - 330b998b-0ca4-11ed-8127-7c8ae1979a87
    - 330b998c-0ca4-11ed-b034-7c8ae1979a87
    - 330b998d-0ca4-11ed-9f03-7c8ae1979a87
    - 330b998e-0ca4-11ed-9918-7c8ae1979a87
    - 330b998f-0ca4-11ed-82e6-7c8ae1979a87
    - 330b9990-0ca4-11ed-9503-7c8ae1979a87
    - 330b9991-0ca4-11ed-b31d-7c8ae1979a87
    valid:
    - 330b997f-0ca4-11ed-859e-7c8ae1979a87
    - 330b9980-0ca4-11ed-9da2-7c8ae1979a87
    - 330b9981-0ca4-11ed-a746-7c8ae1979a87
    - 330b9982-0ca4-11ed-9501-7c8ae1979a87
unique_attribute:
- name
- temp
