imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 0xemzpzoh4
    - bclcc9973y
    - rjo6yulakq
    - iwdtz92kr3
    - em1jbfign9
    - de5ccye1z0
    - jhlh5iarqr
    - 699yl9hu5u
    - ia0h6neo0x
    - n3cpr1uftl
    - 344ynku414
    - hlniikvvaa
    - dai4aj4kli
    - osofhav40j
    - 0emrl860o8
    valid:
    - rmg0ci3280
    - 00uyzozt8i
    - 7kz8txccmx
    - hxd0zftxyv
  type: string
- attribute: temp
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -959
    - -528
    - -463
    - 617
    - -386
    - -504
    - -597
    - 502
    - -1000
    - -131
    - 906
    - -497
    - -432
    - -919
    - -427
    valid:
    - 995
    - -145
    - -895
    - 157
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - 78.96365483416878
    - -173.85685465598198
    - 599.8812000804619
    - 799.9165898271451
    - 901.3746716655593
    - -409.83222056900377
    - 409.51468327323454
    - -131.1162502508257
    - 240.70371282376718
    - 174.6094029304402
    - -364.8029145191496
    - -201.51420928107285
    - -993.300668333156
    - 550.1008361778528
    - 5.250967735837334
    valid:
    - -646.2783523870356
    - 691.8377095617526
    - -37.369098995812074
    - -910.7154113249186
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 275.293.291.291
    multiple_valids: &id002
    - 75.79.234.114
    - 75.79.179.156
    - 75.79.202.97
    - 75.79.142.9
    - 75.79.146.166
    - 75.79.26.197
    - 75.79.138.3
    - 75.79.95.115
    - 75.79.32.164
    - 75.79.65.120
    - 75.79.16.219
    - 75.79.250.103
    - 75.79.62.225
    - 75.79.224.13
    - 75.79.168.140
    valid: &id003
    - 75.79.234.114
    - 75.79.179.156
    - 75.79.202.97
    - 75.79.142.9
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 64822
    - 25760
    - 55882
    - 65180
    - 27433
    - 44286
    - 18239
    - 3758
    - 37356
    - 61418
    - 61551
    - 30877
    - 22068
    valid:
    - 1
    - 65535
    - 30387
    - 30659
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      type: string
    type: schema
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 8m9nkjhl80
    - 41ctxik7dl
    - 5f6wof2noh
    - wz60s139ml
    - 032xwdifj4
    - 4gijyaiyso
    - n6bpggujuh
    - nbxxhcmuie
    - ecj4lo9ka2
    - avn1auuy5x
    - t0csqprp8h
    - wpz9pe2svy
    - yufwn54cof
    - x58jehjfug
    - fcndvr1fzx
    valid:
    - go84gno9yz
    - i0iffsfiet
    - utc66kp1lx
    - dziib04dop
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 51
    - 70
    - 7
    - 61
    - 27
    - 95
    - 37
    - 17
    - 97
    - 34
    - 23
    - 71
    valid:
    - 1
    - 100
    - 50
    - 21
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - 1hcm1rbfzt
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 11
    - 10
    - 9
    - 3
    - 22
    - 8
    - 27
    - 29
    - 26
    - 27
    - 23
    - 30
    valid:
    - 0
    - 32
    - 16
    - 18
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 11.951702786898405
    - 40.06429566002133
    - 58.27596997831721
    - 70.50918507276057
    - 99.15940337544232
    - 25.44496131565167
    - 25.055746399787058
    - 74.6028952467314
    - 12.146250217686921
    - 43.99370554979584
    - 89.36932724097487
    - 68.86512562306207
    valid:
    - 0
    - 100
    - 50.0
    - 10.76018055127108
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -653
    - 442
    - -725
    - -637
    - -939
    - 501
    - -613
    - -98
    - 540
    - 556
    - 466
    - -77
    - 523
    - 238
    - 950
    valid:
    - 773
    - -690
    - -991
    - 162
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 6xulplbg61
        - 58esdbgit1
        - xjsjm5sbqt
        - n14fp4nc4c
        - bp2bgj42fq
        - nzkrbar31i
        - 4izaxeud7y
        - wepbdpy0ci
        - arfqx0awyt
        - vboneevde7
        - rpmcya3a4u
        - nujm0dvdjc
        - m7cb46yvup
        - cow9uellot
        - 1tvkq5fgll
        valid:
        - pkfkfcp1fg
        - zdj1hj5aew
        - j7q89b9cum
        - 868q1qp68a
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - sdnb1dwhto
        - l9ce0rbtd7
        - x433i2l78v
        - xct6o9m67a
        - xbm87fq2ld
        - euax3z7uuj
        - 1s1evbae0t
        - yt3sgdg5eg
        - cgdpwco61a
        - cr23pc1qib
        - l7isasp12t
        - 5rjf4wlduq
        - scrwhsjwmh
        - 0lukovs30e
        - s3i9orfyau
        valid:
        - h46oedwoll
        - acqq5a0s1h
        - xru2dnmice
        - 9r0zvwr4b3
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - uqsr3eq0ez
        - 1pclgzi115
        - y7egsxxx3o
        - xkk26e7lyw
        - 08rac3w8ew
        - sicikt6a4l
        - s3639vm912
        - 3aprfanli7
        - i09dxp0c8m
        - vk0hunkfrz
        - 1yi2pxg5s5
        - iepwxegbgd
        - hsvvfofu4x
        - yl05jtni2u
        - vstsmwnhho
        valid:
        - y1chhelj4f
        - ufvd3frkx6
        - xx28i21fcs
        - 22p3zwxzqj
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - 4iu3d18c8t
            - 5ngi65ym46
            - s4bebbw9pc
            - 3s5m4iyvt0
            - 8e7xla23u4
            - mhg2rfzhjb
            - 4l1muex3r5
            - phu2rr5oyo
            - 0cvuwqhvsl
            - yymff1cfqk
            - 06qszsas3c
            - 39ilr6g6wz
            - ql3pmo5ge7
            - sjffivfx3p
            - tvguh8xsuy
            valid:
            - j66y0ax2gd
            - z7qiocfwbu
            - jv5ly0hyzm
            - uippkxf0ak
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - il0ht05g78
            - 6wy1fpw3xg
            - 22omf9ctv4
            - 3h9x04g6oq
            - xup5q64bo3
            - fnk7x5bksh
            - 872trko4op
            - pgkte0bbww
            - m1w02qreqt
            - pd3s6d9unf
            - k41rbbqjuo
            - n82sfxf6pm
            - 1mh8sxb203
            - 5hlncbe8w4
            - 1n61wr9dme
            valid:
            - 8imkj9tttb
            - lgqw43mzch
            - 5iluuxewhd
            - 64mshji5n2
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f330
            - 2001:db8::34f4:0:0:f3d6
            - 2001:db8::34f4:0:0:f3d9
            - 2001:db8::34f4:0:0:f3ff
            - 2001:db8::34f4:0:0:f34c
            - 2001:db8::34f4:0:0:f35c
            - 2001:db8::34f4:0:0:f3f5
            - 2001:db8::34f4:0:0:f370
            - 2001:db8::34f4:0:0:f369
            - 2001:db8::34f4:0:0:f39b
            - 2001:db8::34f4:0:0:f3b5
            - 2001:db8::34f4:0:0:f387
            - 2001:db8::34f4:0:0:f3ca
            - 2001:db8::34f4:0:0:f38f
            - 2001:db8::34f4:0:0:f3bc
            valid: &id006
            - 2001:db8::34f4:0:0:f330
            - 2001:db8::34f4:0:0:f3d6
            - 2001:db8::34f4:0:0:f3d9
            - 2001:db8::34f4:0:0:f3ff
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - dhesk79skn
            - 06ffn8zrff
            - m8ypbq5ivp
            - 037qs623si
            - osa73cni9i
            - nwtatpn8po
            - yal4ymqfg5
            - t5ceoafu9p
            - 6fgpeyf4of
            - n08l8fkzwp
            - lcrutwby01
            - qnzyqpy2eh
            - r7j2nz21w4
            - v3qm5l28v5
            - 9qwnxv8q48
            valid:
            - jpbq2bnlhb
            - vl2e5fs714
            - y2s1gmf02z
            - dkh6xg3m6v
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - djIwOXU5a2diMQ==
    - aWRocDNqZzM1cA==
    - eGwwN2U4cmZ5OA==
    - dGx4aDJ2cHU4Mw==
    - djlsa2p0ZGswdw==
    - MTZjYTZ4NWpmMw==
    - eW9ubXIxYmlwbw==
    - NHJxeHp3eGltZA==
    - a2o4NnJnNGhoag==
    - eWk1dHF6djQ1aw==
    - bXFkZ202OXYwcQ==
    - bnZkbGVhMDVucQ==
    - YnA1azh5MXZ3Ng==
    - aHRyZW1kcHU4eA==
    - cXU2dWoxOTVjcg==
    valid:
    - YWNucWhycHNlZw==
    - OHBiY2hpc3RyNQ==
    - eHR6c3o2YjRtdQ==
    - aXQxaDd4aW44ZQ==
  cidr:
    invalid:
    - 268.259.290.297/23
    multiple_valids:
    - 75.79.32.0/20
    - 75.79.144.0/20
    - 75.79.48.0/20
    - 75.79.208.0/20
    - 75.79.64.0/20
    - 75.79.0.0/20
    - 75.79.160.0/20
    - 75.79.80.0/20
    - 75.79.16.0/20
    - 75.79.176.0/20
    - 75.79.112.0/20
    - 75.79.96.0/20
    - 75.79.224.0/20
    - 75.79.192.0/20
    - 75.79.128.0/20
    valid:
    - 75.79.32.0/20
    - 75.79.144.0/20
    - 75.79.48.0/20
    - 75.79.208.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 21:a5:fd:f6:ca:b2
    - 98:64:50:49:01:ae
    - 80:47:01:80:2a:07
    - 40:3f:7d:f4:43:a3
    - af:f7:a7:cb:c7:de
    - 26:6d:f9:70:4d:e7
    - d6:52:ca:4a:1f:fb
    - 54:9d:5d:b8:3b:72
    - ae:23:c1:4a:8e:02
    - 79:4b:6b:95:2a:55
    - 66:1e:f5:34:b9:cc
    - 12:6c:28:83:b0:54
    - 5d:35:44:5a:26:6f
    - c2:7f:17:05:43:34
    - 43:cd:5b:e8:5e:6d
    valid:
    - 3b:cc:90:00:a4:de
    - 20:8b:7a:02:06:89
    - b5:7a:96:27:e8:ef
    - 1a:cd:25:de:27:db
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - dhiwvc758h
    - ymoh3w129u
    - sj20rkv9q1
    - qm57acefp8
    - ll2pgvmhcr
    - 5itycxnrvj
    - 9j5833q6ui
    - lf1thf1h9f
    - xuf8k9dker
    - nk9zmvw8hz
    - vc4mxgxtdo
    - ty23snlrvx
    - ipmiukcugu
    - pjucrbn25o
    - 62qly1yi48
    valid:
    - z1onaz8nai
    - ab04soknav
    - 613arjkchn
    - i8fkz40ho2
  time:
    invalid:
    - '2022-08-02 15:53:33.018789'
    multiple_valids:
    - '2022-08-02T10:23:33.018789+00:00'
    - '2022-08-25T10:23:33.018789+00:00'
    - '2022-09-17T10:23:33.018789+00:00'
    - '2022-10-10T10:23:33.018789+00:00'
    - '2022-11-02T10:23:33.018789+00:00'
    - '2022-11-25T10:23:33.018789+00:00'
    - '2022-12-18T10:23:33.018789+00:00'
    - '2023-01-10T10:23:33.018789+00:00'
    - '2023-02-02T10:23:33.018789+00:00'
    - '2023-02-25T10:23:33.018789+00:00'
    - '2023-03-20T10:23:33.018789+00:00'
    - '2023-04-12T10:23:33.018789+00:00'
    - '2023-05-05T10:23:33.018789+00:00'
    - '2023-05-28T10:23:33.018789+00:00'
    - '2023-06-20T10:23:33.018789+00:00'
    valid:
    - '2022-08-02T10:23:33.018789+00:00'
    - '2022-08-25T10:23:33.018789+00:00'
    - '2022-09-17T10:23:33.018789+00:00'
    - '2022-10-10T10:23:33.018789+00:00'
  url-http:
    invalid:
    - ht:/l2z7k8yoq8m13mr.com
    multiple_valids:
    - http://ftqyj5w0wi126pb.com
    - http://dr3k874ftzc9uk7.com
    - http://fhrwc1bj34yg35m.com
    - http://lod146f1iwgybjl.com
    - http://g6leu2luszxbn7s.com
    - http://ztru7oa3b85b1td.com
    - http://yoj0hccety2udsj.com
    - http://txc1pzlad1cmuuh.com
    - http://c8kpw6tihyipzlf.com
    - http://blxwtkj3w81lcl3.com
    - http://gg7k78e21soexyc.com
    - http://q2wpynbmsqdklt2.com
    - http://b3g8g5xbwy4mfm6.com
    - http://2swunlqx6yke3ar.com
    - http://uedg10ejd5289u9.com
    valid:
    - http://4n2yne31gmmpg07.com
    - http://2qhwnsbkdlf0thu.com
    - http://i5mdib87llhyjvg.com
    - http://9xi77q2r5i7qjg8.com
  url-https:
    invalid:
    - hts:/6lzp54h8xfnb19j.com
    multiple_valids:
    - https://59csbn58danqjpd.com
    - https://p82mznj2uymtmrr.com
    - https://try3ha0z8an3xt3.com
    - https://uj73t4mvbj2fln0.com
    - https://gj4st31iu9eimxs.com
    - https://9aythuhb7ed4dyw.com
    - https://ms0knpwb6s1ryge.com
    - https://xdfv0bjaso4sbht.com
    - https://aop8qi1eky638kv.com
    - https://tj5nydp7kgg9bu3.com
    - https://pc7dw0p7qpa2x0n.com
    - https://c1gh0rrp6ntekp9.com
    - https://d7tqi0uucyae2u3.com
    - https://70cuxi3ccmnoigr.com
    - https://mhgrh0hw1455og1.com
    valid:
    - https://122r32tyt3ax0k8.com
    - https://z8t4t5r45kkekr6.com
    - https://8x7zrey9kp3ryvb.com
    - https://5z9jdegrlzwrp3s.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 29215e77-124d-11ed-b7fb-7c8ae1979a87
    - 29215e78-124d-11ed-912f-7c8ae1979a87
    - 29215e79-124d-11ed-bd3f-7c8ae1979a87
    - 29215e7a-124d-11ed-b4d4-7c8ae1979a87
    - 29215e7b-124d-11ed-9296-7c8ae1979a87
    - 29215e7c-124d-11ed-8ecc-7c8ae1979a87
    - 29215e7d-124d-11ed-8d29-7c8ae1979a87
    - 29215e7e-124d-11ed-8534-7c8ae1979a87
    - 29215e7f-124d-11ed-8cb8-7c8ae1979a87
    - 29215e80-124d-11ed-a3eb-7c8ae1979a87
    - 29215e81-124d-11ed-9179-7c8ae1979a87
    - 29215e82-124d-11ed-a53d-7c8ae1979a87
    - 29215e83-124d-11ed-aea5-7c8ae1979a87
    - 29215e84-124d-11ed-9900-7c8ae1979a87
    - 29215e85-124d-11ed-8c84-7c8ae1979a87
    valid:
    - 29215e73-124d-11ed-b991-7c8ae1979a87
    - 29215e74-124d-11ed-9a62-7c8ae1979a87
    - 29215e75-124d-11ed-b1a0-7c8ae1979a87
    - 29215e76-124d-11ed-a704-7c8ae1979a87
unique_attribute:
- name
- temp
