imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - xe5mqz1swa
    - hjqqk6mr99
    - ln32c63fee
    - rrsef9bkl1
    - nnkz1oauv0
    - 45mys62oww
    - czf5exk33q
    - 368gu1kya2
    - ipwzcse1w8
    - lipvnnlk2q
    - fm1svff533
    - wnb234g3pg
    - je7hnrldh7
    - 9i1fv3011j
    - 3g5e2v3k2r
    valid:
    - smd6ckl5u4
    - uf82owcs5x
    - t13ixsohyd
    - aiui74m1gk
  type: string
- attribute: temp
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -130
    - -788
    - -50
    - 856
    - -238
    - 0
    - 60
    - -923
    - -287
    - 378
    - 340
    - 3
    - -620
    - 72
    - 213
    valid:
    - 487
    - -900
    - -181
    - 617
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - -16.87433011706912
    - -271.1035975287523
    - -99.17164653438951
    - 715.359592007264
    - 400.5082272155255
    - 112.49771900383348
    - 669.3074280137902
    - 541.8919025220396
    - -409.4536025900964
    - -693.3191211865272
    - -698.6771238097177
    - -31.52942262931942
    - 182.03215848890224
    - 244.7534859647862
    - 237.92173420737902
    valid:
    - -562.9042259823627
    - 147.7665676303872
    - -692.6021881662369
    - -121.62454076819652
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 267.274.258.269
    multiple_valids: &id002
    - 229.102.196.104
    - 229.102.66.175
    - 229.102.121.110
    - 229.102.212.162
    - 229.102.129.250
    - 229.102.19.188
    - 229.102.245.170
    - 229.102.202.208
    - 229.102.188.22
    - 229.102.135.174
    - 229.102.238.14
    - 229.102.163.208
    - 229.102.67.56
    - 229.102.51.98
    - 229.102.119.99
    valid: &id003
    - 229.102.196.104
    - 229.102.66.175
    - 229.102.121.110
    - 229.102.212.162
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 49916
    - 46494
    - 43759
    - 27843
    - 52793
    - 11479
    - 53742
    - 49821
    - 602
    - 15808
    - 53874
    - 50568
    - 36027
    valid:
    - 1
    - 65535
    - 63248
    - 54076
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      type: string
    type: schema
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - t7eqkhk6uh
    - f42if5pi0z
    - q6hvh1bnm5
    - 5ta30lq725
    - 23k6b2yma2
    - ujf3kqz5r7
    - y4vty5nc85
    - 4wqpmmoapg
    - qx09rnj8df
    - zxhhq3ba0u
    - 5liqpl8q7r
    - 6iwflduygw
    - 8nadcvf87w
    - a4r9yrq6yn
    - hfbe7l9ftx
    valid:
    - 68q6uooi2e
    - 3oxd7ql7n6
    - htdjhguzf4
    - hb4jf8620t
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 89
    - 12
    - 66
    - 99
    - 91
    - 5
    - 77
    - 21
    - 38
    - 40
    - 6
    - 77
    valid:
    - 1
    - 100
    - 50
    - 60
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - e0fqv2pkz2
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 17
    - 2
    - 17
    - 21
    - 10
    - 6
    - 9
    - 1
    - 13
    - 4
    - 14
    - 17
    valid:
    - 0
    - 32
    - 16
    - 18
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 86.30216683262914
    - 28.697958121996233
    - 30.2466450218153
    - 57.535373596025195
    - 55.183192539243464
    - 85.09799420934543
    - 81.98199688488796
    - 56.65772076827832
    - 29.489574913657112
    - 30.80517541192403
    - 53.08141861621937
    - 61.745415560098145
    valid:
    - 0
    - 100
    - 50.0
    - 64.56736269844886
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 241
    - 326
    - 310
    - 482
    - 962
    - -219
    - -264
    - -884
    - -153
    - 347
    - 523
    - -428
    - -318
    - 525
    - -635
    valid:
    - 804
    - 736
    - -590
    - 575
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 5bdz91ft45
        - ue528vglta
        - bypbpcqxej
        - ptplxp4ak1
        - rdbq1vjb80
        - 1lrnx2xn7e
        - ef8oraw3ov
        - hr867u5857
        - 8qatpg9cdr
        - noaxji6nz4
        - w5771ulca2
        - skn8194kiv
        - 74ajl9yx52
        - w790cjpmyv
        - e07a089qk0
        valid:
        - g0bcfswh32
        - hnc7x4l10r
        - bx0s64uh9i
        - 8ohxuhakfq
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 6bhj68r84q
        - exmxa1td75
        - zcqmw6c9qk
        - k58esvpsl9
        - 62iu98tuos
        - eq5uyh0z7l
        - 47e5dm5vf5
        - jqm4k07cm5
        - 6s4gqoi0jc
        - 6w3p3m2x4v
        - 70y0yw5syq
        - c3f3rxdh6z
        - tzgd2ykkqw
        - 2y9v63pf4p
        - 3pmhbx04dc
        valid:
        - 6r6rhi5g8o
        - 9s70qp4mxd
        - 0isb1e7u6s
        - g3ku2we7u3
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - b2hpwvngwc
        - khfcuproil
        - 7r87z20a5v
        - ja2lmtarf8
        - dm7tfd6nn5
        - u1g31vgn65
        - 1353nfndje
        - vho7uxk0of
        - xim7het0cq
        - ldefhdpm4m
        - 0rl5r6fclp
        - c56voar9b7
        - e8mdeqkk7w
        - 5hpucyoacl
        - u9a5z6yn16
        valid:
        - 7e09gm1czw
        - n0hxl82nh7
        - t7fa6x9g22
        - i4dpco22hu
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - dczni4xcf0
            - 1k9cc3wtyc
            - fx96wr5i0q
            - 2wjxu3gia4
            - 563izclm81
            - a7madf4jh8
            - 204vpg3t4g
            - q1soonettg
            - mqjm4i3wyy
            - gul4q29fno
            - a1ylfto90x
            - fkgj0pvrpp
            - bualikc7l6
            - rvzjklr7yg
            - o9a9dwuoyz
            valid:
            - 7ekz66m72e
            - k3pq1rgi4g
            - lavs6szvgl
            - cvu8iuulyd
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - bux3gnqieq
            - tc0v1vu9jh
            - ez47o5lfop
            - kpdlrg1ets
            - zbazczgirz
            - mkqcczapuk
            - jr5bmf89q5
            - iorjzww3r2
            - vyxh4lq9sw
            - df3e0goiyz
            - oux27gn1wm
            - 3pq1k5nbw0
            - bobmiri7wl
            - 0jmnb5dpdd
            - lsslkam5lm
            valid:
            - 8ic14sk2d9
            - hruqrq5a4t
            - 2i8hn4vmlc
            - abbonttg46
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f39f
            - 2001:db8::34f4:0:0:f3f6
            - 2001:db8::34f4:0:0:f3a8
            - 2001:db8::34f4:0:0:f376
            - 2001:db8::34f4:0:0:f357
            - 2001:db8::34f4:0:0:f35f
            - 2001:db8::34f4:0:0:f38c
            - 2001:db8::34f4:0:0:f3f9
            - 2001:db8::34f4:0:0:f375
            - 2001:db8::34f4:0:0:f3b4
            - 2001:db8::34f4:0:0:f3f3
            - 2001:db8::34f4:0:0:f3d6
            - 2001:db8::34f4:0:0:f34b
            - 2001:db8::34f4:0:0:f339
            - 2001:db8::34f4:0:0:f333
            valid: &id006
            - 2001:db8::34f4:0:0:f39f
            - 2001:db8::34f4:0:0:f3f6
            - 2001:db8::34f4:0:0:f3a8
            - 2001:db8::34f4:0:0:f376
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - udvyk6yv0z
            - 3af607gw6l
            - b0vgmaa5qr
            - yu3vzkqxqt
            - 8rl9yxerxq
            - bp0kboi85d
            - wew3bpp0w2
            - 59aja7gnq0
            - 3pljb6rjzo
            - phbuod4rdx
            - chqqm95j7x
            - y3ee6l6zas
            - gf9o85kjco
            - qa58jzf86v
            - mdmr7jepm0
            valid:
            - ert4zif60d
            - h5rd8u1ze9
            - vg7d2jemom
            - olzubnpc07
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - b2NuNjJnZzNoMg==
    - eG1uOXFqYjQ4cg==
    - eDJmandzbTgycg==
    - aTk1ODlicXhtYQ==
    - MjFxN2YxZ3AxOQ==
    - bnFnNGxtdjdiOA==
    - M3VkMTRraW1meA==
    - Y3prb2lhOGd2cw==
    - NmZveGd3NHVqYQ==
    - NnplcGhsNXl1NQ==
    - aGY3dHhwbjdjcQ==
    - bjh4OGs2eTVkZw==
    - NDNreDVzZmJwMw==
    - YzZyeW9seDRlYg==
    - aXZ3a2dnOW0ycw==
    valid:
    - OHN3MnBsanNlbw==
    - c3pnZmxmMGhzdw==
    - Zm04ZHl5cjBlbg==
    - M2owNjVtaDNsMA==
  cidr:
    invalid:
    - 277.259.296.278/8
    multiple_valids:
    - 229.102.240.0/20
    - 229.102.128.0/20
    - 229.102.208.0/20
    - 229.102.160.0/20
    - 229.102.64.0/20
    - 229.102.32.0/20
    - 229.102.144.0/20
    - 229.102.0.0/20
    - 229.102.80.0/20
    - 229.102.224.0/20
    - 229.102.176.0/20
    - 229.102.192.0/20
    - 229.102.112.0/20
    - 229.102.96.0/20
    - 229.102.16.0/20
    valid:
    - 229.102.240.0/20
    - 229.102.128.0/20
    - 229.102.208.0/20
    - 229.102.160.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 6f:53:f8:eb:73:87
    - 33:89:55:e5:69:7e
    - 7a:86:09:d5:e4:d3
    - bd:4c:3c:80:b1:d3
    - 78:6c:0b:71:22:66
    - 4a:68:c5:7a:b8:06
    - 6d:07:21:07:bb:38
    - 4f:46:01:e8:16:91
    - 32:af:43:cc:4e:63
    - e4:c4:2c:a0:23:71
    - a1:1f:9e:12:26:33
    - 8a:24:9a:03:20:4f
    - f7:52:c5:6c:e6:02
    - cc:8b:e6:82:fd:7e
    - ad:6a:ee:5c:a2:d8
    valid:
    - 4e:1f:0b:31:d3:61
    - fe:1d:ca:fd:9b:13
    - 57:08:1e:9c:94:73
    - 13:e0:ae:17:e5:6d
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - fku7g6xuvj
    - yuxmgg8fmu
    - kdllyw8onv
    - if9d0ah3mu
    - w4ho39i0ut
    - darkatcika
    - v9ocyn05s0
    - 43a279cxbl
    - vfcy47ves7
    - eh1ayj6anx
    - ylhmfives4
    - iyalaghjmn
    - ikek2g55kv
    - vx2gl7jsx3
    - wgazk0ltu5
    valid:
    - 492x3tzdd2
    - k2emr4nuoe
    - bb2dox6yru
    - ay7o6nixgn
  time:
    invalid:
    - '2022-07-29 11:13:56.658550'
    multiple_valids:
    - '2022-07-29T05:43:56.658550+00:00'
    - '2022-08-21T05:43:56.658550+00:00'
    - '2022-09-13T05:43:56.658550+00:00'
    - '2022-10-06T05:43:56.658550+00:00'
    - '2022-10-29T05:43:56.658550+00:00'
    - '2022-11-21T05:43:56.658550+00:00'
    - '2022-12-14T05:43:56.658550+00:00'
    - '2023-01-06T05:43:56.658550+00:00'
    - '2023-01-29T05:43:56.658550+00:00'
    - '2023-02-21T05:43:56.658550+00:00'
    - '2023-03-16T05:43:56.658550+00:00'
    - '2023-04-08T05:43:56.658550+00:00'
    - '2023-05-01T05:43:56.658550+00:00'
    - '2023-05-24T05:43:56.658550+00:00'
    - '2023-06-16T05:43:56.658550+00:00'
    valid:
    - '2022-07-29T05:43:56.658550+00:00'
    - '2022-08-21T05:43:56.658550+00:00'
    - '2022-09-13T05:43:56.658550+00:00'
    - '2022-10-06T05:43:56.658550+00:00'
  url-http:
    invalid:
    - ht:/c1qflqgs7rd8m0e.com
    multiple_valids:
    - http://tpq1pu0v0m2epza.com
    - http://t8duyrfagnova9m.com
    - http://howw8oqg0oikrod.com
    - http://d3xqm9lcr5alrsx.com
    - http://mxq514pxypfeen9.com
    - http://zah23i2mrchga7h.com
    - http://0nvmgngla86cneq.com
    - http://xclfpi77puborek.com
    - http://ehlfgun85lpralf.com
    - http://tpecsmyo7kb90m5.com
    - http://z6zm2bn9mtu7e60.com
    - http://h0ves8stvn19a7p.com
    - http://xfkcmjxn9lagwcr.com
    - http://walhw5e3bzau3kx.com
    - http://q98eq0t8wvbufxp.com
    valid:
    - http://uler02xgav0x0hl.com
    - http://7n4p8y1x1ipxwdh.com
    - http://ke3w7kt87ue6evo.com
    - http://rww8dkqg0r6in5p.com
  url-https:
    invalid:
    - hts:/d9v4chvnzej9gjw.com
    multiple_valids:
    - https://t2gl19z4j6kidyr.com
    - https://4v9lpuc7oenmmqs.com
    - https://5k3ya0l1si6mryu.com
    - https://33zj1fb7878e4t1.com
    - https://qcy2rcsumqyw8xk.com
    - https://ay41ffa0cx1vri5.com
    - https://b0xu3l10910oo94.com
    - https://venjdkabvedelms.com
    - https://njipa7lxj3wz7rk.com
    - https://zt9l76cepu7o7dp.com
    - https://rwgzonye6uj7axr.com
    - https://4fwd2yj8rdn7kny.com
    - https://2xv8v3wu6me6iiz.com
    - https://lddsqk8g8g3m4on.com
    - https://bq88whei2lh2pz2.com
    valid:
    - https://4undh4d6bbdu4q3.com
    - https://vm63y4a7x7hrpij.com
    - https://o6qsbgek4xosnba.com
    - https://0gjo5w2888bn8q1.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 6ffcf2a5-0f01-11ed-bd9b-7c8ae1979a87
    - 6ffcf2a6-0f01-11ed-b7ed-7c8ae1979a87
    - 6ffcf2a7-0f01-11ed-a243-7c8ae1979a87
    - 6ffcf2a8-0f01-11ed-8cdd-7c8ae1979a87
    - 6ffcf2a9-0f01-11ed-bf2f-7c8ae1979a87
    - 6ffcf2aa-0f01-11ed-86b3-7c8ae1979a87
    - 6ffcf2ab-0f01-11ed-97e0-7c8ae1979a87
    - 6ffcf2ac-0f01-11ed-a2ff-7c8ae1979a87
    - 6ffcf2ad-0f01-11ed-bf42-7c8ae1979a87
    - 6ffcf2ae-0f01-11ed-b984-7c8ae1979a87
    - 6ffcf2af-0f01-11ed-bfda-7c8ae1979a87
    - 6ffcf2b0-0f01-11ed-943f-7c8ae1979a87
    - 6ffcf2b1-0f01-11ed-937a-7c8ae1979a87
    - 6ffcf2b2-0f01-11ed-bd58-7c8ae1979a87
    - 6ffcf2b3-0f01-11ed-995a-7c8ae1979a87
    valid:
    - 6ffcf2a1-0f01-11ed-a793-7c8ae1979a87
    - 6ffcf2a2-0f01-11ed-ab97-7c8ae1979a87
    - 6ffcf2a3-0f01-11ed-bb28-7c8ae1979a87
    - 6ffcf2a4-0f01-11ed-a05b-7c8ae1979a87
unique_attribute:
- name
- temp
