imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - omveiqpa9h
    - xccun7u74c
    - x1xek2cq3t
    - r29knypxpr
    - ilbeszasdl
    - 84w49uv4sb
    - uevohjg5bp
    - zr7i54qlmo
    - ij6x78gx5w
    - 8guc6z7qvn
    - wi0toouhjq
    - arxxcete13
    - 0qdth24rlt
    - 4xjt8qgf0y
    - tbpkm9n3a7
    valid:
    - fttl3a7le0
    - idqzsogxbv
    - k0tacgwsh0
    - octnprw5yp
  type: string
- attribute: temp
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -361
    - -169
    - 33
    - -84
    - -276
    - -573
    - 652
    - 416
    - -12
    - -352
    - 863
    - 583
    - 348
    - 159
    - -284
    valid:
    - 897
    - 804
    - -111
    - 577
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - 396.61704818119165
    - -299.1554999119677
    - 669.2910093107919
    - -7.692447198279137
    - -3.4549341696035993
    - -307.9839477271708
    - 695.3302007044289
    - -122.27490156308413
    - 514.4869282485754
    - 768.9168003336722
    - -318.23486288269714
    - -854.4322054810292
    - -238.0044113887619
    - -664.7925519134126
    - -357.41266467292917
    valid:
    - -619.3656507351852
    - 218.58163533922868
    - -443.8200879678906
    - -261.68089973322014
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 259.272.284.276
    multiple_valids: &id002
    - 2.57.170.92
    - 2.57.152.75
    - 2.57.93.149
    - 2.57.86.221
    - 2.57.82.81
    - 2.57.41.246
    - 2.57.9.26
    - 2.57.229.163
    - 2.57.216.232
    - 2.57.32.73
    - 2.57.204.189
    - 2.57.206.145
    - 2.57.110.59
    - 2.57.172.114
    - 2.57.121.8
    valid: &id003
    - 2.57.170.92
    - 2.57.152.75
    - 2.57.93.149
    - 2.57.86.221
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 30238
    - 3412
    - 56810
    - 45564
    - 7098
    - 10791
    - 45301
    - 7252
    - 65396
    - 30300
    - 48124
    - 30874
    - 13090
    valid:
    - 1
    - 65535
    - 13255
    - 10842
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      type: string
    type: schema
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - apubzcw79e
    - yd1ufynf3s
    - kran57r8ac
    - vmdfcsx98m
    - 8hdvjcnhox
    - 8dlkoifwwf
    - c2jihfymv2
    - hatvufxajo
    - ig3j6xam4b
    - e6x730wgl9
    - 69nqhpveea
    - s84trzsj4m
    - uaro8hlqgr
    - sk3ck34rnr
    - k1x39fy7ru
    valid:
    - 98lzvzyf4y
    - syzupfhf6c
    - 03k2z6pa8w
    - pis6hpy81y
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 6
    - 70
    - 6
    - 75
    - 25
    - 40
    - 16
    - 37
    - 33
    - 82
    - 16
    - 21
    valid:
    - 1
    - 100
    - 50
    - 68
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - wjtr5rw02k
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 16
    - 4
    - 3
    - 14
    - 10
    - 9
    - 11
    - 19
    - 24
    - 27
    - 25
    - 3
    valid:
    - 0
    - 32
    - 16
    - 20
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 75.77861775975909
    - 31.078783542573078
    - 69.58371633328262
    - 28.02324333884342
    - 94.41547926431878
    - 13.216425366202417
    - 93.46482951956743
    - 79.06542629854187
    - 51.23785698312916
    - 50.95791887972071
    - 80.08095515341373
    - 10.996989642834725
    valid:
    - 0
    - 100
    - 50.0
    - 35.76332566173056
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 503
    - -276
    - 793
    - 316
    - -158
    - 388
    - 706
    - 250
    - 233
    - -885
    - -309
    - 983
    - 248
    - -231
    - -936
    valid:
    - 726
    - 922
    - 290
    - -962
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 2z7xow1rkt
        - 2rosy3pdm6
        - ax82n4gefn
        - jkw5tm0usk
        - 8ilrjy1icj
        - zer5mqjdnu
        - hmhtk72kt2
        - utukatx5zv
        - z88qlictau
        - wx37wk51zz
        - qeyp2ofp7x
        - o14hf9oc77
        - 6psor49iyz
        - 2xl8an0lb6
        - 7l0ckbfn7k
        valid:
        - bhcgo5otx6
        - lj3qde2wz8
        - nr813c532z
        - psp1dkgmp1
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - gvgm2i0veq
        - 3kje3nutgb
        - jmtwhr77g1
        - 9cunj5me9r
        - peyn73d330
        - smp33ophwu
        - 09t4qk0sl9
        - d9l9w8o8nm
        - n11yxqbx9i
        - 3qtwkatud2
        - 3136ew3i2g
        - rhd17f2ljm
        - nr8krmw09t
        - 5pao3cfhmq
        - z4vlt6fwcq
        valid:
        - ggyiwl2egn
        - g7xklsyqkt
        - o4mkltx42h
        - 74hvm04a6u
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - v52j56xeyc
        - uqb0r5iczj
        - 2ixfz2ikvc
        - 6noyewjqcz
        - ml8aoyqzbs
        - nt7axgatfg
        - 5ol0my381t
        - honlr5ct00
        - fx9nas2bhe
        - 9i44guh2hv
        - wur08rgqfr
        - ge1xlzw7vm
        - he6dv8aeyv
        - how7jiv52r
        - fiw3dl75bi
        valid:
        - jkik6ui5ab
        - pdvzsek5kj
        - klemx7w4bi
        - 402gnqju4d
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - d6rciiu7dy
            - hiwt6cjjsl
            - 9v4f96ya0j
            - cghv14c0ec
            - bcbhgudfdw
            - vhy9jfg3hj
            - nd8w08ezh3
            - r8p4oar5dz
            - jaltsaeh0j
            - n93e4g9hho
            - p13l30u9ya
            - imugdwvnpn
            - dgrrf5ji08
            - 4sqj7xob92
            - u5nan19jin
            valid:
            - svrrgfwpk2
            - 48v9p6spn9
            - v2nqora2y1
            - 9dpqsjsoa3
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - h8ic0u62tg
            - 1zomdalihf
            - 9dzieptevb
            - fohxaf9bt5
            - 3a7xcfu786
            - jetfzarsiy
            - vbdzj80vo3
            - t1nup1x80x
            - fe7wufdm5q
            - rfes60kwjl
            - u7m0z5iccf
            - hwt73tz89x
            - uuey6hyzi3
            - rldf5wzm7f
            - 5w68hadqk6
            valid:
            - dfq9tdn16i
            - kif8h38myl
            - vkcjlnlni5
            - 9tcjkk8pqf
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f374
            - 2001:db8::34f4:0:0:f3c8
            - 2001:db8::34f4:0:0:f305
            - 2001:db8::34f4:0:0:f3a5
            - 2001:db8::34f4:0:0:f33f
            - 2001:db8::34f4:0:0:f3f7
            - 2001:db8::34f4:0:0:f3e0
            - 2001:db8::34f4:0:0:f346
            - 2001:db8::34f4:0:0:f369
            - 2001:db8::34f4:0:0:f33e
            - 2001:db8::34f4:0:0:f3fd
            - 2001:db8::34f4:0:0:f3bd
            - 2001:db8::34f4:0:0:f3dc
            - 2001:db8::34f4:0:0:f38a
            - 2001:db8::34f4:0:0:f33d
            valid: &id006
            - 2001:db8::34f4:0:0:f374
            - 2001:db8::34f4:0:0:f3c8
            - 2001:db8::34f4:0:0:f305
            - 2001:db8::34f4:0:0:f3a5
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - 5pg99e8np0
            - l0f9thcj7r
            - 63o6i6acg3
            - uoeqd5hnwp
            - fc15ef08wr
            - vbum8emj5p
            - f2cj7op1fj
            - ea4kgsuwas
            - 8kpqan1frw
            - oiil4mlb0s
            - b7bfp8xmgh
            - dyp8guq24j
            - 47wpwdu7oq
            - dcchpinkbc
            - 8cd6l8oawx
            valid:
            - 56qh6o3my7
            - dmoq2asbwn
            - gkdsqgerwy
            - 2vmkiuvdce
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - YXQ3cGpjNnlqNg==
    - cHE4c2Izd2FoZA==
    - am4xdWV6YzBscw==
    - azFqZDlsdnc1aQ==
    - N3M5dmYwMHhiZA==
    - YWd6MHh2eDJ2cA==
    - NnRnaG83aGY0bQ==
    - cm8wM3dpcGRlNg==
    - cWJsM3dzeHVkYg==
    - b2NveHNtNHgzOQ==
    - cXJxOHllaTE4cQ==
    - OHhhcmZvem82dQ==
    - ZDk3dnk1NHVoOQ==
    - MHdsYTYwcTEzYg==
    - NmI3NTFrMmQ2ag==
    valid:
    - ZmFlamJ0ZDhoNA==
    - aHN1eDR2MWY5Mg==
    - ZDh0MHc3bTFjZg==
    - enk3azY4anhnbA==
  cidr:
    invalid:
    - 285.266.272.287/14
    multiple_valids:
    - 2.57.160.0/20
    - 2.57.32.0/20
    - 2.57.64.0/20
    - 2.57.112.0/20
    - 2.57.80.0/20
    - 2.57.0.0/20
    - 2.57.224.0/20
    - 2.57.16.0/20
    - 2.57.144.0/20
    - 2.57.240.0/20
    - 2.57.96.0/20
    - 2.57.208.0/20
    - 2.57.48.0/20
    - 2.57.192.0/20
    - 2.57.176.0/20
    valid:
    - 2.57.160.0/20
    - 2.57.32.0/20
    - 2.57.64.0/20
    - 2.57.112.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - d8:c2:64:c6:11:63
    - e3:49:08:81:38:49
    - f2:69:8b:4c:89:f8
    - ba:af:e7:ee:63:4d
    - 1f:ae:b2:9e:1d:6d
    - 46:d2:c7:80:d9:0b
    - eb:d2:fa:03:24:f5
    - d1:bc:d9:97:26:47
    - 72:c6:7e:bf:dd:8e
    - 23:3c:dd:17:6e:07
    - 2c:2a:69:22:24:dd
    - c9:b4:b4:58:68:2f
    - 6a:de:20:10:4d:8d
    - af:e7:67:00:ec:9b
    - f9:ba:70:93:54:2b
    valid:
    - fb:d8:fc:12:f7:80
    - fa:82:71:a0:ad:bf
    - 7c:2c:56:cb:ab:94
    - bf:2a:6e:5a:0a:02
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 60s77xyoih
    - gom84u8ijb
    - 5ckwsqdy0g
    - q4q3jkhj9g
    - 60wtkcct7n
    - c0nb82b3os
    - ybs2fwziah
    - t86cid1r7w
    - mpwc06r7ur
    - hnct5po9ca
    - r5a7f0f9j5
    - 8z0jl29di7
    - c6nm9swl4h
    - z9c90chegf
    - kmub7sdgj6
    valid:
    - vfcaf10nm9
    - 1ne4zb3bde
    - js731p1zzk
    - k386239d8t
  time:
    invalid:
    - '2022-08-01 17:50:39.587061'
    multiple_valids:
    - '2022-08-01T12:20:39.587061+00:00'
    - '2022-08-24T12:20:39.587061+00:00'
    - '2022-09-16T12:20:39.587061+00:00'
    - '2022-10-09T12:20:39.587061+00:00'
    - '2022-11-01T12:20:39.587061+00:00'
    - '2022-11-24T12:20:39.587061+00:00'
    - '2022-12-17T12:20:39.587061+00:00'
    - '2023-01-09T12:20:39.587061+00:00'
    - '2023-02-01T12:20:39.587061+00:00'
    - '2023-02-24T12:20:39.587061+00:00'
    - '2023-03-19T12:20:39.587061+00:00'
    - '2023-04-11T12:20:39.587061+00:00'
    - '2023-05-04T12:20:39.587061+00:00'
    - '2023-05-27T12:20:39.587061+00:00'
    - '2023-06-19T12:20:39.587061+00:00'
    valid:
    - '2022-08-01T12:20:39.587061+00:00'
    - '2022-08-24T12:20:39.587061+00:00'
    - '2022-09-16T12:20:39.587061+00:00'
    - '2022-10-09T12:20:39.587061+00:00'
  url-http:
    invalid:
    - ht:/3w14onhht2i79tb.com
    multiple_valids:
    - http://28zi9h0x8xkr2oj.com
    - http://28zcxpodto88d8e.com
    - http://km8rr44dfu3d932.com
    - http://tuhbqy0qz4dbshd.com
    - http://xgp32bfkbsov2t1.com
    - http://e5bklln2wlk1k1u.com
    - http://2cdny5wz55ph2p6.com
    - http://y6qksf084aey41z.com
    - http://9ej0n8r5ujmecmd.com
    - http://o5aze5o7rkdq6wc.com
    - http://v7i1m0okva7d8kh.com
    - http://7yfrmaci5tckj59.com
    - http://i5pfiyc6fj4in57.com
    - http://dgu59qej9nl0d6o.com
    - http://j625e4azj44sqjh.com
    valid:
    - http://rnijoxcoag3o0qq.com
    - http://mmx1lqw731xf8sr.com
    - http://fw9bo9ht0ec5zjn.com
    - http://y5omdlmeobmxowt.com
  url-https:
    invalid:
    - hts:/6w0kc0gsrlkjeo2.com
    multiple_valids:
    - https://ki7o9hdvl4pfecu.com
    - https://06skrnfb7prkaa7.com
    - https://6uelnu9z72vjqsu.com
    - https://0pt9jow0bkchnqu.com
    - https://v6dryqod8f3ao7u.com
    - https://fjpi5ua2m81pkiy.com
    - https://kd1604o7rkeactz.com
    - https://px7brhjps84ex4a.com
    - https://0xgaw1d8xcru54a.com
    - https://rgm90loumxg6sb5.com
    - https://ry5rr1vr41pdx94.com
    - https://2txgvybbn5xbrdo.com
    - https://qh3ypbmz2z0x3yp.com
    - https://qzc4vi5ewxplueu.com
    - https://6jlk4kt15alywl5.com
    valid:
    - https://cjhj5o2vhr1obwx.com
    - https://i6oj03e0iqw2kij.com
    - https://if1o4me0ft6f55v.com
    - https://i520wfugyuhehfh.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 5ae0d99a-1194-11ed-a2a5-dc214861057a
    - 5ae0d99b-1194-11ed-8a0b-dc214861057a
    - 5ae0d99c-1194-11ed-b16d-dc214861057a
    - 5ae0d99d-1194-11ed-868c-dc214861057a
    - 5ae0d99e-1194-11ed-a53a-dc214861057a
    - 5ae0d99f-1194-11ed-9ba8-dc214861057a
    - 5ae0d9a0-1194-11ed-9961-dc214861057a
    - 5ae0d9a1-1194-11ed-a1e5-dc214861057a
    - 5ae0d9a2-1194-11ed-8159-dc214861057a
    - 5ae0d9a3-1194-11ed-af31-dc214861057a
    - 5ae0d9a4-1194-11ed-8988-dc214861057a
    - 5ae0d9a5-1194-11ed-b907-dc214861057a
    - 5ae0d9a6-1194-11ed-a5d9-dc214861057a
    - 5ae0d9a7-1194-11ed-aba3-dc214861057a
    - 5ae0d9a8-1194-11ed-90ce-dc214861057a
    valid:
    - 5ae0d996-1194-11ed-bbeb-dc214861057a
    - 5ae0d997-1194-11ed-9c28-dc214861057a
    - 5ae0d998-1194-11ed-97ea-dc214861057a
    - 5ae0d999-1194-11ed-977d-dc214861057a
unique_attribute:
- name
- temp
