imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ospudvcpo9
    - n16rvmuttq
    - vh2sgp3fii
    - xgv08e7sb8
    - sbli8jyhla
    - 6g2tb40i43
    - yyyccdx1r1
    - nxq0wxg5d6
    - v0y2b8o48j
    - 0qsa29irsj
    - wq65kiwvik
    - 3p22z52fgv
    - 7uxku2x3fj
    - qwka09iocf
    - ls23jqu1np
    valid:
    - 339ejsl0yj
    - nbcnhg8pmt
    - qyfjtj5r57
    - f8tonu07d8
  type: string
- attribute: temp
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -804
    - -227
    - 168
    - 222
    - 526
    - 216
    - -415
    - -146
    - 180
    - 86
    - -294
    - -150
    - 859
    - 213
    - 754
    valid:
    - -284
    - 589
    - -236
    - 705
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - 319.18381781449693
    - -472.97921658705553
    - 716.0301034107652
    - -691.1588089038291
    - 389.89399500665354
    - -827.553988401624
    - 591.8776117690678
    - 939.8164024217876
    - -808.8711046670858
    - 25.27995723916262
    - -50.88913784581502
    - -376.9786197440769
    - 459.954616909363
    - -997.5163236511363
    - 667.480310522205
    valid:
    - -367.6832974114676
    - -266.0667323234808
    - 0.4129568598387541
    - -982.2076670365478
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 259.294.282.298
    multiple_valids: &id002
    - 49.197.60.17
    - 49.197.208.199
    - 49.197.82.116
    - 49.197.203.104
    - 49.197.39.120
    - 49.197.227.245
    - 49.197.137.190
    - 49.197.133.114
    - 49.197.166.41
    - 49.197.184.75
    - 49.197.25.101
    - 49.197.210.83
    - 49.197.130.127
    - 49.197.38.250
    - 49.197.140.30
    valid: &id003
    - 49.197.60.17
    - 49.197.208.199
    - 49.197.82.116
    - 49.197.203.104
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 56944
    - 39987
    - 65048
    - 50108
    - 1626
    - 40950
    - 45600
    - 13450
    - 38385
    - 50933
    - 10794
    - 3338
    - 4111
    valid:
    - 1
    - 65535
    - 13665
    - 62100
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      type: string
    type: schema
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - eydn0ybkc1
    - 57yxcx5c6x
    - 97mah44uox
    - kuiob0qhla
    - zvuhmskjz0
    - qdet6hwbc6
    - icsrs2yd6m
    - vqe5qkjb2b
    - ofzj7jrcjw
    - u0q4b6erdm
    - c7rho51y5e
    - 97ypdpppwn
    - 41yv6do4qx
    - kduihz7kpf
    - 4dc33jdo4t
    valid:
    - culjc3cq4q
    - frx381kvp7
    - prf5hcx9y7
    - nbtvgjk0ki
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 46
    - 18
    - 8
    - 13
    - 26
    - 17
    - 81
    - 81
    - 24
    - 33
    - 48
    - 8
    valid:
    - 1
    - 100
    - 50
    - 94
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - m3yfd0q9xt
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 27
    - 17
    - 31
    - 15
    - 22
    - 6
    - 18
    - 9
    - 19
    - 10
    - 13
    - 3
    valid:
    - 0
    - 32
    - 16
    - 9
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 47.57515386365044
    - 2.6393158702025854
    - 70.70747762216465
    - 49.89513949329155
    - 84.72902461858548
    - 69.91148885795366
    - 52.58246819145676
    - 55.40824191540879
    - 77.2727347930307
    - 47.42123446887018
    - 61.594803589385364
    - 22.620986281045738
    valid:
    - 0
    - 100
    - 50.0
    - 34.67262119273435
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -927
    - 129
    - -32
    - -133
    - 784
    - 51
    - -145
    - 693
    - -916
    - 335
    - -894
    - -241
    - -975
    - 111
    - -328
    valid:
    - 987
    - 55
    - -449
    - -582
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 5vl7ro9aju
        - x460oda65i
        - hgnvm3gnrg
        - g1xx5ip95c
        - an00eem9lb
        - g1l59pzeyk
        - t42asjt8v6
        - fueqgt1ttp
        - ue9qt33r1q
        - k5jiitbhh5
        - jhhu4q2ez6
        - u08gqnutay
        - zhomdb0vsn
        - 82c4j1mon9
        - go73znib4l
        valid:
        - a6hm7mgsn7
        - o0oxkmuczz
        - ql6k3m9e6l
        - u6wd030ynt
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - h2jktzlmxi
        - k7wylndfi6
        - 96uz9hd6ae
        - sj00n5fu44
        - 2cw8dj1rvl
        - kr00q441tp
        - nop6bf3nba
        - 14zmmar81g
        - 4b9kbo4625
        - xhhepvxgwq
        - tb0akzlybp
        - 0bavs408xq
        - acw9lkmcwk
        - 783jvm3aju
        - apxar1t8ag
        valid:
        - j632g9e156
        - 4k3hjrme0d
        - cxchfdpy5p
        - 8ibel9fpoo
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - uf226cscng
        - tly6q7p7cw
        - iwrjdrc4qw
        - 1csu4id3kg
        - tqspap3jvv
        - 6986odgrra
        - g6y10d44hj
        - 2btb7ygni6
        - uvt0lcm2ga
        - hq1hhhi6e1
        - co5q8aif38
        - dzoznockqs
        - oho6leruj3
        - aukeso1vwp
        - y6di0fzfh7
        valid:
        - vkldopc8dc
        - progmpem9g
        - hpt4a2lxib
        - g76p83hdbr
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - xkzepfxoeo
            - ez5uzd46ev
            - obocyjqs1e
            - 967qdg08k5
            - wdc85qsqpc
            - 7plicfp2tb
            - tgbzwmozuh
            - mplfnfu7s9
            - bpn24cs9bm
            - exaxrrj1ci
            - abomnikdts
            - 5hvg2wxu43
            - ltc97gsfzk
            - okln8bmqij
            - bivvzgva2g
            valid:
            - q4msyvkc3k
            - lkvbo73eye
            - ecygflg6s9
            - mlteicc7aw
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - lvdx3misbh
            - o9ho8kcuw0
            - n0p5ge1nwc
            - n8057aj3iz
            - 5v1rm3mae5
            - as45xs8kkb
            - 2mf8lcf6xw
            - 6l4obgjh7e
            - jwvuzk1szr
            - kvb0dmmveh
            - y6hraotfwk
            - zt1ev35int
            - npko9w9ckr
            - zsdz79w0gq
            - hddal169ui
            valid:
            - pws8j5du3l
            - bp0woks3g9
            - yk7ixqs5qd
            - s6mhtjrcpc
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f309
            - 2001:db8::34f4:0:0:f3ab
            - 2001:db8::34f4:0:0:f323
            - 2001:db8::34f4:0:0:f391
            - 2001:db8::34f4:0:0:f385
            - 2001:db8::34f4:0:0:f366
            - 2001:db8::34f4:0:0:f3d6
            - 2001:db8::34f4:0:0:f350
            - 2001:db8::34f4:0:0:f318
            - 2001:db8::34f4:0:0:f353
            - 2001:db8::34f4:0:0:f36b
            - 2001:db8::34f4:0:0:f379
            - 2001:db8::34f4:0:0:f351
            - 2001:db8::34f4:0:0:f392
            - 2001:db8::34f4:0:0:f349
            valid: &id006
            - 2001:db8::34f4:0:0:f309
            - 2001:db8::34f4:0:0:f3ab
            - 2001:db8::34f4:0:0:f323
            - 2001:db8::34f4:0:0:f391
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - teusny09tm
            - py1kgfl1vf
            - 0btiqmm85u
            - tqs4dfgz1r
            - o2iq2ymb20
            - q1jlxyrllh
            - t2bsv9z4wt
            - 6bg0tehv3p
            - bpylbgzbt3
            - 4a8kzddmiy
            - vqdeknad72
            - 9hogrutzm0
            - kxa53qwj7j
            - x70s24df4t
            - z963zq8vfv
            valid:
            - 4ov6gqpxau
            - zf6fxi2clx
            - he8hj2yggs
            - 10pbqu42wm
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - ZDg5aHRwcDhhdg==
    - NWh5bnJ0emhvdA==
    - YXpkcW1ndWo1cA==
    - NWViYW1oeXdudg==
    - ejk3MnQyZ3d4bw==
    - anF5bDJxNmhoNQ==
    - MnAwZnNkeDQwaA==
    - cGI4bWxtMjdsag==
    - a3MzbTNtZmg0NQ==
    - cHhzbDc4YmJvMA==
    - ODhhbW02Z2UwNw==
    - aTc4cW9yaWk4eg==
    - ajV4bGNhMnpwbA==
    - bXBjNnJocXB2bQ==
    - aWM3a3h5ZmZnbA==
    valid:
    - YzY5eDJxajRtaA==
    - b3BmZzFybWlkeQ==
    - cG9pMDk2Zmhqag==
    - djE3aW1nYmU0Yg==
  cidr:
    invalid:
    - 298.292.292.264/31
    multiple_valids:
    - 49.197.16.0/20
    - 49.197.64.0/20
    - 49.197.112.0/20
    - 49.197.176.0/20
    - 49.197.240.0/20
    - 49.197.32.0/20
    - 49.197.224.0/20
    - 49.197.208.0/20
    - 49.197.128.0/20
    - 49.197.96.0/20
    - 49.197.80.0/20
    - 49.197.0.0/20
    - 49.197.144.0/20
    - 49.197.48.0/20
    - 49.197.160.0/20
    valid:
    - 49.197.16.0/20
    - 49.197.64.0/20
    - 49.197.112.0/20
    - 49.197.176.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 64:79:d5:0d:7a:13
    - a0:32:cb:ec:f4:ac
    - f1:1b:34:27:db:e0
    - 92:bf:1a:89:e1:ac
    - 70:09:42:8f:4c:ae
    - 0a:88:13:02:2b:63
    - bd:44:e0:5b:91:82
    - 50:16:4a:bc:15:2e
    - b3:a0:42:40:b7:1f
    - 5a:86:98:d3:6a:36
    - b9:af:4e:d0:a5:c4
    - bd:ce:fc:62:d3:66
    - 26:63:9e:b6:d8:5b
    - f2:12:12:57:4a:66
    - af:91:00:8a:2b:e5
    valid:
    - 95:c4:9b:f0:b0:61
    - 0e:10:6d:3b:03:03
    - f3:c2:aa:e0:0b:21
    - 8a:b6:0e:6d:79:f1
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - e3i4003ua5
    - 7by6huxpwz
    - hadyu2d98k
    - pr940p607f
    - 4emmkx5fro
    - dh98ydwr4a
    - g32wy6uw1e
    - 2qjdi1t350
    - wy4fjv3wr0
    - 4ldo0y67qf
    - jqonvdwehj
    - e21zewjxgi
    - cdjc3smcds
    - tqotlqbajl
    - qmpmmd1ggk
    valid:
    - s2ws6ogi5o
    - 27s1zxcynz
    - bcein37iod
    - 8jck1x1a0o
  time:
    invalid:
    - '2022-07-25 12:40:47.184922'
    multiple_valids:
    - '2022-07-25T07:10:47.184922+00:00'
    - '2022-08-17T07:10:47.184922+00:00'
    - '2022-09-09T07:10:47.184922+00:00'
    - '2022-10-02T07:10:47.184922+00:00'
    - '2022-10-25T07:10:47.184922+00:00'
    - '2022-11-17T07:10:47.184922+00:00'
    - '2022-12-10T07:10:47.184922+00:00'
    - '2023-01-02T07:10:47.184922+00:00'
    - '2023-01-25T07:10:47.184922+00:00'
    - '2023-02-17T07:10:47.184922+00:00'
    - '2023-03-12T07:10:47.184922+00:00'
    - '2023-04-04T07:10:47.184922+00:00'
    - '2023-04-27T07:10:47.184922+00:00'
    - '2023-05-20T07:10:47.184922+00:00'
    - '2023-06-12T07:10:47.184922+00:00'
    valid:
    - '2022-07-25T07:10:47.184922+00:00'
    - '2022-08-17T07:10:47.184922+00:00'
    - '2022-09-09T07:10:47.184922+00:00'
    - '2022-10-02T07:10:47.184922+00:00'
  url-http:
    invalid:
    - ht:/lb4sid3wfipnd18.com
    multiple_valids:
    - http://qqdqzarbkr4dqk9.com
    - http://yeploiqprdnyab2.com
    - http://gr743a09pt069sy.com
    - http://8vtfeqzc3kn9y1c.com
    - http://lba7vg913b1phuo.com
    - http://nfea9d5mz4ajfm1.com
    - http://wmp7ce9221cu26h.com
    - http://yxdbqp0lg87zpm0.com
    - http://ofpa1hbqqwr1o43.com
    - http://wie92z1zzgldjzj.com
    - http://1chpxa2iz3vyjfx.com
    - http://c24g8o9ls2qyzem.com
    - http://s6do8ie432mcxqc.com
    - http://4cdnipck3i57z4v.com
    - http://8gfo567ah1uhxqm.com
    valid:
    - http://xfjufgyfms2trmo.com
    - http://oel6kdkx6ps1myz.com
    - http://jc5098le3vq3bhe.com
    - http://o2lxxoqekuculaj.com
  url-https:
    invalid:
    - hts:/w52uqkrlzkiihyz.com
    multiple_valids:
    - https://w1jufpym579p7lw.com
    - https://hkci85y69zvads2.com
    - https://h4znckkq4nrxw4u.com
    - https://v7f4fcl9eeyv2s7.com
    - https://4lx9u9gyyf50pq0.com
    - https://eboaj4oq4os8ebf.com
    - https://xlujx1e6g2yhn4q.com
    - https://sgb4lpjoakca8t5.com
    - https://ry2qna8xfeoqw2u.com
    - https://q4z8zd435x87j6d.com
    - https://4z1ya08jqxitmga.com
    - https://ll08ek6duq46nvh.com
    - https://t60bxtdc2kxqxha.com
    - https://765dfilmm12zpm3.com
    - https://450xkvoeng828fx.com
    valid:
    - https://6hi097gjct279uj.com
    - https://b6nyvls9lkxkf0d.com
    - https://k0li6d6rv5mdtz3.com
    - https://gwiw41u2yjgqaxw.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - e80d2d0c-0be8-11ed-afc0-7c8ae1979a87
    - e80d2d0d-0be8-11ed-8210-7c8ae1979a87
    - e80d2d0e-0be8-11ed-8a64-7c8ae1979a87
    - e80d2d0f-0be8-11ed-8b35-7c8ae1979a87
    - e80d2d10-0be8-11ed-a0d2-7c8ae1979a87
    - e80d2d11-0be8-11ed-94e3-7c8ae1979a87
    - e80d2d12-0be8-11ed-aefa-7c8ae1979a87
    - e80d2d13-0be8-11ed-9858-7c8ae1979a87
    - e80d2d14-0be8-11ed-bac7-7c8ae1979a87
    - e80d2d15-0be8-11ed-ac3d-7c8ae1979a87
    - e80d2d16-0be8-11ed-8ae0-7c8ae1979a87
    - e80d2d17-0be8-11ed-b769-7c8ae1979a87
    - e80d2d18-0be8-11ed-91c9-7c8ae1979a87
    - e80d2d19-0be8-11ed-ac1e-7c8ae1979a87
    - e80d2d1a-0be8-11ed-ba2f-7c8ae1979a87
    valid:
    - e80d2d08-0be8-11ed-80fe-7c8ae1979a87
    - e80d2d09-0be8-11ed-b1fc-7c8ae1979a87
    - e80d2d0a-0be8-11ed-93a1-7c8ae1979a87
    - e80d2d0b-0be8-11ed-b4a5-7c8ae1979a87
unique_attribute:
- name
- temp
