imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - o6zqggyqdr
    - j2psmq7bf7
    - oo46o3xt43
    - hajas50u0i
    - jhn4wv4na9
    - 4yaxs1ry7p
    - di1jzijez7
    - 5cxwx3y82m
    - 9p9mfu07og
    - k65aiy85kk
    - dr9tqyemkq
    - rj8iwueutk
    - 7cdsrt94l5
    - zgu4islpt0
    - irmcv2p5p0
    valid:
    - td3x57dcnw
    - 3rn530xywy
    - 7zztumwq3v
    - rzdka9y3nx
  type: string
- attribute: temp
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -746
    - -959
    - 124
    - -644
    - -214
    - 374
    - -577
    - 82
    - -171
    - -276
    - 485
    - 618
    - -62
    - -8
    - -19
    valid:
    - 584
    - 634
    - -529
    - 336
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - 659.053733042753
    - 91.88403435668613
    - 263.96083545796756
    - 238.34641600565843
    - 837.3374610477138
    - 62.32031611304981
    - -942.994334373159
    - -147.13889968763883
    - 770.3492566753991
    - -948.543273578449
    - -548.7792195214039
    - 705.8106964878438
    - 271.5789129869211
    - -831.5030382251954
    - 624.5002109974238
    valid:
    - 517.9374974717994
    - -349.2415987501051
    - -83.17024941765625
    - -557.6707867734283
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 276.256.288.298
    multiple_valids: &id002
    - 102.205.128.29
    - 102.205.225.88
    - 102.205.199.165
    - 102.205.120.111
    - 102.205.148.108
    - 102.205.135.71
    - 102.205.76.201
    - 102.205.214.47
    - 102.205.205.125
    - 102.205.241.90
    - 102.205.147.122
    - 102.205.144.46
    - 102.205.250.97
    - 102.205.172.26
    - 102.205.187.59
    valid: &id003
    - 102.205.128.29
    - 102.205.225.88
    - 102.205.199.165
    - 102.205.120.111
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 58416
    - 58046
    - 3964
    - 43315
    - 1416
    - 50135
    - 37192
    - 31539
    - 35403
    - 58406
    - 44023
    - 55824
    - 46527
    valid:
    - 1
    - 65535
    - 19130
    - 13038
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      type: string
    type: schema
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - gai83nvj7n
    - 3tfsdfzpbl
    - gln04mwfv8
    - kdwu7qhoa9
    - q7yt69q6kw
    - ygi8v1c1qe
    - dlmeasnfv6
    - tvewcrhinz
    - jule5br1gw
    - j7dnusy6t9
    - w5cmlg3x8w
    - eyiraonu1s
    - m1saey2z6o
    - ipmahw1lif
    - isho3er3tf
    valid:
    - 2wfmyxu44q
    - 7fymbz79jb
    - eb70eup3e7
    - 77zbzxz9mw
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 60
    - 28
    - 62
    - 56
    - 40
    - 24
    - 88
    - 32
    - 45
    - 40
    - 2
    - 67
    valid:
    - 1
    - 100
    - 50
    - 78
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - yprysen0r0
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 7
    - 3
    - 2
    - 21
    - 27
    - 3
    - 26
    - 21
    - 9
    - 28
    - 25
    - 5
    valid:
    - 0
    - 32
    - 16
    - 19
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 37.84965571972133
    - 97.62913062498487
    - 85.6279401634932
    - 59.461403229611854
    - 57.89964889155733
    - 56.37982990084091
    - 71.57013792103602
    - 33.60252762510597
    - 73.65912440300049
    - 76.51693284914289
    - 89.07739487160481
    - 71.1579542599886
    valid:
    - 0
    - 100
    - 50.0
    - 84.86998218385702
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 246
    - 870
    - 583
    - -623
    - -281
    - -202
    - 351
    - 854
    - -1
    - 431
    - 676
    - 261
    - 832
    - 567
    - 224
    valid:
    - -449
    - 749
    - 66
    - -39
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 9638i8fxmt
        - 0txucegldy
        - i4d73gla3r
        - kjhevuvvi8
        - zxpnnognda
        - vrob8v2bc6
        - ibrllnvuza
        - cews0bklus
        - 9lbsny7hw7
        - 0unh37rckd
        - 5wkkoge8xv
        - 3nf523i2rl
        - 6l5myxsg7f
        - yrcoe0bm0y
        - 9gso7w0dyp
        valid:
        - zevb1qincz
        - gnx4y8fdk8
        - 02ltrmjbij
        - 84kco7maij
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - ek68pz3k2m
        - vyzbnykd1g
        - espokn62w0
        - qpjkwfrv3p
        - 21d9dtaz0y
        - avk2p3jqwo
        - nvjauefnpf
        - ut7i5ozmmv
        - 3ruyz1xme6
        - e0t378xm8y
        - y64hxequdo
        - iliio1n3kf
        - w9wfomx19p
        - xriz0xzm9b
        - 4lvyxg34v4
        valid:
        - skm56c2h2h
        - 67zs1zi4yt
        - 1kxakyznnq
        - bsmtajnhez
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - v5y91tl9r1
        - oa03fiib0n
        - dmv935mtf1
        - bzqyrxtk39
        - hgtx6g9b9o
        - spy230lxpl
        - 8t8lccpbmw
        - 39au9l6ott
        - fi7y2jdv01
        - cr67b5kcv9
        - 29uu9hi0fc
        - 3hnsjj81zv
        - p2ejvo46r9
        - i9w9xexaad
        - ytun9llwhq
        valid:
        - 9dpng02czx
        - kyz16dv26d
        - g9b2491qo2
        - 001r3ezoga
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - n5vp68bg92
            - hwmldifnlb
            - wl1515f27n
            - czwnk9whmf
            - 4dc05xjkcu
            - lznf4ba3dm
            - 4ecqafh3ft
            - immimfv9bc
            - 938u7wanzm
            - eokepluf6s
            - bqorxdisx6
            - gsiuq2y9qw
            - objh12k95p
            - f2blkicfe3
            - qejwdxm9qp
            valid:
            - qpplrnif7f
            - a9y9h0ollo
            - 1zj7hw87mw
            - b0urgp2gqx
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - bukb7on99d
            - yo0y7c0zg6
            - ghxhxzhc1n
            - pmyt6fx4md
            - fzbxzyy83x
            - t1yf4r8uhi
            - nauz7dip46
            - hdvwsj2loa
            - r1l4zq0k85
            - z3i6j9jygi
            - xe2bc5sdni
            - 0qj9j422eq
            - 1e1hnescjg
            - 8gu19p3f1t
            - zqcs7nnyr7
            valid:
            - ce3gbgha23
            - xh74jxtu33
            - hkgrqqucxx
            - a3zgr3r5t6
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f3c6
            - 2001:db8::34f4:0:0:f3e8
            - 2001:db8::34f4:0:0:f3bd
            - 2001:db8::34f4:0:0:f3f1
            - 2001:db8::34f4:0:0:f3ce
            - 2001:db8::34f4:0:0:f348
            - 2001:db8::34f4:0:0:f394
            - 2001:db8::34f4:0:0:f32f
            - 2001:db8::34f4:0:0:f3be
            - 2001:db8::34f4:0:0:f3c9
            - 2001:db8::34f4:0:0:f3da
            - 2001:db8::34f4:0:0:f330
            - 2001:db8::34f4:0:0:f382
            - 2001:db8::34f4:0:0:f344
            - 2001:db8::34f4:0:0:f339
            valid: &id006
            - 2001:db8::34f4:0:0:f3c6
            - 2001:db8::34f4:0:0:f3e8
            - 2001:db8::34f4:0:0:f3bd
            - 2001:db8::34f4:0:0:f3f1
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - 0jc3jmuxxb
            - rten8yehtl
            - 3xfsu2n1mt
            - si7wsn1dr2
            - df0pvq9kco
            - rtxvfazqi4
            - ltadlrx2cv
            - 02mmfczllu
            - a24tiay9wh
            - zu7x5k8zso
            - cl05msg63s
            - aht8vhko7u
            - s5rica1iqj
            - z78goi63p8
            - 5quj9oomzd
            valid:
            - ykncyrm0xu
            - vfb95jmqkj
            - uq0v5pg7ta
            - tluthmdls3
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - ZWFpczdxeW90OA==
    - bTB0YWk1Y2ZqbQ==
    - ZGdsOWNsZTF4ag==
    - bGpwdjcxZTMwbA==
    - bWI4d3Z1OGdiMQ==
    - ZTJ0YmZwMXAwdQ==
    - dG8yYjcwNDF4bg==
    - cmowcGRxZ3A4Ng==
    - cWk3eWh6cjExdA==
    - cWxjbWR0ZjRkOA==
    - OGRwZHE4cDE1OQ==
    - M3BvbmNhanh1Mw==
    - NG1rbzcxM2x2YQ==
    - N3p3OWNvdXNiNw==
    - bDYyOW8xdzgwZA==
    valid:
    - N2FnczR3N29rcg==
    - NHEwcnluMjhwMQ==
    - OHViYnMwOXB6MQ==
    - NWVhMXNjY3l4MA==
  cidr:
    invalid:
    - 272.272.278.258/31
    multiple_valids:
    - 102.205.144.0/20
    - 102.205.192.0/20
    - 102.205.112.0/20
    - 102.205.80.0/20
    - 102.205.0.0/20
    - 102.205.64.0/20
    - 102.205.160.0/20
    - 102.205.176.0/20
    - 102.205.224.0/20
    - 102.205.48.0/20
    - 102.205.16.0/20
    - 102.205.240.0/20
    - 102.205.208.0/20
    - 102.205.32.0/20
    - 102.205.128.0/20
    valid:
    - 102.205.144.0/20
    - 102.205.192.0/20
    - 102.205.112.0/20
    - 102.205.80.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - b6:b1:2e:fc:b7:41
    - 6a:0d:71:96:b6:a2
    - 80:8d:94:9d:4c:e5
    - 15:24:7f:13:29:45
    - 39:e3:b2:32:8e:89
    - 58:e8:a6:65:8a:fc
    - c9:d1:7e:45:0d:8d
    - 33:c4:be:65:46:c4
    - f5:c3:3c:de:ba:14
    - aa:5e:ed:40:1b:b6
    - 82:65:b2:2d:a8:6e
    - 8f:86:5a:41:24:a2
    - b5:43:1d:dd:8f:37
    - 9e:16:19:be:86:06
    - 67:e4:80:ea:fb:ec
    valid:
    - 0a:75:84:6d:2d:f0
    - e9:f1:94:24:49:f0
    - e9:97:89:c2:ef:d6
    - 05:e1:80:0a:c2:2b
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 3mfxw0ubbr
    - waqz2d4e2c
    - yqyasc7cbl
    - 5u50lue1jf
    - dd6smrhfqz
    - t0yv1hgs4y
    - jxsrz6iejl
    - zdu0xj8cvt
    - zm2mxjp3zq
    - hvmtizj78r
    - s4bpzb9heg
    - gryg2ljc8h
    - 1oft8m8bc6
    - kpwxprg7jv
    - 4zq1au3q43
    valid:
    - 4byh40cqig
    - wo2u8bji0h
    - uu326935eb
    - 6x1ds7960x
  time:
    invalid:
    - '2022-08-02 10:47:49.519019'
    multiple_valids:
    - '2022-08-02T05:17:49.519019+00:00'
    - '2022-08-25T05:17:49.519019+00:00'
    - '2022-09-17T05:17:49.519019+00:00'
    - '2022-10-10T05:17:49.519019+00:00'
    - '2022-11-02T05:17:49.519019+00:00'
    - '2022-11-25T05:17:49.519019+00:00'
    - '2022-12-18T05:17:49.519019+00:00'
    - '2023-01-10T05:17:49.519019+00:00'
    - '2023-02-02T05:17:49.519019+00:00'
    - '2023-02-25T05:17:49.519019+00:00'
    - '2023-03-20T05:17:49.519019+00:00'
    - '2023-04-12T05:17:49.519019+00:00'
    - '2023-05-05T05:17:49.519019+00:00'
    - '2023-05-28T05:17:49.519019+00:00'
    - '2023-06-20T05:17:49.519019+00:00'
    valid:
    - '2022-08-02T05:17:49.519019+00:00'
    - '2022-08-25T05:17:49.519019+00:00'
    - '2022-09-17T05:17:49.519019+00:00'
    - '2022-10-10T05:17:49.519019+00:00'
  url-http:
    invalid:
    - ht:/4xz659pxt4fzemy.com
    multiple_valids:
    - http://v3eixo4mtpxs5d0.com
    - http://t655twu6qutgu7a.com
    - http://xxp2kyses70ldn3.com
    - http://vep5lztw6r33ycj.com
    - http://kz4rt9wy2zqw1pf.com
    - http://3u4f8qfr901ft5u.com
    - http://uu1aedkb48rdatg.com
    - http://7uk6t4d1zjfo5cn.com
    - http://wwbkmdi3z49e3re.com
    - http://kpk7g5zpf7vdm0b.com
    - http://kzipkoga0jn9tat.com
    - http://e7y2bnsoidshu1s.com
    - http://1qfiqt9cu9zbtw7.com
    - http://8bg36hvtfoyasit.com
    - http://jdszhttopxhaa2b.com
    valid:
    - http://93ykxbagwsl7i7q.com
    - http://j69x1gjye4htp7v.com
    - http://8cgbi93xbqnncn6.com
    - http://nq5b9fldezko2ty.com
  url-https:
    invalid:
    - hts:/cein6rqz8k9pej9.com
    multiple_valids:
    - https://8u9jrvbwv0bg37o.com
    - https://kqcig8kgnkaff97.com
    - https://5vv188xg7pr3s5z.com
    - https://8ql9skowgfuph3h.com
    - https://aoc6nh4rlg0n73f.com
    - https://wm8uojh40b7eqq8.com
    - https://cmfa2613g794hu8.com
    - https://7fnajgjqsfwcghz.com
    - https://vwmertdf58csv8c.com
    - https://7w0rl3122iaorss.com
    - https://97jzxsbtsvm2ny2.com
    - https://53jzhnegxr474ld.com
    - https://hun6av1e59t8ehl.com
    - https://xx4gr7sw0epwlni.com
    - https://z23q8yi0ygkryuk.com
    valid:
    - https://c3pgpzfk1sqdqfi.com
    - https://qdv3fk3mcz5tw6q.com
    - https://rqmyd97in86z98x.com
    - https://3iismf1qc3lidib.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 738d6eb5-1222-11ed-a039-dc214861057a
    - 738d6eb6-1222-11ed-bbf6-dc214861057a
    - 738d6eb7-1222-11ed-a61e-dc214861057a
    - 738d6eb8-1222-11ed-bcca-dc214861057a
    - 738d6eb9-1222-11ed-ad81-dc214861057a
    - 738d6eba-1222-11ed-b18f-dc214861057a
    - 738d6ebb-1222-11ed-ad19-dc214861057a
    - 738d6ebc-1222-11ed-910c-dc214861057a
    - 738d6ebd-1222-11ed-be48-dc214861057a
    - 738d6ebe-1222-11ed-a87e-dc214861057a
    - 738d6ebf-1222-11ed-99c1-dc214861057a
    - 738d6ec0-1222-11ed-a69c-dc214861057a
    - 738d6ec1-1222-11ed-92d7-dc214861057a
    - 738d6ec2-1222-11ed-93da-dc214861057a
    - 738d6ec3-1222-11ed-926f-dc214861057a
    valid:
    - 738d6eb1-1222-11ed-b31d-dc214861057a
    - 738d6eb2-1222-11ed-8f58-dc214861057a
    - 738d6eb3-1222-11ed-9361-dc214861057a
    - 738d6eb4-1222-11ed-86ec-dc214861057a
unique_attribute:
- name
- temp
