imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: movie
provider_name: Movies
schemas:
- attribute: title
  description: Title of the Movie
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - kmt5pqt5x3
    - 8jf0empo7a
    - 953ibr8d6g
    - leedhy76jh
    - 19q6ptj0ru
    - awdk1bbgme
    - l253sga41s
    - 4hv00aquy1
    - qyocyxsoba
    - jneo385xmw
    - k6bb697wul
    - 3d4v835o2m
    - 29lxw6jpix
    - xdosbnx8m7
    - 5otmb1jyrr
    valid:
    - 99hhdx4261
    - xb6lfxtirc
    - 8yexn0bmdz
    - eryjhc2mw2
  type: string
- attribute: isbn
  description: ISBN of the Movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 0hk5b7vep9
    - ty13n1gqhd
    - 45y9wsvnak
    - m666vw5a3l
    - xu26vtkxqx
    - 988fo33iz2
    - uxi8jtc48k
    - pp6doah7jn
    - 2v82o1t8ns
    - pyrqqmg4ep
    - z838ywely9
    - e5xcpcg613
    - ybf9a7xlow
    - rm8iu1zpz5
    - t3i91ij5xb
    valid:
    - 5vswb3497c
    - jukmxnfjg1
    - 1oduz5w7x3
    - 89j4quj0a0
  type: string
- attribute: genre
  default: thriller
  description: Genre of the movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - wjtjfxckjx
    multiple_valids:
    - thriller
    - action
    - horror
    - fiction
    - comedy
    valid:
    - thriller
    - action
    - horror
    - fiction
    - comedy
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: false
    params:
    - thriller
    - action
    - horror
    - fiction
    - comedy
- attribute: director
  description: Director of the Movie
  element:
    schema:
    - attribute: firstname
      description: Firstname of the Director
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - hxc5lmvshx
        - qmzenbob8l
        - che65v0jl8
        - ymt3buepbt
        - snl28wnkpg
        - mzaj7w0lxk
        - xmdgx89j93
        - ji4djzta8e
        - bknoox20vz
        - 83sgw6oyjo
        - 65q1x6pc3n
        - f9gceywju1
        - bzmu2negvv
        - fjk9mof25o
        - jebrvmvzmo
        valid:
        - f88siirf52
        - fs0le561cm
        - e1gmp29x4w
        - i4bmof1ybv
      type: string
    - attribute: lastname
      description: Lastname of the Director
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 54tn2jr0xo
        - mox6a23ouj
        - w8jhswkh45
        - 18z3sa9soz
        - gkg3zvstgd
        - tunsek53sf
        - jpuzp01lzo
        - yyd41f8mo3
        - oocfq7k4fw
        - xblx606iho
        - 1pnl9uvsmj
        - 77cyr21ct3
        - 2isvjk7a8s
        - sismvt7xia
        - yfsmr7urht
        valid:
        - vhpny3j0et
        - 395zxb410e
        - so91t4oiw5
        - jv1e3cqrad
      type: string
    type: resource
  max_items: 1
  optional: true
  type: list
- attribute: rating
  element:
    schema:
    - attribute: rater
      description: Rater that provide rating
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - fvjjgy2e3e
        - u3mwebdnof
        - g98yt5ij4o
        - iltatzz75z
        - 0slzlqsnl6
        - 8nmp1i99cx
        - 1ihvxyumy7
        - 93c2twt86j
        - 4t0b71ka7b
        - mj5cnbh5tr
        - bfyn6gtlwu
        - gcnkkqdj0w
        - 2bba5fu8qa
        - 3zbdrxq77p
        - 1lq5xnkyob
        valid:
        - mn5xn7rocx
        - d04xa1lvnz
        - lgiw39iwlk
        - 49d3kw6phn
      type: string
    - attribute: rating
      default: 1
      optional: true
      subtype: range
      test_params:
        invalid:
        - 0
        - 11
        multiple_valids:
        - 1
        - 10
        - 5.5
        - 3.1548733314639033
        - 3.1990321682761347
        - 6.2909868090457755
        - 9.31794082427057
        - 1.7018579478482165
        - 7.1345833196718775
        - 6.568438141110016
        - 3.4925379361942945
        - 3.351440909737909
        - 1.141482412828489
        - 3.641270395452192
        - 6.196542281859955
        valid:
        - 1
        - 10
        - 5.5
        - 9.932782905152834
      type: float
      validation:
        func_name: FloatBetween
        params:
        - 1
        - 10
    type: resource
  optional: true
  type: list
- attribute: casts
  element:
    schema:
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - mw3ikvzoi2
    - 3ifwtxq9hy
    - r5po7u2mz2
    - jv9l9h8j1i
    - igdi8hxltn
    - rf8yu8l3es
    - yzp242g0h9
    - k987l5ol97
    - jf3zz8990u
    - x2waa4cb6w
    - 8l2o0r94lf
    - rpdkmcxd9s
    - 0jr4orojt7
    - xt98f2v5jl
    - p76mdoisi8
    valid:
    - 16at12msla
    - lb22i7ncog
    - 59qsm9duwb
    - 1fdst3lgrk
  type: set
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - eDNnMnlyNnphcQ==
    - b253NDZ2MGc0dQ==
    - bnczMmtyYWNycQ==
    - NHY2ZG9wcXNmOA==
    - dzhpYmk2aGh6ZQ==
    - eW9oZ21tZzVqdw==
    - cGdrcHZnaDdhOA==
    - MjB0a3RrYjhqbA==
    - Ynk4Nm10aWxjaQ==
    - eGpjZDdneGxpcg==
    - MXlqbnVrazAzYQ==
    - cjA4dmc2OWtsbQ==
    - c2U3ajZleDd3eA==
    - bzQ1NGpndDYyMg==
    - dGpkaW9vZHRyag==
    valid:
    - MTdoM2p1dHN6eg==
    - bXFvczE1ZDhpNQ==
    - Z3dwejhoYWlyYQ==
    - MWkzbGRrbWlhOA==
  cidr:
    invalid:
    - 292.265.287.296/9
    multiple_valids:
    - 50.202.0.0/20
    - 50.202.160.0/20
    - 50.202.112.0/20
    - 50.202.96.0/20
    - 50.202.192.0/20
    - 50.202.80.0/20
    - 50.202.240.0/20
    - 50.202.176.0/20
    - 50.202.32.0/20
    - 50.202.64.0/20
    - 50.202.224.0/20
    - 50.202.128.0/20
    - 50.202.144.0/20
    - 50.202.16.0/20
    - 50.202.48.0/20
    valid:
    - 50.202.0.0/20
    - 50.202.160.0/20
    - 50.202.112.0/20
    - 50.202.96.0/20
  ipv4:
    invalid:
    - 263.292.280.276
    multiple_valids:
    - 50.202.22.91
    - 50.202.178.89
    - 50.202.200.166
    - 50.202.9.1
    - 50.202.177.115
    - 50.202.162.151
    - 50.202.195.48
    - 50.202.128.78
    - 50.202.211.161
    - 50.202.187.5
    - 50.202.235.85
    - 50.202.195.230
    - 50.202.89.192
    - 50.202.78.166
    - 50.202.29.66
    valid:
    - 50.202.22.91
    - 50.202.178.89
    - 50.202.200.166
    - 50.202.9.1
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f36d
    - 2001:db8::34f4:0:0:f342
    - 2001:db8::34f4:0:0:f31b
    - 2001:db8::34f4:0:0:f331
    - 2001:db8::34f4:0:0:f3e5
    - 2001:db8::34f4:0:0:f3d6
    - 2001:db8::34f4:0:0:f310
    - 2001:db8::34f4:0:0:f31e
    - 2001:db8::34f4:0:0:f368
    - 2001:db8::34f4:0:0:f3a4
    - 2001:db8::34f4:0:0:f3e0
    - 2001:db8::34f4:0:0:f341
    - 2001:db8::34f4:0:0:f36c
    - 2001:db8::34f4:0:0:f334
    - 2001:db8::34f4:0:0:f376
    valid:
    - 2001:db8::34f4:0:0:f36d
    - 2001:db8::34f4:0:0:f342
    - 2001:db8::34f4:0:0:f31b
    - 2001:db8::34f4:0:0:f331
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 64:32:7c:07:5c:a2
    - 8e:1b:a9:d7:89:a7
    - 03:00:7e:ef:a8:0d
    - fb:7f:44:55:90:70
    - d0:7b:35:03:45:07
    - a6:88:b8:b0:2d:10
    - 61:f1:e9:6f:f1:12
    - 17:c2:88:d9:aa:65
    - ec:de:71:17:37:ba
    - a9:20:71:e2:9f:1a
    - 66:21:69:ed:0e:a8
    - 93:f3:05:cc:1b:fa
    - 01:cb:2c:fe:4b:19
    - e2:94:33:79:1f:ea
    - 21:23:44:6c:97:47
    valid:
    - 07:34:04:74:0a:5a
    - 63:e2:c9:58:b3:ca
    - c5:2a:48:74:91:e0
    - ab:7b:7b:21:f0:2a
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - bup3mxnpw8
    - 06zxwbl4ig
    - hgm77fs0gk
    - 0tdtc001ll
    - s9krtlmlta
    - ldlb7e4w6t
    - 53rvuip1k5
    - b42t1cpnes
    - ht1juc5a9b
    - 34nd9j3ry2
    - yyn0ippo9r
    - up5p42b79j
    - b5u0bspk58
    - okiczqvdah
    - 86m8q9vs1p
    valid:
    - 77cncyr2ld
    - 7dx649x3wp
    - gsrlzeudkh
    - jv3d254z1k
  time:
    invalid:
    - '2022-07-26 11:01:29.245998'
    multiple_valids:
    - '2022-07-26T05:31:29.245998+00:00'
    - '2022-08-18T05:31:29.245998+00:00'
    - '2022-09-10T05:31:29.245998+00:00'
    - '2022-10-03T05:31:29.245998+00:00'
    - '2022-10-26T05:31:29.245998+00:00'
    - '2022-11-18T05:31:29.245998+00:00'
    - '2022-12-11T05:31:29.245998+00:00'
    - '2023-01-03T05:31:29.245998+00:00'
    - '2023-01-26T05:31:29.245998+00:00'
    - '2023-02-18T05:31:29.245998+00:00'
    - '2023-03-13T05:31:29.245998+00:00'
    - '2023-04-05T05:31:29.245998+00:00'
    - '2023-04-28T05:31:29.245998+00:00'
    - '2023-05-21T05:31:29.245998+00:00'
    - '2023-06-13T05:31:29.245998+00:00'
    valid:
    - '2022-07-26T05:31:29.245998+00:00'
    - '2022-08-18T05:31:29.245998+00:00'
    - '2022-09-10T05:31:29.245998+00:00'
    - '2022-10-03T05:31:29.245998+00:00'
  url-http:
    invalid:
    - ht:/uktc8mjq5uxpx8c.com
    multiple_valids:
    - http://i6i3dmb6t7kqbx9.com
    - http://pzr9z7cvbe9zrih.com
    - http://qk2qha38deku6uh.com
    - http://iu19jt77nz243xa.com
    - http://03uj1aoqa8so4p8.com
    - http://xftd8zwk8ddbsk1.com
    - http://jdokcyrs5htr6sv.com
    - http://jre2blemfbzp7nm.com
    - http://2mm7bm55rzi8p5d.com
    - http://borp32sihf25gzg.com
    - http://lr7d0d7uzcliea0.com
    - http://ig1wbbumy3oo51v.com
    - http://b04m08t6afkqnja.com
    - http://4jtpsrp2b1xvu33.com
    - http://zl75eit7howszoo.com
    valid:
    - http://vw1i83nacfef3f2.com
    - http://45kxchm8yvihf2j.com
    - http://m22la164976wxwu.com
    - http://o69s94nruq3knot.com
  url-https:
    invalid:
    - hts:/1uju8qsy2dq7136.com
    multiple_valids:
    - https://451oppyyd4d0ums.com
    - https://d2x53cop9hjt83f.com
    - https://6ybbb4ygpz6rxq1.com
    - https://wwmuvwmhv9resqs.com
    - https://m3ox2e0d92ntb8x.com
    - https://7u6773j86xyqpbi.com
    - https://ot4jezxn8as7cwp.com
    - https://sou3cflbr6rrenw.com
    - https://e5iv68hiew27lit.com
    - https://ukt8f81xtbda6fs.com
    - https://6d0j6fizmx9oh7m.com
    - https://7tei1pwz77ic60q.com
    - https://9vzdwa3i2v86fny.com
    - https://qpwh5tu5i72nxzy.com
    - https://7pe0mljwtr6yevy.com
    valid:
    - https://54670six3cgbs0g.com
    - https://d83bzmtqsx16fdr.com
    - https://suipxnnab0nhbcd.com
    - https://3qru831bx1bk2tj.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 334197d1-0ca4-11ed-9c3b-7c8ae1979a87
    - 334197d2-0ca4-11ed-9b52-7c8ae1979a87
    - 334197d3-0ca4-11ed-88c0-7c8ae1979a87
    - 334197d4-0ca4-11ed-9030-7c8ae1979a87
    - 334197d5-0ca4-11ed-8e88-7c8ae1979a87
    - 334197d6-0ca4-11ed-abd0-7c8ae1979a87
    - 334197d7-0ca4-11ed-8717-7c8ae1979a87
    - 334197d8-0ca4-11ed-a505-7c8ae1979a87
    - 334197d9-0ca4-11ed-ab6d-7c8ae1979a87
    - 334197da-0ca4-11ed-ada8-7c8ae1979a87
    - 334197db-0ca4-11ed-bff1-7c8ae1979a87
    - 334197dc-0ca4-11ed-8473-7c8ae1979a87
    - 334197dd-0ca4-11ed-a27e-7c8ae1979a87
    - 334197de-0ca4-11ed-8f29-7c8ae1979a87
    - 334197df-0ca4-11ed-a491-7c8ae1979a87
    valid:
    - 334197cd-0ca4-11ed-b0a0-7c8ae1979a87
    - 334197ce-0ca4-11ed-9734-7c8ae1979a87
    - 334197cf-0ca4-11ed-93bd-7c8ae1979a87
    - 334197d0-0ca4-11ed-abc0-7c8ae1979a87
unique_attribute:
- title
