imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: movie
provider_name: Movies
schemas:
- attribute: title
  description: Title of the Movie
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ob0ltflto3
    - v8roaufxtx
    - lbzhdtpbmp
    - ak16ikax65
    - y2ial7u17p
    - jyo2eb8nnp
    - skhm9lawbg
    - c6qywudjkw
    - vpro67zaay
    - v1j0bx9o3h
    - beu3bcxgcc
    - 0okzjjqg4q
    - l4jdcd6dtm
    - nafmob8y82
    - 1nkd9rmbug
    valid:
    - mdrne172y8
    - ojztrgecbb
    - bnvph6wxvh
    - 1t1zn1ct4c
  type: string
- attribute: isbn
  description: ISBN of the Movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - qglswcuk13
    - ohe9z57k97
    - na86d6wawj
    - fre2pr5806
    - w5fgwz1qfm
    - bagknn6o7h
    - eyabkuowaa
    - p3wul03qmn
    - cogziylw6i
    - rl4e6b32jo
    - dadcvjicar
    - bezaw4dvul
    - xf2ptzua02
    - yt25b5oxm4
    - yp73qemmeg
    valid:
    - 0xzc62f8ls
    - xpw06eocsz
    - dn6mcsw3vf
    - 9ldyymplg0
  type: string
- attribute: genre
  default: thriller
  description: Genre of the movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - pdk963p6e9
    multiple_valids:
    - thriller
    - action
    - horror
    - fiction
    - comedy
    valid:
    - thriller
    - action
    - horror
    - fiction
    - comedy
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: false
    params:
    - thriller
    - action
    - horror
    - fiction
    - comedy
- attribute: director
  description: Director of the Movie
  element:
    schema:
    - attribute: firstname
      description: Firstname of the Director
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - a8yb8tmpce
        - ovk7za4mjc
        - 5wxsykar4l
        - 4l32vpfjmu
        - xqfu9jc2ui
        - oqqkzy6n3j
        - ogk9ln6v34
        - k3tymui9f8
        - izattc2hnc
        - hhb6xepfwj
        - 7su7v18gfm
        - 1hl0hv9ma7
        - 8brqb3xlyy
        - k5q4zj0ilh
        - cxpundh3mz
        valid:
        - j2ncbixwyy
        - sfzi9uxubl
        - l4i646l8fu
        - v7qv3bze7d
      type: string
    - attribute: lastname
      description: Lastname of the Director
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 8svw0irj0n
        - 3yehyh9jkr
        - jkb7bwg664
        - n6vgwooaw6
        - 6js4ywpq2h
        - ps7s2bjml7
        - mpxugvdgof
        - 1whjxzw62h
        - swldj74c6a
        - p8v65ycu9j
        - r9txdk8su3
        - rs3p8fwypt
        - fwgt86rbwk
        - d9wn9sohpx
        - 8l9k9z7nd1
        valid:
        - hnv9m5kbxv
        - 6qk6zicobp
        - rsv3wvxhk0
        - yv1kghv2tn
      type: string
    type: resource
  max_items: 1
  optional: true
  type: list
- attribute: rating
  element:
    schema:
    - attribute: rater
      description: Rater that provide rating
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - nw3mazocku
        - uihez42vt0
        - ojz3zjhl0k
        - rpja8qpt5p
        - xse54c5qvc
        - 0ygqcdj1hw
        - gb0ypqpdd2
        - wtilvln91d
        - qps0ch2zdy
        - ql7y59jtr0
        - qsul78g4g3
        - q24xt1cqnq
        - d2rp5mbb0u
        - e13f9dncu8
        - ohjvlf3xw1
        valid:
        - tyam7jq9tg
        - 0d68zq3mgm
        - fru3jgz7fp
        - jvsmvaiys4
      type: string
    - attribute: rating
      default: 1
      optional: true
      subtype: range
      test_params:
        invalid:
        - 0
        - 11
        multiple_valids:
        - 1
        - 10
        - 5.5
        - 5.88864319712869
        - 3.30047352771708
        - 5.931623106206509
        - 2.7583784252828636
        - 6.674745501939268
        - 1.3035616671302068
        - 9.384990519712265
        - 9.433761189444018
        - 4.519737805457349
        - 1.4172843297613316
        - 9.42110534922723
        - 3.8649940589778327
        valid:
        - 1
        - 10
        - 5.5
        - 9.086049142732044
      type: float
      validation:
        func_name: FloatBetween
        params:
        - 1
        - 10
    type: resource
  optional: true
  type: list
- attribute: casts
  element:
    schema:
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - a6yinlhm7v
    - pbouip1jiv
    - rbz621s3q8
    - yg3orimhoq
    - nih3ygqba8
    - cdgnk53c14
    - eeblrzfkod
    - xf1fvufpbq
    - 8x174nfwvu
    - 7tclo3l4ct
    - k9hszawu5h
    - 77catc4e25
    - 7darv5adp1
    - yyl4noe9h6
    - 234qri61el
    valid:
    - hzzlml5pq6
    - s42x5qqtq0
    - 1f3zasw504
    - xwhbe9gr0z
  type: set
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - djY4ZmVyejd2NA==
    - ODZmaGkwNjU5cw==
    - aXRhOTJuMm05cQ==
    - bHk5dnk2dmgzbA==
    - ZGJuY21pbThxZA==
    - a25ycHZxYmU4dA==
    - dXpxNnB0MXExOQ==
    - aDkyYjNqeHlucQ==
    - d2N6YWlxeXJseg==
    - YWx5anduNTN3ag==
    - dGt5bjFvYzZzNg==
    - ZnprNWlrYjl2bQ==
    - NzBxNHBiMjcxcg==
    - cGM4dXhycXgybQ==
    - bXJsbzhsZ3FxYw==
    valid:
    - dmVtZGtxcHVocQ==
    - OW8wNHR0ejhibQ==
    - eHMwamRvMndzMA==
    - N3FveTNrenI4eA==
  cidr:
    invalid:
    - 257.282.286.263/1
    multiple_valids:
    - 128.230.16.0/20
    - 128.230.224.0/20
    - 128.230.48.0/20
    - 128.230.96.0/20
    - 128.230.32.0/20
    - 128.230.160.0/20
    - 128.230.208.0/20
    - 128.230.64.0/20
    - 128.230.112.0/20
    - 128.230.128.0/20
    - 128.230.240.0/20
    - 128.230.0.0/20
    - 128.230.176.0/20
    - 128.230.80.0/20
    - 128.230.192.0/20
    valid:
    - 128.230.16.0/20
    - 128.230.224.0/20
    - 128.230.48.0/20
    - 128.230.96.0/20
  ipv4:
    invalid:
    - 287.279.292.273
    multiple_valids:
    - 128.230.33.109
    - 128.230.63.168
    - 128.230.104.121
    - 128.230.148.5
    - 128.230.27.206
    - 128.230.74.158
    - 128.230.105.224
    - 128.230.48.207
    - 128.230.181.173
    - 128.230.40.220
    - 128.230.137.188
    - 128.230.85.157
    - 128.230.175.195
    - 128.230.142.227
    - 128.230.230.204
    valid:
    - 128.230.33.109
    - 128.230.63.168
    - 128.230.104.121
    - 128.230.148.5
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f3b0
    - 2001:db8::34f4:0:0:f384
    - 2001:db8::34f4:0:0:f3c6
    - 2001:db8::34f4:0:0:f3cb
    - 2001:db8::34f4:0:0:f36a
    - 2001:db8::34f4:0:0:f315
    - 2001:db8::34f4:0:0:f369
    - 2001:db8::34f4:0:0:f325
    - 2001:db8::34f4:0:0:f301
    - 2001:db8::34f4:0:0:f35f
    - 2001:db8::34f4:0:0:f3a1
    - 2001:db8::34f4:0:0:f3aa
    - 2001:db8::34f4:0:0:f3c8
    - 2001:db8::34f4:0:0:f3f7
    - 2001:db8::34f4:0:0:f33e
    valid:
    - 2001:db8::34f4:0:0:f3b0
    - 2001:db8::34f4:0:0:f384
    - 2001:db8::34f4:0:0:f3c6
    - 2001:db8::34f4:0:0:f3cb
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 39:0c:8a:18:9b:75
    - 82:82:3d:38:76:18
    - 2a:7b:e3:4e:b6:e1
    - 66:4b:0e:22:d9:b9
    - 8c:3d:f5:79:27:17
    - 07:86:f8:ed:91:f1
    - ca:90:82:4f:e5:5a
    - f3:47:65:3b:84:61
    - cf:28:db:e9:10:3a
    - ea:a0:c4:59:20:96
    - 5b:fd:bc:94:a8:f6
    - 52:64:7b:94:e5:2f
    - 24:74:c4:b9:7d:72
    - 89:bc:d4:28:c1:17
    - d8:fd:58:22:7c:6b
    valid:
    - d2:5c:8d:f8:78:2e
    - 25:e9:f5:8b:d5:55
    - 77:a7:0d:b0:cc:ee
    - 7e:1d:5a:e0:5c:3d
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - h7j8bn88tf
    - qaq85kg6vl
    - a0iegkq9s9
    - 78i6nyzs6e
    - rf7hclje62
    - cs1hp749uy
    - 3yjc3dgfz9
    - cqy0bkal0b
    - 49gbko5gup
    - uxjmaf75kd
    - fm2x2gu7la
    - 5m67fhcmb7
    - y7xsgrdwug
    - dztcvpqrwh
    - 59f7tkmkwx
    valid:
    - kqgyjmgmnf
    - 6d17b5toxm
    - lgrv4awlhc
    - xqyspwie30
  time:
    invalid:
    - '2022-07-25 12:40:47.671170'
    multiple_valids:
    - '2022-07-25T07:10:47.671170+00:00'
    - '2022-08-17T07:10:47.671170+00:00'
    - '2022-09-09T07:10:47.671170+00:00'
    - '2022-10-02T07:10:47.671170+00:00'
    - '2022-10-25T07:10:47.671170+00:00'
    - '2022-11-17T07:10:47.671170+00:00'
    - '2022-12-10T07:10:47.671170+00:00'
    - '2023-01-02T07:10:47.671170+00:00'
    - '2023-01-25T07:10:47.671170+00:00'
    - '2023-02-17T07:10:47.671170+00:00'
    - '2023-03-12T07:10:47.671170+00:00'
    - '2023-04-04T07:10:47.671170+00:00'
    - '2023-04-27T07:10:47.671170+00:00'
    - '2023-05-20T07:10:47.671170+00:00'
    - '2023-06-12T07:10:47.671170+00:00'
    valid:
    - '2022-07-25T07:10:47.671170+00:00'
    - '2022-08-17T07:10:47.671170+00:00'
    - '2022-09-09T07:10:47.671170+00:00'
    - '2022-10-02T07:10:47.671170+00:00'
  url-http:
    invalid:
    - ht:/g1ah9hr56l6pkdz.com
    multiple_valids:
    - http://v1nsj1btro87uxf.com
    - http://0vjruwhxexofff2.com
    - http://evhs821yxxn20e3.com
    - http://9sp12imwr5lugwc.com
    - http://7c87vz99tyne2vn.com
    - http://q69urdfakpkr1jb.com
    - http://1g8oe2f96w8lr5c.com
    - http://yr6m2758ncxqa9h.com
    - http://o29khxf2yt8y9nx.com
    - http://zibww6i7rn3q0jj.com
    - http://kn4ezh4vp8chfaw.com
    - http://akce48csfxff3dr.com
    - http://d0i4q9yvwd8kdt0.com
    - http://uovu164updg1xcy.com
    - http://6o1t43meg3jo760.com
    valid:
    - http://np9qy5zh26f1q1j.com
    - http://p12uuu5q6w92tiv.com
    - http://essawpm1c1p4sz8.com
    - http://f7oavh6jxdm7bsn.com
  url-https:
    invalid:
    - hts:/6k583o50q0qib2g.com
    multiple_valids:
    - https://6ntsrpopnur1syh.com
    - https://qom9207b3qg0z5k.com
    - https://akqrw4kfsmzw57z.com
    - https://5v1s2wzo8u0j6it.com
    - https://l60w7jus6a92idw.com
    - https://okuzp2rzo9vp9ov.com
    - https://jq4gvlu5y4lsilh.com
    - https://lnsilxnqsaryw4p.com
    - https://vebqzrghspq7arx.com
    - https://atwlogj043pbjr0.com
    - https://df44y6amj4r1ocr.com
    - https://bmot4mmxc1mhk50.com
    - https://flfpcrq2t85ir86.com
    - https://pbn0k75d0vsi54p.com
    - https://wdmx1juzukcsyk1.com
    valid:
    - https://x8lzwqu6e94q55u.com
    - https://5sqpp37dyvz1keg.com
    - https://ldziuumu8kqe6id.com
    - https://7tpmn45qaz8tb5b.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - e8575f1c-0be8-11ed-a6f9-7c8ae1979a87
    - e8575f1d-0be8-11ed-93c6-7c8ae1979a87
    - e8575f1e-0be8-11ed-9316-7c8ae1979a87
    - e8575f1f-0be8-11ed-9ec2-7c8ae1979a87
    - e8575f20-0be8-11ed-a7e2-7c8ae1979a87
    - e8575f21-0be8-11ed-b7ae-7c8ae1979a87
    - e8575f22-0be8-11ed-a523-7c8ae1979a87
    - e8575f23-0be8-11ed-8eab-7c8ae1979a87
    - e8575f24-0be8-11ed-bdf6-7c8ae1979a87
    - e8575f25-0be8-11ed-a57b-7c8ae1979a87
    - e8575f26-0be8-11ed-8949-7c8ae1979a87
    - e8575f27-0be8-11ed-97e6-7c8ae1979a87
    - e8575f28-0be8-11ed-b26d-7c8ae1979a87
    - e8575f29-0be8-11ed-a4cd-7c8ae1979a87
    - e8575f2a-0be8-11ed-8e58-7c8ae1979a87
    valid:
    - e8575f18-0be8-11ed-b75f-7c8ae1979a87
    - e8575f19-0be8-11ed-a2c5-7c8ae1979a87
    - e8575f1a-0be8-11ed-bb61-7c8ae1979a87
    - e8575f1b-0be8-11ed-9505-7c8ae1979a87
unique_attribute:
- title
