imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: movie
provider_name: Movies
schemas:
- attribute: title
  description: Title of the Movie
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 0c6qftrc96
    - bbhrc37br4
    - 80goza4wjd
    - gwvcxdhqo4
    - 5gv2vg9bfe
    - aecm6wowtm
    - 5iv2sr9fkw
    - nic2cxpef6
    - kehstxdisz
    - 95prn0da6o
    - 0m0inxrmj4
    - u2r8yjceaz
    - 8v2fqiwubq
    - lqi0wottda
    - yojza1gk7k
    valid:
    - bi12ecqdpt
    - g10k8st8vb
    - pbc5lpa7zv
    - 89kb81x19j
  type: string
- attribute: isbn
  description: ISBN of the Movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 4xhypuxr0a
    - pohbsmf1jj
    - knd1buqtwh
    - cnxf4kl54d
    - bf0dfxdnkv
    - xr33nxp9et
    - ubz56az630
    - 93i4cpto5a
    - lh0l4ex925
    - u7nnba14vv
    - fia38wyhgs
    - cktksi74nz
    - 6fp9w11lgy
    - y1riifdhv1
    - 7pn4k1wpuc
    valid:
    - azyc460iya
    - aw7ehffsgm
    - hskw4ucvyw
    - gux2wth09b
  type: string
- attribute: genre
  default: thriller
  description: Genre of the movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - dptxs28keq
    multiple_valids:
    - thriller
    - action
    - horror
    - fiction
    - comedy
    valid:
    - thriller
    - action
    - horror
    - fiction
    - comedy
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: false
    params:
    - thriller
    - action
    - horror
    - fiction
    - comedy
- attribute: director
  description: Director of the Movie
  element:
    schema:
    - attribute: firstname
      description: Firstname of the Director
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - q29z7b76u1
        - 60fyr3rwjv
        - dgnbf621v0
        - fat9fe5ecr
        - 81cqm7dul5
        - qsk5hepagv
        - aimebotl0s
        - p8g4eowow2
        - 0bf6zb7kvn
        - 1lss7qa5ux
        - b40bbt55oe
        - 2gu6fvhv8j
        - sirvu2huey
        - kxlgg6p0h3
        - kecydashlt
        valid:
        - zftu4plj41
        - jmnoi641tu
        - brwkr73bro
        - yehzdarj9w
      type: string
    - attribute: lastname
      description: Lastname of the Director
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - g2oic5k1jm
        - mrub4lowdq
        - 84z2pg2c7f
        - 7n7o06kibo
        - ac7kj6f2sw
        - orv725yvn1
        - 6i9os2mosk
        - ncmngmwcaj
        - ta3gnq8wgb
        - cd9j1svzgz
        - crl3tq3k07
        - gtthzjia2s
        - v9uiexuwa5
        - ns520us2p4
        - kry1bl8zfv
        valid:
        - 3hnq8hd3zd
        - 4ty1gmwgno
        - x9kqu3if9v
        - jtopnnbboz
      type: string
    type: resource
  max_items: 1
  optional: true
  type: list
- attribute: rating
  element:
    schema:
    - attribute: rater
      description: Rater that provide rating
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - tx5k4lhh9d
        - 17rbyxpmt5
        - 3ehbdceu3p
        - zy3m7w9utt
        - 9rlryfmdrj
        - dlmdwowugg
        - nt937yjjt1
        - bxqk432v3x
        - pdo05m8zuk
        - codj3gi3je
        - 1oeoudxz0p
        - eb953zrusx
        - n5tede77oj
        - y5wbdswj2v
        - sgvs2ajgpv
        valid:
        - 5gnta1wnqb
        - 2gep7cbazs
        - km0aqeex6q
        - ago56iho9e
      type: string
    - attribute: rating
      default: 1
      optional: true
      subtype: range
      test_params:
        invalid:
        - 0
        - 11
        multiple_valids:
        - 1
        - 10
        - 5.5
        - 7.277998490999482
        - 3.9296203776369145
        - 9.485619061086568
        - 6.58116251770152
        - 4.796728646838828
        - 9.547192150502617
        - 5.337477873572943
        - 7.39654871199933
        - 3.4940000092597714
        - 1.53492001184281
        - 9.826211541081646
        - 7.142181782247966
        valid:
        - 1
        - 10
        - 5.5
        - 7.195167161442151
      type: float
      validation:
        func_name: FloatBetween
        params:
        - 1
        - 10
    type: resource
  optional: true
  type: list
- attribute: casts
  element:
    schema:
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - hthbqlif3y
    - qpwflvicg8
    - 21utpg7g71
    - 3aho71r880
    - gb30v1bcfh
    - yaynu0td92
    - j6zhwhz9md
    - hp5kheuby9
    - h2eo3iygz4
    - kdje4ud4kf
    - c4r6gznei8
    - bwpg3a3ycy
    - jkdpe9cw3j
    - b7mi57opsi
    - dfpr3x31oe
    valid:
    - jlu3v8in34
    - 95tipep9fm
    - 4iaj0805ah
    - dpmrm73qow
  type: set
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - YmRidnNtdjM0bg==
    - NHVobHM5M2htcw==
    - ZDJvZXh1bnVpNQ==
    - NWljeTMzcHd1cw==
    - d3hmd3B1b25xMQ==
    - azN5b2dsaHIzcw==
    - dHVqMjhsNDcwZw==
    - dWpidHhmZzc2cg==
    - MmVycnkzdG8xdg==
    - cWI3NGhxb3YwYg==
    - aWJzczg2c2Ftaw==
    - aTg1NHN1M3VtNw==
    - aHk1c29xMGVwNw==
    - cHljdXJnaHZqcg==
    - dG1saDVnb2duNA==
    valid:
    - aDBxdHVidzRwZA==
    - eHo1Y2dybDFjNw==
    - d3l1dGpyeDV6ZQ==
    - MXU3NG1ld2d4Mw==
  cidr:
    invalid:
    - 278.285.268.258/0
    multiple_valids:
    - 82.84.48.0/20
    - 82.84.80.0/20
    - 82.84.64.0/20
    - 82.84.96.0/20
    - 82.84.32.0/20
    - 82.84.208.0/20
    - 82.84.16.0/20
    - 82.84.176.0/20
    - 82.84.224.0/20
    - 82.84.0.0/20
    - 82.84.240.0/20
    - 82.84.160.0/20
    - 82.84.144.0/20
    - 82.84.128.0/20
    - 82.84.112.0/20
    valid:
    - 82.84.48.0/20
    - 82.84.80.0/20
    - 82.84.64.0/20
    - 82.84.96.0/20
  ipv4:
    invalid:
    - 270.289.285.297
    multiple_valids:
    - 82.84.92.117
    - 82.84.61.10
    - 82.84.255.163
    - 82.84.5.13
    - 82.84.180.46
    - 82.84.156.158
    - 82.84.210.166
    - 82.84.122.214
    - 82.84.23.88
    - 82.84.222.183
    - 82.84.226.212
    - 82.84.244.212
    - 82.84.34.242
    - 82.84.127.82
    - 82.84.179.128
    valid:
    - 82.84.92.117
    - 82.84.61.10
    - 82.84.255.163
    - 82.84.5.13
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f364
    - 2001:db8::34f4:0:0:f34a
    - 2001:db8::34f4:0:0:f3f3
    - 2001:db8::34f4:0:0:f36b
    - 2001:db8::34f4:0:0:f3df
    - 2001:db8::34f4:0:0:f33b
    - 2001:db8::34f4:0:0:f380
    - 2001:db8::34f4:0:0:f3e7
    - 2001:db8::34f4:0:0:f34b
    - 2001:db8::34f4:0:0:f35a
    - 2001:db8::34f4:0:0:f355
    - 2001:db8::34f4:0:0:f36a
    - 2001:db8::34f4:0:0:f30f
    - 2001:db8::34f4:0:0:f39d
    - 2001:db8::34f4:0:0:f38c
    valid:
    - 2001:db8::34f4:0:0:f364
    - 2001:db8::34f4:0:0:f34a
    - 2001:db8::34f4:0:0:f3f3
    - 2001:db8::34f4:0:0:f36b
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - a7:24:3b:99:29:cd
    - a5:98:e6:5e:4f:9d
    - 93:19:ec:1b:4e:28
    - 69:db:e7:07:83:4d
    - 56:36:0c:36:bf:95
    - 9a:eb:9a:15:13:7c
    - c7:27:1f:46:8b:93
    - e4:66:dc:dd:b3:4e
    - 3d:7d:d0:03:d8:ad
    - 74:b2:1e:6a:c7:9f
    - b5:77:e8:d8:73:dc
    - ac:68:b4:a5:0b:50
    - 90:6c:92:45:3a:09
    - 89:ec:59:22:cd:6f
    - 32:84:f2:fd:39:2b
    valid:
    - 58:34:48:51:82:f1
    - 0b:5e:a1:9e:69:a8
    - 2a:ac:98:5e:4e:c8
    - 69:ec:58:70:7b:f1
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 0a2fr8su1t
    - zfrny7s63o
    - z2gq9hh87r
    - ip6lr1pqt2
    - s7rw2vk2qj
    - xg62e0rwe1
    - 7xw1leu230
    - r0dwzizfyt
    - tzawau72f3
    - 5g8i5hff2d
    - k5q1fxmlm3
    - n1mbnccuj1
    - 8oqsh9kbcn
    - 74i2yj028y
    - nyc84l0drc
    valid:
    - jt7egaj37q
    - 2qglzanvw8
    - nxu3ikfnkf
    - r8cgn0cdb7
  time:
    invalid:
    - '2022-08-01 17:50:40.544214'
    multiple_valids:
    - '2022-08-01T12:20:40.544214+00:00'
    - '2022-08-24T12:20:40.544214+00:00'
    - '2022-09-16T12:20:40.544214+00:00'
    - '2022-10-09T12:20:40.544214+00:00'
    - '2022-11-01T12:20:40.544214+00:00'
    - '2022-11-24T12:20:40.544214+00:00'
    - '2022-12-17T12:20:40.544214+00:00'
    - '2023-01-09T12:20:40.544214+00:00'
    - '2023-02-01T12:20:40.544214+00:00'
    - '2023-02-24T12:20:40.544214+00:00'
    - '2023-03-19T12:20:40.544214+00:00'
    - '2023-04-11T12:20:40.544214+00:00'
    - '2023-05-04T12:20:40.544214+00:00'
    - '2023-05-27T12:20:40.544214+00:00'
    - '2023-06-19T12:20:40.544214+00:00'
    valid:
    - '2022-08-01T12:20:40.544214+00:00'
    - '2022-08-24T12:20:40.544214+00:00'
    - '2022-09-16T12:20:40.544214+00:00'
    - '2022-10-09T12:20:40.544214+00:00'
  url-http:
    invalid:
    - ht:/mpd76tuq1tz5gzr.com
    multiple_valids:
    - http://srmf1ncxpjqslrg.com
    - http://5c072vpbhnhq1if.com
    - http://97yrczq9ik4lckz.com
    - http://cma18kc5ip5csd4.com
    - http://lyue2ttsv5olcb0.com
    - http://91f0nh4iem3yhff.com
    - http://8cluwqx6o2ff6qk.com
    - http://5czz3hpj4eenc4y.com
    - http://uh2t8vc9izkh2x4.com
    - http://0ie4plca3n7ugkg.com
    - http://6cctsd1oe5fwgez.com
    - http://cspdky6o8ukknbr.com
    - http://n3u32p8h2ags7eq.com
    - http://s0c7lnuankp1dpr.com
    - http://7gzcpo109wy3bia.com
    valid:
    - http://yy2py4x1t23c7ym.com
    - http://jso8bkj8aw0mggh.com
    - http://lazng6sp4vuu3bv.com
    - http://8c4u2ayst2bdr1y.com
  url-https:
    invalid:
    - hts:/qy3lx2aewmqx24u.com
    multiple_valids:
    - https://myz8lxyudnebtab.com
    - https://6jidevwzelfakom.com
    - https://a06bk9q2u131dep.com
    - https://1rkjo3j046teynm.com
    - https://7owilb6gdp4g060.com
    - https://5ils0h3kuqqlnph.com
    - https://w8yix6clfeuu6v2.com
    - https://8yeqqn7rzzfum2e.com
    - https://tpcqayi90iraug5.com
    - https://faf850xnujf2xvx.com
    - https://3tf2h6p230lheqa.com
    - https://la802n6fc1qdlr1.com
    - https://83axfjveb9stl1k.com
    - https://xbnbi7m5sqi672a.com
    - https://is385snsxca5m5d.com
    valid:
    - https://4974qu0377qcb79.com
    - https://hf3zj0pjsu31esm.com
    - https://aom7lt9invg50wh.com
    - https://u4ba7n4ypx005tr.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 5b72e668-1194-11ed-a360-dc214861057a
    - 5b72e669-1194-11ed-ad0d-dc214861057a
    - 5b72e66a-1194-11ed-b2d8-dc214861057a
    - 5b72e66b-1194-11ed-b793-dc214861057a
    - 5b72e66c-1194-11ed-b9b5-dc214861057a
    - 5b72e66d-1194-11ed-863a-dc214861057a
    - 5b72e66e-1194-11ed-9ff6-dc214861057a
    - 5b72e66f-1194-11ed-a8bb-dc214861057a
    - 5b72e670-1194-11ed-9532-dc214861057a
    - 5b72e671-1194-11ed-be56-dc214861057a
    - 5b72e672-1194-11ed-a080-dc214861057a
    - 5b72e673-1194-11ed-8979-dc214861057a
    - 5b72e674-1194-11ed-b125-dc214861057a
    - 5b72e675-1194-11ed-8c3e-dc214861057a
    - 5b72e676-1194-11ed-96e4-dc214861057a
    valid:
    - 5b72e664-1194-11ed-8c16-dc214861057a
    - 5b72e665-1194-11ed-b30e-dc214861057a
    - 5b72e666-1194-11ed-a97a-dc214861057a
    - 5b72e667-1194-11ed-86b1-dc214861057a
unique_attribute:
- title
