imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: movie
provider_name: Movies
schemas:
- attribute: title
  description: Title of the Movie
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 1hocnewm5v
    - ylxck3tg5m
    - sy2r78jrbr
    - d6ykke3f0y
    - ll184pgo94
    - x2r0qhg3vm
    - a9pms4dr1s
    - vc9sa5dmhv
    - 4w220onag3
    - e1t2346ntr
    - 1guqff2s50
    - patpjco6m5
    - 03tqobr5r5
    - 9035j55ohv
    - kapme6802k
    valid:
    - tunn413dtj
    - 7nj4b7w22r
    - 909lvtnzh0
    - frydbrwcfi
  type: string
- attribute: isbn
  description: ISBN of the Movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - r3mm4q3bvg
    - 9iwtifzsfy
    - 5z74juwstk
    - z9iohgyz7g
    - urgre26fct
    - kfwyskh21e
    - 49ez2gfb1x
    - qlh9nayz6p
    - 12lbmdszaw
    - 9ow65kp28o
    - u257zlz674
    - xotak97jvz
    - 6zg5v9luj7
    - 7ycin6yp1u
    - ems14yni73
    valid:
    - 5s8k7bj0la
    - mr9u3tlado
    - sajidzvob3
    - xdy154tolt
  type: string
- attribute: genre
  default: thriller
  description: Genre of the movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - bckmav0f6h
    multiple_valids:
    - thriller
    - action
    - horror
    - fiction
    - comedy
    valid:
    - thriller
    - action
    - horror
    - fiction
    - comedy
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: false
    params:
    - thriller
    - action
    - horror
    - fiction
    - comedy
- attribute: director
  description: Director of the Movie
  element:
    schema:
    - attribute: firstname
      description: Firstname of the Director
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - j65m2e7fjf
        - xjdh36ghb2
        - 2g1q6lbfs7
        - a2lg4u9h71
        - t3t209m71f
        - nk9lkb1ug3
        - 8zqxvotwfw
        - i85od8jeuh
        - o0tzwj4od4
        - urq4ddygov
        - v1o6k3nntr
        - rv5y3oo8w4
        - 5qawvyvo0z
        - urstn1q18m
        - bftejdaooo
        valid:
        - 2pivafjwf4
        - nelywkajh5
        - ujudi1d454
        - rvz86cgf2w
      type: string
    - attribute: lastname
      description: Lastname of the Director
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - bjcv1pm7b2
        - ry97zr940k
        - t7d8uklk83
        - drzez3aaaf
        - uaw3o7bmm2
        - q0obcmlwvi
        - 2whipf3pgo
        - 29fpbyqfie
        - gbkjq2j2ns
        - yvpcuv86cv
        - 90p4ifoew2
        - sx1ae6ohl7
        - z3a2hujw4f
        - knlufd3win
        - 18k6oxh7o0
        valid:
        - 3tzri9lo0m
        - tkf00fv6sa
        - i07s2jevpf
        - eqsymomhfj
      type: string
    type: resource
  max_items: 1
  optional: true
  type: list
- attribute: rating
  element:
    schema:
    - attribute: rater
      description: Rater that provide rating
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - i0fvny6ns0
        - kxwi5u7nwm
        - 0t3i9mp68s
        - it6n7z7j2f
        - 9w22wwq29c
        - 83760xf760
        - dcih8y85ec
        - 981ftjkbvd
        - isyk35yq49
        - 9k84qpnxz7
        - xc6bqxkppx
        - bah2e1axts
        - 43dxmmnbhh
        - j22jtkwazm
        - tcvpw8h2hq
        valid:
        - brqj72lrqb
        - 18ajprtdwu
        - 4o7n982kbk
        - 0sn3xv7uwa
      type: string
    - attribute: rating
      default: 1
      optional: true
      subtype: range
      test_params:
        invalid:
        - 0
        - 11
        multiple_valids:
        - 1
        - 10
        - 5.5
        - 3.991762745849335
        - 2.774075357772899
        - 5.626167755557554
        - 9.861530554426153
        - 6.078563245626334
        - 8.35679194234499
        - 7.883745975374167
        - 8.795056744489173
        - 8.937490815935266
        - 4.884552001473584
        - 4.330438872503776
        - 4.330237893179739
        valid:
        - 1
        - 10
        - 5.5
        - 9.519684239474277
      type: float
      validation:
        func_name: FloatBetween
        params:
        - 1
        - 10
    type: resource
  optional: true
  type: list
- attribute: casts
  element:
    schema:
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - fejwygf1p8
    - gkffts80w2
    - y3hbu9r43h
    - 7w0wtdpjgf
    - tmplolv90z
    - xx6xvmht74
    - u39ug4rwa9
    - 3h7ry89852
    - 7ku9c1ps1v
    - w84w6qbxoc
    - 42u1sokplt
    - gyk7vffnvv
    - ayczzm030c
    - l5vixpqtme
    - go018bbd74
    valid:
    - 1e20xahu5f
    - evwxc95s8d
    - 0hobfw3yun
    - n01r8hwul1
  type: set
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - YXZ5enU0bjQwMw==
    - dzVza3JoM3NhZQ==
    - ajAwb2RlcHp1eQ==
    - d2lxY21naTFwNg==
    - azF6dmczeTBtZQ==
    - czBmOW1hMXAwbg==
    - NnFlZnNlaDZyag==
    - cDM4aWdwM2tpNw==
    - MWl6eWh2Nms5bw==
    - dDNma2w1NWw2NQ==
    - M3JjNXhxcXRkbA==
    - bDFsNXh3cWhtMQ==
    - aHo2djNidnV2Mg==
    - cGl5MDN6cDhjZw==
    - c2Z2NnQ3ZWxzcA==
    valid:
    - aXZsZGxqN21pag==
    - cW10bDhtNnl5eA==
    - OGNnd2Jtc3dnMw==
    - cHBnd3M1aWV1Yg==
  cidr:
    invalid:
    - 292.279.277.300/17
    multiple_valids:
    - 8.186.208.0/20
    - 8.186.176.0/20
    - 8.186.160.0/20
    - 8.186.240.0/20
    - 8.186.48.0/20
    - 8.186.224.0/20
    - 8.186.96.0/20
    - 8.186.192.0/20
    - 8.186.80.0/20
    - 8.186.0.0/20
    - 8.186.32.0/20
    - 8.186.144.0/20
    - 8.186.128.0/20
    - 8.186.112.0/20
    - 8.186.64.0/20
    valid:
    - 8.186.208.0/20
    - 8.186.176.0/20
    - 8.186.160.0/20
    - 8.186.240.0/20
  ipv4:
    invalid:
    - 300.282.256.269
    multiple_valids:
    - 8.186.93.1
    - 8.186.61.12
    - 8.186.241.223
    - 8.186.19.11
    - 8.186.30.19
    - 8.186.176.157
    - 8.186.29.24
    - 8.186.9.154
    - 8.186.166.107
    - 8.186.201.141
    - 8.186.113.56
    - 8.186.246.166
    - 8.186.220.23
    - 8.186.184.5
    - 8.186.132.222
    valid:
    - 8.186.93.1
    - 8.186.61.12
    - 8.186.241.223
    - 8.186.19.11
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f3a8
    - 2001:db8::34f4:0:0:f390
    - 2001:db8::34f4:0:0:f3e9
    - 2001:db8::34f4:0:0:f394
    - 2001:db8::34f4:0:0:f3c6
    - 2001:db8::34f4:0:0:f314
    - 2001:db8::34f4:0:0:f340
    - 2001:db8::34f4:0:0:f33c
    - 2001:db8::34f4:0:0:f345
    - 2001:db8::34f4:0:0:f38e
    - 2001:db8::34f4:0:0:f36c
    - 2001:db8::34f4:0:0:f39a
    - 2001:db8::34f4:0:0:f329
    - 2001:db8::34f4:0:0:f33a
    - 2001:db8::34f4:0:0:f3e1
    valid:
    - 2001:db8::34f4:0:0:f3a8
    - 2001:db8::34f4:0:0:f390
    - 2001:db8::34f4:0:0:f3e9
    - 2001:db8::34f4:0:0:f394
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 61:ee:50:b7:50:0b
    - e9:f0:59:36:ff:e2
    - c9:fd:93:ce:f2:1c
    - 99:75:37:2a:16:9b
    - a3:43:35:41:6c:e0
    - 19:b8:61:df:fb:55
    - b1:f7:4f:8a:eb:14
    - f4:ce:ba:56:5f:4c
    - d6:ff:c5:c9:5b:a9
    - 21:e4:13:af:0a:5c
    - f8:f6:85:d0:2c:e6
    - 43:40:ed:28:1b:48
    - ca:cc:2b:fe:ca:0f
    - c6:03:d7:28:6b:12
    - 81:40:4e:20:74:19
    valid:
    - 46:92:e8:14:d5:c5
    - 76:4c:a7:32:1e:51
    - ba:69:e6:6f:29:f6
    - b4:36:58:bd:7e:6a
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - zqrlwom83z
    - lw1qeec5j2
    - io2m79r2l2
    - x4p9tpsuph
    - 6tjwzt7q00
    - 7gk0st3501
    - mxtkmeqswg
    - j6diduuwf2
    - npkdd04kcg
    - rx510acq2s
    - ro90uic5oi
    - h3acw8hryu
    - 0cz56c5rto
    - z0d79rjoln
    - fmm2pg670t
    valid:
    - k6anwdeotw
    - yrgin18i42
    - qr60v2cxuy
    - dzvr76nss4
  time:
    invalid:
    - '2022-08-02 10:47:49.865097'
    multiple_valids:
    - '2022-08-02T05:17:49.865097+00:00'
    - '2022-08-25T05:17:49.865097+00:00'
    - '2022-09-17T05:17:49.865097+00:00'
    - '2022-10-10T05:17:49.865097+00:00'
    - '2022-11-02T05:17:49.865097+00:00'
    - '2022-11-25T05:17:49.865097+00:00'
    - '2022-12-18T05:17:49.865097+00:00'
    - '2023-01-10T05:17:49.865097+00:00'
    - '2023-02-02T05:17:49.865097+00:00'
    - '2023-02-25T05:17:49.865097+00:00'
    - '2023-03-20T05:17:49.865097+00:00'
    - '2023-04-12T05:17:49.865097+00:00'
    - '2023-05-05T05:17:49.865097+00:00'
    - '2023-05-28T05:17:49.865097+00:00'
    - '2023-06-20T05:17:49.865097+00:00'
    valid:
    - '2022-08-02T05:17:49.865097+00:00'
    - '2022-08-25T05:17:49.865097+00:00'
    - '2022-09-17T05:17:49.865097+00:00'
    - '2022-10-10T05:17:49.865097+00:00'
  url-http:
    invalid:
    - ht:/v0xcejpum4vjlb0.com
    multiple_valids:
    - http://agft28wrdq0h4tn.com
    - http://vevg1yvor7x72ja.com
    - http://77w01ea44zt6n24.com
    - http://6wazjbz5xefjq1q.com
    - http://otufrkv1wd9biqx.com
    - http://875snbmahodc2xb.com
    - http://vr0n5m1u0sc2lwr.com
    - http://hn9knc85q40nngj.com
    - http://pflhtngibjqhxtn.com
    - http://itqa0rrl1ptzzmu.com
    - http://anzhkdpl1hky0lg.com
    - http://wk9utd3hiym6vq0.com
    - http://a6vri6ludkxb5jd.com
    - http://yiolw59qztj2nix.com
    - http://70miutkbr0dh7qi.com
    valid:
    - http://5li70a8wi02lg3h.com
    - http://x59oitf8p4qk7ma.com
    - http://96n98uhencgd07m.com
    - http://6uq5yra92vgis09.com
  url-https:
    invalid:
    - hts:/b3iuqptoaaxcxu3.com
    multiple_valids:
    - https://47w90tlhqjfs083.com
    - https://6foo3l71uwckakd.com
    - https://c28ndf4mcfcumff.com
    - https://7y053iqdh14oyob.com
    - https://afjluenwmvfbi50.com
    - https://1tr1stqcg8ym0hc.com
    - https://i93k5uqyerxg4im.com
    - https://jha298ol3vkl0t1.com
    - https://dh3js1stz8xczyy.com
    - https://pam752c0402v8pg.com
    - https://tmbn6zshqi5c6pr.com
    - https://chhgps2oq8v69kp.com
    - https://8xqivdekeonyye4.com
    - https://v091q2ymg2q1c6a.com
    - https://7d0j0jrem5qlvgh.com
    valid:
    - https://nd6u3woa00kdho2.com
    - https://51f94w1b0yqul5i.com
    - https://5l9q1q5ygy5a9kh.com
    - https://sdkg6b4jjl4ciwa.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 73c23d66-1222-11ed-8a72-dc214861057a
    - 73c23d67-1222-11ed-b08a-dc214861057a
    - 73c23d68-1222-11ed-beb4-dc214861057a
    - 73c23d69-1222-11ed-b5e1-dc214861057a
    - 73c23d6a-1222-11ed-824e-dc214861057a
    - 73c23d6b-1222-11ed-8762-dc214861057a
    - 73c23d6c-1222-11ed-a87c-dc214861057a
    - 73c23d6d-1222-11ed-8183-dc214861057a
    - 73c23d6e-1222-11ed-a96e-dc214861057a
    - 73c23d6f-1222-11ed-ba9b-dc214861057a
    - 73c23d70-1222-11ed-bc89-dc214861057a
    - 73c23d71-1222-11ed-ace2-dc214861057a
    - 73c23d72-1222-11ed-b42b-dc214861057a
    - 73c23d73-1222-11ed-b426-dc214861057a
    - 73c23d74-1222-11ed-8f2f-dc214861057a
    valid:
    - 73c23d62-1222-11ed-8d23-dc214861057a
    - 73c23d63-1222-11ed-89e0-dc214861057a
    - 73c23d64-1222-11ed-a85d-dc214861057a
    - 73c23d65-1222-11ed-8bb8-dc214861057a
unique_attribute:
- title
