imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: movie
provider_name: Movies
schemas:
- attribute: title
  description: Title of the Movie
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 7h83i010rv
    - 5w2oif9as5
    - oghhvxtpuz
    - 2bcthd3uuv
    - uaqfz96g7m
    - vtjlyjka8d
    - qfmpiuh1j3
    - qhvuzvrwql
    - 0e003n7bye
    - vk6y4nb936
    - 3ivkdhr899
    - hd1r6z4kus
    - 9uod3rzxnh
    - k149dhtet7
    - aj7du398v3
    valid:
    - 6qp0ught3b
    - tr67nnv4fp
    - wyps1alg1q
    - 76qvmpkwr1
  type: string
- attribute: isbn
  description: ISBN of the Movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - oae163u8sl
    - av3ee0mupe
    - m3xc5ojjdr
    - 8yrstynpk7
    - emjvoq4qtp
    - iklu7ftx1x
    - ommecdx8aw
    - fqmy620xtw
    - g9it2o3481
    - 1rqyjvuimr
    - dwaqmb9sdm
    - 4myml9nvpe
    - ox4uvy58qx
    - nqanjmc6xd
    - 3q3dbzr0rq
    valid:
    - 16btnttikv
    - tst5sdh96h
    - ga6hb0bpdm
    - dky8o130ay
  type: string
- attribute: genre
  default: thriller
  description: Genre of the movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - o4358e8i4h
    multiple_valids:
    - thriller
    - action
    - horror
    - fiction
    - comedy
    valid:
    - thriller
    - action
    - horror
    - fiction
    - comedy
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: false
    params:
    - thriller
    - action
    - horror
    - fiction
    - comedy
- attribute: director
  description: Director of the Movie
  element:
    schema:
    - attribute: firstname
      description: Firstname of the Director
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - v73rw47gr2
        - 20gnkn5zer
        - fnukm5ugml
        - qi816rut80
        - u45v9rtr5i
        - 6aoh2va0nw
        - akitjm1e4d
        - fh0mr5rjaj
        - l5cc0s0he5
        - x1umlf78zr
        - 54flj2j2hi
        - mgqthf5onu
        - iy6opgxvy3
        - m1dgd6epsm
        - ho2f6us27d
        valid:
        - 0c1m24jrkr
        - h5nol8g56m
        - z2vzohifp3
        - xowe01jnu9
      type: string
    - attribute: lastname
      description: Lastname of the Director
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - n855w57zpa
        - ezehhi279j
        - s3780dfk58
        - o4ielld0w2
        - 6spgtlakc2
        - t98gkhzrlt
        - 8eqw8k8u72
        - r70soag2xg
        - c464eo84wb
        - yf46lc1x6e
        - aoxxf30u73
        - 07m5c0zun5
        - lgf7ec543f
        - mkgno4jppj
        - 6pp83ojuf8
        valid:
        - ud8hkfmcfr
        - 0um1a4tji1
        - 56u8j11waa
        - xhxtwtwonp
      type: string
    type: resource
  max_items: 1
  optional: true
  type: list
- attribute: rating
  element:
    schema:
    - attribute: rater
      description: Rater that provide rating
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - irtmp03fu4
        - tkmr1e3kzq
        - 8yseicgsk1
        - dhte9br3rn
        - pv16ceddq5
        - g7kygoiizq
        - e78ma644sq
        - r74a23fytq
        - gdl0319ci3
        - fupxouw80c
        - 6ofj5duzql
        - pdgjl8ldzd
        - 9twkl789x2
        - 2wwvmrokpo
        - rdnaus8wes
        valid:
        - cpivt7xnic
        - tli5ib7kzx
        - 3pp23rrpjv
        - 49na50e04i
      type: string
    - attribute: rating
      default: 1
      optional: true
      subtype: range
      test_params:
        invalid:
        - 0
        - 11
        multiple_valids:
        - 1
        - 10
        - 5.5
        - 2.5804163587670588
        - 5.4190255302505115
        - 6.730749760586948
        - 3.5738943781345296
        - 9.082686500462481
        - 2.494236276044194
        - 4.907738308459483
        - 8.029432146434225
        - 2.8296974745327854
        - 3.9604738935391706
        - 7.740396722069354
        - 9.909498071267056
        valid:
        - 1
        - 10
        - 5.5
        - 9.536539757661387
      type: float
      validation:
        func_name: FloatBetween
        params:
        - 1
        - 10
    type: resource
  optional: true
  type: list
- attribute: casts
  element:
    schema:
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 3sd32r1ru6
    - 6iyk67org7
    - sd0fr07uj2
    - 7llafnmelp
    - lbr1v5ipj6
    - lgvshvk74j
    - 5ed4ugh3ro
    - aswt6aavwp
    - tngprfs9lj
    - 0ykcuw7zl6
    - r2kvbr0v10
    - pdhi2r20pj
    - dzkun0rqli
    - 5m9m2luppy
    - jkxvev5e4u
    valid:
    - juiiy50hov
    - 96zhtnpif9
    - kyw6c8szka
    - ln2bri7wws
  type: set
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - Ym5qNjF0MDBnYw==
    - ajRmMmh3MDhvNw==
    - NXdpNWtva3IzcQ==
    - bzh1aWVuYW01dQ==
    - dXNzb2o2bjV6cw==
    - ODJuZzJxM21tMw==
    - aG1uNGNubnlqaQ==
    - aXk3d3g0aG96MQ==
    - dnV5dXpreHVsbA==
    - cnRmdWg1MmkwYw==
    - ZmY5dzB4czZ2OA==
    - aWRya2pmM25xbw==
    - ZTlrMGxocmt0bA==
    - M21hNDdvMHBxNA==
    - MnFpbWI1cTlibw==
    valid:
    - MGU3NWY1bmp6NA==
    - ejV4dTN1OHJjMg==
    - Z3czdDZnbmE0bA==
    - bnJzbXFpY3U0Yg==
  cidr:
    invalid:
    - 269.281.284.261/8
    multiple_valids:
    - 107.84.48.0/20
    - 107.84.0.0/20
    - 107.84.112.0/20
    - 107.84.192.0/20
    - 107.84.208.0/20
    - 107.84.32.0/20
    - 107.84.240.0/20
    - 107.84.160.0/20
    - 107.84.176.0/20
    - 107.84.128.0/20
    - 107.84.80.0/20
    - 107.84.96.0/20
    - 107.84.16.0/20
    - 107.84.64.0/20
    - 107.84.144.0/20
    valid:
    - 107.84.48.0/20
    - 107.84.0.0/20
    - 107.84.112.0/20
    - 107.84.192.0/20
  ipv4:
    invalid:
    - 294.273.284.299
    multiple_valids:
    - 107.84.106.236
    - 107.84.71.226
    - 107.84.248.131
    - 107.84.154.129
    - 107.84.180.185
    - 107.84.245.2
    - 107.84.93.104
    - 107.84.160.88
    - 107.84.254.245
    - 107.84.15.251
    - 107.84.97.144
    - 107.84.131.210
    - 107.84.94.54
    - 107.84.88.66
    - 107.84.58.49
    valid:
    - 107.84.106.236
    - 107.84.71.226
    - 107.84.248.131
    - 107.84.154.129
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f338
    - 2001:db8::34f4:0:0:f37c
    - 2001:db8::34f4:0:0:f303
    - 2001:db8::34f4:0:0:f35a
    - 2001:db8::34f4:0:0:f309
    - 2001:db8::34f4:0:0:f372
    - 2001:db8::34f4:0:0:f330
    - 2001:db8::34f4:0:0:f393
    - 2001:db8::34f4:0:0:f3cf
    - 2001:db8::34f4:0:0:f375
    - 2001:db8::34f4:0:0:f3c6
    - 2001:db8::34f4:0:0:f332
    - 2001:db8::34f4:0:0:f3d8
    - 2001:db8::34f4:0:0:f32c
    - 2001:db8::34f4:0:0:f32d
    valid:
    - 2001:db8::34f4:0:0:f338
    - 2001:db8::34f4:0:0:f37c
    - 2001:db8::34f4:0:0:f303
    - 2001:db8::34f4:0:0:f35a
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 97:b0:f0:6a:76:33
    - 4e:f9:b7:df:3e:35
    - a0:b4:2d:b0:a0:49
    - e2:d7:a6:85:84:70
    - 25:ae:86:61:07:fc
    - 0a:1a:fd:4c:97:e1
    - 66:26:af:73:8d:6d
    - 5b:e3:c5:65:a4:2f
    - 54:b7:3d:1d:59:8e
    - 9e:42:a5:ad:e9:77
    - 4e:29:97:39:3f:12
    - b9:b5:95:c4:4a:74
    - 38:95:24:60:b6:a6
    - 8b:b8:bc:68:b7:1e
    - 85:95:f7:94:34:85
    valid:
    - 3b:a8:de:fa:ee:c8
    - d1:1d:bf:8b:fc:3c
    - 1c:12:5b:64:e2:1a
    - b9:8b:52:2c:f2:24
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 11j8pdys7v
    - wcq4fvqmxq
    - nehb8qax8x
    - jj11eq4joi
    - 8w3b6240rx
    - wb1zxermxr
    - uxkzuat82g
    - zgycrgyz7y
    - z6o9fbwthq
    - 9stn8791np
    - 10kpyap3vf
    - bzrkql04t5
    - ifm21rnqr5
    - 44e7xp6yh7
    - xf4ef7bgm3
    valid:
    - kpbj2qhwgt
    - ae92zu8ypy
    - 1s9q7ib2ip
    - 04b5p5lpf7
  time:
    invalid:
    - '2022-07-29 11:13:57.053868'
    multiple_valids:
    - '2022-07-29T05:43:57.053868+00:00'
    - '2022-08-21T05:43:57.053868+00:00'
    - '2022-09-13T05:43:57.053868+00:00'
    - '2022-10-06T05:43:57.053868+00:00'
    - '2022-10-29T05:43:57.053868+00:00'
    - '2022-11-21T05:43:57.053868+00:00'
    - '2022-12-14T05:43:57.053868+00:00'
    - '2023-01-06T05:43:57.053868+00:00'
    - '2023-01-29T05:43:57.053868+00:00'
    - '2023-02-21T05:43:57.053868+00:00'
    - '2023-03-16T05:43:57.053868+00:00'
    - '2023-04-08T05:43:57.053868+00:00'
    - '2023-05-01T05:43:57.053868+00:00'
    - '2023-05-24T05:43:57.053868+00:00'
    - '2023-06-16T05:43:57.053868+00:00'
    valid:
    - '2022-07-29T05:43:57.045875+00:00'
    - '2022-08-21T05:43:57.053868+00:00'
    - '2022-09-13T05:43:57.053868+00:00'
    - '2022-10-06T05:43:57.053868+00:00'
  url-http:
    invalid:
    - ht:/n0qrnprxn1ht9a8.com
    multiple_valids:
    - http://7j06ga7e5xlmk4q.com
    - http://enzczceqfu0hu28.com
    - http://ox1uvxnc5142s4r.com
    - http://r6iuvw1k94lkyec.com
    - http://31qzqt4cvdu559r.com
    - http://e0vainbanxl2xvi.com
    - http://heb0k1a3n6vni00.com
    - http://urd4g9reh4bt2wr.com
    - http://cpnt0nc39cfwcuq.com
    - http://vm2s0ckkyzrm6qy.com
    - http://t2vq18u85py9shw.com
    - http://ps7qqwdf0te3r9w.com
    - http://zahulgikp784e5o.com
    - http://pxefvvqprnw8nso.com
    - http://zm7ngp748yl9n3t.com
    valid:
    - http://mxu01ybk6fbqbfy.com
    - http://h4hftvfiqe7knhz.com
    - http://0idubcb99tqz97p.com
    - http://olvy4iyzg6lpoku.com
  url-https:
    invalid:
    - hts:/lz5hvsis0z7ax8r.com
    multiple_valids:
    - https://ubt2rqs8j1hkara.com
    - https://sidh5gu73qomzke.com
    - https://wzjayev89cpiyp2.com
    - https://fnw14v7uqmogxoc.com
    - https://9bempzmshqmrdkz.com
    - https://3upni0xwteb1ubl.com
    - https://2rt3t1neakh4zw2.com
    - https://j0yaac29fhtqrpk.com
    - https://pjbb5wmvb0jownz.com
    - https://r6qqbbm683575t1.com
    - https://ykv8r4nsqto4323.com
    - https://dmiwvce7uhaoycm.com
    - https://2lvnrpqb82w70zy.com
    - https://rlpys0c8rve7k9x.com
    - https://kczrreyhnc7ila3.com
    valid:
    - https://ifyxz0219dk6svw.com
    - https://8022eg943hehzbe.com
    - https://5poadbpgg71shtl.com
    - https://lgwb4nzqxk4qg0k.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 70394f69-0f01-11ed-80fd-7c8ae1979a87
    - 70394f6a-0f01-11ed-8782-7c8ae1979a87
    - 70394f6b-0f01-11ed-b9cb-7c8ae1979a87
    - 70394f6c-0f01-11ed-aa65-7c8ae1979a87
    - 70394f6d-0f01-11ed-9b72-7c8ae1979a87
    - 70394f6e-0f01-11ed-9e77-7c8ae1979a87
    - 70394f6f-0f01-11ed-b6df-7c8ae1979a87
    - 70394f70-0f01-11ed-9050-7c8ae1979a87
    - 70394f71-0f01-11ed-950c-7c8ae1979a87
    - 70394f72-0f01-11ed-a450-7c8ae1979a87
    - 70394f73-0f01-11ed-b95c-7c8ae1979a87
    - 70394f74-0f01-11ed-bec2-7c8ae1979a87
    - 70394f75-0f01-11ed-b587-7c8ae1979a87
    - 70394f76-0f01-11ed-b9f1-7c8ae1979a87
    - 70394f77-0f01-11ed-bb82-7c8ae1979a87
    valid:
    - 70394f65-0f01-11ed-9b18-7c8ae1979a87
    - 70394f66-0f01-11ed-a045-7c8ae1979a87
    - 70394f67-0f01-11ed-8af7-7c8ae1979a87
    - 70394f68-0f01-11ed-9869-7c8ae1979a87
unique_attribute:
- title
