imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
name: Tenant
provider_name: Aci
schemas:
- attribute: name
  description: Name of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 7d90pp9ght
    - 9llqfm0pee
    - uqp5cmt82u
    - kfq5gsajym
    - q7uif1mngw
    - x7to5b4k5x
    - w68yqtyz0r
    - 820owrd09q
    - f5j6plrojo
    - ldxmy7vjzz
    - mu7a6a2qrp
    - wt0rhrzwc9
    - jsst086vgt
    - z3faue4igj
    - 6m9reuqzi1
    valid:
    - 2r1ghzgpvn
    - xtakvk8qv7
    - i3kyyxw7jn
    - pjjihqxyfj
  type: string
- attribute: name_alias
  computed: true
  description: annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - qj1qg30me3
    - owm7j15i20
    - vocfts4djx
    - cn9dauwgd4
    - e81erf2cns
    - ru9xvac8ie
    - 1za51mr5j1
    - 2ybfgknu4h
    - k8ufq74uw1
    - zwce29qdsv
    - qc9medz5eo
    - gvprjf51z1
    - ladcxh32d6
    - y2iaw0alg6
    - fa8ovcn2sg
    valid:
    - ciaok5nbnf
    - rcuu54osur
    - 7m34hxhnhc
    - 3jxwnyr8ni
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 1wqclfk0i4
    - yrce0920tt
    - xerptxbafb
    - 3vwa417a6x
    - ixkiziadp5
    - q8a15tji4v
    - 6yvpa1ixsa
    - wab2cnk6ls
    - ayfzqmx4wg
    - 4y0lsvwjp9
    - g0l1b21lra
    - u2h85ssczb
    - egse1jxl5v
    - gxzzmy5e8j
    - xpwoe59jxm
    valid:
    - 6lm8cjexy2
    - 64kizsl59h
    - jsfbjenukf
    - i91nam5ni7
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 38l8c6gk8w
    - cg1x7pmmdr
    - 52bwz98f9g
    - kj5tgvnr7p
    - rdtyww7hu7
    - gjwo8pl8by
    - 50rs6609gj
    - nemcvyxcw1
    - 3qw8qgglum
    - ebjdeszru6
    - 3ijmabao0t
    - vaiepe7iid
    - h3mlbb60w2
    - xwem6fqnnk
    - ya3hot8uvk
    valid:
    - th7h55vekx
    - oig89gi7p3
    - rwfei662lr
    - bhkdsjsrqq
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - aHJ5cDJwZmZwcQ==
    - MTZibHEzZjZnNg==
    - dzJ2d28zamJveQ==
    - b3hydzA3YXJkMw==
    - aXNjdXdpYXE1dg==
    - azd3N2NnNHBtZA==
    - MDA4NDFuczRmbw==
    - bjU3MG42cWx2aQ==
    - MTBzbG9nOHljNw==
    - a2VobGo4bHFqOQ==
    - ZnQ4YWF0bXNkbA==
    - c2hidHI2MWVzMg==
    - NHhhcmZ4bW9jNA==
    - c2NlOWk1ZjY2Yw==
    - ZGtvY3pjbGt6aQ==
    valid:
    - am1udXBjczFxdg==
    - c3I5N21iNzJiYQ==
    - N2NlajZoMzVqaw==
    - M2NzeWZhaXUzNA==
  cidr:
    invalid:
    - 286.260.259.264/3
    multiple_valids:
    - 123.239.48.0/20
    - 123.239.96.0/20
    - 123.239.0.0/20
    - 123.239.16.0/20
    - 123.239.80.0/20
    - 123.239.208.0/20
    - 123.239.192.0/20
    - 123.239.128.0/20
    - 123.239.112.0/20
    - 123.239.64.0/20
    - 123.239.240.0/20
    - 123.239.224.0/20
    - 123.239.144.0/20
    - 123.239.32.0/20
    - 123.239.160.0/20
    valid:
    - 123.239.48.0/20
    - 123.239.96.0/20
    - 123.239.0.0/20
    - 123.239.16.0/20
  ipv4:
    invalid:
    - 289.263.279.271
    multiple_valids:
    - 123.239.128.165
    - 123.239.123.152
    - 123.239.215.240
    - 123.239.124.153
    - 123.239.147.59
    - 123.239.108.168
    - 123.239.198.92
    - 123.239.94.87
    - 123.239.51.8
    - 123.239.176.14
    - 123.239.28.166
    - 123.239.122.117
    - 123.239.228.56
    - 123.239.52.68
    - 123.239.16.81
    valid:
    - 123.239.128.165
    - 123.239.123.152
    - 123.239.215.240
    - 123.239.124.153
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f386
    - 2001:db8::34f4:0:0:f3f9
    - 2001:db8::34f4:0:0:f391
    - 2001:db8::34f4:0:0:f3e4
    - 2001:db8::34f4:0:0:f328
    - 2001:db8::34f4:0:0:f3e8
    - 2001:db8::34f4:0:0:f316
    - 2001:db8::34f4:0:0:f3bb
    - 2001:db8::34f4:0:0:f3b4
    - 2001:db8::34f4:0:0:f34c
    - 2001:db8::34f4:0:0:f32a
    - 2001:db8::34f4:0:0:f3d0
    - 2001:db8::34f4:0:0:f3e0
    - 2001:db8::34f4:0:0:f3ef
    - 2001:db8::34f4:0:0:f397
    valid:
    - 2001:db8::34f4:0:0:f386
    - 2001:db8::34f4:0:0:f3f9
    - 2001:db8::34f4:0:0:f391
    - 2001:db8::34f4:0:0:f3e4
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 16:7f:f8:c8:ea:2f
    - 00:d4:0f:fb:77:c7
    - 48:44:17:a1:4a:5d
    - 34:cf:15:ee:08:d0
    - f4:fd:18:c1:09:cb
    - 80:13:e2:96:21:2b
    - 5a:be:ba:2c:cd:98
    - a7:ab:a0:93:4c:ed
    - da:8c:62:f4:f1:0b
    - e3:38:d1:c8:0d:9e
    - ad:35:73:89:c2:1b
    - 4c:be:3f:74:25:bc
    - aa:5f:08:00:cd:b3
    - a9:71:1d:c5:bd:05
    - 69:2b:dc:20:63:cd
    valid:
    - 5f:b7:95:53:37:b7
    - 19:d7:a0:de:be:c3
    - f3:df:d1:b4:b1:82
    - b5:6e:0c:40:a2:8b
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - eu0s1lukb9
    - 74sbtfe5p0
    - vm6q4es1c9
    - 5c9nnulks3
    - npn715xcqd
    - lj1ei8jtbo
    - xh0sij1ps7
    - 9161bcy5y9
    - zhdwdzzci3
    - cemk80q9rx
    - 1bmcm89czp
    - 8dd11dwizo
    - x6ep90aokl
    - 9uwx6zvcu3
    - jqfy1lvisg
    valid:
    - sr0fln6ym2
    - 30fyek3c6n
    - ewhxj2hzjd
    - 2sbwasoa0k
  time:
    invalid:
    - '2022-08-01 17:50:41.443204'
    multiple_valids:
    - '2022-08-01T12:20:41.443204+00:00'
    - '2022-08-24T12:20:41.443204+00:00'
    - '2022-09-16T12:20:41.443204+00:00'
    - '2022-10-09T12:20:41.443204+00:00'
    - '2022-11-01T12:20:41.443204+00:00'
    - '2022-11-24T12:20:41.443204+00:00'
    - '2022-12-17T12:20:41.443204+00:00'
    - '2023-01-09T12:20:41.443204+00:00'
    - '2023-02-01T12:20:41.443204+00:00'
    - '2023-02-24T12:20:41.443204+00:00'
    - '2023-03-19T12:20:41.443204+00:00'
    - '2023-04-11T12:20:41.443204+00:00'
    - '2023-05-04T12:20:41.443204+00:00'
    - '2023-05-27T12:20:41.443204+00:00'
    - '2023-06-19T12:20:41.443204+00:00'
    valid:
    - '2022-08-01T12:20:41.443204+00:00'
    - '2022-08-24T12:20:41.443204+00:00'
    - '2022-09-16T12:20:41.443204+00:00'
    - '2022-10-09T12:20:41.443204+00:00'
  url-http:
    invalid:
    - ht:/cxz0aie5xds7dyj.com
    multiple_valids:
    - http://kf1af37pnkh9ztk.com
    - http://a0l7ert0w55vh7e.com
    - http://36859b00s6l8e7i.com
    - http://vtu9joqmof6mxht.com
    - http://ama3rzfj850dyn0.com
    - http://m2xmrwktwajyhpl.com
    - http://tzo8omig0rg0qt4.com
    - http://ulanr9zfmvh933e.com
    - http://epacgwha59q0ofh.com
    - http://yemmunm5dgvnp9j.com
    - http://52r900pqt2gj8ia.com
    - http://41dzbzhvqepwxta.com
    - http://6uc6qbpvydizq7m.com
    - http://kqvhm4x1xcoz4bi.com
    - http://ktba28jt7tho94e.com
    valid:
    - http://4j1vyrs22twm70r.com
    - http://vfmpwawbjknbfli.com
    - http://235k338qwu0hupn.com
    - http://krp9vjgxuxrooik.com
  url-https:
    invalid:
    - hts:/v8ucj8jdu205us0.com
    multiple_valids:
    - https://0zzzkjk2sh4uktn.com
    - https://z8fjl7gv7htcw5j.com
    - https://nsipserlpcqptai.com
    - https://oi7b7zp2qnvfnu5.com
    - https://lgzp5x5jlvt2pch.com
    - https://h2yq8fcw5o4p6vr.com
    - https://qzgay863eg8p7p1.com
    - https://zm3qd54pxn2t5aq.com
    - https://uot502mqtkossf9.com
    - https://jwmm6q7gj1zrgm7.com
    - https://49qufv752mjuqma.com
    - https://759vn69hcuw3l1v.com
    - https://gzs2e6wca2non7z.com
    - https://lfi461j8dgrwaem.com
    - https://w3i1nqgdnavtbvd.com
    valid:
    - https://bx1lbv817h4276h.com
    - https://8iab9lbdq3sddl9.com
    - https://6ijt2uv1bcqftzb.com
    - https://tdnjy552b5q7uu8.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 5bfc1331-1194-11ed-b64a-dc214861057a
    - 5bfc1332-1194-11ed-944b-dc214861057a
    - 5bfc1333-1194-11ed-b9f3-dc214861057a
    - 5bfc1334-1194-11ed-925f-dc214861057a
    - 5bfc1335-1194-11ed-a48a-dc214861057a
    - 5bfc1336-1194-11ed-8500-dc214861057a
    - 5bfc1337-1194-11ed-8bc2-dc214861057a
    - 5bfc1338-1194-11ed-ac09-dc214861057a
    - 5bfc1339-1194-11ed-9fa4-dc214861057a
    - 5bfc133a-1194-11ed-a697-dc214861057a
    - 5bfc133b-1194-11ed-8740-dc214861057a
    - 5bfc133c-1194-11ed-9b09-dc214861057a
    - 5bfc133d-1194-11ed-8753-dc214861057a
    - 5bfc133e-1194-11ed-8109-dc214861057a
    - 5bfc133f-1194-11ed-a2a8-dc214861057a
    valid:
    - 5bfc132d-1194-11ed-8baa-dc214861057a
    - 5bfc132e-1194-11ed-b6aa-dc214861057a
    - 5bfc132f-1194-11ed-8572-dc214861057a
    - 5bfc1330-1194-11ed-913b-dc214861057a
unique_attribute:
- name
