imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
name: Tenant
provider_name: Aci
schemas:
- attribute: name
  description: Name of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 19qnqpv8pk
    - 00qmk1x00y
    - 914tndspdz
    - ww9ey2g9kh
    - 3geovre8mv
    - saqrudftc9
    - 7bd55rdm7g
    - 0v4cs8nlr2
    - aev2s04ozm
    - xumwb5q65h
    - tzc2zve1td
    - z67f11b2m0
    - 0s2rz8qpe4
    - 5oskwkkmzp
    - pq6y482jtt
    valid:
    - 7sng5qtts2
    - ff0ny2nxa0
    - tbruipvz5l
    - t1ta8mo18i
  type: string
- attribute: name_alias
  computed: true
  description: annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 30kj5ad91r
    - 2yl7nhwrwk
    - 09gaqspp1u
    - stu4bkygfi
    - b3h6p7sw6o
    - cynhspaebr
    - 43smckueae
    - 7zwknk4lcl
    - mveaqped3g
    - 5pcjyqluyz
    - 3s5ssd1f3h
    - xabgzrdbnf
    - xinjozgyfm
    - qxhfh0oywh
    - vdup6sxmuc
    valid:
    - rk7j37vf4w
    - grb5iql2yb
    - p7mj6907hq
    - ru6gxl70r6
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ihudozjzec
    - oif8llfkd9
    - v0p8x0z43q
    - l4288d7r9f
    - 5a2lnww5wc
    - edffmcbtxv
    - vabiazymjz
    - kn65s6uc2m
    - 7dywchpwpb
    - maywny1ltx
    - xsz2jm1ml4
    - mfzrxnfncs
    - iq44nixgbb
    - 787ceiqhsp
    - 7xuhfxd1o3
    valid:
    - 4q9mu31qjl
    - ezpq54u985
    - fkp7e78mvi
    - 6mt0draasu
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - k3s0ktxd6e
    - hyjqsy7h8y
    - 2ryp0n4qvb
    - 0a7ql05ftc
    - 8ej7fpstf8
    - nykdxz6stj
    - iehkl9h4n0
    - sva02t2q16
    - x8as2xuye7
    - dihwfdqxcx
    - f80o46rtuk
    - c50sc7omtv
    - ogd29yjjuk
    - ykimy0crmm
    - 9nfr5i9kdc
    valid:
    - eeg6z6jy0f
    - gwt8wybxdl
    - q2ll7qsh35
    - 6iaq0yk6de
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - d2U2NTR0eGVqaQ==
    - NmRxMGdmODdoZA==
    - MHhrbDRmZnl5ag==
    - OXFsb2R5NWZpag==
    - Nm1xN2dpOGlubQ==
    - MXo5cmQ5azNreQ==
    - NXYzcDNmYW1qbg==
    - eDVobGFiNTgwag==
    - bnVqZWNmZG55Ng==
    - NTJyOGRub3dzbg==
    - YWNzbXMzMHN4aw==
    - Mml1ZHJqaTh5Ng==
    - cGxicWwwOGtoNQ==
    - Znl3bnpsdDJ1dw==
    - MHV6bGF0ZGJueg==
    valid:
    - YTdnajMybTJ1dw==
    - d213azBpZWszZQ==
    - NmJmMG9veHB5ZQ==
    - amsycHJsanE0Zw==
  cidr:
    invalid:
    - 280.261.290.260/24
    multiple_valids:
    - 188.52.0.0/20
    - 188.52.224.0/20
    - 188.52.176.0/20
    - 188.52.112.0/20
    - 188.52.208.0/20
    - 188.52.160.0/20
    - 188.52.16.0/20
    - 188.52.32.0/20
    - 188.52.80.0/20
    - 188.52.128.0/20
    - 188.52.48.0/20
    - 188.52.240.0/20
    - 188.52.144.0/20
    - 188.52.64.0/20
    - 188.52.96.0/20
    valid:
    - 188.52.0.0/20
    - 188.52.224.0/20
    - 188.52.176.0/20
    - 188.52.112.0/20
  ipv4:
    invalid:
    - 300.288.287.295
    multiple_valids:
    - 188.52.115.159
    - 188.52.153.174
    - 188.52.234.132
    - 188.52.20.158
    - 188.52.63.168
    - 188.52.22.15
    - 188.52.86.243
    - 188.52.183.143
    - 188.52.238.62
    - 188.52.134.78
    - 188.52.78.195
    - 188.52.12.252
    - 188.52.222.145
    - 188.52.68.2
    - 188.52.82.74
    valid:
    - 188.52.115.159
    - 188.52.153.174
    - 188.52.234.132
    - 188.52.20.158
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f322
    - 2001:db8::34f4:0:0:f3e3
    - 2001:db8::34f4:0:0:f3f1
    - 2001:db8::34f4:0:0:f3de
    - 2001:db8::34f4:0:0:f3a8
    - 2001:db8::34f4:0:0:f33c
    - 2001:db8::34f4:0:0:f35a
    - 2001:db8::34f4:0:0:f32a
    - 2001:db8::34f4:0:0:f3e8
    - 2001:db8::34f4:0:0:f368
    - 2001:db8::34f4:0:0:f332
    - 2001:db8::34f4:0:0:f3b5
    - 2001:db8::34f4:0:0:f359
    - 2001:db8::34f4:0:0:f31c
    - 2001:db8::34f4:0:0:f314
    valid:
    - 2001:db8::34f4:0:0:f322
    - 2001:db8::34f4:0:0:f3e3
    - 2001:db8::34f4:0:0:f3f1
    - 2001:db8::34f4:0:0:f3de
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 16:b8:5e:78:6d:3e
    - 3b:7b:d2:e3:d3:22
    - ae:89:d3:24:cd:e9
    - 71:76:82:b2:5e:53
    - 3a:73:ca:53:d6:e4
    - f7:c2:99:6f:d3:fb
    - 12:0b:45:f8:8e:b6
    - ad:ed:cf:5d:26:59
    - 99:fd:2d:88:ba:d5
    - e1:2d:b3:67:b6:d2
    - f3:7e:73:d4:6f:4d
    - 08:87:4b:da:9d:fb
    - 3b:46:46:f3:70:79
    - 3b:6c:7c:bf:1b:97
    - a0:ab:de:db:49:ca
    valid:
    - 85:5c:30:92:0f:cb
    - 70:d3:b4:d0:ae:ab
    - d4:1a:ab:67:b0:60
    - 24:6d:23:17:88:43
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - xop69eziio
    - hmsam9ukfp
    - b7041kb8sa
    - g47th2q8l6
    - 66rmgh34s8
    - zpucjfvlpq
    - jpqopshfl9
    - sgsgfnwsja
    - y8n1sk2fr8
    - 60kre5byds
    - bqjdtky5zq
    - bvs6cpdlxe
    - nicxjulm1h
    - yeh23l1n02
    - dxroyxdbtd
    valid:
    - 5zzd7vjeqp
    - hc3gu3u1hg
    - 9zzlgxi03s
    - wjnhtiug3z
  time:
    invalid:
    - '2022-07-25 12:40:48.167554'
    multiple_valids:
    - '2022-07-25T07:10:48.167554+00:00'
    - '2022-08-17T07:10:48.167554+00:00'
    - '2022-09-09T07:10:48.167554+00:00'
    - '2022-10-02T07:10:48.167554+00:00'
    - '2022-10-25T07:10:48.167554+00:00'
    - '2022-11-17T07:10:48.167554+00:00'
    - '2022-12-10T07:10:48.167554+00:00'
    - '2023-01-02T07:10:48.167554+00:00'
    - '2023-01-25T07:10:48.167554+00:00'
    - '2023-02-17T07:10:48.167554+00:00'
    - '2023-03-12T07:10:48.167554+00:00'
    - '2023-04-04T07:10:48.167554+00:00'
    - '2023-04-27T07:10:48.167554+00:00'
    - '2023-05-20T07:10:48.167554+00:00'
    - '2023-06-12T07:10:48.167554+00:00'
    valid:
    - '2022-07-25T07:10:48.167554+00:00'
    - '2022-08-17T07:10:48.167554+00:00'
    - '2022-09-09T07:10:48.167554+00:00'
    - '2022-10-02T07:10:48.167554+00:00'
  url-http:
    invalid:
    - ht:/z3pc44myvjpzcil.com
    multiple_valids:
    - http://mqwvvtx0zq3pk50.com
    - http://vqk8ik96zm2bru2.com
    - http://szsmigwvxgahesc.com
    - http://k9gjkogukrgr8ui.com
    - http://8zv69lcv8fgdk9q.com
    - http://ua4baivi0ofu2ae.com
    - http://ijbfxx0d05r14my.com
    - http://q0lu2vq9q1qrq7f.com
    - http://5ept53n8m6ixpf6.com
    - http://pk2yoy62gr5nmlv.com
    - http://zrwpdul3klef0ze.com
    - http://1znqjxsvw3p7n7m.com
    - http://n4p2eknbmv7zp2q.com
    - http://qqnswahm7jn55bv.com
    - http://a6cbjf2za5778jb.com
    valid:
    - http://h42xf7bgs4glz0d.com
    - http://rrxumqh2ez29dja.com
    - http://0jtgt117g98gu2p.com
    - http://urerpcyz2ggbw91.com
  url-https:
    invalid:
    - hts:/pob46qc3e497j6a.com
    multiple_valids:
    - https://9ys60jpx9mhwyny.com
    - https://q39vuzfvipzd9oe.com
    - https://32mdphbdwtjbfya.com
    - https://1422oatlu5otwd4.com
    - https://5tdjutsaf0mvvr5.com
    - https://s46zxj99csvkm8y.com
    - https://4bcyze8xxy6mf9m.com
    - https://bxmoye9b6c8iz9l.com
    - https://i38jeuzfg1f248x.com
    - https://hjcwfaycu46d3hm.com
    - https://ym41sgrc8vbe6uh.com
    - https://ccpxebqgybbmoa2.com
    - https://uwtu1gg64nnjrbw.com
    - https://mrwqwpq4oyl76jr.com
    - https://2dk95rio91whkzd.com
    valid:
    - https://4i5r75sg36fuoyg.com
    - https://gsc2waw878du6a6.com
    - https://y9jbecp122so4ne.com
    - https://sotr2r1nrq0baie.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - e8a31d1d-0be8-11ed-95da-7c8ae1979a87
    - e8a31d1e-0be8-11ed-9525-7c8ae1979a87
    - e8a31d1f-0be8-11ed-bd28-7c8ae1979a87
    - e8a31d20-0be8-11ed-bd12-7c8ae1979a87
    - e8a31d21-0be8-11ed-ba93-7c8ae1979a87
    - e8a31d22-0be8-11ed-9664-7c8ae1979a87
    - e8a31d23-0be8-11ed-b394-7c8ae1979a87
    - e8a31d24-0be8-11ed-a81e-7c8ae1979a87
    - e8a31d25-0be8-11ed-9ee5-7c8ae1979a87
    - e8a31d26-0be8-11ed-b265-7c8ae1979a87
    - e8a31d27-0be8-11ed-bc36-7c8ae1979a87
    - e8a31d28-0be8-11ed-b0ab-7c8ae1979a87
    - e8a31d29-0be8-11ed-8286-7c8ae1979a87
    - e8a31d2a-0be8-11ed-b2e4-7c8ae1979a87
    - e8a31d2b-0be8-11ed-9dc1-7c8ae1979a87
    valid:
    - e8a31d19-0be8-11ed-bebb-7c8ae1979a87
    - e8a31d1a-0be8-11ed-acf2-7c8ae1979a87
    - e8a31d1b-0be8-11ed-8f7c-7c8ae1979a87
    - e8a31d1c-0be8-11ed-b072-7c8ae1979a87
unique_attribute:
- name
