imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
name: Tenant
provider_name: Aci
schemas:
- attribute: name
  description: Name of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 5qx1udljs3
    - waqtva5hex
    - c1ro0ou694
    - nz1z60cmbp
    - bswhyiw3mc
    - 90qp9fk1xu
    - 6x3sj2hs7q
    - t4brxocv3g
    - 7zfdvx1oca
    - me2lqbimzl
    - 690pa59kp2
    - ssp550phsl
    - rttg8h4tep
    - ficta3pv0l
    - 2ar3ogruc5
    valid:
    - ih7hlr8gd3
    - 1avsdtit7y
    - 9xeiok0i7u
    - 31ife7jixw
  type: string
- attribute: name_alias
  computed: true
  description: annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - waxorhq46b
    - dzm0o0t813
    - ja8a2q3vst
    - gcphjcotec
    - ocoi62t049
    - kz7lo2joio
    - 7jbfbulbyh
    - bqcach45vf
    - 7ldm6fq6k6
    - 57nb5xfqtp
    - k9xcsjm6jz
    - fwe7oirqdt
    - tvhnin1k5a
    - lq01y8am7a
    - nql6lelo7y
    valid:
    - x88fw5rkd1
    - bevxcb8fqh
    - wto0m4gzcf
    - 9pl8ftg1ss
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - seyujw08fk
    - a0jt2iguwo
    - 1wkedvxg3b
    - girf10roms
    - c4zpwdmoyb
    - p3isgogusd
    - dv3zz43cfe
    - vtjdy8lzm4
    - c5kffb49z1
    - ga11c9a30b
    - 12fdy7ybfr
    - a0g1jf8i0l
    - dy6bcmykhs
    - t3uclbnwfe
    - 4sf56irk4g
    valid:
    - y9rfu9hvxf
    - yvxa6m1d3e
    - u05cp2relg
    - 886z3pa3us
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - ibtlnwae5o
    - 86dsaow6cj
    - v27q0ucpk9
    - hnaxhho64i
    - 3ifl03vxh2
    - 4uc8aqjcrc
    - 8pirwyrjqh
    - 19dxwqtzb5
    - hzwd2ptywx
    - p7o69z5bzg
    - nzndmb4cqx
    - 0y2m1gqog6
    - rjiq5ae27y
    - 39b0bswel2
    - xf68347gi8
    valid:
    - yglcr1ray4
    - tkakwejnl7
    - 5ozgizwvrw
    - ocxtjns999
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - cTI0eGFteHhqZg==
    - dTlvNHU3cHhwMQ==
    - Z2xnbG1mank2dQ==
    - YmZkcTl4N3dzdg==
    - NjU1NWpsMmF3ZQ==
    - MHo2YzBrajJuNQ==
    - eG90Z2s4anoyOQ==
    - bGl6YjZkaWQyNA==
    - MXd4dnVvdWIxag==
    - MHI3MmczdmptZg==
    - eDVlanZwNHQ3eQ==
    - dzFocjB1cmVpdw==
    - NGhkam5ocGI0dA==
    - a3d0M2l0bGwyYQ==
    - cGZhY3JoMnd5aw==
    valid:
    - YjUxdnRhaTF0dw==
    - ZmRpNTdjdWJyeA==
    - ZzR3bmJ6OGY3Mw==
    - Mm8zd3Vnd3k4ag==
  cidr:
    invalid:
    - 264.288.279.287/4
    multiple_valids:
    - 144.234.192.0/20
    - 144.234.0.0/20
    - 144.234.160.0/20
    - 144.234.208.0/20
    - 144.234.176.0/20
    - 144.234.96.0/20
    - 144.234.128.0/20
    - 144.234.224.0/20
    - 144.234.32.0/20
    - 144.234.80.0/20
    - 144.234.240.0/20
    - 144.234.144.0/20
    - 144.234.64.0/20
    - 144.234.16.0/20
    - 144.234.112.0/20
    valid:
    - 144.234.192.0/20
    - 144.234.0.0/20
    - 144.234.160.0/20
    - 144.234.208.0/20
  ipv4:
    invalid:
    - 259.270.256.286
    multiple_valids:
    - 144.234.202.94
    - 144.234.43.75
    - 144.234.140.48
    - 144.234.141.242
    - 144.234.234.80
    - 144.234.118.199
    - 144.234.4.238
    - 144.234.90.206
    - 144.234.50.199
    - 144.234.157.67
    - 144.234.122.167
    - 144.234.187.71
    - 144.234.52.132
    - 144.234.1.12
    - 144.234.171.130
    valid:
    - 144.234.202.94
    - 144.234.43.75
    - 144.234.140.48
    - 144.234.141.242
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f326
    - 2001:db8::34f4:0:0:f3b2
    - 2001:db8::34f4:0:0:f3a2
    - 2001:db8::34f4:0:0:f38c
    - 2001:db8::34f4:0:0:f31a
    - 2001:db8::34f4:0:0:f339
    - 2001:db8::34f4:0:0:f3c6
    - 2001:db8::34f4:0:0:f329
    - 2001:db8::34f4:0:0:f351
    - 2001:db8::34f4:0:0:f347
    - 2001:db8::34f4:0:0:f3e1
    - 2001:db8::34f4:0:0:f33c
    - 2001:db8::34f4:0:0:f391
    - 2001:db8::34f4:0:0:f37c
    - 2001:db8::34f4:0:0:f3b6
    valid:
    - 2001:db8::34f4:0:0:f326
    - 2001:db8::34f4:0:0:f3b2
    - 2001:db8::34f4:0:0:f3a2
    - 2001:db8::34f4:0:0:f38c
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 2e:1a:c5:e1:77:29
    - 96:62:7c:22:ed:62
    - f6:cc:fe:d3:7b:37
    - ff:1e:dd:27:dd:af
    - b3:61:db:5f:13:53
    - 24:3b:06:04:75:fb
    - be:8d:6a:eb:2b:52
    - b9:0d:44:c7:60:18
    - 00:25:be:6c:90:d8
    - b1:bd:b0:b9:05:b9
    - 11:ce:e0:b7:95:be
    - 9e:3b:65:63:b8:f9
    - f9:11:fe:bf:ce:96
    - 78:e2:6b:78:53:79
    - 96:1d:70:d9:5f:ec
    valid:
    - 8f:25:b9:e9:b2:7f
    - d8:02:05:45:74:71
    - bb:85:da:e7:92:ab
    - b5:1e:c5:0e:7f:ac
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 3gm9qb9t1d
    - ebgblpg1na
    - 2jwpb34gvp
    - mfyvmlc9ld
    - pgvru062pp
    - hrnrpqsv47
    - tjr3bl7auw
    - jef2lb22ie
    - uwg16ub4kf
    - f2wwt8byn2
    - 0mg0gtcwdj
    - q7b6bn7gba
    - 99xrj94u4g
    - gn41tghcmx
    - ejqskhqdpi
    valid:
    - ni1srnjma1
    - 1g5o9cxkc3
    - b374dlm0rd
    - odg64qw752
  time:
    invalid:
    - '2022-07-26 11:01:29.705810'
    multiple_valids:
    - '2022-07-26T05:31:29.705810+00:00'
    - '2022-08-18T05:31:29.705810+00:00'
    - '2022-09-10T05:31:29.705810+00:00'
    - '2022-10-03T05:31:29.705810+00:00'
    - '2022-10-26T05:31:29.705810+00:00'
    - '2022-11-18T05:31:29.705810+00:00'
    - '2022-12-11T05:31:29.705810+00:00'
    - '2023-01-03T05:31:29.705810+00:00'
    - '2023-01-26T05:31:29.705810+00:00'
    - '2023-02-18T05:31:29.705810+00:00'
    - '2023-03-13T05:31:29.705810+00:00'
    - '2023-04-05T05:31:29.705810+00:00'
    - '2023-04-28T05:31:29.705810+00:00'
    - '2023-05-21T05:31:29.705810+00:00'
    - '2023-06-13T05:31:29.705810+00:00'
    valid:
    - '2022-07-26T05:31:29.705311+00:00'
    - '2022-08-18T05:31:29.705810+00:00'
    - '2022-09-10T05:31:29.705810+00:00'
    - '2022-10-03T05:31:29.705810+00:00'
  url-http:
    invalid:
    - ht:/0s302jkp3gmxg14.com
    multiple_valids:
    - http://tt7zrkk7cgrdc17.com
    - http://1obmo5ljkq67e3q.com
    - http://i66tzuc7qyngdm3.com
    - http://9dsbjvkwh55dhuq.com
    - http://0atdf9iy88cxurt.com
    - http://m4c9ljehu1s6hvn.com
    - http://n3sy9kylhvdmvsx.com
    - http://jy1z26q6f41vtk3.com
    - http://odji1e6vhsesbmv.com
    - http://3b9mxml78qs3g7g.com
    - http://zkt3w0o7u9c2q6w.com
    - http://5lvng948fa6l0fp.com
    - http://437jdbjsfirqzjn.com
    - http://86y90kgp1olkdbf.com
    - http://85bumuqt5poipsd.com
    valid:
    - http://0fhxfhgpeoggd92.com
    - http://kyeamr6up8sl434.com
    - http://5ol1bni7k8y000w.com
    - http://u97ym4niryunym2.com
  url-https:
    invalid:
    - hts:/1j6frhqma7ihoi7.com
    multiple_valids:
    - https://0s871eckvm32kvt.com
    - https://bhul52k9php307j.com
    - https://puooahpi8v4uvwy.com
    - https://ppw95a4tjx5y6l6.com
    - https://jqvw6xie1gg3stx.com
    - https://aiao2cgwci999fo.com
    - https://bv4wjzgsum95zv9.com
    - https://04nn27x0d3e5m2w.com
    - https://niwswchur7rgy02.com
    - https://sdl9jvuxalu36a9.com
    - https://yfpbhw94en7g2mm.com
    - https://h13zp25fiftf4u8.com
    - https://088so06zsj1vsty.com
    - https://9mssq91o7hmguxd.com
    - https://0wkwhqc47tiqfa0.com
    valid:
    - https://gwczb43lk48vzwd.com
    - https://cvnn44066psh5fs.com
    - https://3jved0d0dkbiaa7.com
    - https://wc8tjn8h87sxlkz.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 3387d4c4-0ca4-11ed-a487-7c8ae1979a87
    - 3387d4c5-0ca4-11ed-9d3b-7c8ae1979a87
    - 3387d4c6-0ca4-11ed-97c9-7c8ae1979a87
    - 3387d4c7-0ca4-11ed-8a02-7c8ae1979a87
    - 3387d4c8-0ca4-11ed-9aba-7c8ae1979a87
    - 3387d4c9-0ca4-11ed-9b7c-7c8ae1979a87
    - 3387d4ca-0ca4-11ed-b272-7c8ae1979a87
    - 3387d4cb-0ca4-11ed-a662-7c8ae1979a87
    - 3387e84f-0ca4-11ed-867e-7c8ae1979a87
    - 3387e850-0ca4-11ed-9b71-7c8ae1979a87
    - 3387e851-0ca4-11ed-acf0-7c8ae1979a87
    - 3387e852-0ca4-11ed-b6d9-7c8ae1979a87
    - 3387e853-0ca4-11ed-81a6-7c8ae1979a87
    - 3387e854-0ca4-11ed-ae1f-7c8ae1979a87
    - 3387e855-0ca4-11ed-94f2-7c8ae1979a87
    valid:
    - 3387d4c0-0ca4-11ed-b2a9-7c8ae1979a87
    - 3387d4c1-0ca4-11ed-9a3d-7c8ae1979a87
    - 3387d4c2-0ca4-11ed-a2fd-7c8ae1979a87
    - 3387d4c3-0ca4-11ed-abe5-7c8ae1979a87
unique_attribute:
- name
