imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
name: Tenant
provider_name: Aci
schemas:
- attribute: name
  description: Name of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - i7moew9334
    - jh18qbbyf7
    - eu1sr0tr05
    - j4exsg8olp
    - wmkykh7prs
    - h9cwfcdyqe
    - 1z5zp582gm
    - aj1wljo4fk
    - vefuu8rptd
    - 1hyefaypa3
    - m002qjpnx3
    - re9v6zi733
    - 5h52ouuvae
    - g91tchpqvv
    - tfk0sekrxg
    valid:
    - r2z0t7fmx2
    - 35cblg62s5
    - eozgz92vnh
    - s6xhp6i9ux
  type: string
- attribute: name_alias
  computed: true
  description: annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 678bu08ewv
    - 5vypczc7fb
    - z77ix7qzwi
    - eki3ar806o
    - 7oppitjgqi
    - kbxm0y7w3z
    - q4t8gcbgln
    - o48oq89tb4
    - 70nko183u9
    - i2xigi4d8v
    - txrh4ykr3w
    - lgvaq7qecq
    - gfd2g24ozk
    - ggs3t1n6d1
    - gwycliiwrx
    valid:
    - ji7oj8j3d9
    - sr63gcjmvh
    - 3mi4aumelx
    - rzoifritxy
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - m68tb7lkul
    - tmjiugfqh7
    - vke46pkmxp
    - wjw3j9hpls
    - nbqrexw3su
    - h0go9tppx0
    - sn8aahv7r6
    - go2qj2odtv
    - pdksq61bk0
    - i391etdjdu
    - dojhxp9no2
    - 2itxui6f7w
    - 5yfkh1lbsq
    - t6v0dpqnc7
    - 40dnunhq47
    valid:
    - scq32gecw1
    - bkzpauvdxk
    - uemjk5k5lm
    - hihnpuoii0
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - z1n5bfpxh4
    - qkmft75y11
    - tihqak3o9v
    - q8nsgaguo2
    - myjntb492b
    - yqw4xcvtbc
    - 5m1ldkl66i
    - r4tbcr5l9e
    - 3y9b6tj5b9
    - ggcs5atko4
    - xlcelcrz4m
    - aaj20j94ut
    - fm4343l6i5
    - mo2oq6tr31
    - jcjyqd62qm
    valid:
    - wsr61xd03c
    - aw8sih0oq5
    - 9udti5pyd9
    - 2urt2uu6fc
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - Y3RvaTYzcnhwZg==
    - M3VxdHRqYThkMQ==
    - czE5dW04ZWtuMg==
    - YzFoY2hhYnl0Yg==
    - ZnVsYjFjbjR6dQ==
    - MGZtcWRlc2IzaQ==
    - dmlpdngxbW1jNg==
    - YTV4c2gwdnhpYQ==
    - NGFlY256b2FtcQ==
    - YnZqaDg3dGtjOA==
    - d3FmOW8wZ212eg==
    - aDh1YWN2N2RmYQ==
    - MDFqeWV1NjIzYg==
    - enBnNHF4YjRhOA==
    - Y254ZXVmMmdheg==
    valid:
    - OWlmemdjcjNkNg==
    - NWJpN2hmMjc4MQ==
    - ZjE2a3V1djBiNQ==
    - aTNteTdodTJtbA==
  cidr:
    invalid:
    - 293.257.256.288/6
    multiple_valids:
    - 61.61.224.0/20
    - 61.61.160.0/20
    - 61.61.16.0/20
    - 61.61.32.0/20
    - 61.61.128.0/20
    - 61.61.48.0/20
    - 61.61.96.0/20
    - 61.61.176.0/20
    - 61.61.208.0/20
    - 61.61.240.0/20
    - 61.61.112.0/20
    - 61.61.0.0/20
    - 61.61.144.0/20
    - 61.61.80.0/20
    - 61.61.64.0/20
    valid:
    - 61.61.224.0/20
    - 61.61.160.0/20
    - 61.61.16.0/20
    - 61.61.32.0/20
  ipv4:
    invalid:
    - 285.266.267.278
    multiple_valids:
    - 61.61.102.242
    - 61.61.130.33
    - 61.61.243.107
    - 61.61.72.177
    - 61.61.199.15
    - 61.61.79.129
    - 61.61.72.219
    - 61.61.205.197
    - 61.61.86.205
    - 61.61.237.221
    - 61.61.92.229
    - 61.61.144.93
    - 61.61.23.177
    - 61.61.12.138
    - 61.61.135.177
    valid:
    - 61.61.102.242
    - 61.61.130.33
    - 61.61.243.107
    - 61.61.72.177
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f332
    - 2001:db8::34f4:0:0:f3ce
    - 2001:db8::34f4:0:0:f371
    - 2001:db8::34f4:0:0:f383
    - 2001:db8::34f4:0:0:f33c
    - 2001:db8::34f4:0:0:f343
    - 2001:db8::34f4:0:0:f39d
    - 2001:db8::34f4:0:0:f36b
    - 2001:db8::34f4:0:0:f334
    - 2001:db8::34f4:0:0:f3c8
    - 2001:db8::34f4:0:0:f315
    - 2001:db8::34f4:0:0:f30e
    - 2001:db8::34f4:0:0:f31b
    - 2001:db8::34f4:0:0:f3c1
    - 2001:db8::34f4:0:0:f342
    valid:
    - 2001:db8::34f4:0:0:f332
    - 2001:db8::34f4:0:0:f3ce
    - 2001:db8::34f4:0:0:f371
    - 2001:db8::34f4:0:0:f383
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - fd:48:14:1e:70:b4
    - 88:89:f3:a4:44:e6
    - bb:11:72:f2:e8:ef
    - 11:b0:3a:0a:32:b6
    - e8:be:c2:90:bd:27
    - 1e:18:87:6f:9a:29
    - 49:c8:53:43:75:3e
    - 94:b9:18:0c:1e:bd
    - be:2e:b5:4d:db:39
    - 02:3e:8c:77:48:ac
    - 4a:88:10:7c:39:21
    - 4d:5a:95:ce:49:78
    - 23:20:31:c9:a9:80
    - 72:c7:6e:b9:93:de
    - 62:67:67:d1:f0:ce
    valid:
    - f9:dc:db:6f:16:0e
    - d9:81:8d:dc:4c:e7
    - d6:fd:1f:01:b4:4b
    - 5b:1b:6b:3b:a0:6a
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - xb8pgl7hlm
    - fyoyfxppn5
    - je2khkduxb
    - 6f32h9tezt
    - icfbtqkv4o
    - xjdzmoz3vm
    - uodj8fdn2i
    - lr61p4csgl
    - sv4qz6ufzx
    - z97j2xttld
    - zvlf3kz3f4
    - 34amr5qu3t
    - 5z34mq3ccx
    - me3e58yf6c
    - jqhar5wv4a
    valid:
    - 7ymhoe028c
    - slm41m142b
    - j3m79ffd8o
    - rl7d8s8sx2
  time:
    invalid:
    - '2022-08-02 10:47:50.436830'
    multiple_valids:
    - '2022-08-02T05:17:50.436830+00:00'
    - '2022-08-25T05:17:50.436830+00:00'
    - '2022-09-17T05:17:50.436830+00:00'
    - '2022-10-10T05:17:50.436830+00:00'
    - '2022-11-02T05:17:50.436830+00:00'
    - '2022-11-25T05:17:50.436830+00:00'
    - '2022-12-18T05:17:50.436830+00:00'
    - '2023-01-10T05:17:50.436830+00:00'
    - '2023-02-02T05:17:50.436830+00:00'
    - '2023-02-25T05:17:50.436830+00:00'
    - '2023-03-20T05:17:50.436830+00:00'
    - '2023-04-12T05:17:50.436830+00:00'
    - '2023-05-05T05:17:50.436830+00:00'
    - '2023-05-28T05:17:50.436830+00:00'
    - '2023-06-20T05:17:50.436830+00:00'
    valid:
    - '2022-08-02T05:17:50.436830+00:00'
    - '2022-08-25T05:17:50.436830+00:00'
    - '2022-09-17T05:17:50.436830+00:00'
    - '2022-10-10T05:17:50.436830+00:00'
  url-http:
    invalid:
    - ht:/uw7xp514umpxwn6.com
    multiple_valids:
    - http://7ozf923lyeqwd75.com
    - http://ritj1v8761mqd0k.com
    - http://kbjwuvji0j4jqwx.com
    - http://sgkt0xxk7mo3hz5.com
    - http://dn1l2cfi6a1063w.com
    - http://rwela3scekxiw3w.com
    - http://dek5drsuzs6egqe.com
    - http://p6dc33qv992curj.com
    - http://rtrdi1ooqrt7w5h.com
    - http://b8ger9up5vr992m.com
    - http://zsclrr0k1pgqg6f.com
    - http://54sgztu972c93yc.com
    - http://eullonvbyealelz.com
    - http://ytjh1okhakfr8aq.com
    - http://nydnwo7xqlt5ng6.com
    valid:
    - http://2dpbtvx454oitl3.com
    - http://hdtg1jei2oic3fs.com
    - http://89syiewtnh6tcxw.com
    - http://xm870w2lgu7be36.com
  url-https:
    invalid:
    - hts:/ud5kksl948mzqdq.com
    multiple_valids:
    - https://b1ymx6hn3uytyul.com
    - https://xwywkji9qmd3eh3.com
    - https://8s6bq27e44vtdx4.com
    - https://c0tqsw7bno7g258.com
    - https://kfn84dc69uh2hjs.com
    - https://rbum3zu9rwyxnnc.com
    - https://h4ckor4i7e8yxcx.com
    - https://xtdq7pcdmi7eof1.com
    - https://v6fkozxg4kw05au.com
    - https://x6snfe7ncqfm550.com
    - https://x3hvape6begkos0.com
    - https://ch2qikqpvimfd3o.com
    - https://a6vbxmmia3ifzi0.com
    - https://3x7b778v3kmgm5i.com
    - https://v8ti289aap7ws40.com
    valid:
    - https://3lhufwplskopzc1.com
    - https://j9lxakk935jxucl.com
    - https://k6wjc1p885ivaya.com
    - https://qrkqbz7purngnnj.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 74197ab4-1222-11ed-9f13-dc214861057a
    - 74197ab5-1222-11ed-85d6-dc214861057a
    - 74197ab6-1222-11ed-9925-dc214861057a
    - 74197ab7-1222-11ed-b23a-dc214861057a
    - 74197ab8-1222-11ed-8fbd-dc214861057a
    - 74197ab9-1222-11ed-8872-dc214861057a
    - 74197aba-1222-11ed-bdae-dc214861057a
    - 74197abb-1222-11ed-b7ba-dc214861057a
    - 74197abc-1222-11ed-9991-dc214861057a
    - 74197abd-1222-11ed-bd42-dc214861057a
    - 74197abe-1222-11ed-8709-dc214861057a
    - 74197abf-1222-11ed-afcf-dc214861057a
    - 74197ac0-1222-11ed-9887-dc214861057a
    - 74197ac1-1222-11ed-aa68-dc214861057a
    - 74197ac2-1222-11ed-ba9c-dc214861057a
    valid:
    - 74197ab0-1222-11ed-9ee4-dc214861057a
    - 74197ab1-1222-11ed-bc4b-dc214861057a
    - 74197ab2-1222-11ed-8e5f-dc214861057a
    - 74197ab3-1222-11ed-b96b-dc214861057a
unique_attribute:
- name
