imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
name: Tenant
provider_name: Aci
schemas:
- attribute: name
  description: Name of Tenant
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - mpk50cvt6b
    - wqj4nmy3dz
    - ltnv2b2fvk
    - 2v7g27thby
    - 2q2vxlh1s9
    - wagkf5vv8y
    - q62gh1y6e0
    - kk5sbhpv8j
    - 90xzojgpwy
    - 83vegbxz8u
    - fwm4odhz6n
    - 2vgobv04jy
    - e1cpnc5mub
    - 0d303dceor
    - fnlfshzjxz
    valid:
    - fe8bh6rjax
    - 70bt57y7dd
    - 62hd01ny1l
    - x1mh8z4tqq
  type: string
- attribute: name_alias
  computed: true
  description: annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - oetqz8161u
    - nd0occz4xf
    - jn2s754cxn
    - x3fif9s4w3
    - rcoxigtzte
    - ttm1nt7627
    - sjlghvb9r2
    - 7i3489no7h
    - xz05g3ytpw
    - ayjajnb1t0
    - ic0yu0e6wq
    - 56r0i8u5lq
    - ytj3xrczoh
    - 4cqn4snp16
    - vyf3ae9brz
    valid:
    - 7pkh3ihvgl
    - odo9i29m8e
    - dmh9hvgiv3
    - 8db2mq3hkj
  type: string
- attribute: description
  computed: true
  description: description for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 8zo7s5zlr6
    - u28fyjhc3p
    - kqyhbzvq8m
    - gidnzx3dq1
    - gfk2fofkw8
    - iuz89eysr4
    - ssnm9duene
    - ggkx7zmjka
    - sgyp6vh1sy
    - 9hjow4bwwc
    - 42ipofbsak
    - muw3kg6tqv
    - 0e9xz00imm
    - 91bdzt9s2w
    - 24lyuxdg6h
    valid:
    - scwnpoaact
    - pnfz746x56
    - c9g2f18x5e
    - rxhc1z3pwh
  type: string
- attribute: annotation
  computed: true
  default: orchestrator:terraform
  description: Annotation for Tenant
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - j747ldswq6
    - yzgaikf836
    - fqwopa4682
    - s3sfxxx3i4
    - 2ptibpvo25
    - evx798jgnn
    - 58jcc5cj60
    - 2ugym68u3c
    - yks3kya09a
    - k6zag2dt42
    - hv6tbuy36i
    - yw9qteun0g
    - 1y9f2dqb6d
    - nl1b7glsyz
    - bby9hp9zd5
    valid:
    - a7dq3zym60
    - p42jyg0yus
    - olz76h7mgr
    - 62r5q94x96
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - bTF0Nmt4MHN1dA==
    - c2Fmd3J5ZWUycA==
    - bWlqM3J1YXpuNg==
    - M3B2ZDAyNjQwYg==
    - NXFlM3BuNmgxZw==
    - ZmQzYm5zZWN0ag==
    - dHhnNTQ0OW8xaQ==
    - MWs3Y3I4bncwcw==
    - Nnl3Y3dmaGMxNA==
    - bWV0bjU2Y3B6dQ==
    - ZXRmd3BzMzR6NA==
    - OWxpN3IxbGwwbg==
    - d3JoNnp1bzhpcQ==
    - eGNiZmFwZTQ2Nw==
    - ODdmM2ltMmhqNQ==
    valid:
    - ZTV0ZTJpZGZqNA==
    - cjE2b3c4cGF0eg==
    - M21ramptaXRkOA==
    - bW11aHV6bzZneg==
  cidr:
    invalid:
    - 272.260.256.285/27
    multiple_valids:
    - 140.37.144.0/20
    - 140.37.176.0/20
    - 140.37.0.0/20
    - 140.37.128.0/20
    - 140.37.112.0/20
    - 140.37.80.0/20
    - 140.37.32.0/20
    - 140.37.240.0/20
    - 140.37.208.0/20
    - 140.37.192.0/20
    - 140.37.96.0/20
    - 140.37.160.0/20
    - 140.37.16.0/20
    - 140.37.48.0/20
    - 140.37.224.0/20
    valid:
    - 140.37.144.0/20
    - 140.37.176.0/20
    - 140.37.0.0/20
    - 140.37.128.0/20
  ipv4:
    invalid:
    - 292.297.263.287
    multiple_valids:
    - 140.37.46.75
    - 140.37.127.39
    - 140.37.44.32
    - 140.37.6.186
    - 140.37.114.200
    - 140.37.244.173
    - 140.37.7.13
    - 140.37.198.188
    - 140.37.56.217
    - 140.37.8.119
    - 140.37.47.88
    - 140.37.145.66
    - 140.37.136.216
    - 140.37.182.238
    - 140.37.78.129
    valid:
    - 140.37.46.75
    - 140.37.127.39
    - 140.37.44.32
    - 140.37.6.186
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f3b8
    - 2001:db8::34f4:0:0:f357
    - 2001:db8::34f4:0:0:f34b
    - 2001:db8::34f4:0:0:f3c0
    - 2001:db8::34f4:0:0:f3c3
    - 2001:db8::34f4:0:0:f35d
    - 2001:db8::34f4:0:0:f31d
    - 2001:db8::34f4:0:0:f33a
    - 2001:db8::34f4:0:0:f3cc
    - 2001:db8::34f4:0:0:f30c
    - 2001:db8::34f4:0:0:f337
    - 2001:db8::34f4:0:0:f3b5
    - 2001:db8::34f4:0:0:f3b7
    - 2001:db8::34f4:0:0:f366
    - 2001:db8::34f4:0:0:f3a4
    valid:
    - 2001:db8::34f4:0:0:f3b8
    - 2001:db8::34f4:0:0:f357
    - 2001:db8::34f4:0:0:f34b
    - 2001:db8::34f4:0:0:f3c0
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 07:8e:e1:05:4a:d7
    - 54:9b:6d:22:5a:0b
    - 2d:06:5d:59:39:08
    - b3:65:ad:d3:e8:6a
    - 5f:2c:34:fa:82:3c
    - ba:28:82:8d:87:5f
    - da:1c:27:0f:81:12
    - 9c:72:d7:51:84:62
    - 9e:f4:99:f6:e2:3b
    - ba:bd:3e:db:bd:39
    - 1c:29:d6:1d:2d:a0
    - c5:69:47:ea:40:88
    - 08:d0:7d:9e:e6:a2
    - af:1f:9f:b5:1f:9a
    - 84:d0:7d:f6:ed:db
    valid:
    - 22:a6:f5:53:35:dd
    - 0a:cb:8b:77:27:d4
    - 00:2c:83:ce:21:56
    - 29:00:61:f0:25:af
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - i60lzpdwvv
    - 9o27ry7awh
    - t8acyjbxob
    - ak22r2tnva
    - fxh4p84w9m
    - zd8xujmxke
    - 74ifjqtvuh
    - hou4t98sks
    - uqny3emnk5
    - h0jvggoxfu
    - 7fwiv6d3o8
    - oxlv6zk14u
    - knaszert61
    - krhhouhhi2
    - mdkl4nd9gs
    valid:
    - frijcc1qn7
    - usofx1f3ef
    - njyolx19n8
    - l26d6vuvb0
  time:
    invalid:
    - '2022-07-29 11:13:57.465316'
    multiple_valids:
    - '2022-07-29T05:43:57.465316+00:00'
    - '2022-08-21T05:43:57.465316+00:00'
    - '2022-09-13T05:43:57.465316+00:00'
    - '2022-10-06T05:43:57.465316+00:00'
    - '2022-10-29T05:43:57.465316+00:00'
    - '2022-11-21T05:43:57.465316+00:00'
    - '2022-12-14T05:43:57.465316+00:00'
    - '2023-01-06T05:43:57.465316+00:00'
    - '2023-01-29T05:43:57.465316+00:00'
    - '2023-02-21T05:43:57.465316+00:00'
    - '2023-03-16T05:43:57.465316+00:00'
    - '2023-04-08T05:43:57.465316+00:00'
    - '2023-05-01T05:43:57.465316+00:00'
    - '2023-05-24T05:43:57.465316+00:00'
    - '2023-06-16T05:43:57.465316+00:00'
    valid:
    - '2022-07-29T05:43:57.465316+00:00'
    - '2022-08-21T05:43:57.465316+00:00'
    - '2022-09-13T05:43:57.465316+00:00'
    - '2022-10-06T05:43:57.465316+00:00'
  url-http:
    invalid:
    - ht:/lrork4v6vrqeuao.com
    multiple_valids:
    - http://mpp7w9zn03i37i8.com
    - http://dhe9aaor10ljtbt.com
    - http://kvb5ayt6sdqsyx4.com
    - http://847fq9dl9lllis2.com
    - http://k1jlixh505yl2d4.com
    - http://9dvayjmxpa6v08t.com
    - http://py5vrz423ae8w58.com
    - http://rxh8beat4f8b3nq.com
    - http://bxsuounv07j2ef7.com
    - http://pqxb4amh9rmzz0b.com
    - http://6yhu0ncyu9msifv.com
    - http://qy3gqshvx8w5n1b.com
    - http://zlmoy1ev2wxkp97.com
    - http://ogw7i726p06n5lz.com
    - http://qktanghuyhcdbc3.com
    valid:
    - http://y4zgee9e4mzrm58.com
    - http://4zyhlg2ixcvxjhq.com
    - http://f8z2flx7mpaqrhi.com
    - http://l6fs92jzle6yf65.com
  url-https:
    invalid:
    - hts:/z441d3fd5w6eosx.com
    multiple_valids:
    - https://qq15ei93gbrop76.com
    - https://n93ret8ny759yqm.com
    - https://ojhmkpm635zp2qx.com
    - https://53iri6wlgojt4xd.com
    - https://7dngkw3lyjlu8n7.com
    - https://7nu4dmz1xpi3r3p.com
    - https://0nsc9kzmbth1eg8.com
    - https://zbikzg8uxm7ouib.com
    - https://66mf7dktf1y1epp.com
    - https://44tyhb6qhvd1mza.com
    - https://0qom0b10u9wnc0a.com
    - https://stlnmgkp90re6y2.com
    - https://k3k1cyaw6raxsjf.com
    - https://nt281m7um7srzso.com
    - https://oeepqomdlkd68yd.com
    valid:
    - https://0zxgdhynk4tlleq.com
    - https://99uhg6bkagx4zkl.com
    - https://69bkzqw2dmfajui.com
    - https://zll30jrrh1iv7ms.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 7078218f-0f01-11ed-9960-7c8ae1979a87
    - 70782190-0f01-11ed-82ff-7c8ae1979a87
    - 70782191-0f01-11ed-aba5-7c8ae1979a87
    - 70782192-0f01-11ed-87de-7c8ae1979a87
    - 70782193-0f01-11ed-b9dc-7c8ae1979a87
    - 70782194-0f01-11ed-9ebf-7c8ae1979a87
    - 70782195-0f01-11ed-946b-7c8ae1979a87
    - 70782196-0f01-11ed-b2f4-7c8ae1979a87
    - 70782197-0f01-11ed-b4a2-7c8ae1979a87
    - 70782198-0f01-11ed-b401-7c8ae1979a87
    - 70782199-0f01-11ed-9f1b-7c8ae1979a87
    - 7078219a-0f01-11ed-9d67-7c8ae1979a87
    - 7078219b-0f01-11ed-b5a2-7c8ae1979a87
    - 7078219c-0f01-11ed-8fcd-7c8ae1979a87
    - 7078219d-0f01-11ed-93ef-7c8ae1979a87
    valid:
    - 7078218b-0f01-11ed-9032-7c8ae1979a87
    - 7078218c-0f01-11ed-a439-7c8ae1979a87
    - 7078218d-0f01-11ed-8bcc-7c8ae1979a87
    - 7078218e-0f01-11ed-a08c-7c8ae1979a87
unique_attribute:
- name
