datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/Jeffail/gabs/v2
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - bThkMm9sYjJ4cw==
    - Z3psNHNteTM4dg==
    - OWZiZ3l0dWZpYg==
    - Z3lkbzVzc3Y4bg==
    - MmVlYmpuOWd0Yw==
    - c2k3empseGMzeA==
    - cGR5Y3E2MGxncQ==
    - bmtmM2hvb2tvOA==
    - N2FlcnZyMWU2bA==
    - aG9wbmZjOWdqMQ==
    - MWV0cG96ZGdmYg==
    - ODYzZ2QxbHN5OA==
    - b2U5a3hjdWNnZw==
    - N3o1MW51MGVicg==
    - M2Y1eXp6cWhlYQ==
    valid:
    - dmZ3eXV4NnJ4OA==
    - cHRnb2RnYWR1NQ==
    - MHZmdHRqNjA0eA==
    - ZWhjaDJpaGJxaA==
  cidr:
    invalid:
    - 299.276.298.271/14
    multiple_valids:
    - 9.118.96.0/20
    - 9.118.208.0/20
    - 9.118.16.0/20
    - 9.118.240.0/20
    - 9.118.112.0/20
    - 9.118.144.0/20
    - 9.118.64.0/20
    - 9.118.32.0/20
    - 9.118.224.0/20
    - 9.118.176.0/20
    - 9.118.0.0/20
    - 9.118.80.0/20
    - 9.118.128.0/20
    - 9.118.48.0/20
    - 9.118.160.0/20
    valid:
    - 9.118.96.0/20
    - 9.118.208.0/20
    - 9.118.16.0/20
    - 9.118.240.0/20
  ipv4:
    invalid:
    - 300.270.282.266
    multiple_valids:
    - 9.118.15.22
    - 9.118.161.143
    - 9.118.156.77
    - 9.118.44.19
    - 9.118.126.86
    - 9.118.175.71
    - 9.118.248.92
    - 9.118.241.142
    - 9.118.160.239
    - 9.118.52.155
    - 9.118.216.43
    - 9.118.48.39
    - 9.118.129.103
    - 9.118.37.85
    - 9.118.158.2
    valid:
    - 9.118.15.22
    - 9.118.161.143
    - 9.118.156.77
    - 9.118.44.19
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f3e2
    - 2001:db8::34f4:0:0:f3f9
    - 2001:db8::34f4:0:0:f340
    - 2001:db8::34f4:0:0:f39c
    - 2001:db8::34f4:0:0:f30c
    - 2001:db8::34f4:0:0:f3a3
    - 2001:db8::34f4:0:0:f3dd
    - 2001:db8::34f4:0:0:f309
    - 2001:db8::34f4:0:0:f32b
    - 2001:db8::34f4:0:0:f39f
    - 2001:db8::34f4:0:0:f3ec
    - 2001:db8::34f4:0:0:f3e3
    - 2001:db8::34f4:0:0:f3c8
    - 2001:db8::34f4:0:0:f308
    - 2001:db8::34f4:0:0:f36c
    valid:
    - 2001:db8::34f4:0:0:f3e2
    - 2001:db8::34f4:0:0:f3f9
    - 2001:db8::34f4:0:0:f340
    - 2001:db8::34f4:0:0:f39c
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 8a:d3:fc:5d:94:a5
    - 47:e2:57:d8:15:3c
    - 3b:63:97:f3:45:05
    - 94:05:79:13:17:3d
    - ea:0a:f8:25:59:fb
    - 5e:d7:cc:9d:c8:36
    - 63:04:c4:69:58:6f
    - 50:09:e5:b0:95:7b
    - 49:07:00:fe:0d:98
    - 9c:91:21:35:ad:bf
    - 25:a4:17:4d:17:7a
    - 8f:71:73:c6:2a:91
    - 9d:f3:f6:e4:c8:12
    - 9f:52:eb:4a:f3:99
    - 67:52:d3:f9:73:d0
    valid:
    - 92:4e:46:bb:43:8b
    - 82:30:67:9d:b9:68
    - 8c:41:bf:49:e3:da
    - 63:95:b1:ea:7c:3b
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - wnnzd0rjmn
    - l353hqgnbl
    - 392d1v7yjh
    - 8r2j74hgds
    - 0q2xm77nge
    - l328ll5nsf
    - 11y16o0gvq
    - jlui3hf9gq
    - q24wslx2vq
    - pjxby0fp61
    - 8luxeq0xrt
    - 3anaisb0hp
    - sh80gdz94q
    - tp7jh7rn84
    - 2kz3rhula3
    valid:
    - r5y77ot4w8
    - 6o1uei3g1t
    - momkjncezv
    - 3lb6ik6wpm
  time:
    invalid:
    - '2022-08-02 10:47:54.531832'
    multiple_valids:
    - '2022-08-02T05:17:54.531832+00:00'
    - '2022-08-25T05:17:54.531832+00:00'
    - '2022-09-17T05:17:54.531832+00:00'
    - '2022-10-10T05:17:54.531832+00:00'
    - '2022-11-02T05:17:54.531832+00:00'
    - '2022-11-25T05:17:54.531832+00:00'
    - '2022-12-18T05:17:54.531832+00:00'
    - '2023-01-10T05:17:54.531832+00:00'
    - '2023-02-02T05:17:54.531832+00:00'
    - '2023-02-25T05:17:54.531832+00:00'
    - '2023-03-20T05:17:54.531832+00:00'
    - '2023-04-12T05:17:54.531832+00:00'
    - '2023-05-05T05:17:54.531832+00:00'
    - '2023-05-28T05:17:54.531832+00:00'
    - '2023-06-20T05:17:54.531832+00:00'
    valid:
    - '2022-08-02T05:17:54.531832+00:00'
    - '2022-08-25T05:17:54.531832+00:00'
    - '2022-09-17T05:17:54.531832+00:00'
    - '2022-10-10T05:17:54.531832+00:00'
  url-http:
    invalid:
    - ht:/tbm7q4dg2j44gh2.com
    multiple_valids:
    - http://7suogtucgvm0pbz.com
    - http://p5osv7v6rhd62j5.com
    - http://jhxy8n4xn136nb7.com
    - http://4mehe1w15pewk4y.com
    - http://wv5hlacnzazdax7.com
    - http://aiiq3olfns8eedn.com
    - http://5olmynwtam7nkua.com
    - http://gr4iu4l48x2y6xt.com
    - http://nkzgyaogc7u8nuu.com
    - http://rduubvljj9mm210.com
    - http://k78ph36gk9h32pn.com
    - http://waukz32g9r6zyzv.com
    - http://d6eexh0tz5nzkss.com
    - http://c9elmm3fhwmqnud.com
    - http://09hs2ywxuxiar28.com
    valid:
    - http://lrjg0a2e4s0rxr1.com
    - http://pvz9bwgrly3ku1x.com
    - http://fot7iqw1c8ymztp.com
    - http://5fed0w002m4xzvw.com
  url-https:
    invalid:
    - hts:/09aox9vsydgghtb.com
    multiple_valids:
    - https://9ha6xca43acciq4.com
    - https://4asogn650f0pfxm.com
    - https://buewzj5k9kt9xod.com
    - https://3zorry4tg3rxbqk.com
    - https://bpuib3rs7ijv3hq.com
    - https://ohznl1x6lmtii8o.com
    - https://s5p95vj1pycozl4.com
    - https://xveisbz4ezxppvr.com
    - https://8h8rv568efcffl4.com
    - https://0sb36o51k7zz7ha.com
    - https://jif3u8ngoyijrki.com
    - https://r9em3x4r8cr6kmv.com
    - https://fi497rh8vcjs6r7.com
    - https://f5x2fqkw6tcxl4d.com
    - https://uuljmo9zh0el93l.com
    valid:
    - https://kk1kwhippatne04.com
    - https://5w9ydtgigtvpqoo.com
    - https://x27wnvo5cot4au9.com
    - https://l8hfx463y3yagy1.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 768a53bc-1222-11ed-ad5f-dc214861057a
    - 768a53bd-1222-11ed-bece-dc214861057a
    - 768a53be-1222-11ed-9a84-dc214861057a
    - 768a53bf-1222-11ed-affc-dc214861057a
    - 768a53c0-1222-11ed-bdb6-dc214861057a
    - 768a53c1-1222-11ed-836b-dc214861057a
    - 768a53c2-1222-11ed-89bd-dc214861057a
    - 768a53c3-1222-11ed-bee5-dc214861057a
    - 768a53c4-1222-11ed-9a26-dc214861057a
    - 768a53c5-1222-11ed-b058-dc214861057a
    - 768a53c6-1222-11ed-b0e2-dc214861057a
    - 768a53c7-1222-11ed-b8d5-dc214861057a
    - 768a53c8-1222-11ed-b377-dc214861057a
    - 768a53c9-1222-11ed-90d9-dc214861057a
    - 768a53ca-1222-11ed-932b-dc214861057a
    valid:
    - 768a53b8-1222-11ed-a555-dc214861057a
    - 768a53b9-1222-11ed-8193-dc214861057a
    - 768a53ba-1222-11ed-83a3-dc214861057a
    - 768a53bb-1222-11ed-8c4e-dc214861057a
