datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/Jeffail/gabs/v2
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - cmthM2RqN3Nnbw==
    - MWRsZDhucGs4Mw==
    - eXZiZ3U5MmxvMQ==
    - eGNpejZnN2ZrZQ==
    - aDU1Zm5vanRleQ==
    - NjBkZjQ5N3p2Yg==
    - MTRsZzF4a2FjZA==
    - bjlsaHcxeWkybg==
    - eDZ3OWJyMnR1Zg==
    - cXNxNGo2c3c3bw==
    - ZjFsdTk3a25paQ==
    - YnB0Yzh0dnRibg==
    - dnQwMjFudGkwdA==
    - bmljMnAxZnkwbQ==
    - bWVuc2ZjdTZpaw==
    valid:
    - ZWRycHp5ZnJ0NQ==
    - NWUwNDMyZnlyNw==
    - djM4c3JsZDU2cw==
    - bHN3djM4b29lOA==
  cidr:
    invalid:
    - 261.268.280.273/24
    multiple_valids:
    - 235.131.144.0/20
    - 235.131.32.0/20
    - 235.131.192.0/20
    - 235.131.16.0/20
    - 235.131.80.0/20
    - 235.131.208.0/20
    - 235.131.96.0/20
    - 235.131.160.0/20
    - 235.131.112.0/20
    - 235.131.0.0/20
    - 235.131.128.0/20
    - 235.131.48.0/20
    - 235.131.176.0/20
    - 235.131.224.0/20
    - 235.131.64.0/20
    valid:
    - 235.131.144.0/20
    - 235.131.32.0/20
    - 235.131.192.0/20
    - 235.131.16.0/20
  ipv4:
    invalid:
    - 270.273.297.257
    multiple_valids:
    - 235.131.34.73
    - 235.131.168.145
    - 235.131.3.83
    - 235.131.58.168
    - 235.131.82.80
    - 235.131.23.37
    - 235.131.69.165
    - 235.131.119.73
    - 235.131.110.79
    - 235.131.106.8
    - 235.131.210.98
    - 235.131.143.221
    - 235.131.197.212
    - 235.131.39.42
    - 235.131.133.28
    valid:
    - 235.131.34.73
    - 235.131.168.145
    - 235.131.3.83
    - 235.131.58.168
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f32f
    - 2001:db8::34f4:0:0:f3dc
    - 2001:db8::34f4:0:0:f31c
    - 2001:db8::34f4:0:0:f306
    - 2001:db8::34f4:0:0:f3b2
    - 2001:db8::34f4:0:0:f30e
    - 2001:db8::34f4:0:0:f3a6
    - 2001:db8::34f4:0:0:f396
    - 2001:db8::34f4:0:0:f358
    - 2001:db8::34f4:0:0:f3a8
    - 2001:db8::34f4:0:0:f34b
    - 2001:db8::34f4:0:0:f3b0
    - 2001:db8::34f4:0:0:f395
    - 2001:db8::34f4:0:0:f33a
    - 2001:db8::34f4:0:0:f3cc
    valid:
    - 2001:db8::34f4:0:0:f32f
    - 2001:db8::34f4:0:0:f3dc
    - 2001:db8::34f4:0:0:f31c
    - 2001:db8::34f4:0:0:f306
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 56:c8:a9:89:cb:25
    - 6e:af:f8:af:ca:24
    - d6:12:8d:01:da:59
    - 46:6a:43:bb:c4:45
    - 70:22:85:a5:64:3f
    - a2:f9:84:52:ad:6f
    - b2:7b:65:83:21:f7
    - b3:6f:78:c3:84:92
    - 4f:3c:5b:f9:88:69
    - 86:39:52:28:96:ea
    - 81:42:85:13:3f:98
    - a5:4c:0f:9d:13:79
    - 96:bf:88:a2:64:46
    - f5:fe:e7:45:cc:1d
    - 63:02:3c:41:d7:c5
    valid:
    - 53:6c:f8:0b:cc:a4
    - 6b:56:71:2e:9f:76
    - f4:99:e0:a4:1e:16
    - fd:d6:12:0f:ba:06
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - 1sl6y6hmza
    - 71ygb9bqm3
    - rsbh6bm6c8
    - 30xncue9tb
    - t5p8pdadrs
    - hmyubjja3q
    - v435jtav60
    - 3fc5xy31b8
    - ho8qn235ea
    - hj7au5crun
    - i1vyfuy77b
    - 9015pye6mb
    - nlvm3xroio
    - iae7bhtwf6
    - pp7o8hm3ak
    valid:
    - fbk4mqz022
    - dhiwd2e8o7
    - cav1e6sx85
    - po2tcz09kh
  time:
    invalid:
    - '2022-07-26 11:01:33.952415'
    multiple_valids:
    - '2022-07-26T05:31:33.952415+00:00'
    - '2022-08-18T05:31:33.952415+00:00'
    - '2022-09-10T05:31:33.952415+00:00'
    - '2022-10-03T05:31:33.952415+00:00'
    - '2022-10-26T05:31:33.952415+00:00'
    - '2022-11-18T05:31:33.952415+00:00'
    - '2022-12-11T05:31:33.952415+00:00'
    - '2023-01-03T05:31:33.952415+00:00'
    - '2023-01-26T05:31:33.952415+00:00'
    - '2023-02-18T05:31:33.952415+00:00'
    - '2023-03-13T05:31:33.952415+00:00'
    - '2023-04-05T05:31:33.952415+00:00'
    - '2023-04-28T05:31:33.952415+00:00'
    - '2023-05-21T05:31:33.952415+00:00'
    - '2023-06-13T05:31:33.952415+00:00'
    valid:
    - '2022-07-26T05:31:33.952415+00:00'
    - '2022-08-18T05:31:33.952415+00:00'
    - '2022-09-10T05:31:33.952415+00:00'
    - '2022-10-03T05:31:33.952415+00:00'
  url-http:
    invalid:
    - ht:/3drn0donnerejs7.com
    multiple_valids:
    - http://6d9m0cwlhj43970.com
    - http://42zwy7kcacp0ew5.com
    - http://za1uw8oao1avq6s.com
    - http://vwq6aqmctagg7na.com
    - http://yd9zh4w2c8g8cxt.com
    - http://xo15yvx1a8kd78j.com
    - http://5au433qvlk5xau4.com
    - http://gatazjsdvxj17vi.com
    - http://r2q2zehtgy0l49x.com
    - http://acfgs2qd13hqabe.com
    - http://7qbhi7z0rnies5s.com
    - http://lgvp1mnsvo5qdwr.com
    - http://iah13g5aptdjed9.com
    - http://e4sbaj8buvr0rr5.com
    - http://khpcdsh7gsri53x.com
    valid:
    - http://wm3idx0zz7mr0vb.com
    - http://237xavw4i5qq5nc.com
    - http://fvmzy7fbg4oc96p.com
    - http://yyinjmit9xpk55o.com
  url-https:
    invalid:
    - hts:/tzcfop3ta27d74q.com
    multiple_valids:
    - https://0gqri4gzgjr0rlu.com
    - https://sbetptrlhurjca1.com
    - https://3r43tux0u98tlv4.com
    - https://yo4crr98eve3089.com
    - https://5mkp1b3wph7sgj6.com
    - https://demdj0aydr0djq3.com
    - https://qwx6n4ad3ldtd36.com
    - https://newv8q07spmogtx.com
    - https://6gzv4zcq511hmnb.com
    - https://pd1vy9okgxon27n.com
    - https://atusxd8t8k9v193.com
    - https://h1x5sby51j6ewqt.com
    - https://qdwu9qysmhxj715.com
    - https://tosxg2skuijndey.com
    - https://a84hk16j3m3lwp3.com
    valid:
    - https://ymly98jxq6ncjx5.com
    - https://9w7nogzhzj2epu1.com
    - https://qeikr3rshz15a15.com
    - https://9ozee7pfr1b7z13.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 360fca83-0ca4-11ed-aa39-7c8ae1979a87
    - 360fca84-0ca4-11ed-961f-7c8ae1979a87
    - 360fca85-0ca4-11ed-b702-7c8ae1979a87
    - 360fca86-0ca4-11ed-b6db-7c8ae1979a87
    - 360fca87-0ca4-11ed-8df1-7c8ae1979a87
    - 360fca88-0ca4-11ed-bfa4-7c8ae1979a87
    - 360fca89-0ca4-11ed-b59e-7c8ae1979a87
    - 360fca8a-0ca4-11ed-9806-7c8ae1979a87
    - 360fca8b-0ca4-11ed-a935-7c8ae1979a87
    - 360fca8c-0ca4-11ed-8ff2-7c8ae1979a87
    - 360fca8d-0ca4-11ed-ac34-7c8ae1979a87
    - 360fca8e-0ca4-11ed-a078-7c8ae1979a87
    - 360fca8f-0ca4-11ed-bf3e-7c8ae1979a87
    - 360fca90-0ca4-11ed-99d6-7c8ae1979a87
    - 360fd4d0-0ca4-11ed-8753-7c8ae1979a87
    valid:
    - 360fca7f-0ca4-11ed-9b99-7c8ae1979a87
    - 360fca80-0ca4-11ed-bdc1-7c8ae1979a87
    - 360fca81-0ca4-11ed-934b-7c8ae1979a87
    - 360fca82-0ca4-11ed-bc83-7c8ae1979a87
