datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    valid:
    - cHJtNWIwaHVlaw==
  cidr:
    invalid:
    - 277.268.279.265/29
    valid:
    - 19.152.40.31/20
  ipv4:
    invalid:
    - 275.297.295.284
    valid:
    - 238.52.197.160
  ipv6:
    invalid:
    - invalidIPv6
    valid:
    - 9a50:82d5:e85f:e33c:da27:ce4d
  json:
    invalid:
    - 'json({ name : val)'
    valid:
    - 'json({ "attribute" : "value" })'
  mac:
    invalid:
    - invalidMAC
    valid:
    - b1:3b:93:74:3c:79
  regex:
    invalid:
    - '[0-9)++'
    valid:
    - (?m)^[0-9]{2}$
  string:
    invalid:
    - 12345
    valid:
    - n8udrsczga
  time:
    invalid:
    - '2022-06-15 10:33:17.275769'
    valid:
    - '2022-06-15T05:03:17.275769+00:00'
  url-http:
    invalid:
    - ht:/5uwx9x0grkim642.com
    valid:
    - http://87aterv456pm5fx.com
  url-https:
    invalid:
    - hts:/uu08asw6d10w6ie.com
    valid:
    - https://mw360o1q8h8282j.com
  uuid:
    invalid:
    - invalid323Uuid12
    valid:
    - 77d3acbe-ec68-11ec-9279-7c8ae1943087
