datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    valid:
    - aWdrcXNhYTMwMA==
  cidr:
    invalid:
    - 290.272.261.290/18
    valid:
    - 191.223.38.116/16
  ipv4:
    invalid:
    - 263.266.257.296
    valid:
    - 26.224.23.179
  ipv6:
    invalid:
    - invalidIPv6
    valid:
    - c2ba:8207:1c3e:5f9f:97e9:d921
  json:
    invalid:
    - 'json({ name : val)'
    valid:
    - 'json({ "attribute" : "value" })'
  mac:
    invalid:
    - invalidMAC
    valid:
    - 6d:9f:78:69:c2:27
  regex:
    invalid:
    - '[0-9)++'
    valid:
    - (?m)^[0-9]{2}$
  string:
    invalid:
    - 12345
    valid:
    - lbs1g9r4cy
  time:
    invalid:
    - '2022-06-14 18:52:46.949170'
    valid:
    - '2022-06-14T13:22:46.949170+00:00'
  url-http:
    invalid:
    - ht:/ucjj3eauy2djxix.com
    valid:
    - http://nyll6x8izll0pmy.com
  url-https:
    invalid:
    - hts:/fndlnh16wlwou33.com
    valid:
    - https://ols3bp4h8mw9zur.com
  uuid:
    invalid:
    - invalid323Uuid12
    valid:
    - 14bb2bf8-ebe5-11ec-afe4-7c8ae1943087
