datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/Jeffail/gabs/v2
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    valid:
    - ejRkMXBvanFodA==
    - YnQ2bXJiZTZ5eA==
    - bnNmaHV1ZGR5Yg==
    - Z2RodjI2Y3RnaQ==
  cidr:
    invalid:
    - 270.271.281.277/20
    valid:
    - 244.119.144.0/20
    - 244.119.240.0/20
    - 244.119.80.0/20
    - 244.119.208.0/20
  ipv4:
    invalid:
    - 268.268.257.289
    valid:
    - 244.119.54.218
    - 244.119.36.244
    - 244.119.97.114
    - 244.119.4.88
  ipv6:
    invalid:
    - invalidIPv6
    valid:
    - 2001:db8::34f4:0:0:f304
    - 2001:db8::34f4:0:0:f389
    - 2001:db8::34f4:0:0:f3f0
    - 2001:db8::34f4:0:0:f3c1
  json:
    invalid:
    - 'json({ name : val)'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    valid:
    - 3b:ab:04:78:14:eb
    - ad:75:fe:a7:fe:e7
    - 77:cc:0a:3f:95:c1
    - 5a:03:7f:36:b4:ec
  regex:
    invalid:
    - '[0-9)++'
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    valid:
    - 26s3fh68yv
    - ejkg2wzka0
    - oft2shujf9
    - bk7aieggc3
  time:
    invalid:
    - '2022-06-29 18:09:34.897900'
    valid:
    - '2022-06-29T12:39:34.897900+00:00'
    - '2022-07-22T12:39:34.897900+00:00'
    - '2022-08-14T12:39:34.897900+00:00'
    - '2022-09-06T12:39:34.897900+00:00'
  url-http:
    invalid:
    - ht:/gme0w5dtwmxwmyj.com
    valid:
    - http://w1fvaum3qgod67o.com
    - http://hmnv4vtt4l2blif.com
    - http://sdsjlwmbgblzi72.com
    - http://ewpd2xilcst7a12.com
  url-https:
    invalid:
    - hts:/0s41ej8edgtn82w.com
    valid:
    - https://uwrixu4kvb6sjo9.com
    - https://9idsu4ajojkaj3x.com
    - https://la39uzl85cxnpck.com
    - https://2h5dthrfrfct0m5.com
  uuid:
    invalid:
    - invalid323Uuid12
    valid:
    - 87f1c93b-f7a8-11ec-a40b-7c8ae1979a87
    - 87f1c93c-f7a8-11ec-a617-7c8ae1979a87
    - 87f1c93d-f7a8-11ec-a2c0-7c8ae1979a87
    - 87f1c93e-f7a8-11ec-b1a6-7c8ae1979a87
