datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/Jeffail/gabs/v2
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - a2hqbm9lcm5vbA==
    - eDAwdTJpb2ppMw==
    - YXJjejdvdmF0eg==
    - bnRpeWpmMGUwNQ==
    - dThlZW9vNGVxdA==
    - OW95djlxZTVkcA==
    - NjhlcjF5OTVqZw==
    - emkxZjV5dHlwdg==
    - Z2p5bDB2a2EzMw==
    - cG5pZTFwem9uaw==
    - MGN1ZjAzamU1dg==
    - ZnU3OG1hbGJ6bg==
    - ZmswbnZvdjkzcw==
    - cHdpcmQxNWQ3Zg==
    - eHVjZG8wYmdoYg==
    valid:
    - NzBiMHozNzYwNw==
    - a2hrdHF4ajFvYw==
    - aW85aGNkbDd6Ng==
    - bHQxZ3BicmxwMA==
  cidr:
    invalid:
    - 275.256.263.259/2
    multiple_valids:
    - 127.84.176.0/20
    - 127.84.32.0/20
    - 127.84.80.0/20
    - 127.84.16.0/20
    - 127.84.208.0/20
    - 127.84.128.0/20
    - 127.84.240.0/20
    - 127.84.224.0/20
    - 127.84.112.0/20
    - 127.84.64.0/20
    - 127.84.48.0/20
    - 127.84.192.0/20
    - 127.84.160.0/20
    - 127.84.0.0/20
    - 127.84.144.0/20
    valid:
    - 127.84.176.0/20
    - 127.84.32.0/20
    - 127.84.80.0/20
    - 127.84.16.0/20
  ipv4:
    invalid:
    - 260.277.256.295
    multiple_valids:
    - 127.84.39.236
    - 127.84.202.98
    - 127.84.86.45
    - 127.84.114.70
    - 127.84.10.153
    - 127.84.188.203
    - 127.84.208.133
    - 127.84.154.241
    - 127.84.210.114
    - 127.84.165.120
    - 127.84.27.248
    - 127.84.34.85
    - 127.84.216.55
    - 127.84.109.251
    - 127.84.23.42
    valid:
    - 127.84.39.236
    - 127.84.202.98
    - 127.84.86.45
    - 127.84.114.70
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f303
    - 2001:db8::34f4:0:0:f358
    - 2001:db8::34f4:0:0:f3fc
    - 2001:db8::34f4:0:0:f30b
    - 2001:db8::34f4:0:0:f3c6
    - 2001:db8::34f4:0:0:f330
    - 2001:db8::34f4:0:0:f3af
    - 2001:db8::34f4:0:0:f305
    - 2001:db8::34f4:0:0:f3cc
    - 2001:db8::34f4:0:0:f38b
    - 2001:db8::34f4:0:0:f337
    - 2001:db8::34f4:0:0:f3b0
    - 2001:db8::34f4:0:0:f3f2
    - 2001:db8::34f4:0:0:f395
    - 2001:db8::34f4:0:0:f3d5
    valid:
    - 2001:db8::34f4:0:0:f303
    - 2001:db8::34f4:0:0:f358
    - 2001:db8::34f4:0:0:f3fc
    - 2001:db8::34f4:0:0:f30b
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 50:64:0a:e1:99:18
    - 3a:b4:e6:bb:8a:5d
    - a1:df:5e:97:69:17
    - 23:2a:c9:02:0c:34
    - c5:08:19:1d:97:4b
    - 2a:7a:73:03:58:dd
    - bf:f0:9a:9c:d4:84
    - a5:9d:d7:1c:b1:f0
    - be:bb:52:f0:8e:b5
    - 54:f1:cb:27:6a:33
    - 7b:38:c1:ad:b4:5e
    - e7:d6:7c:d4:cb:11
    - 9b:1f:29:7f:49:03
    - bb:7f:67:24:b8:d1
    - 18:56:9b:d3:b2:6b
    valid:
    - 57:aa:47:93:70:90
    - 0c:6a:7d:b7:23:6f
    - 7e:ec:cc:e3:76:34
    - 97:18:ec:7a:93:09
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - c3gkp9ijfx
    - s6xogrkp50
    - njpfrihl9u
    - dyxynu22ij
    - sjcxjame4k
    - e8s36t6bjn
    - bxknbub78g
    - g0g4ziw69h
    - uiljhnb5sz
    - t0bhfvs6gu
    - n0a434ecjl
    - 9n1bpvg70l
    - bgie37v6yo
    - 85ee3myw6z
    - ji4gh8jjlq
    valid:
    - oz8p758ph3
    - gl5o76frql
    - lgai7sdra1
    - 02k9d7xm68
  time:
    invalid:
    - '2022-07-25 12:40:51.346512'
    multiple_valids:
    - '2022-07-25T07:10:51.346512+00:00'
    - '2022-08-17T07:10:51.346512+00:00'
    - '2022-09-09T07:10:51.346512+00:00'
    - '2022-10-02T07:10:51.346512+00:00'
    - '2022-10-25T07:10:51.346512+00:00'
    - '2022-11-17T07:10:51.346512+00:00'
    - '2022-12-10T07:10:51.346512+00:00'
    - '2023-01-02T07:10:51.346512+00:00'
    - '2023-01-25T07:10:51.346512+00:00'
    - '2023-02-17T07:10:51.346512+00:00'
    - '2023-03-12T07:10:51.346512+00:00'
    - '2023-04-04T07:10:51.346512+00:00'
    - '2023-04-27T07:10:51.346512+00:00'
    - '2023-05-20T07:10:51.346512+00:00'
    - '2023-06-12T07:10:51.346512+00:00'
    valid:
    - '2022-07-25T07:10:51.346512+00:00'
    - '2022-08-17T07:10:51.346512+00:00'
    - '2022-09-09T07:10:51.346512+00:00'
    - '2022-10-02T07:10:51.346512+00:00'
  url-http:
    invalid:
    - ht:/tltv309tvpmn3ou.com
    multiple_valids:
    - http://jtmqnp4tho1vznj.com
    - http://ef1k2w0sfjcv6a1.com
    - http://xd9sgvyft6x9fey.com
    - http://rti251m4po42r67.com
    - http://3k30c58um6i916n.com
    - http://4kjgax5v32gg8s1.com
    - http://2e1dqob46zo0rm3.com
    - http://hyrt36hcz8anoqn.com
    - http://n653hycptvqyg2f.com
    - http://sy0wqs65a5710ml.com
    - http://awwu6cmf14k6r84.com
    - http://b02ldxcrhymxpuv.com
    - http://92n249m56qkifky.com
    - http://oayocpsfh5dxhi4.com
    - http://qp4yn1aud4u1x82.com
    valid:
    - http://ycu6rhzm2vz9jhm.com
    - http://0b1l5gkng2xbdom.com
    - http://uw6hphgqhhqvntf.com
    - http://qrm9tk5qewgm0k2.com
  url-https:
    invalid:
    - hts:/mjfn90xr0pcrv47.com
    multiple_valids:
    - https://fedxqm42jr2zq8t.com
    - https://d0mygsi7zram5h9.com
    - https://2vmzknzzpc6ujih.com
    - https://bftgsbmtr091t53.com
    - https://i4ehm39ygys89ws.com
    - https://mdoe18z459b2rx5.com
    - https://rxkc16texcoah3h.com
    - https://p6jvwk0lwl2gkye.com
    - https://u89d3tjadlakbjx.com
    - https://gxbmteugi07uyh9.com
    - https://u0lm9vh77sx30ay.com
    - https://e093e815gx1y9nr.com
    - https://26ey3levsrwzvyx.com
    - https://geyyc7iahznnep9.com
    - https://u6m5wksbv5mhjup.com
    valid:
    - https://39j3agrfvvvpj5j.com
    - https://iz9pm5sw7gqrpce.com
    - https://3oi3wj5io6k0ix3.com
    - https://qcy967btx1vt7un.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - ea882f28-0be8-11ed-8c5f-7c8ae1979a87
    - ea882f29-0be8-11ed-9757-7c8ae1979a87
    - ea882f2a-0be8-11ed-89bc-7c8ae1979a87
    - ea882f2b-0be8-11ed-916b-7c8ae1979a87
    - ea882f2c-0be8-11ed-9769-7c8ae1979a87
    - ea882f2d-0be8-11ed-8762-7c8ae1979a87
    - ea882f2e-0be8-11ed-9af1-7c8ae1979a87
    - ea882f2f-0be8-11ed-9a3a-7c8ae1979a87
    - ea882f30-0be8-11ed-9f86-7c8ae1979a87
    - ea882f31-0be8-11ed-808a-7c8ae1979a87
    - ea882f32-0be8-11ed-a361-7c8ae1979a87
    - ea882f33-0be8-11ed-8fe5-7c8ae1979a87
    - ea882f34-0be8-11ed-8e92-7c8ae1979a87
    - ea882f35-0be8-11ed-b366-7c8ae1979a87
    - ea882f36-0be8-11ed-bcfb-7c8ae1979a87
    valid:
    - ea882f24-0be8-11ed-ab67-7c8ae1979a87
    - ea882f25-0be8-11ed-a72e-7c8ae1979a87
    - ea882f26-0be8-11ed-8beb-7c8ae1979a87
    - ea882f27-0be8-11ed-9b34-7c8ae1979a87
