datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/Jeffail/gabs/v2
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    valid:
    - MWM4cjYxNXBoZw==
    - ZTZnNnlxeGd2cg==
    - bjM0YmlmOWpkOQ==
    - Mjg4dzcyeDd3aQ==
  cidr:
    invalid:
    - 274.266.283.262/30
    valid:
    - 130.108.0.0/20
    - 130.108.192.0/20
    - 130.108.144.0/20
    - 130.108.80.0/20
  ipv4:
    invalid:
    - 294.259.295.299
    valid:
    - 130.108.231.110
    - 130.108.202.160
    - 130.108.43.127
    - 130.108.135.181
  ipv6:
    invalid:
    - invalidIPv6
    valid:
    - 2001:db8::34f4:0:0:f379
    - 2001:db8::34f4:0:0:f34b
    - 2001:db8::34f4:0:0:f312
    - 2001:db8::34f4:0:0:f3e8
  json:
    invalid:
    - 'json({ name : val)'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    valid:
    - be:e8:ba:fb:3c:72
    - 3c:85:03:83:98:8f
    - 39:a8:d1:99:2d:97
    - ef:1b:64:b0:fa:97
  regex:
    invalid:
    - '[0-9)++'
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    valid:
    - tu59znwjey
    - 9j60mvxaey
    - davprq8qtm
    - nwfgq0uxli
  time:
    invalid:
    - '2022-07-01 18:30:28.611928'
    valid:
    - '2022-07-01T13:00:28.611928+00:00'
    - '2022-07-24T13:00:28.611928+00:00'
    - '2022-08-16T13:00:28.611928+00:00'
    - '2022-09-08T13:00:28.611928+00:00'
  url-http:
    invalid:
    - ht:/x9b3p9e88idrfu5.com
    valid:
    - http://sw834mnli9ho2ts.com
    - http://xz2henjjhbhln63.com
    - http://ld3sfb6vf8hu1xf.com
    - http://xiddmwyqlcoqjsh.com
  url-https:
    invalid:
    - hts:/e48el2dczs72z7x.com
    valid:
    - https://rswhqj3l65617zg.com
    - https://sn2nr7f1af8kd7m.com
    - https://nzkqawgjuo20d76.com
    - https://3keuv9rnej0djtf.com
  uuid:
    invalid:
    - invalid323Uuid12
    valid:
    - c80add71-f93d-11ec-92f6-7c8ae1979a87
    - c80add72-f93d-11ec-a425-7c8ae1979a87
    - c80add73-f93d-11ec-93fd-7c8ae1979a87
    - c80add74-f93d-11ec-9373-7c8ae1979a87
