datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/Jeffail/gabs/v2
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - aHVqNGQzcHlmcQ==
    - ajA1ODE4a2ltOA==
    - NnJsbzVjemFmNQ==
    - bmU3bzA2enRydQ==
    - YXJxb21lOTZpbg==
    - cnhtMWRsaTRibw==
    - d2UwYTN6d296OQ==
    - d2NndjFjNTVuMg==
    - NmViZnljd2V0NQ==
    - amQ0bWt4N3MydA==
    - bjZ0NHZteTV3MQ==
    - dXJsdHQxemhrbQ==
    - cnhwMjVsbzJtcw==
    - bzZrODMzZDdicg==
    - NDk5aHoyY2ZtMg==
    valid:
    - bGFoMGp2c2o3ZA==
    - NWhpY2xrbDZ5Zg==
    - aTNwZTVkNzJ3ZA==
    - MG1sMTNuczk1MQ==
  cidr:
    invalid:
    - 264.290.269.260/23
    multiple_valids:
    - 253.99.32.0/20
    - 253.99.160.0/20
    - 253.99.176.0/20
    - 253.99.0.0/20
    - 253.99.192.0/20
    - 253.99.128.0/20
    - 253.99.16.0/20
    - 253.99.80.0/20
    - 253.99.112.0/20
    - 253.99.208.0/20
    - 253.99.96.0/20
    - 253.99.144.0/20
    - 253.99.48.0/20
    - 253.99.64.0/20
    - 253.99.224.0/20
    valid:
    - 253.99.32.0/20
    - 253.99.160.0/20
    - 253.99.176.0/20
    - 253.99.0.0/20
  ipv4:
    invalid:
    - 271.276.257.293
    multiple_valids:
    - 253.99.29.58
    - 253.99.21.65
    - 253.99.143.169
    - 253.99.49.65
    - 253.99.189.47
    - 253.99.22.6
    - 253.99.14.255
    - 253.99.166.18
    - 253.99.248.97
    - 253.99.138.116
    - 253.99.150.163
    - 253.99.176.200
    - 253.99.222.109
    - 253.99.198.59
    - 253.99.215.246
    valid:
    - 253.99.29.58
    - 253.99.21.65
    - 253.99.143.169
    - 253.99.49.65
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f32c
    - 2001:db8::34f4:0:0:f314
    - 2001:db8::34f4:0:0:f317
    - 2001:db8::34f4:0:0:f3d5
    - 2001:db8::34f4:0:0:f38b
    - 2001:db8::34f4:0:0:f36e
    - 2001:db8::34f4:0:0:f3a9
    - 2001:db8::34f4:0:0:f34e
    - 2001:db8::34f4:0:0:f335
    - 2001:db8::34f4:0:0:f39a
    - 2001:db8::34f4:0:0:f383
    - 2001:db8::34f4:0:0:f380
    - 2001:db8::34f4:0:0:f325
    - 2001:db8::34f4:0:0:f324
    - 2001:db8::34f4:0:0:f345
    valid:
    - 2001:db8::34f4:0:0:f32c
    - 2001:db8::34f4:0:0:f314
    - 2001:db8::34f4:0:0:f317
    - 2001:db8::34f4:0:0:f3d5
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 03:11:85:fe:63:a5
    - 35:bd:b5:41:20:fe
    - c6:5f:71:61:25:70
    - d1:ae:18:ea:27:e6
    - 42:63:dc:bb:66:82
    - 31:c7:87:fd:d5:10
    - 47:97:9c:b7:3d:34
    - 65:29:7f:71:4a:97
    - 57:d5:5a:0d:bb:b7
    - ca:bf:1e:03:25:41
    - e9:c9:ba:b0:a1:22
    - 1e:f4:ab:12:1c:9b
    - 6a:f2:53:4d:c4:8e
    - 7a:27:d7:51:b7:00
    - cc:7e:03:94:0b:74
    valid:
    - 1e:c7:0d:8f:8b:03
    - 26:ca:aa:64:ca:66
    - 39:9e:3e:fb:f5:a9
    - 9c:36:6a:cd:21:3a
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - e59x5eptnc
    - vqmvgnwyg8
    - 0ci1vfeihh
    - 09p8r4hkh4
    - fooejn4wl5
    - 2hpi34mhwu
    - hn5t1zvc8g
    - fpk288rjf8
    - ntaye5na53
    - 74r6rq295z
    - 89cpjjixxq
    - v8l7a9ejm2
    - 5dj4550xku
    - 83idjda7ck
    - gnbhtsmxu0
    valid:
    - coo2t07lgd
    - c4yur05oh7
    - l575lv2p7f
    - 7dg5j5dtdl
  time:
    invalid:
    - '2022-07-29 11:24:23.431555'
    multiple_valids:
    - '2022-07-29T05:54:23.431555+00:00'
    - '2022-08-21T05:54:23.431555+00:00'
    - '2022-09-13T05:54:23.431555+00:00'
    - '2022-10-06T05:54:23.431555+00:00'
    - '2022-10-29T05:54:23.431555+00:00'
    - '2022-11-21T05:54:23.431555+00:00'
    - '2022-12-14T05:54:23.431555+00:00'
    - '2023-01-06T05:54:23.431555+00:00'
    - '2023-01-29T05:54:23.431555+00:00'
    - '2023-02-21T05:54:23.431555+00:00'
    - '2023-03-16T05:54:23.431555+00:00'
    - '2023-04-08T05:54:23.431555+00:00'
    - '2023-05-01T05:54:23.431555+00:00'
    - '2023-05-24T05:54:23.431555+00:00'
    - '2023-06-16T05:54:23.431555+00:00'
    valid:
    - '2022-07-29T05:54:23.431555+00:00'
    - '2022-08-21T05:54:23.431555+00:00'
    - '2022-09-13T05:54:23.431555+00:00'
    - '2022-10-06T05:54:23.431555+00:00'
  url-http:
    invalid:
    - ht:/ztth0onlnq01e8y.com
    multiple_valids:
    - http://4151iigpc2rp73r.com
    - http://qy922td6xe5a4o4.com
    - http://lsryw4rj9dot02r.com
    - http://htk27litib6yhxc.com
    - http://35vijzd98r1y6s5.com
    - http://dx9yb6zzxqg90tr.com
    - http://axf9cfo15owbrn8.com
    - http://vtg57xoni7s9sc0.com
    - http://ed9x1r28qzhxykv.com
    - http://ty1vkwnuj6bsg61.com
    - http://g502e6r52yxww2v.com
    - http://q35xaj5mped2psk.com
    - http://ki65h83l8zg81le.com
    - http://7iymap2cp3rbil5.com
    - http://9n6viaholnvslii.com
    valid:
    - http://fu17ppqpw8hhbol.com
    - http://mehb1nku4orcscb.com
    - http://r2d3fxnxdfhj3qc.com
    - http://6tcs6jxkgcuznf2.com
  url-https:
    invalid:
    - hts:/axtvut05pv2axot.com
    multiple_valids:
    - https://i114j9fc6m9p5yk.com
    - https://c6pehpwhqluk9py.com
    - https://usab2j4akgu2wsr.com
    - https://j9yy4gnwt9htr6o.com
    - https://089gkvi07h0cqsf.com
    - https://6m085ghz67y0jcx.com
    - https://uc4nc2iok8r7kgv.com
    - https://qwsjtjs4m1a03wc.com
    - https://166zgq41fh8eymb.com
    - https://um3b0hb0c25ivqz.com
    - https://49xkyffb2b22vxo.com
    - https://m1l8cxksy38sx82.com
    - https://3otwi4i3o70sq0s.com
    - https://lezmgeb12j3hm1h.com
    - https://5hp4818vjoiep31.com
    valid:
    - https://z8hhnk988k4a154.com
    - https://3lcd8983b3ciyz5.com
    - https://a3dyv5fw9wojsow.com
    - https://gw3pj3l4g5zlvor.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - e592eb25-0f02-11ed-b073-7c8ae1979a87
    - e592eb26-0f02-11ed-a8f9-7c8ae1979a87
    - e592eb27-0f02-11ed-b9e4-7c8ae1979a87
    - e592eb28-0f02-11ed-84ae-7c8ae1979a87
    - e592eb29-0f02-11ed-8817-7c8ae1979a87
    - e592eb2a-0f02-11ed-88ba-7c8ae1979a87
    - e592eb2b-0f02-11ed-9701-7c8ae1979a87
    - e592eb2c-0f02-11ed-8e00-7c8ae1979a87
    - e592eb2d-0f02-11ed-9c25-7c8ae1979a87
    - e592eb2e-0f02-11ed-920f-7c8ae1979a87
    - e592eb2f-0f02-11ed-a66a-7c8ae1979a87
    - e592eb30-0f02-11ed-b312-7c8ae1979a87
    - e592eb31-0f02-11ed-9964-7c8ae1979a87
    - e592eb32-0f02-11ed-a1c3-7c8ae1979a87
    - e592eb33-0f02-11ed-bd2b-7c8ae1979a87
    valid:
    - e592eb21-0f02-11ed-8272-7c8ae1979a87
    - e592eb22-0f02-11ed-af56-7c8ae1979a87
    - e592eb23-0f02-11ed-af7d-7c8ae1979a87
    - e592eb24-0f02-11ed-a7b2-7c8ae1979a87
