provider_name: "Aci"
imports:
  - "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
  - "github.com/ciscoecosystem/aci-go-client/client"
resources:
  - "tenant"
  - "application_profile"
datasources:
  - "tenant"
  - "application_profile"
schemas:
  - attribute: "username"
    type: "string"
    required: "true"
    default_func: "true"
    envvar: "ACI_USERNAME"
    description: "Username of the ACI user"
  - attribute: "password"
    type: "string"
    required: "true"
    default_func: "true"
    envvar: "ACI_PASSWORD"
    description: "Password of the ACI user"
  - attribute: "url"
    type: "string"
    required: "true"
    default_func: "true"
    envvar: "ACI_URL"
    description: "URL of the ACI server"
