datasources:
- tenant
- application_profile
imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/ciscoecosystem/aci-go-client/client
imports_for_test:
- os
- testing
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/Jeffail/gabs/v2
provider_name: Aci
resources:
- tenant
- application_profile
schemas:
- attribute: username
  default_func: true
  description: Username of the ACI user
  envvar: ACI_USERNAME
  required: true
  type: string
- attribute: password
  default_func: true
  description: Password of the ACI user
  envvar: ACI_PASSWORD
  required: true
  type: string
- attribute: url
  default_func: true
  description: URL of the ACI server
  envvar: ACI_URL
  required: true
  type: string
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - aDQ5NnIybDNnYg==
    - bzZpZml5ZnBlaQ==
    - bHhkOHV3Mzc5Zw==
    - azRlbG13bTkyZA==
    - ZTQ4a2F1enZuMQ==
    - YWNiN3BsaWhqbQ==
    - ODMxbGF0eXVndw==
    - Mjl2Ym5ldjQ1bg==
    - bGRsYTI2amlmMA==
    - MTIxdDhkazB6eg==
    - bm5mZHI3dm9yYw==
    - ZWI5M2d3d2t3OA==
    - b2Jmcmc5MzN6NQ==
    - MW9vZmk4OHZubQ==
    - b3VvMGk3Nm85aQ==
    valid:
    - YTZtZDB0dTdoZg==
    - OGRycTRmbGJpNw==
    - ZndieTkzcWFkdg==
    - Ymk3MWZqODBsOQ==
  cidr:
    invalid:
    - 263.276.290.281/12
    multiple_valids:
    - 58.25.160.0/20
    - 58.25.112.0/20
    - 58.25.240.0/20
    - 58.25.192.0/20
    - 58.25.0.0/20
    - 58.25.48.0/20
    - 58.25.16.0/20
    - 58.25.64.0/20
    - 58.25.32.0/20
    - 58.25.96.0/20
    - 58.25.176.0/20
    - 58.25.208.0/20
    - 58.25.224.0/20
    - 58.25.80.0/20
    - 58.25.144.0/20
    valid:
    - 58.25.160.0/20
    - 58.25.112.0/20
    - 58.25.240.0/20
    - 58.25.192.0/20
  ipv4:
    invalid:
    - 292.279.299.298
    multiple_valids:
    - 58.25.97.146
    - 58.25.234.54
    - 58.25.184.167
    - 58.25.96.86
    - 58.25.137.198
    - 58.25.11.60
    - 58.25.55.8
    - 58.25.36.88
    - 58.25.119.124
    - 58.25.121.81
    - 58.25.190.158
    - 58.25.150.207
    - 58.25.19.211
    - 58.25.78.17
    - 58.25.70.52
    valid:
    - 58.25.97.146
    - 58.25.234.54
    - 58.25.184.167
    - 58.25.96.86
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f317
    - 2001:db8::34f4:0:0:f36b
    - 2001:db8::34f4:0:0:f30e
    - 2001:db8::34f4:0:0:f310
    - 2001:db8::34f4:0:0:f3e4
    - 2001:db8::34f4:0:0:f36d
    - 2001:db8::34f4:0:0:f323
    - 2001:db8::34f4:0:0:f391
    - 2001:db8::34f4:0:0:f363
    - 2001:db8::34f4:0:0:f345
    - 2001:db8::34f4:0:0:f3a2
    - 2001:db8::34f4:0:0:f3f0
    - 2001:db8::34f4:0:0:f313
    - 2001:db8::34f4:0:0:f3a8
    - 2001:db8::34f4:0:0:f332
    valid:
    - 2001:db8::34f4:0:0:f317
    - 2001:db8::34f4:0:0:f36b
    - 2001:db8::34f4:0:0:f30e
    - 2001:db8::34f4:0:0:f310
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 89:af:41:a2:53:d5
    - 5f:1f:a4:a8:99:24
    - e5:4e:ff:70:37:8a
    - 29:b2:53:61:98:bf
    - 9c:8c:f9:21:26:ef
    - 5c:a4:bc:67:c8:45
    - 11:7a:c1:fd:ec:91
    - 9c:56:3b:5d:8b:86
    - 3e:76:43:0f:1b:3c
    - 46:ed:f3:b2:43:b1
    - 43:36:53:bd:8e:d2
    - dd:a3:3f:ba:49:d8
    - f9:53:bb:af:eb:7d
    - 54:be:05:27:84:e4
    - 23:33:ab:87:13:a8
    valid:
    - 78:42:fb:b2:d8:87
    - 0c:42:82:e4:59:53
    - da:0e:2d:6f:e9:f8
    - 92:91:c6:f3:25:af
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - t67yrlhg05
    - vwpvik5teo
    - 6vfcgf8rtl
    - fw9qa3uimo
    - 0rsmr8mkt3
    - agx9e6bz6o
    - 7u4g52f36c
    - f97gx28sh6
    - 8adoldxh9u
    - zfh04in5so
    - 3scuace8se
    - ab8lbpyvye
    - 7zvcsdxasd
    - uns0cfsv0i
    - r5lstronqj
    valid:
    - kixql3a8ir
    - m3oii1aeps
    - hhon7mdeqt
    - jbaor4jpd7
  time:
    invalid:
    - '2022-08-01 17:50:46.328843'
    multiple_valids:
    - '2022-08-01T12:20:46.328843+00:00'
    - '2022-08-24T12:20:46.328843+00:00'
    - '2022-09-16T12:20:46.328843+00:00'
    - '2022-10-09T12:20:46.328843+00:00'
    - '2022-11-01T12:20:46.328843+00:00'
    - '2022-11-24T12:20:46.328843+00:00'
    - '2022-12-17T12:20:46.328843+00:00'
    - '2023-01-09T12:20:46.328843+00:00'
    - '2023-02-01T12:20:46.328843+00:00'
    - '2023-02-24T12:20:46.328843+00:00'
    - '2023-03-19T12:20:46.328843+00:00'
    - '2023-04-11T12:20:46.328843+00:00'
    - '2023-05-04T12:20:46.328843+00:00'
    - '2023-05-27T12:20:46.328843+00:00'
    - '2023-06-19T12:20:46.328843+00:00'
    valid:
    - '2022-08-01T12:20:46.328843+00:00'
    - '2022-08-24T12:20:46.328843+00:00'
    - '2022-09-16T12:20:46.328843+00:00'
    - '2022-10-09T12:20:46.328843+00:00'
  url-http:
    invalid:
    - ht:/ceyz1n2z8oe8vti.com
    multiple_valids:
    - http://bk9ezoccu5ddjim.com
    - http://ibmfdkf9vk7bfdi.com
    - http://k7exh41jv5sbf9c.com
    - http://0f2t7dq22lbxa5i.com
    - http://s7qsvfw8vikb179.com
    - http://g1i69hmugigq4ox.com
    - http://nf3tiq2d2fvesbq.com
    - http://0c59lvlbq7y3x53.com
    - http://kfe3k5b8wfzsj1g.com
    - http://vogh0x3vxnncwqg.com
    - http://lqnkoyn5yxxdk4o.com
    - http://ickbjth8xwa3n8u.com
    - http://t9ipjne770ec4hm.com
    - http://0u5izde3xi384o3.com
    - http://cvdkjkbzmq5wulh.com
    valid:
    - http://dbrmrg6g7athb8i.com
    - http://e882wzlxe4wmd9l.com
    - http://r0e9s1qc91rzwpk.com
    - http://lrrzazk0sjgraok.com
  url-https:
    invalid:
    - hts:/d3dy0s8ydizz13b.com
    multiple_valids:
    - https://0824wcyvzyu3o4y.com
    - https://11oaxhx2n4psqos.com
    - https://k4jiq76uerltw6f.com
    - https://sq5bm7z88c0sh11.com
    - https://tc9jvbealbnplzh.com
    - https://npi4d2nggbgtg3m.com
    - https://o1wb9ji0plkhv3a.com
    - https://975mlgyw54z65m2.com
    - https://gum3y1obu1izlc2.com
    - https://4247ljn3tuxsatr.com
    - https://68nn3k2s5raqbip.com
    - https://4377irjr4kgr955.com
    - https://jhcrnwim8cluv4g.com
    - https://l0xbuq5acsyert7.com
    - https://z8fsaoa72swecp3.com
    valid:
    - https://92suw6shxag54op.com
    - https://7ae7s90gch3cszk.com
    - https://4ocwovvns74683n.com
    - https://eu9t1cmfzhbn9vv.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 5ee5907b-1194-11ed-93d3-dc214861057a
    - 5ee5907c-1194-11ed-9c54-dc214861057a
    - 5ee5907d-1194-11ed-8778-dc214861057a
    - 5ee5907e-1194-11ed-8637-dc214861057a
    - 5ee5907f-1194-11ed-a7c4-dc214861057a
    - 5ee59080-1194-11ed-9cbd-dc214861057a
    - 5ee59081-1194-11ed-8b30-dc214861057a
    - 5ee59082-1194-11ed-9d37-dc214861057a
    - 5ee59083-1194-11ed-8eba-dc214861057a
    - 5ee59084-1194-11ed-98a0-dc214861057a
    - 5ee59085-1194-11ed-ab4c-dc214861057a
    - 5ee59086-1194-11ed-a19e-dc214861057a
    - 5ee59087-1194-11ed-9f83-dc214861057a
    - 5ee59088-1194-11ed-8ab5-dc214861057a
    - 5ee59089-1194-11ed-acc7-dc214861057a
    valid:
    - 5ee59077-1194-11ed-bb7f-dc214861057a
    - 5ee59078-1194-11ed-b98c-dc214861057a
    - 5ee59079-1194-11ed-802b-dc214861057a
    - 5ee5907a-1194-11ed-8f00-dc214861057a
