imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - u6tiz6dpue
    - 3nrsifokyv
    - gfo9ryv19j
    - 2yp28720so
    - 1bv3elitet
    - x6rr19evs2
    - 88mmpx9wy2
    - d9chmqq0d4
    - gzr7fq2wcx
    - 5u6tfjvpzc
    - bjhvhi1j6r
    - j0wy1nfvya
    - yomql4wczx
    - evglf7apjm
    - tgqx78wl2o
    valid:
    - 842tdoegpk
    - ld55pl95da
    - 7saiu1emqo
    - 4kbzp8z9vq
  type: string
- attribute: temp
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -287
    - -39
    - -223
    - 36
    - -206
    - 170
    - -923
    - 851
    - 375
    - 87
    - -721
    - -200
    - -55
    - 116
    - -75
    valid:
    - 847
    - -941
    - -801
    - 775
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - -7.155055526372872
    - 878.8920952172142
    - -713.2090098513197
    - -70.03526134240262
    - 412.3917999628997
    - -483.04172075899214
    - 633.0257238032513
    - -837.0136241061234
    - 94.44565312388174
    - 839.0377796448514
    - 46.244602285351455
    - -137.09317193582547
    - -512.1921989017839
    - 534.0129345440284
    - 969.9956529810715
    valid:
    - 334.11668833885426
    - -451.89954404515476
    - 184.33204114487862
    - 144.01122849382145
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 295.283.274.263
    multiple_valids: &id002
    - 196.45.95.250
    - 196.45.134.5
    - 196.45.54.14
    - 196.45.26.216
    - 196.45.37.4
    - 196.45.92.191
    - 196.45.124.250
    - 196.45.50.34
    - 196.45.186.180
    - 196.45.147.127
    - 196.45.88.194
    - 196.45.34.215
    - 196.45.38.216
    - 196.45.170.221
    - 196.45.118.79
    valid: &id003
    - 196.45.95.250
    - 196.45.134.5
    - 196.45.54.14
    - 196.45.26.216
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 20074
    - 13692
    - 43434
    - 799
    - 21488
    - 43684
    - 51910
    - 13700
    - 7448
    - 15425
    - 48936
    - 9349
    - 10784
    valid:
    - 1
    - 65535
    - 28231
    - 2375
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      default:
      - Hello
      - '10.3442'
      - '2'
      type: string
    type: schema
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - babzpjh7tm
    - 75ttzzweoh
    - l12dg07g0z
    - cnnrzbg1cd
    - sbyhi3l318
    - wa0wot8r86
    - jkdf5guhst
    - 7pufuu91rx
    - kpdtvdpttv
    - bdfg4uel1b
    - a316zear2u
    - 528xoal448
    - 9nym7c1vp5
    - 10rpk6ie67
    - czazuhnzkq
    valid:
    - ss0r3ypkob
    - jkfx5jg9ks
    - yzb1b0hkes
    - 6y2o1398yp
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 17
    - 33
    - 71
    - 42
    - 73
    - 44
    - 60
    - 22
    - 90
    - 18
    - 30
    - 40
    valid:
    - 1
    - 100
    - 50
    - 4
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - eq2ngek2y7
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 19
    - 6
    - 6
    - 27
    - 5
    - 18
    - 29
    - 27
    - 15
    - 1
    - 11
    - 14
    valid:
    - 0
    - 32
    - 16
    - 20
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 3.941630479536311
    - 25.196954411393087
    - 57.2318936412743
    - 34.33504792271919
    - 22.14940474581236
    - 30.985024072017353
    - 15.648824366728032
    - 40.17833504040795
    - 93.54987665056657
    - 22.387746032230588
    - 63.219888930043865
    - 88.38087955210844
    valid:
    - 0
    - 100
    - 50.0
    - 82.61514905355706
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 963
    - 528
    - 201
    - 689
    - -888
    - -745
    - 172
    - -426
    - 518
    - 305
    - -316
    - 575
    - 735
    - 725
    - 796
    valid:
    - 345
    - 785
    - -572
    - -678
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 9wtzevls2x
        - nyi0014fxy
        - le4c9q5syh
        - 5zq96dvntb
        - oauai5gtj4
        - d3isjjyy85
        - g1he25fpg9
        - a2s3yeia7b
        - w1jflg7h19
        - li6vn9lbi8
        - jmvd9ts5bf
        - x9f84rm2c2
        - mye7rzgtup
        - qtw80zkz37
        - 8qkahzfdbu
        valid:
        - 85ekmn8t8y
        - x81wo4xzv8
        - 5nimez1hm9
        - vfcw2n32ah
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - rr0nc5uche
        - z0v1d6nyzx
        - pvlftq1r4r
        - uwf9onhs4w
        - dctk6qx4l6
        - 17sbbgzqu7
        - d56eqq1s6y
        - wvrbi0k9gv
        - cq3ci22984
        - jfk1sacuix
        - 8pwv8biu0t
        - 5pgoglnfjo
        - qdv5x4w4uq
        - c5psn2rg7m
        - zdcfnc6cbr
        valid:
        - m4fq877c05
        - rkw7qco802
        - syr4nx5vuf
        - abeezz8xcw
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - ev8lacjqdg
        - 92s9d8cj56
        - 28zm1ellt0
        - 5matbqwcyd
        - 333vudqe1d
        - qyiysdkzgd
        - 17i3tlxtes
        - sv4k86vrfu
        - dohy908ma6
        - 5y1m53488l
        - ghegnkrrwc
        - 4ae7sftpb1
        - l26mjjm970
        - 5qm91oq72q
        - 8pcwm0rsas
        valid:
        - b2ta3g8zf1
        - hlfuapi0zg
        - cj3kx1vtno
        - uz3z9qk6fg
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - 6g2p6opblz
            - m5rcavu7v7
            - z9pb0x5v5a
            - skdg4vylzl
            - tv30lumrkw
            - g55y9cg805
            - cq97w6qxu9
            - ybwbx02tzl
            - icg9ia1cye
            - s5y2ul74fb
            - ji9tv1maxc
            - eic2qvfddo
            - 475ifaow0i
            - 9yt222fild
            - jzloe2dz33
            valid:
            - 2jsxw2k4ad
            - bc9uiy9kv8
            - bh2cy2do2u
            - uhizgd4dne
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - p6tl8rdmes
            - tuoo14y1lh
            - 1ycko6azwt
            - b9xd3p74of
            - djuyuizw9q
            - 4njtkgh3g5
            - ancajxiqnt
            - 9kei21cmas
            - z4xw0gcc8w
            - tqdq2qryae
            - lev5m8enf0
            - 1rj3sd8ebu
            - 1gpijs7fbb
            - 0kox88xhd7
            - bjjpfqk2ni
            valid:
            - 2l8fu52afr
            - 25h4s0yjxu
            - p90a1ai7et
            - shil66ds05
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f30c
            - 2001:db8::34f4:0:0:f3c3
            - 2001:db8::34f4:0:0:f38b
            - 2001:db8::34f4:0:0:f3e3
            - 2001:db8::34f4:0:0:f32f
            - 2001:db8::34f4:0:0:f370
            - 2001:db8::34f4:0:0:f336
            - 2001:db8::34f4:0:0:f3da
            - 2001:db8::34f4:0:0:f367
            - 2001:db8::34f4:0:0:f393
            - 2001:db8::34f4:0:0:f341
            - 2001:db8::34f4:0:0:f3b8
            - 2001:db8::34f4:0:0:f3e7
            - 2001:db8::34f4:0:0:f3cc
            - 2001:db8::34f4:0:0:f3f9
            valid: &id006
            - 2001:db8::34f4:0:0:f30c
            - 2001:db8::34f4:0:0:f3c3
            - 2001:db8::34f4:0:0:f38b
            - 2001:db8::34f4:0:0:f3e3
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - vzwfujfhfv
            - 3vb31bn01m
            - 17nqyktnhw
            - csunt7irx2
            - 6ujp5nblr9
            - on7q63wqp8
            - xcwerm5xtl
            - ncw68p6ely
            - tvj720cfsk
            - 7t2en6ms3v
            - cb61dyp8xa
            - h8atadgpny
            - eh5ywg0a15
            - 1w5x2460g2
            - 8xgzqmxc8l
            valid:
            - niyg9d4kmz
            - ldvxtuzyxt
            - f7e2ajgs07
            - sakc3ewxkn
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - YTczMmE5c3Uzeg==
    - eWp4dGI0bW50eA==
    - ZGs1bnI2ZWR3dQ==
    - endiN2xhOXNmbg==
    - dDRueHhlZXBjeQ==
    - b3gyaHIwYTg1eA==
    - c3F4M3htcnl1ag==
    - Ym85dDN5aXptYg==
    - cXk3YXRmdGpvcA==
    - ZHNhNmliNzc0cg==
    - bnRjcHpqb2VyYw==
    - ZDZncjE4ZXRhbQ==
    - enJqa3Jva2Q0bQ==
    - bGpmbXZjMjd3bg==
    - Y3hhY2t0YmlwNQ==
    valid:
    - YjgyOXEyNHd4OA==
    - OTFxemdobHByeg==
    - dXphN3B2N2Q2dA==
    - OXpxcGJhOWF0Mw==
  cidr:
    invalid:
    - 258.271.280.280/7
    multiple_valids:
    - 196.45.208.0/20
    - 196.45.192.0/20
    - 196.45.32.0/20
    - 196.45.176.0/20
    - 196.45.80.0/20
    - 196.45.112.0/20
    - 196.45.48.0/20
    - 196.45.64.0/20
    - 196.45.224.0/20
    - 196.45.16.0/20
    - 196.45.240.0/20
    - 196.45.96.0/20
    - 196.45.160.0/20
    - 196.45.144.0/20
    - 196.45.0.0/20
    valid:
    - 196.45.208.0/20
    - 196.45.192.0/20
    - 196.45.32.0/20
    - 196.45.176.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 57:0e:60:88:2e:10
    - f0:25:11:64:2f:14
    - 96:2f:4a:40:ba:53
    - 43:fb:bf:f4:46:75
    - 6b:ab:cc:a7:c2:e3
    - 2b:44:f1:c7:2b:2c
    - b3:94:78:d3:fd:ab
    - 9f:66:17:0e:79:8a
    - cd:55:7a:fc:f2:20
    - 03:90:cc:57:6b:08
    - f5:a4:b0:dd:21:4c
    - c6:8c:94:3c:69:b4
    - 07:c6:37:24:3c:b4
    - 54:ea:83:a2:13:52
    - 19:aa:7f:29:8f:94
    valid:
    - 35:b1:5c:ee:3c:16
    - 8c:e3:f6:35:f7:ec
    - ec:ca:d8:39:ed:17
    - 8a:86:5f:b2:9e:c3
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - g2dsw89g3i
    - gk4unt4w5t
    - opioy6q2o5
    - o2j79trhnp
    - k9h9oc7xau
    - ftpe1ckxht
    - 9k3qgi59oi
    - tbj8qa0vag
    - 90rx1zneoa
    - vq71tbdqay
    - 2jmu3c7n6v
    - sy9wwcwz8e
    - 859bn3y3uq
    - drdwohxk6q
    - erwzh1go3b
    valid:
    - cofodgf90h
    - ifu97w9wn2
    - 5rpru9xklx
    - p342s5qrq3
  time:
    invalid:
    - '2022-07-11 10:46:34.459318'
    multiple_valids:
    - '2022-07-11T05:16:34.463330+00:00'
    - '2022-08-03T05:16:34.463330+00:00'
    - '2022-08-26T05:16:34.463330+00:00'
    - '2022-09-18T05:16:34.463330+00:00'
    - '2022-10-11T05:16:34.463330+00:00'
    - '2022-11-03T05:16:34.463330+00:00'
    - '2022-11-26T05:16:34.463330+00:00'
    - '2022-12-19T05:16:34.463330+00:00'
    - '2023-01-11T05:16:34.463330+00:00'
    - '2023-02-03T05:16:34.463330+00:00'
    - '2023-02-26T05:16:34.463330+00:00'
    - '2023-03-21T05:16:34.463330+00:00'
    - '2023-04-13T05:16:34.463330+00:00'
    - '2023-05-06T05:16:34.463330+00:00'
    - '2023-05-29T05:16:34.463330+00:00'
    valid:
    - '2022-07-11T05:16:34.459318+00:00'
    - '2022-08-03T05:16:34.459318+00:00'
    - '2022-08-26T05:16:34.459318+00:00'
    - '2022-09-18T05:16:34.459318+00:00'
  url-http:
    invalid:
    - ht:/aviy2ucwzybo51j.com
    multiple_valids:
    - http://lnagacgkjly17wa.com
    - http://9u6e03fyi2vn6xx.com
    - http://jd07rraeo60jp32.com
    - http://2wvaxevwzwrtgcf.com
    - http://6hhq1igv47d5ywj.com
    - http://8erehcgcqd49cln.com
    - http://vdf1g7cn4be2oqj.com
    - http://iadvlg4bmudzwax.com
    - http://7ugczoz82vlqveu.com
    - http://kgennib04g3m67m.com
    - http://00ltfsivfopcn80.com
    - http://ht83vswrokdeh5s.com
    - http://r31zi8loy7idcu2.com
    - http://22gfmgsmoxiogpt.com
    - http://viwecqkq23lhq5b.com
    valid:
    - http://poixrqsawz6jxqc.com
    - http://dojylzfyju117ph.com
    - http://0j30cnzgh0460h6.com
    - http://gsnzllmse1zeqm2.com
  url-https:
    invalid:
    - hts:/1gaiyqip49gbwdj.com
    multiple_valids:
    - https://ds9dt7yw8pykwig.com
    - https://6dfu05pj6kme07a.com
    - https://nagl7aq09xk3e5h.com
    - https://lgsr7991hj2ubj9.com
    - https://yz2h1sjfwkukqef.com
    - https://brfxi9jc229pjza.com
    - https://u8zqz4awoa9xh68.com
    - https://zf86504xy6howas.com
    - https://5ksmsqm16y0orxx.com
    - https://467qufsxhbkj593.com
    - https://5uq3djd2n6eviar.com
    - https://om4rc86pdrlpz97.com
    - https://vlxfz5d48qh5vhr.com
    - https://64npls6pf4uoxqn.com
    - https://vdoldbt0pczejlh.com
    valid:
    - https://lt91m693ngy0tbh.com
    - https://sjolaz1l03et4r0.com
    - https://zklh8il8m2qcbfa.com
    - https://nsmoeu9goq84n50.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - a1ba57da-00d8-11ed-9733-7c8ae1979a87
    - a1ba57db-00d8-11ed-a68d-7c8ae1979a87
    - a1ba57dc-00d8-11ed-8912-7c8ae1979a87
    - a1ba57dd-00d8-11ed-ae9c-7c8ae1979a87
    - a1ba57de-00d8-11ed-b4c0-7c8ae1979a87
    - a1ba57df-00d8-11ed-bd5e-7c8ae1979a87
    - a1ba57e0-00d8-11ed-8677-7c8ae1979a87
    - a1ba57e1-00d8-11ed-91d0-7c8ae1979a87
    - a1ba57e2-00d8-11ed-97a7-7c8ae1979a87
    - a1ba57e3-00d8-11ed-a4d2-7c8ae1979a87
    - a1ba57e4-00d8-11ed-b159-7c8ae1979a87
    - a1ba57e5-00d8-11ed-ac4d-7c8ae1979a87
    - a1ba57e6-00d8-11ed-8fe4-7c8ae1979a87
    - a1ba57e7-00d8-11ed-bdb6-7c8ae1979a87
    - a1ba57e8-00d8-11ed-9e93-7c8ae1979a87
    valid:
    - a1ba57d6-00d8-11ed-b487-7c8ae1979a87
    - a1ba57d7-00d8-11ed-8e7f-7c8ae1979a87
    - a1ba57d8-00d8-11ed-aaa6-7c8ae1979a87
    - a1ba57d9-00d8-11ed-b71c-7c8ae1979a87
