imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 234
    - 987
    valid:
    - Hello
    - World
  type: string
- attribute: id
  description: id of someone
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - Hello
    - World
    valid:
    - 234
    - 987
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - Hello
    - World
    valid:
    - 23.4
    - 987
  type: float
- attribute: ipv4_for
  description: IP-address v4
  required: true
  subtype: ipv4
  test_params:
    invalid:
    - 272.296.264.277
    valid:
    - 211.242.42.76
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    valid:
    - 1
    - 53
    - 65535
  type: int
  validation:
    func_name: IsPortNumber
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    valid:
    - 1
    - 100
    - 50
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - nqa0pvxzrh
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    valid:
    - 0
    - 32
    - 16
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
types:
  base64:
    invalid: a3+J1b%mFs//
    valid: d3lic3M5d3F3eg==
  cidr:
    invalid: 283.271.279.300/24
    valid: 224.3.222.219/17
  ipv4:
    invalid: 272.296.264.277
    valid: 211.242.42.76
  ipv6:
    invalid: invalidIPv6
    valid: cd49:cc6e:2d7b:3073:33e6:41b2
  json:
    invalid: 'json({ name : val)'
    valid: 'json({ "attribute" : "value" })'
  mac:
    invalid: invalidMAC
    valid: 9c:aa:8f:12:83:5c
  regex:
    invalid: '[0-9)++'
    valid: (?m)^[0-9]{2}$
  string:
    invalid: 12345
    valid: sfdcuye0gr
  time:
    invalid: '2022-06-14 18:52:46.924161'
    valid: '2022-06-14T13:22:46.924161+00:00'
  url-http:
    invalid: ht:/qskkk0ewxbf326y.com
    valid: http://su7ph1aoecp0cs1.com
  url-https:
    invalid: hts:/ym80ze8uag4drts.com
    valid: https://er9p02yp76vfw8h.com
  uuid:
    invalid: invalid323Uuid12
    valid: 14b75b11-ebe5-11ec-a851-7c8ae1943087
