imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  depends_on:
    attribute_name: id
    resource_name: tenant
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  type: string
- attribute: temp
  depends_on:
    attribute_name: application_dn
    resource_name: application_profile
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - Hello
    - World
    valid:
    - 23.4
    - 987
  type: float
- attribute: ipv4_for
  description: IP-address v4
  required: true
  subtype: ipv4
  test_params:
    invalid:
    - 294.290.292.266
    valid:
    - 79.205.173.76
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    valid:
    - 1
    - 53
    - 65535
  type: int
  validation:
    func_name: IsPortNumber
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    valid:
    - 1
    - 100
    - 50
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - 6xxqoku5qi
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    valid:
    - 0
    - 32
    - 16
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
types:
  base64:
    invalid: a3+J1b%mFs//
    valid: bGQ1NjNheG15MA==
  cidr:
    invalid: 268.279.298.279/20
    valid: 177.182.221.39/9
  ipv4:
    invalid: 294.290.292.266
    valid: 79.205.173.76
  ipv6:
    invalid: invalidIPv6
    valid: 193d:bd49:4521:c2d4:b82b:586d
  json:
    invalid: 'json({ name : val)'
    valid: 'json({ "attribute" : "value" })'
  mac:
    invalid: invalidMAC
    valid: 4d:c2:27:ad:b6:90
  regex:
    invalid: '[0-9)++'
    valid: (?m)^[0-9]{2}$
  string:
    invalid: 12345
    valid: 753klrtgtp
  time:
    invalid: '2022-06-22 11:21:56.004440'
    valid: '2022-06-22T05:51:56.004440+00:00'
  url-http:
    invalid: ht:/obs8axwed1nowbp.com
    valid: http://lcj8wxfzwbp2l23.com
  url-https:
    invalid: hts:/w7puffz8tcby9qx.com
    valid: https://0k7w9r404xztqk4.com
  uuid:
    invalid: invalid323Uuid12
    valid: 6c6a9379-f1ef-11ec-885d-7c8ae1943087
