base64:
  invalid: a3+J1b%mFs//
  valid: b2tjYThwc25pcg==
cidr:
  invalid: 294.281.295.288/3
  valid: 198.45.35.129/9
imports:
<<<<<<< HEAD
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
ipv4:
  invalid: 280.281.292.269
  valid: 71.230.128.82
ipv6:
  invalid: invalidIPv6
  valid: fb2d:2b35:b822:be17:b361:6691
json:
  invalid: '{ name : val'
  valid: '{ "attribute" : "value" }'
mac:
  invalid: invalidMAC
  valid: 52:af:5f:a6:77:24
name: Contract
provider_name: Aci
regex:
  invalid: '[0-9)++'
  valid: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
schemas:
- attribute: name
  description: name
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid: 12345
    valid: ufl4ow8f3q
  type: string
- attribute: annotation
  description: annotation
  optional: true
  subtype: string
  test_params:
    invalid: 12345
    valid: ufl4ow8f3q
  type: string
- attribute: description
  description: description
  optional: true
  subtype: string
  test_params:
    invalid: 12345
    valid: ufl4ow8f3q
  type: string  
- attribute: ipv4
  description: IP-address v4
  required: true
  subtype: ipv4
  test_params:
    invalid: 280.281.292.269
    valid: 71.230.128.82
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: ipv6
  description: IP-address v6
  required: true
  subtype: ipv6
  test_params:
    invalid: invalidIPv6
    valid: fb2d:2b35:b822:be17:b361:6691
  type: string
  validation:
    func_name: IsIPv6Address
- attribute: mac
  required: true
  subtype: mac
  test_params:
    invalid: invalidMAC
    valid: 52:af:5f:a6:77:24
  type: string
  validation:
    func_name: IsMACAddress
- attribute: cidr
  required: true
  subtype: cidr
  test_params:
    invalid: 294.281.295.288/3
    valid: 198.45.35.129/9
  type: string
  validation:
    func_name: IsCIDR
- attribute: time
  required: true
  subtype: time
  test_params:
    invalid: &id001 2022-06-10 10:35:34.280848
    valid: '2022-06-10T05:05:34.280848+00:00'
  type: string
  validation:
    func_name: IsRFC3339Time
- attribute: url_https
  required: true
  subtype: url-https
  test_params:
    invalid: hts:/mwr55uu54uidy92.com
    valid: https://er388ujn1sa2dn2.com
  type: string
  validation:
    func_name: IsURLWithHTTPS
- attribute: url_http
  required: true
  subtype: url-http
  test_params:
    invalid: ht:/2egn4f7t90tfzhc.com
    valid: http://clb80ylsgjrrf6d.com
  type: string
  validation:
    func_name: IsURLWithHTTPorHTTPS
- attribute: uuid
  required: true
  subtype: uuid
  test_params:
    invalid: invalid323Uuid12
    valid: f56c3da5-e87a-11ec-a5f9-7c8ae19799de
  type: string
  validation:
    func_name: IsUUID
- attribute: base_64
  required: true
  subtype: base64
  test_params:
    invalid: a3+J1b%mFs//
    valid: b2tjYThwc25pcg==
  type: string
  validation:
    func_name: StringIsBase64
- attribute: json
  required: true
  subtype: json
  test_params:
    invalid: '{ name : val'
    valid: '{ "attribute" : "value" }'
  type: string
  validation:
    func_name: StringIsJSON
- attribute: reg_exp
  required: true
  subtype: regex
  test_params:
    invalid: '[0-9)++'
    valid: \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b
  type: string
  validation:
    func_name: StringIsValidRegExp
- attribute: gender
  subtype: string
  test_params:
    invalid: 12345
    valid: ufl4ow8f3q
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - male
    - female
    - other
- attribute: port_number
  required: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    valid:
    - 1
    - 53
    - 65535
  type: int
  validation:
    func_name: IsPortNumber
- attribute: port_with_zero
  required: true
  subtype: port0
  test_params:
    invalid:
    - -1
    - 65536
    valid:
    - 0
    - 1
    - 53
    - 65535
  type: int
  validation:
    func_name: IsPortNumberOrZero
- attribute: nuclear_code
  description: Nuclear code
  required: true
  sensitive: true
  subtype: string
  test_params:
    invalid: 12345
    valid: ufl4ow8f3q
  type: string
  validation:
    func_name: NotInYourList
- attribute: test_score
  computed: true
  description: range
  required: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    valid:
    - 1
    - 100
    - 50
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: percentage
  computed: true
  required: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    valid:
    - 0
    - 100
    - 50
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: filter
  computed: true
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      required: true
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      optional: true
      type: string
    - attribute: filter_entry
      computed: true
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
=======
  - "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
  - "github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

schemas:
  - attribute: "name"
    type: "string"
    # optional: true
    required: true
    forcenew: true
    description: "name of someone"
    # depends_on:
    #   resource_name: "tenant"
    #   attribute_name:
    #     - "filter"
    #     - "filter_entry"
    #     - "name"

  - attribute: "temp"
    type: "int"
    required: true
    # optional: true
    forcenew: true
    description: "temp of some resource"
    # depends_on:
    #   resource_name: "application_profile"
    #   attribute_name:
    #     - "application_dn"

  - attribute: "weight"
    type: "float"
    # optional: true
    required: true
    forcenew: true
    description: "weight of someone"

  # - attribute: "is_good_student"
  #   type: "bool"
  #   required: true
  #   forcenew: true
  #   description: "Honesty of someone"

  - attribute: "ipv4_for"
    type: "string"
    optional: true
    # required: true
    description: "IP-address v4"
    validation:
      func_name: "IsIPv4Address"

  # - attribute: "ipv6"
  #   type: "string"
  #   # optional: true
  #   required: true
  #   description: "IP-address v6"
  #   validation:
  #     func_name: "IsIPv6Address"

  # - attribute: "mac"
  #   type: "string"
  #   # optional: true
  #   required: true
  #   validation:
  #     func_name: "IsMACAddress"

  # - attribute: "cidr"
  #   type: "string"
  #   optional: true
  #   # required: true
  #   validation:
  #     func_name: "IsCIDR"

  # - attribute: "time"
  #   type: "string"
  #   # optional: true
  #   required: true
  #   validation:
  #     func_name: "IsRFC3339Time"

  # - attribute: "url_https"
  #   type: "string"
  #   optional: true
  #   # required: true
  #   validation:
  #     func_name: "IsURLWithHTTPS"

  # - attribute: "url_http"
  #   type: "string"
  #   # optional: true
  #   required: true
  #   validation:
  #     func_name: "IsURLWithHTTPorHTTPS"

  # - attribute: "uuid"
  #   type: "string"
  #   optional: true
  #   # required: true
  #   validation:
  #     func_name: "IsUUID"

  # - attribute: "base_64"
  #   type: "string"
  #   optional: true
  #   # required: true
  #   validation:
  #     func_name: "StringIsBase64"

  # - attribute: "json"
  #   type: "string"
  #   optional: true
  #   # required: true
  #   validation:
  #     func_name: "StringIsJSON"

  # - attribute: "reg_exp"
  #   type: "string"
  #   # optional: true
  #   required: true
  #   validation:
  #     func_name: "StringIsValidRegExp"

  # - attribute: "gender"
  #   type: "string"
  #   validation:
  #     func_name: "StringInSlice"
  #     ignore_case: true
  #     params:
  #       - "male"
  #       - "female"
  #       - "other"

  - attribute: "port_number"
    type: "int"
    optional: true
    # required: true
    validation:
      func_name: "IsPortNumber"

  # - attribute: "port_with_zero"
  #   type: "int"
  #   optional: true
  #   # required: true
  #   validation:
  #     func_name: "IsPortNumberOrZero"

  # - attribute: "nuclear_code"
  #   optional: true
  #   # required: true
  #   sensitive: true
  #   description: "Nuclear code"
  #   validation:
  #     func_name: "NotInYourList"
  #   type: "string"
  #   # type: "list"
  #   # element:
  #   #   schema:
  #   #     type: "string"

  - attribute: "temp_schema_list"
    type: "set"
    # optional: true
    required: true
    element:
      type: "schema"
      schema:
        default: ["Hello", "10.3442", "2"]
        type: "string"

  - attribute: "test_score"
    type: "int"
    # required: true
    optional: true
    computed: true
    description: "range"
    validation:
      func_name: "IntBetween"
      params:
        - 1
        - 100
  - attribute: "string_in_some_names"
    type: "string"
    # required: true
    optional: true
    computed: true
    description: "string in valid list"
    default: parth
    validation:
      func_name: "StringInSlice"
      params:
        - parth
        - aarsh
        - arjun
        - alfatah
        - krunal
      ignore_case: true

  - attribute: "valid_cidr"
    type: "string"
    # required: true
    optional: true
    computed: true
    description: "cidr network"
    validation:
      func_name: "IsCIDRNetwork"
      params:
        - 0
        - 32
      ignore_case: true
  - attribute: "percentage"
    type: "float"
    # required: true
    optional: true
    computed: true
    validation:
      func_name: "FloatBetween"
      params:
        - 0
        - 100
  - attribute: "testingmap"
    type: "map"
    optional: true
    computed: true
    element:
      type: "schema"
      schema:
        type: "int"   

  - attribute: "filter"
    type: "list"
    # optional: true
    required: true
    # computed: true
    description: "filter list"
    max_items: 10
    element:
      type: "resource"
      schema:
        - attribute: "filter_name"
          type: "float"
          # required: true
          optional: true
          description: "name of filter"
          validation:
            func_name: "FloatBetween"
            params:
              - 50
              - 100
        - attribute: "id"
          type: "string"
          computed: true
          description: "id of filter"
          default_func: true
          envvar: "FILTER_ID"
        - attribute: "description"
          type: "string"
          required: true
          # optional: true
          computed: true
          description: "description of filter"
          default_func: true
        - attribute: "filter_entry"
          type: "list"
          required: true
          # optional: true
          # computed: true
          description: "list of filter_entry"
          min_items: 1
          max_items: 4
>>>>>>> efbc3794e66f8eff9890f6294fd3a234e47f290b
          element:
            schema:
<<<<<<< HEAD
              type: string
            type: schema
          required: true
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          type: string
          validation:
            func_name: StringInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        type: resource
      max_items: 4
      min_items: 1
      optional: true
      type: list
    type: resource
  max_items: 10
  optional: true
  type: list
string:
  invalid: 12345
  valid: ufl4ow8f3q
time:
  invalid: *id001
  valid: '2022-06-10T05:05:34.280848+00:00'
url-http:
  invalid: ht:/2egn4f7t90tfzhc.com
  valid: http://clb80ylsgjrrf6d.com
url-https:
  invalid: hts:/mwr55uu54uidy92.com
  valid: https://er388ujn1sa2dn2.com
uuid:
  invalid: invalid323Uuid12
  valid: f56c3da5-e87a-11ec-a5f9-7c8ae19799de
=======
              - attribute: "id_list"
                type: "set"
                required: true
                element:
                  type: "schema"
                  schema:
                    type: "string"
              - attribute: "filter_entry_name"
                type: "string"
                required: true
                description: "name of filter entry"
                diff_suppress: true
              - attribute: "ipv6"
                type: "string"
                optional: true
                # computed: true
                description: "ipv6"
                validation:
                  func_name: "IsIPv6Address"
              - attribute: "apply_to_frag"
                type: "string"
                optional: true
                computed: true
                validation:
                  func_name: "StringNotInSlice"
                  ignore_case: "false"
                  params:
                    - "yes"
                    - "no"
                description: "apply to fragment"
              - attribute: "apply_to_frag_liist_schema"
                type: "list"
                optional: true
                computed: true
                description: "apply to fragment"
                element:
                  type: schema
                  schema:
                    type: "bool"
>>>>>>> efbc3794e66f8eff9890f6294fd3a234e47f290b
