imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  subtype: string
  test_params:
    invalid:
    - 234
    - 987
    valid:
    - Hello
    - World
  type: string
- attribute: id
  description: id of someone
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - Hello
    - World
    valid:
    - 234
    - 987
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - Hello
    - World
    valid:
    - 23.4
    - 987
  type: float
- attribute: is_good_student
  description: Honesty of someone
  forcenew: true
  required: true
  subtype: bool
  test_params:
    invalid:
    - 235
    - World
    valid:
    - true
    - false
  type: bool
- attribute: ipv4
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid:
    - 296.281.285.274
    valid:
    - 101.235.83.204
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: ipv6
  description: IP-address v6
  required: true
  subtype: ipv6
  test_params:
    invalid:
    - invalidIPv6
    valid:
    - 1cc9:d6b9:7b99:4f83:eb3b:d2aa
  type: string
  validation:
    func_name: IsIPv6Address
- attribute: mac
  required: true
  subtype: mac
  test_params:
    invalid:
    - invalidMAC
    valid:
    - d9:88:f1:b2:2c:66
  type: string
  validation:
    func_name: IsMACAddress
- attribute: cidr
  optional: true
  subtype: cidr
  test_params:
    invalid:
    - 280.283.272.286/11
    valid:
    - 92.170.124.56/7
  type: string
  validation:
    func_name: IsCIDR
- attribute: time
  required: true
  subtype: time
  test_params:
    invalid:
    - '2022-06-13 18:21:15.953419'
    valid:
    - '2022-06-13T12:51:15.953419+00:00'
  type: string
  validation:
    func_name: IsRFC3339Time
- attribute: url_https
  optional: true
  subtype: url-https
  test_params:
    invalid:
    - hts:/wmw6xh4gq4xevbc.com
    valid:
    - https://vue6ep1bbldkfa9.com
  type: string
  validation:
    func_name: IsURLWithHTTPS
- attribute: url_http
  required: true
  subtype: url-http
  test_params:
    invalid:
    - ht:/5f6kjcinv9vqo6c.com
    valid:
    - http://bxgacoq7epli06c.com
  type: string
  validation:
    func_name: IsURLWithHTTPorHTTPS
- attribute: uuid
  optional: true
  subtype: uuid
  test_params:
    invalid:
    - invalid323Uuid12
    valid:
    - 83325e73-eb17-11ec-9b4b-7c8ae1943087
  type: string
  validation:
    func_name: IsUUID
- attribute: base_64
  optional: true
  subtype: base64
  test_params:
    invalid:
    - a3+J1b%mFs//
    valid:
    - OGc2Nm9rOW54eQ==
  type: string
  validation:
    func_name: StringIsBase64
- attribute: json
  optional: true
  subtype: json
  test_params:
    invalid:
    - 'json({ name : val)'
    valid:
    - 'json({ "attribute" : "value" })'
  type: string
  validation:
    func_name: StringIsJSON
- attribute: reg_exp
  required: true
  subtype: regex
  test_params:
    invalid:
    - '[0-9)++'
    valid:
    - (?m)^[0-9]{2}$
  type: string
  validation:
    func_name: StringIsValidRegExp
- attribute: gender
  subtype: string
  test_params:
    invalid:
    - 12345
    valid:
    - 701vogs508
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - male
    - female
    - other
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    valid:
    - 1
    - 53
    - 65535
  type: int
  validation:
    func_name: IsPortNumber
- attribute: port_with_zero
  optional: true
  subtype: port0
  test_params:
    invalid:
    - -1
    - 65536
    valid:
    - 0
    - 1
    - 53
    - 65535
  type: int
  validation:
    func_name: IsPortNumberOrZero
- attribute: nuclear_code
  description: Nuclear code
  optional: true
  sensitive: true
  subtype: string
  test_params:
    invalid:
    - 12345
    valid:
    - 701vogs508
  type: string
  validation:
    func_name: NotInYourList
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    valid:
    - 1
    - 100
    - 50
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    valid:
    - 0
    - 100
    - 50
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: filter
  computed: true
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      required: true
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      optional: true
      type: string
    - attribute: filter_entry
      computed: true
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          type: string
          validation:
            func_name: StringInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        type: resource
      max_items: 4
      min_items: 1
      optional: true
      type: list
    type: resource
  max_items: 10
  optional: true
  type: list
types:
  base64:
    invalid: a3+J1b%mFs//
    valid: OGc2Nm9rOW54eQ==
  cidr:
    invalid: 280.283.272.286/11
    valid: 92.170.124.56/7
  ipv4:
    invalid: 296.281.285.274
    valid: 101.235.83.204
  ipv6:
    invalid: invalidIPv6
    valid: 1cc9:d6b9:7b99:4f83:eb3b:d2aa
  json:
    invalid: 'json({ name : val)'
    valid: 'json({ "attribute" : "value" })'
  mac:
    invalid: invalidMAC
    valid: d9:88:f1:b2:2c:66
  regex:
    invalid: '[0-9)++'
    valid: (?m)^[0-9]{2}$
  string:
    invalid: 12345
    valid: 701vogs508
  time:
    invalid: '2022-06-13 18:21:15.953419'
    valid: '2022-06-13T12:51:15.953419+00:00'
  url-http:
    invalid: ht:/5f6kjcinv9vqo6c.com
    valid: http://bxgacoq7epli06c.com
  url-https:
    invalid: hts:/wmw6xh4gq4xevbc.com
    valid: https://vue6ep1bbldkfa9.com
  uuid:
    invalid: invalid323Uuid12
    valid: 83325e73-eb17-11ec-9b4b-7c8ae1943087
