imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  depends_on:
    attribute_name:
    - filter
    - filter_entry
    - name
    resource_name: tenant
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - smr1avunoq
    - q3sl11q8t6
    - spysatatjm
    - sx0jluog06
    - w4wmvy587s
    - so3yh6zw09
    - n5e032xu1c
    - wqfs1mgf9y
    - pltz5tsvj4
    - kl30pt3xs3
    - dl0fhfjkce
    - fphdulnrvq
    - s45iya9odx
    - wyw21vd6p5
    - yx2ihkylzl
    valid:
    - ib57k6k0ob
    - sy3kn34px9
    - 5g0oxhd0dd
    - fg6fhq52uw
  type: string
- attribute: temp
  depends_on:
    attribute_name:
    - application_dn
    resource_name: application_profile
  description: temp of some resource
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - -1000
    - 301
    - -188
    - -475
    - -232
    - -201
    - 408
    - -850
    - 167
    - -217
    - -438
    - -860
    - -69
    - 238
    - 280
    valid:
    - -943
    - -863
    - -615
    - -440
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - -0.42853307801350426
    - 188.67339266292572
    - 39.462590117803934
    - -639.7643873528164
    - -145.8702448802587
    - -306.2923820171308
    - -336.4600235502115
    - 643.6038105074292
    - 152.81087148216577
    - -230.13598768146088
    - -273.86151467246873
    - -123.17694977239557
    - -467.7534722258367
    - 175.6709677092868
    - 103.03241124207479
    valid:
    - -232.95313868437975
    - -96.95418868143406
    - -100.53403174895872
    - -153.46931907789437
  type: float
- attribute: ipv4_for
  description: IP-address v4
  required: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 267.277.281.286
    multiple_valids: &id002
    - 208.41.80.53
    - 208.41.0.131
    - 208.41.32.130
    - 208.41.58.15
    - 208.41.181.61
    - 208.41.151.152
    - 208.41.213.168
    - 208.41.229.158
    - 208.41.18.205
    - 208.41.208.140
    - 208.41.137.0
    - 208.41.205.210
    - 208.41.210.121
    - 208.41.41.108
    - 208.41.104.207
    valid: &id003
    - 208.41.80.53
    - 208.41.0.131
    - 208.41.32.130
    - 208.41.58.15
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 2092
    - 27356
    - 5698
    - 21721
    - 8200
    - 3654
    - 4679
    - 63781
    - 52123
    - 39407
    - 22047
    - 60818
    - 45608
    valid:
    - 1
    - 65535
    - 39319
    - 62959
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      default:
      - Hello
      - '10.3442'
      - '2'
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - asnyiktdiu
    - yx8vp6ia82
    - wru6clk9fy
    - d4pwld83iw
    - 77xo07fv5l
    - emybd0cxzz
    - u375ju5b9i
    - 0lhwadcoij
    - k6j0iu02ys
    - 8habasmzem
    - zhcos7tk1u
    - crs09ihmnx
    - rdown2p67y
    - okb4ngk7hh
    - hfzkc3s3jm
    valid:
    - l0ce6bicqr
    - t6tqfxypan
    - jn79uvss2k
    - 9axw2vh42x
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 30
    - 37
    - 36
    - 66
    - 53
    - 37
    - 77
    - 46
    - 3
    - 24
    - 29
    - 35
    valid:
    - 1
    - 100
    - 50
    - 48
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - wnoe5v1ltx
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 30
    - 10
    - 5
    - 12
    - 29
    - 21
    - 28
    - 15
    - 31
    - 5
    - 20
    - 4
    valid:
    - 0
    - 32
    - 16
    - 21
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 31.39012924699733
    - 14.552797639146688
    - 7.683031514319582
    - 53.339113566464306
    - 39.74839659807847
    - 23.870415037284626
    - 55.48580085505294
    - 11.85264443892742
    - 0.4145263169945834
    - 7.358523616848771
    - 13.811146447944788
    - 0.5287296784194194
    valid:
    - 0
    - 100
    - 50.0
    - 79.25895836369423
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 656
    - 943
    - 387
    - 905
    - 344
    - -10
    - 505
    - -279
    - 198
    - -398
    - 419
    - -913
    - -752
    - 762
    - -761
    valid:
    - -319
    - 717
    - 845
    - -48
  type: map
- attribute: filter
  computed: true
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 1h01rgdbbx
        - v58fxfrfm8
        - q6rni9yuym
        - 1x1v7dxk42
        - hhaj7zxaw2
        - 32hfmysi97
        - lozdc6ypd2
        - xd6ppmyhkv
        - 3mnd78x97k
        - 33adg17a8f
        - nyoeb5k53z
        - ah905i61rq
        - kwxvs3hxcs
        - fng6v8h2kp
        - c0u70qto06
        valid:
        - b3m2rks0pa
        - bqw0fnv2dv
        - yufofii005
        - ha8b0w39ad
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 4uvcqkruvk
        - b5o5spxgpn
        - ie91zbt1cw
        - osv52f820q
        - g2vzz1p6eu
        - o7s2k423gg
        - eriri4lsyd
        - hkit2zsq8p
        - dhayvod9q2
        - 4uxwe0x7ew
        - kmer14xvrm
        - jza9r5g1ob
        - ngbvi7prne
        - l4x8cwvluo
        - zqh27hs388
        valid:
        - cwtl9jl5dl
        - 3tbpki57j1
        - d1wzbikz34
        - w0np8ipbbu
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - qi53fweqwu
        - ts9zdkcbyo
        - 40t9y82ayz
        - zwrf9hk7hy
        - ko6w9t6f6u
        - v331lkxda6
        - kosn4ija6z
        - o4ocssfhms
        - igzxcvrw63
        - axxbablnz8
        - pdu9vvsdmv
        - wm6eodb6ao
        - 8cjbquxov8
        - hsm9ictzxj
        - 30irtvxhya
        valid:
        - grfar7akjm
        - eokmc4yxw6
        - qxh9uctivj
        - p4b065xhj6
      type: string
    - attribute: filter_entry
      computed: true
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - opdbinmxur
            - 2tkx0a814s
            - 3fs5uz5we7
            - ehnt8cb4au
            - ua4w2wvr13
            - 7fyfg0elw4
            - d7vkf7r0q4
            - xdn60l052r
            - tzr6xjb1jz
            - xggvme6hxk
            - v06m4ycnf9
            - yeddvm3tsp
            - j6ix7djs2x
            - nnwkzr16rl
            - 8bz45hazhp
            valid:
            - zgcpqsjbf8
            - wieiuvwpva
            - 2f856ubhuu
            - xu2p664hzr
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - 445slsb139
            - e7eu9kgm66
            - rfw3w2tm9k
            - p90iv52bcd
            - jdzu2qy85w
            - 4ln6f8jk8j
            - 0pj0wqp06y
            - nchmd5nfvl
            - a5a5eawook
            - mybpoib260
            - hkgz532dcn
            - 1u0vu7cqlw
            - v6mhd9wwtl
            - cfdewt4rfp
            - lw3wydup37
            valid:
            - dj1fbp5hek
            - v7jdigiz0x
            - dnarfr2byc
            - soppt6a4nc
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f3d4
            - 2001:db8::34f4:0:0:f363
            - 2001:db8::34f4:0:0:f317
            - 2001:db8::34f4:0:0:f304
            - 2001:db8::34f4:0:0:f329
            - 2001:db8::34f4:0:0:f30b
            - 2001:db8::34f4:0:0:f3e4
            - 2001:db8::34f4:0:0:f35d
            - 2001:db8::34f4:0:0:f362
            - 2001:db8::34f4:0:0:f335
            - 2001:db8::34f4:0:0:f3aa
            - 2001:db8::34f4:0:0:f3a9
            - 2001:db8::34f4:0:0:f3d7
            - 2001:db8::34f4:0:0:f35b
            - 2001:db8::34f4:0:0:f349
            valid: &id006
            - 2001:db8::34f4:0:0:f3d4
            - 2001:db8::34f4:0:0:f363
            - 2001:db8::34f4:0:0:f317
            - 2001:db8::34f4:0:0:f304
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - 57yjrpnc2o
            - 865i9yrqjb
            - 2p6q5rit52
            - zshbeqoh3h
            - tc07o5w9it
            - kfbu25w9or
            - cvdblfr6vb
            - gmbo567a5l
            - 2sarz43gry
            - 8dk1qnq3cq
            - xhe12vre6h
            - fd0wuk6l0v
            - mucg7teqse
            - yjq8wrizns
            - y475ody7ir
            valid:
            - gqdrd01uu3
            - qkbx6thckg
            - qz6bk4akah
            - 26fa61kfo6
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      optional: true
      type: list
    type: resource
  max_items: 10
  optional: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - dnh4YngxNHI0Yg==
    - YnV3aW8xMTh1NA==
    - YTNsenVyM3Bncg==
    - ODl4YzRkNHFqNA==
    - MjRoZTJhY3AzcQ==
    - NnBwbGM4OHAwMA==
    - bDJvaXd4eXdsNg==
    - b2FzeXBzMzY2Zg==
    - eDZ5N2F5YjVlYw==
    - dGd5Y2RnNXR1ZQ==
    - M29qdG40YXg2aQ==
    - MGpvc3pkamc4MA==
    - eTlreXBwYTEzMQ==
    - aXk3MTdjd3J3dA==
    - MmZ2dXgyMHQ1ag==
    valid:
    - Ynp5ZjVyenlmdQ==
    - ZmlhOGVremR3Zw==
    - a3NkM3JmNHVyNw==
    - aG1xMTBwYzFjdQ==
  cidr:
    invalid:
    - 268.290.266.297/28
    multiple_valids:
    - 208.41.112.0/20
    - 208.41.144.0/20
    - 208.41.160.0/20
    - 208.41.224.0/20
    - 208.41.48.0/20
    - 208.41.240.0/20
    - 208.41.176.0/20
    - 208.41.80.0/20
    - 208.41.0.0/20
    - 208.41.32.0/20
    - 208.41.64.0/20
    - 208.41.96.0/20
    - 208.41.192.0/20
    - 208.41.16.0/20
    - 208.41.128.0/20
    valid:
    - 208.41.112.0/20
    - 208.41.144.0/20
    - 208.41.160.0/20
    - 208.41.224.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 0d:54:6b:8d:94:be
    - 49:aa:6e:08:d0:7e
    - 7f:5d:b0:10:9c:dc
    - da:2c:42:27:af:04
    - 48:6e:62:32:fa:99
    - 04:89:77:9b:64:7d
    - df:5b:b7:e3:a3:eb
    - cf:05:1c:b4:a3:6d
    - b5:b8:42:d6:11:51
    - f2:a5:12:05:83:52
    - 79:56:d8:d9:e8:48
    - bc:ec:f0:21:e3:f3
    - 05:e8:73:05:6d:0e
    - 78:b7:66:d9:3b:ea
    - 72:54:da:d9:e6:4e
    valid:
    - 46:63:fa:d6:37:9b
    - 29:11:b4:19:94:5a
    - 2f:12:d4:47:43:13
    - 14:2d:a0:3c:52:a7
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - shdp0ui7tu
    - xpqkhw5hug
    - 3r5pa3hg0h
    - jvmenvi832
    - ei9h88qltm
    - s6woc3wljo
    - nk89cqogre
    - cppsr01z11
    - 5492pi0weg
    - par2qyby43
    - hmwthn90w9
    - vvjm65rtjg
    - jrly1nvews
    - byfmbrrn36
    - c1gq2mn5p7
    valid:
    - 6x0i6m7s38
    - wtfvka8zu3
    - mnjg5rr1s1
    - s1mgkyj5j7
  time:
    invalid:
    - '2022-06-29 18:09:34.703210'
    multiple_valids:
    - '2022-06-29T12:39:34.703210+00:00'
    - '2022-07-22T12:39:34.703210+00:00'
    - '2022-08-14T12:39:34.703210+00:00'
    - '2022-09-06T12:39:34.703210+00:00'
    - '2022-09-29T12:39:34.703210+00:00'
    - '2022-10-22T12:39:34.703210+00:00'
    - '2022-11-14T12:39:34.703210+00:00'
    - '2022-12-07T12:39:34.703210+00:00'
    - '2022-12-30T12:39:34.703210+00:00'
    - '2023-01-22T12:39:34.703210+00:00'
    - '2023-02-14T12:39:34.703210+00:00'
    - '2023-03-09T12:39:34.703210+00:00'
    - '2023-04-01T12:39:34.703210+00:00'
    - '2023-04-24T12:39:34.703210+00:00'
    - '2023-05-17T12:39:34.703210+00:00'
    valid:
    - '2022-06-29T12:39:34.703210+00:00'
    - '2022-07-22T12:39:34.703210+00:00'
    - '2022-08-14T12:39:34.703210+00:00'
    - '2022-09-06T12:39:34.703210+00:00'
  url-http:
    invalid:
    - ht:/5m5e2ehz0mlt8wn.com
    multiple_valids:
    - http://i318zxkvpnbmxal.com
    - http://pj6g2q2drhxtfae.com
    - http://7mgjst34wj084l5.com
    - http://7s0nmke71ob5a3c.com
    - http://yewl2bcs54i0pbu.com
    - http://3sza856qkivmy94.com
    - http://izw5p5kbzqr6oy7.com
    - http://b5xo3iwesng1b1w.com
    - http://2znr5z76yvckpan.com
    - http://oirid2dawg0jo8c.com
    - http://90qz0npy0p1qslg.com
    - http://2i3mytbafj2u9la.com
    - http://y8v44woh8k85r1z.com
    - http://leg3d7jum61yj1s.com
    - http://9fn6uyns4sboywo.com
    valid:
    - http://by39542cb8nsrxb.com
    - http://hv6mmy75phf7dkh.com
    - http://0s0kzggfn66jqa0.com
    - http://r3xvyodrbdu2amt.com
  url-https:
    invalid:
    - hts:/wzzqycpdam4lubd.com
    multiple_valids:
    - https://zi1hxxxt1oq3ahj.com
    - https://2kmwtep6un3pk8a.com
    - https://sk9yt43lz0k9yds.com
    - https://ap7qqgtlu8d6uvm.com
    - https://s6ztw71oxskeovp.com
    - https://6yt8lmp4g97cca7.com
    - https://7gar5abh5sh31lw.com
    - https://yaic13hx6peisyt.com
    - https://xuo2x0ubj8pk4ua.com
    - https://2t9rg8j9lb7idrz.com
    - https://1qswdbczmypmdz7.com
    - https://fljoqm1buepj2x1.com
    - https://7mcxmbdi2wdkia1.com
    - https://8p2wxj3fa1wdwck.com
    - https://udn77knnk0ketrg.com
    valid:
    - https://tua54wukmxgdj3d.com
    - https://ebtaunojr8pmgv4.com
    - https://ct5w9je06yl3bvw.com
    - https://oc0yntxe8abensq.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 87d41428-f7a8-11ec-bd7e-7c8ae1979a87
    - 87d41429-f7a8-11ec-a792-7c8ae1979a87
    - 87d4142a-f7a8-11ec-8ffd-7c8ae1979a87
    - 87d4142b-f7a8-11ec-a895-7c8ae1979a87
    - 87d4142c-f7a8-11ec-a804-7c8ae1979a87
    - 87d4142d-f7a8-11ec-8bfc-7c8ae1979a87
    - 87d4142e-f7a8-11ec-8e36-7c8ae1979a87
    - 87d4142f-f7a8-11ec-811f-7c8ae1979a87
    - 87d41430-f7a8-11ec-98a1-7c8ae1979a87
    - 87d41431-f7a8-11ec-ae22-7c8ae1979a87
    - 87d41432-f7a8-11ec-b1f4-7c8ae1979a87
    - 87d41433-f7a8-11ec-92b5-7c8ae1979a87
    - 87d41434-f7a8-11ec-b227-7c8ae1979a87
    - 87d41435-f7a8-11ec-b4c9-7c8ae1979a87
    - 87d41436-f7a8-11ec-8527-7c8ae1979a87
    valid:
    - 87d41424-f7a8-11ec-9c90-7c8ae1979a87
    - 87d41425-f7a8-11ec-bb2c-7c8ae1979a87
    - 87d41426-f7a8-11ec-af61-7c8ae1979a87
    - 87d41427-f7a8-11ec-a2ee-7c8ae1979a87
