imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  depends_on:
    attribute_name:
    - filter
    - filter_entry
    - name
    resource_name: tenant
  description: name of someone
  forcenew: true
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - x0wanm0gbo
    - psu2uj8ru6
    - hxk01plejg
    - t4wbpxia1a
    - 8s6g5axb64
    - 8i1z8clv0g
    - w8r6uzhl6a
    - ax3zn7f3ze
    - 5jjy4bpqai
    - bxjm638ew4
    - 2qhy7riu5t
    - npsgq8aexb
    - i09cau00lo
    - twopfbyo5a
    - bewdzivx5d
    valid:
    - dog29cgbx7
    - thditkywge
    - s9zr01jl71
    - a3cy79t1di
  type: string
- attribute: temp
  depends_on:
    attribute_name:
    - application_dn
    resource_name: application_profile
  description: temp of some resource
  forcenew: true
  optional: true
  subtype: int
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 952
    - -310
    - 769
    - 560
    - 24
    - 51
    - -758
    - -241
    - 954
    - 554
    - -137
    - -769
    - -885
    - 618
    - -725
    valid:
    - 855
    - 310
    - -882
    - 843
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  optional: true
  subtype: float
  test_params:
    invalid:
    - random
    - 10
    multiple_valids:
    - 146.53423243762458
    - 424.3870565252249
    - -98.18066272555735
    - -2.4812242490388305
    - 315.79298059869234
    - 61.57851805742344
    - -236.03076418672552
    - -36.002983362634936
    - 20.089460256561694
    - -588.1158558479557
    - -62.07760109992273
    - -107.61136447124511
    - -6.7284332508830715
    - 181.62199436543168
    - 174.37393623658653
    valid:
    - -620.2431013475352
    - -10.947170497216792
    - -276.22230374899914
    - -21.87166550490303
  type: float
- attribute: ipv4_for
  description: IP-address v4
  optional: true
  subtype: ipv4
  test_params:
    invalid: &id001
    - 299.296.279.286
    multiple_valids: &id002
    - 44.154.26.3
    - 44.154.32.133
    - 44.154.142.159
    - 44.154.17.171
    - 44.154.199.105
    - 44.154.166.135
    - 44.154.59.83
    - 44.154.45.209
    - 44.154.209.141
    - 44.154.189.155
    - 44.154.59.143
    - 44.154.4.251
    - 44.154.54.149
    - 44.154.252.206
    - 44.154.44.110
    valid: &id003
    - 44.154.26.3
    - 44.154.32.133
    - 44.154.142.159
    - 44.154.17.171
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    multiple_valids:
    - 1
    - 65535
    - 5264
    - 62225
    - 36156
    - 36955
    - 44089
    - 53790
    - 52847
    - 39829
    - 51321
    - 20314
    - 19567
    - 16858
    - 61858
    valid:
    - 1
    - 65535
    - 31
    - 56795
  type: int
  validation:
    func_name: IsPortNumber
- attribute: temp_schema_list
  element:
    schema:
      default:
      - Hello
      - '10.3442'
      - '2'
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 4p5h1igmn8
    - sldti28ur8
    - 41qtmbpal3
    - 971zavq22q
    - mrrwtoz98j
    - dnpgyhwgj6
    - imxdefd11a
    - 5be15p5d38
    - fs50oht9v9
    - 7b030xx0l1
    - p46dlvjbr9
    - qodnydrlsq
    - h4sr8a8ffl
    - dj3q2dr6yr
    - cmwh4qxayj
    valid:
    - vh1wn6sa37
    - 0enkk5vg7w
    - e4b1wuuz4c
    - d721y6s4pq
  type: set
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    multiple_valids:
    - 1
    - 100
    - 50
    - 47
    - 73
    - 7
    - 55
    - 75
    - 30
    - 73
    - 7
    - 24
    - 64
    - 66
    - 94
    valid:
    - 1
    - 100
    - 50
    - 3
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - o8qrpf7ity
    multiple_valids:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    multiple_valids:
    - 0
    - 32
    - 16
    - 19
    - 8
    - 27
    - 10
    - 14
    - 29
    - 16
    - 21
    - 19
    - 3
    - 29
    - 20
    valid:
    - 0
    - 32
    - 16
    - 20
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
- attribute: percentage
  computed: true
  optional: true
  subtype: range
  test_params:
    invalid:
    - -1
    - 101
    multiple_valids:
    - 0
    - 100
    - 50.0
    - 21.401215060940316
    - 2.0298738607518314
    - 0.2767017212757983
    - 44.83748055132128
    - 28.491863294091697
    - 45.26616306375774
    - 56.6841764981046
    - 9.402481425859676
    - 58.521954533675896
    - 10.212731457116416
    - 7.116431470799252
    - 49.59825999487307
    valid:
    - 0
    - 100
    - 50.0
    - 11.502678360929142
  type: float
  validation:
    func_name: FloatBetween
    params:
    - 0
    - 100
- attribute: testingmap
  computed: true
  element:
    schema:
      type: int
    type: schema
  optional: true
  subtype: map
  test_params:
    invalid:
    - random
    - 10.023
    multiple_valids:
    - 785
    - -51
    - 867
    - 316
    - 881
    - 715
    - -557
    - 253
    - -909
    - 923
    - 594
    - 779
    - 196
    - -168
    - -511
    valid:
    - -949
    - -222
    - -597
    - 414
  type: map
- attribute: filter
  description: filter list
  element:
    schema:
    - attribute: filter_name
      description: name of filter
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - bcbb1elbxi
        - vguyupzdya
        - fnvv1hfyks
        - 202n9q447z
        - j4vfuamq1y
        - ks6ybril75
        - drlo64t4vo
        - pwreufmjfc
        - 234b2d04xu
        - yoibyj91ep
        - fhk5x2y9lv
        - 4yyucf0qoi
        - jfsfugwplt
        - 0ssmtzxmsk
        - gpf6t1ud5i
        valid:
        - cj16wvewl0
        - dfuogsazrb
        - apybpq2sqj
        - yt4d8jzx19
      type: string
    - attribute: id
      computed: true
      default_func: true
      description: id of filter
      envvar: FILTER_ID
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - pm2m7codbh
        - gdm4w45sku
        - 544x24sbm2
        - 7d6o3x1kte
        - hq8qbij8wq
        - 6vnk6peapy
        - nmi0z1w14x
        - vdddy4oll4
        - oilnopgf4i
        - bvtte7157a
        - mum2q6mob4
        - ilqzhvd2nj
        - oi22qw0reu
        - zg0k04xx0o
        - bnlklq54q2
        valid:
        - j2yxcwzg5s
        - w2v06n68ae
        - npd3wcagxq
        - 4ke0iouu6t
      type: string
    - attribute: description
      computed: true
      default_func: true
      description: description of filter
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - hq3pzxij3e
        - w9x1bml5rj
        - addxs3s57v
        - sw63r84c24
        - 9jfzhhansh
        - buqxvkre4t
        - hfqph4k4ve
        - 4uz1szmybs
        - 4vlvfamnvr
        - ibem92h1de
        - f9igm4yvi5
        - frd2fsi9s2
        - dro7ubicg6
        - 8i72bedttg
        - 7934w0cf4e
        valid:
        - 1aytcmj6jx
        - 28y2l5qqhh
        - 2avbjrt5gw
        - v0n2ftujyi
      type: string
    - attribute: filter_entry
      description: list of filter_entry
      element:
        schema:
        - attribute: id_list
          element:
            schema:
              type: string
            type: schema
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - 3qrsh4ah96
            - yh1rc9xo4j
            - s3y3wlwciq
            - g9elrb7qdl
            - dslypobmf2
            - 58n20sf8r2
            - q8hekxm9zt
            - u05cwdlo0i
            - 58v9l15hap
            - yeiygovbe3
            - pvzoutfps7
            - 4ox14rqao3
            - w1ikykz0mw
            - gksg8yedxk
            - s7n38xa5a9
            valid:
            - 5x2t2sp1sc
            - dk1ztkdsat
            - hntn240s14
            - agk0zd3u6n
          type: set
        - attribute: filter_entry_name
          description: name of filter entry
          diff_suppress: true
          required: true
          subtype: string
          test_params:
            invalid:
            - 10
            - 12.43
            multiple_valids:
            - wczvblpv37
            - 1r32n8qhe4
            - dnjvf0n447
            - ma8l5cjz7h
            - 4y7ifywi2r
            - w41n1f2iur
            - u0ewtei7io
            - deo7rya2gy
            - 0zizxjrcg0
            - 3ngupcmddd
            - u3a1r885oo
            - 2ouvrb4bgw
            - hqklk3jzsa
            - 30ft7rorhp
            - 8hxpstax52
            valid:
            - ifd92s6xyb
            - a1ggj6s5b4
            - 2t0p710hug
            - xvgio06j93
          type: string
        - attribute: ipv6
          description: ipv6
          optional: true
          subtype: ipv6
          test_params:
            invalid: &id004
            - invalidIPv6
            multiple_valids: &id005
            - 2001:db8::34f4:0:0:f3ae
            - 2001:db8::34f4:0:0:f38d
            - 2001:db8::34f4:0:0:f393
            - 2001:db8::34f4:0:0:f3ba
            - 2001:db8::34f4:0:0:f35e
            - 2001:db8::34f4:0:0:f378
            - 2001:db8::34f4:0:0:f345
            - 2001:db8::34f4:0:0:f324
            - 2001:db8::34f4:0:0:f320
            - 2001:db8::34f4:0:0:f36c
            - 2001:db8::34f4:0:0:f315
            - 2001:db8::34f4:0:0:f3d1
            - 2001:db8::34f4:0:0:f369
            - 2001:db8::34f4:0:0:f312
            - 2001:db8::34f4:0:0:f30d
            valid: &id006
            - 2001:db8::34f4:0:0:f3ae
            - 2001:db8::34f4:0:0:f38d
            - 2001:db8::34f4:0:0:f393
            - 2001:db8::34f4:0:0:f3ba
          type: string
          validation:
            func_name: IsIPv6Address
        - attribute: apply_to_frag
          computed: true
          description: apply to fragment
          optional: true
          subtype: string
          test_params:
            invalid:
            - 'yes'
            - 'no'
            multiple_valids:
            - h0ftixw831
            - nwtws3qypw
            - 4upvqibk0s
            - shafjb3c86
            - zfbqeq5dpn
            - sc1j1t682t
            - tfin8qpylh
            - twdnhmw8uu
            - aw6nonosmr
            - estg0u0cyd
            - 46dxyrzsrt
            - ubtatfehr2
            - 6bh2o8bn1o
            - 9vl3zfsd9s
            - hyrk2qshy6
            valid:
            - rerom2vime
            - l28lblt2ij
            - 1z7y904lq3
            - q1umjetxun
          type: string
          validation:
            func_name: StringNotInSlice
            ignore_case: 'false'
            params:
            - 'yes'
            - 'no'
        - attribute: apply_to_frag_liist_schema
          computed: true
          description: apply to fragment
          element:
            schema:
              type: bool
            type: schema
          optional: true
          subtype: bool
          test_params:
            invalid:
            - random
            - 10
            multiple_valids:
            - true
            - false
            valid:
            - true
            - false
          type: list
        type: resource
      max_items: 4
      min_items: 1
      required: true
      type: list
    type: resource
  max_items: 10
  required: true
  type: list
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - N3lpdnJsOHNzeg==
    - M3J4MGRrZ2tvcA==
    - d21sc3M5eTdzag==
    - cDlwemdvczRpeQ==
    - d3ZwN3ducmdraw==
    - amh1NnU1MmQ2dg==
    - aWY4aWxrbWxoeA==
    - MDJiY24xeGVzdA==
    - cHh6NHpoenprMA==
    - dWF0czN3YXIyMg==
    - YzVpZDR5eWx0cg==
    - a2o4ZHN2MHVoMA==
    - dmp4dm0wMWJncg==
    - dGxld3c2bWdyNw==
    - aG03bjhsdmUzMA==
    valid:
    - NmZiczAybm1xaA==
    - YXBwemN0cGZ2NQ==
    - eGN2eHQ1Ymlldw==
    - cThxMmE5Z2g2MA==
  cidr:
    invalid:
    - 296.276.256.286/27
    multiple_valids:
    - 44.154.64.0/20
    - 44.154.128.0/20
    - 44.154.208.0/20
    - 44.154.240.0/20
    - 44.154.80.0/20
    - 44.154.96.0/20
    - 44.154.0.0/20
    - 44.154.176.0/20
    - 44.154.192.0/20
    - 44.154.32.0/20
    - 44.154.144.0/20
    - 44.154.48.0/20
    - 44.154.16.0/20
    - 44.154.112.0/20
    - 44.154.224.0/20
    valid:
    - 44.154.64.0/20
    - 44.154.128.0/20
    - 44.154.208.0/20
    - 44.154.240.0/20
  ipv4:
    invalid: *id001
    multiple_valids: *id002
    valid: *id003
  ipv6:
    invalid: *id004
    multiple_valids: *id005
    valid: *id006
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - dc:30:c8:04:0a:97
    - d7:06:17:8c:b9:da
    - 53:0c:08:02:ed:e4
    - 26:8c:81:ac:a3:b1
    - bc:6e:4e:4f:ed:bb
    - 0e:35:1a:52:fc:e4
    - c9:07:81:21:a4:c9
    - 0c:45:76:59:cc:1e
    - 60:77:48:36:a1:19
    - c1:1b:b8:55:7e:d3
    - 9a:ff:f8:f2:2b:04
    - 67:71:0a:f6:00:d9
    - b0:5a:a8:f3:67:bf
    - a4:71:eb:ec:e5:ee
    - 4e:0a:51:ba:48:e3
    valid:
    - 0f:ce:10:eb:6f:c4
    - d0:8c:1d:d4:0b:81
    - a3:ed:7f:a8:97:4d
    - 8f:18:64:9e:d5:85
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - grpz39tbut
    - nxyhe26jep
    - 02j5wd3zp3
    - 6kql562phj
    - qylw9zl5ha
    - 0dk11uvc3n
    - xtou4k64n8
    - yb80as84h7
    - epq6oafl3a
    - qh85dmx3n7
    - i198kekg3j
    - qzb79addx8
    - m0rvpnx439
    - g33fumtb7w
    - 2d6y5luwop
    valid:
    - oabngsgd5n
    - dpl6dt2pvm
    - cwy9hahqmj
    - ydkw2mx2lf
  time:
    invalid:
    - '2022-07-01 15:49:49.314298'
    multiple_valids:
    - '2022-07-01T10:19:49.314298+00:00'
    - '2022-07-24T10:19:49.314298+00:00'
    - '2022-08-16T10:19:49.314298+00:00'
    - '2022-09-08T10:19:49.314298+00:00'
    - '2022-10-01T10:19:49.314298+00:00'
    - '2022-10-24T10:19:49.314298+00:00'
    - '2022-11-16T10:19:49.314298+00:00'
    - '2022-12-09T10:19:49.314298+00:00'
    - '2023-01-01T10:19:49.314298+00:00'
    - '2023-01-24T10:19:49.314298+00:00'
    - '2023-02-16T10:19:49.314298+00:00'
    - '2023-03-11T10:19:49.314298+00:00'
    - '2023-04-03T10:19:49.314298+00:00'
    - '2023-04-26T10:19:49.314298+00:00'
    - '2023-05-19T10:19:49.314298+00:00'
    valid:
    - '2022-07-01T10:19:49.314298+00:00'
    - '2022-07-24T10:19:49.314298+00:00'
    - '2022-08-16T10:19:49.314298+00:00'
    - '2022-09-08T10:19:49.314298+00:00'
  url-http:
    invalid:
    - ht:/erbfld8bnh3khmp.com
    multiple_valids:
    - http://gj0u05j8bb1g5ge.com
    - http://xsljueqvsr2rleo.com
    - http://nvg1chkily4hrcu.com
    - http://imcd80wb3uwehag.com
    - http://q57zm9u69qby8gg.com
    - http://wbi4suy3j32jw9s.com
    - http://e0vbhqcz3nnt9df.com
    - http://w3q87gch7dw5z5k.com
    - http://wtwww96vyb4zzyp.com
    - http://7mtu061xdofjll6.com
    - http://om06mtat0djifgs.com
    - http://ezfcbdwxgx1zt1u.com
    - http://g2kbv376tq0x8zv.com
    - http://zfasubildoes5hm.com
    - http://4ppw44qgvvcubpx.com
    valid:
    - http://g2ugtk9ta21dyu6.com
    - http://hboktkuf9gye7ka.com
    - http://cuds7gqitdq8x7p.com
    - http://09xmi6xp0bhgbnp.com
  url-https:
    invalid:
    - hts:/24f0wyap9hl0v23.com
    multiple_valids:
    - https://cqdh7luaim4gqf5.com
    - https://5vjp5o5yalmgro9.com
    - https://udn4f86pf80hn4z.com
    - https://76qi43cefku6zje.com
    - https://9ultv82tor6cggc.com
    - https://g5z28dhantj4pq4.com
    - https://ftmt4ljq30df8pb.com
    - https://nyvsxr4v78dfx85.com
    - https://3coo8th49tddhyk.com
    - https://07j3ukzydf7ozqp.com
    - https://luepht7czcvz67p.com
    - https://fm14jxc6c5ok5c3.com
    - https://ygrqc6pprn1mj22.com
    - https://n0cusbqpjgos8pc.com
    - https://g69d3nv1sqwk9en.com
    valid:
    - https://4hsurshpdbcrbre.com
    - https://xzn3c1cy0x5448m.com
    - https://i9vpf9qkskpn7xw.com
    - https://pdgzjihzd8ojro9.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - 5692ec80-f927-11ec-ab74-7c8ae1979a87
    - 5692ec81-f927-11ec-b2e2-7c8ae1979a87
    - 5692ec82-f927-11ec-843e-7c8ae1979a87
    - 5692ec83-f927-11ec-9b28-7c8ae1979a87
    - 5692ec84-f927-11ec-abab-7c8ae1979a87
    - 5692ec85-f927-11ec-9bd5-7c8ae1979a87
    - 5692ec86-f927-11ec-a73d-7c8ae1979a87
    - 5692ec87-f927-11ec-be09-7c8ae1979a87
    - 5692ec88-f927-11ec-ab99-7c8ae1979a87
    - 5692ec89-f927-11ec-91bd-7c8ae1979a87
    - 5692ec8a-f927-11ec-ad7c-7c8ae1979a87
    - 5692ec8b-f927-11ec-ba92-7c8ae1979a87
    - 5692ec8c-f927-11ec-b916-7c8ae1979a87
    - 5692ec8d-f927-11ec-bb7c-7c8ae1979a87
    - 5692ec8e-f927-11ec-a51a-7c8ae1979a87
    valid:
    - 5692ec7c-f927-11ec-b440-7c8ae1979a87
    - 5692ec7d-f927-11ec-b060-7c8ae1979a87
    - 5692ec7e-f927-11ec-9310-7c8ae1979a87
    - 5692ec7f-f927-11ec-822a-7c8ae1979a87
