imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: Contract
provider_name: Aci
schemas:
- attribute: name
  description: name of someone
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 234
    - 987
    valid:
    - Hello
    - World
  type: string
- attribute: id
  description: id of someone
  forcenew: true
  required: true
  subtype: int
  test_params:
    invalid:
    - Hello
    - World
    valid:
    - 234
    - 987
  type: int
- attribute: weight
  description: weight of someone
  forcenew: true
  required: true
  subtype: float
  test_params:
    invalid:
    - Hello
    - World
    valid:
    - 23.4
    - 987
  type: float
- attribute: ipv4_for
  description: IP-address v4
  required: true
  subtype: ipv4
  test_params:
    invalid:
    - 296.257.262.296
    valid:
    - 36.191.150.65
  type: string
  validation:
    func_name: IsIPv4Address
- attribute: port_number
  optional: true
  subtype: port
  test_params:
    invalid:
    - 0
    - 65536
    valid:
    - 1
    - 53
    - 65535
  type: int
  validation:
    func_name: IsPortNumber
- attribute: test_score
  computed: true
  description: range
  optional: true
  subtype: range
  test_params:
    invalid:
    - 0
    - 101
    valid:
    - 1
    - 100
    - 50
  type: int
  validation:
    func_name: IntBetween
    params:
    - 1
    - 100
- attribute: string_in_some_names
  computed: true
  default: parth
  description: string in valid list
  optional: true
  subtype: string
  test_params:
    invalid:
    - j3d9d0yum6
    valid:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: true
    params:
    - parth
    - aarsh
    - arjun
    - alfatah
    - krunal
- attribute: valid_cidr
  computed: true
  description: cidr network
  optional: true
  subtype: string
  test_params:
    invalid:
    - -1
    - 33
    valid:
    - 0
    - 32
    - 16
  type: string
  validation:
    func_name: IsCIDRNetwork
    ignore_case: true
    params:
    - 0
    - 32
types:
  base64:
    invalid: a3+J1b%mFs//
    valid: YzUwaXE1ZXF3dQ==
  cidr:
    invalid: 262.292.259.272/19
    valid: 91.225.67.140/9
  ipv4:
    invalid: 296.257.262.296
    valid: 36.191.150.65
  ipv6:
    invalid: invalidIPv6
    valid: 1091:17a3:8f36:8a7d:c266:ffb2
  json:
    invalid: 'json({ name : val)'
    valid: 'json({ "attribute" : "value" })'
  mac:
    invalid: invalidMAC
    valid: f2:1f:5e:24:c4:16
  regex:
    invalid: '[0-9)++'
    valid: (?m)^[0-9]{2}$
  string:
    invalid: 12345
    valid: fueer86f3p
  time:
    invalid: '2022-06-15 17:41:01.375236'
    valid: '2022-06-15T12:11:01.375236+00:00'
  url-http:
    invalid: ht:/rp0g6xzwu9i8znb.com
    valid: http://kge853m9atuyfy9.com
  url-https:
    invalid: hts:/spbreezfrhckubr.com
    valid: https://etvjx4f52be5i16.com
  uuid:
    invalid: invalid323Uuid12
    valid: 38d27a2f-eca4-11ec-87c5-7c8ae1943087
