imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: movie
provider_name: Movies
schemas:
- attribute: title
  description: Title of the Movie
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - kg10fbwcz7
    - k1kz1au15a
    - 2ki0e88t4w
    - jd9nakr11f
    - bewjgqjo3q
    - kpofubatve
    - 3fo17tajnv
    - rsuk6jckg4
    - rzl0x2uf6r
    - o4qy52ueri
    - iydt4lult7
    - i8o95dz89b
    - m5efm3d33g
    - gqr7zlix8h
    - ea05g1oocv
    valid:
    - reb9mfgujf
    - rotf377xld
    - pigjrkl2i7
    - qhlphte62c
  type: string
- attribute: isbn
  description: ISBN of the Movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - 9d6is9p00i
    - dn8ybvbs0b
    - 5a83o5swuw
    - f2mwe83rw3
    - 0ytgykwnmh
    - aegb5ka3o4
    - mgjhlvqe2r
    - 9qh6k1zoss
    - 4uvy25sqrj
    - hqszr06926
    - q4p2r3ozcd
    - rvhsezo8im
    - yc008r2gxg
    - 758z3xzdc3
    - kwhu5f9z9b
    valid:
    - vu6t5rb3qx
    - 1n3yo1gvcr
    - 6sbganzn2p
    - wblhz74mcp
  type: string
- attribute: genre
  default: thriller
  description: Genre of the movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - u10gyzoswm
    multiple_valids:
    - thriller
    - action
    - horror
    - fiction
    - comedy
    valid:
    - thriller
    - action
    - horror
    - fiction
    - comedy
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: false
    params:
    - thriller
    - action
    - horror
    - fiction
    - comedy
- attribute: director
  description: Director of the Movie
  element:
    schema:
    - attribute: firstname
      description: Firstname of the Director
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - qdaiwihjj8
        - zcs4ccpv1c
        - q6vcj9xzkg
        - irddgz2emm
        - gbqthyjni6
        - dt7lz1w6wr
        - fvsylqhxgc
        - mqd4ni2f8b
        - 8wd0oo9ske
        - eai9aceltj
        - l6iufp0fg8
        - m1xlst9r6m
        - dnxwmzc1l3
        - avwjtdkl0l
        - cptpne6zgk
        valid:
        - y8fbb197bv
        - s5cawisxjs
        - e21is5fy10
        - 2tkj8myojf
      type: string
    - attribute: lastname
      description: Lastname of the Director
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - mlex79t71s
        - fi7geoq37m
        - 2qqy0e8wo0
        - 3wwgaz0pnh
        - syh8xmyje8
        - qh51boe7gk
        - 7lk5nqro44
        - dziei9tme3
        - 807yse8myd
        - 6fm5u3akp0
        - 1loclap0wh
        - d32s6a19ip
        - dinxpsuhg5
        - o9uumlhb2b
        - 7v23dgzv53
        valid:
        - 9cfkeac00o
        - sm9jlwkl0o
        - l0q337pqsq
        - i0aql3afvq
      type: string
    type: resource
  max_items: 1
  optional: true
  type: list
- attribute: rating
  element:
    schema:
    - attribute: rater
      description: Rater that provide rating
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - qu03wzno10
        - afxdgb0b34
        - 8dxy78k9wp
        - iua9krjv57
        - 9gyqp3lx58
        - jdh0qfd4yx
        - z37cp0jihw
        - ljplqz1s77
        - owqmlpqlvb
        - 9wmh36ucg6
        - zjibh46nw1
        - byhhe6vmx9
        - m4dzpv11tn
        - g2un4gqn1q
        - tp4t74yyu1
        valid:
        - j941xenc9g
        - 0clp8bilj4
        - k8nc5mdrm9
        - 0zjd4itmq2
      type: string
    - attribute: rating
      default: 1
      optional: true
      subtype: range
      test_params:
        invalid:
        - 0
        - 11
        multiple_valids:
        - 1
        - 10
        - 5.5
        - 6.3077942796079425
        - 3.8319217250341877
        - 7.284504431375421
        - 3.938417818790897
        - 4.803870162269427
        - 4.125968612341213
        - 5.012689864396442
        - 6.666219282869619
        - 9.076894442102645
        - 1.0244780871351846
        - 6.451452026875719
        - 2.2539842447992426
        valid:
        - 1
        - 10
        - 5.5
        - 5.327493256150269
      type: float
      validation:
        func_name: FloatBetween
        params:
        - 1
        - 10
    type: resource
  optional: true
  type: list
- attribute: casts
  element:
    schema:
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - og35f0mipd
    - vm5qe7ezh3
    - 0a107dr14y
    - lofl9pcn3p
    - x21nq0p2dg
    - m7wyp6z58z
    - 8n2xfwcrod
    - z39ir85570
    - j6r31a7svi
    - 2es32rzq3g
    - aptehn6o3k
    - kc6x7umvk7
    - ijjqk3dvbs
    - kppufs3o2j
    - rsu1fnbdh9
    valid:
    - ao08fjphu0
    - tj7oh8qu2p
    - fs2hzniqj6
    - ijcsi2kocb
  type: set
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - cmRuN3NlNjQxcg==
    - ZnJyZ3Q1c2xyOQ==
    - Zjh2cWYxOGUzbQ==
    - b3ZnMzBva3k2aA==
    - dXNpajA4M21oeg==
    - ejB5OXNienI2OQ==
    - aHhlZTRmYnB4cg==
    - cTNzZHUzYWV3OA==
    - MWQyaW54bGltcA==
    - ejk0eHdodXR1aA==
    - cmoycWpqNmhpdQ==
    - MmRwa2E3czRpOA==
    - enhxcmlseDJsMg==
    - c3hmdXQ2bnE5aQ==
    - ajk5cXYxb3NwMA==
    valid:
    - MTRzZmF5YnNhbw==
    - NXl2ODhvbnptbg==
    - YTkwN2JnNmFpdw==
    - dXR1Nzl5N3BqaQ==
  cidr:
    invalid:
    - 269.286.291.266/30
    multiple_valids:
    - 9.9.224.0/20
    - 9.9.128.0/20
    - 9.9.16.0/20
    - 9.9.192.0/20
    - 9.9.176.0/20
    - 9.9.32.0/20
    - 9.9.96.0/20
    - 9.9.64.0/20
    - 9.9.48.0/20
    - 9.9.0.0/20
    - 9.9.160.0/20
    - 9.9.240.0/20
    - 9.9.112.0/20
    - 9.9.144.0/20
    - 9.9.208.0/20
    valid:
    - 9.9.224.0/20
    - 9.9.128.0/20
    - 9.9.16.0/20
    - 9.9.192.0/20
  ipv4:
    invalid:
    - 295.280.274.278
    multiple_valids:
    - 9.9.118.201
    - 9.9.129.34
    - 9.9.56.78
    - 9.9.61.152
    - 9.9.179.121
    - 9.9.126.158
    - 9.9.68.164
    - 9.9.101.35
    - 9.9.229.143
    - 9.9.89.48
    - 9.9.148.213
    - 9.9.196.243
    - 9.9.118.162
    - 9.9.44.250
    - 9.9.189.222
    valid:
    - 9.9.118.201
    - 9.9.129.34
    - 9.9.56.78
    - 9.9.61.152
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f390
    - 2001:db8::34f4:0:0:f356
    - 2001:db8::34f4:0:0:f374
    - 2001:db8::34f4:0:0:f32d
    - 2001:db8::34f4:0:0:f35d
    - 2001:db8::34f4:0:0:f37c
    - 2001:db8::34f4:0:0:f347
    - 2001:db8::34f4:0:0:f3a9
    - 2001:db8::34f4:0:0:f34c
    - 2001:db8::34f4:0:0:f324
    - 2001:db8::34f4:0:0:f3da
    - 2001:db8::34f4:0:0:f39b
    - 2001:db8::34f4:0:0:f3e6
    - 2001:db8::34f4:0:0:f335
    - 2001:db8::34f4:0:0:f3f0
    valid:
    - 2001:db8::34f4:0:0:f390
    - 2001:db8::34f4:0:0:f356
    - 2001:db8::34f4:0:0:f374
    - 2001:db8::34f4:0:0:f32d
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 9c:c2:6f:ff:47:d4
    - 51:ee:50:fc:bd:38
    - 52:94:3b:9c:cc:12
    - 73:c9:59:ca:ad:7a
    - f3:4a:06:98:20:7c
    - c9:ba:f5:5b:aa:e0
    - 97:67:96:ab:0c:70
    - 4f:cf:72:76:b3:10
    - 01:39:d0:c2:fb:5c
    - 46:a5:cf:93:48:1d
    - 72:cd:ce:d9:41:5f
    - 8c:9e:d6:02:b8:da
    - 6a:84:4d:bb:9b:96
    - 95:09:1c:96:e0:e6
    - 95:98:85:48:38:8e
    valid:
    - dd:20:88:0d:5e:fa
    - 51:23:98:6a:ea:cc
    - 33:53:1b:2f:b0:0f
    - 44:be:80:49:0c:a3
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - q8xp0k85w0
    - d867zjpkxh
    - ci0qt4q05h
    - lekhy12ql7
    - kc5wif75t9
    - l4hb9t5e11
    - g6t74hij3u
    - 2q2gj65e86
    - 9zn3k5467u
    - dhde6z26u0
    - af8vbr0gwb
    - puqtjbcfzi
    - 0sntlglkd7
    - sfcp6cmrsx
    - 674o5dg0yl
    valid:
    - 0mk6ts0kz6
    - xlvn6qixk5
    - 0m10qe0p9z
    - ei939y9unf
  time:
    invalid:
    - '2022-07-11 10:47:50.928249'
    multiple_valids:
    - '2022-07-11T05:17:50.928249+00:00'
    - '2022-08-03T05:17:50.928249+00:00'
    - '2022-08-26T05:17:50.928249+00:00'
    - '2022-09-18T05:17:50.928249+00:00'
    - '2022-10-11T05:17:50.928249+00:00'
    - '2022-11-03T05:17:50.928249+00:00'
    - '2022-11-26T05:17:50.928249+00:00'
    - '2022-12-19T05:17:50.928249+00:00'
    - '2023-01-11T05:17:50.928249+00:00'
    - '2023-02-03T05:17:50.928249+00:00'
    - '2023-02-26T05:17:50.928249+00:00'
    - '2023-03-21T05:17:50.928249+00:00'
    - '2023-04-13T05:17:50.928249+00:00'
    - '2023-05-06T05:17:50.928249+00:00'
    - '2023-05-29T05:17:50.928249+00:00'
    valid:
    - '2022-07-11T05:17:50.928249+00:00'
    - '2022-08-03T05:17:50.928249+00:00'
    - '2022-08-26T05:17:50.928249+00:00'
    - '2022-09-18T05:17:50.928249+00:00'
  url-http:
    invalid:
    - ht:/2ewjhha7x1yf1i7.com
    multiple_valids:
    - http://s6j0awnpc26zln7.com
    - http://6tiem5n1r76yodo.com
    - http://jsezds06rc9ozrk.com
    - http://71nt5szynh0x27x.com
    - http://v4zj7uz0grwbn9f.com
    - http://300h1k06mou218u.com
    - http://y55796jwbw2a9tc.com
    - http://3d8vp40er7w0uel.com
    - http://f2zrjiwca6rh2j2.com
    - http://seythli52xxl87z.com
    - http://me3vf7cu1zo6llx.com
    - http://wqytsxhnyek12n0.com
    - http://jh3zv2qozsjjwcl.com
    - http://ktejppllfwfm3xb.com
    - http://7znf8sbmw7vnx47.com
    valid:
    - http://ney6ctm10kujmok.com
    - http://ws4kx6kzaz44xwc.com
    - http://0y57x0srhiupr1a.com
    - http://jjl5u2bb89livr4.com
  url-https:
    invalid:
    - hts:/vpjdkk1bco58xfq.com
    multiple_valids:
    - https://viabr9otrmc56n5.com
    - https://15ooriwz8lacnf1.com
    - https://t12aen0oiekiae1.com
    - https://dg6pvldu8ggjcqw.com
    - https://wjaszsnxp1ne2yu.com
    - https://wmeqlj43y11kcew.com
    - https://i3jedabemsplb1c.com
    - https://bavizx2ba0azyjv.com
    - https://mcggcyuwcgxkp4a.com
    - https://dt9kvrxwufko7x9.com
    - https://x0ei8h5wtih9bmw.com
    - https://3b1djma3jb6fmiy.com
    - https://ffsy876zn7z6ddk.com
    - https://szy4taykr0fvb7u.com
    - https://ivh5ko5ddhbq1dl.com
    valid:
    - https://qu0k3gm5vy3xjzc.com
    - https://tq4xty6knsf9ova.com
    - https://58b9wqybbv7i1mz.com
    - https://dpph1lv7muuwjxx.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - cf4e1ea6-00d8-11ed-9b3e-7c8ae1979a87
    - cf4e1ea7-00d8-11ed-9c84-7c8ae1979a87
    - cf4e1ea8-00d8-11ed-9c17-7c8ae1979a87
    - cf4e1ea9-00d8-11ed-8241-7c8ae1979a87
    - cf4e1eaa-00d8-11ed-90a3-7c8ae1979a87
    - cf4e1eab-00d8-11ed-9df2-7c8ae1979a87
    - cf4e1eac-00d8-11ed-bdf0-7c8ae1979a87
    - cf4e1ead-00d8-11ed-9185-7c8ae1979a87
    - cf4e1eae-00d8-11ed-a79c-7c8ae1979a87
    - cf4e1eaf-00d8-11ed-be60-7c8ae1979a87
    - cf4e1eb0-00d8-11ed-af8a-7c8ae1979a87
    - cf4e1eb1-00d8-11ed-bb57-7c8ae1979a87
    - cf4e1eb2-00d8-11ed-97ff-7c8ae1979a87
    - cf4e1eb3-00d8-11ed-9231-7c8ae1979a87
    - cf4e1eb4-00d8-11ed-ac5f-7c8ae1979a87
    valid:
    - cf4df6c0-00d8-11ed-a7d6-7c8ae1979a87
    - cf4e1ea3-00d8-11ed-b22c-7c8ae1979a87
    - cf4e1ea4-00d8-11ed-9d3f-7c8ae1979a87
    - cf4e1ea5-00d8-11ed-860d-7c8ae1979a87
