imports:
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema
- github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation
name: movie
provider_name: Movies
schemas:
- attribute: title
  description: Title of the Movie
  forcenew: true
  required: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - vriqwy63tr
    - 2wbyd53l2m
    - 0qafzrvcwu
    - iq5ryi7jx4
    - bp6zozq4f5
    - lyku3sqim7
    - o258l1nj0m
    - gxb3av4m2p
    - 208f3vbrob
    - nl5d4iw6ga
    - sso7mfgx2r
    - l7udbyrjnb
    - 348la6pic8
    - 1kyqe6a1x5
    - 7cis1d7ywc
    valid:
    - fgxpqzrfed
    - v004mg74n4
    - afecl88eca
    - 6g2mv0fqz8
  type: string
- attribute: isbn
  description: ISBN of the Movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - xpk4vhwf5r
    - 9l0q7b91dw
    - s8x2q50oit
    - 1qmo18o37l
    - m2gc5fk9t1
    - 22q74jqy3a
    - 4zvn5a0t2l
    - 7j7w4ezr4l
    - 9of5amrv2a
    - cfy3zjen74
    - a73q2yf8rs
    - px9ewygk60
    - s2m9prtr8c
    - ikjciim2pl
    - ey70vp3zgn
    valid:
    - 0txp0u7lvc
    - romj7abhkq
    - hhlo68c83j
    - b0hy5b5svb
  type: string
- attribute: genre
  default: thriller
  description: Genre of the movie
  optional: true
  subtype: string
  test_params:
    invalid:
    - 37xaa7khob
    multiple_valids:
    - thriller
    - action
    - horror
    - fiction
    - comedy
    valid:
    - thriller
    - action
    - horror
    - fiction
    - comedy
  type: string
  validation:
    func_name: StringInSlice
    ignore_case: false
    params:
    - thriller
    - action
    - horror
    - fiction
    - comedy
- attribute: director
  description: Director of the Movie
  element:
    schema:
    - attribute: firstname
      description: Firstname of the Director
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - mosknpuezg
        - 1au17yzeo5
        - wna9yiwv7m
        - du8hdjwi2h
        - 3gswxsyybx
        - k1eeqanb0x
        - pormxun4y4
        - hpgdtdx69d
        - ama87qj203
        - 7rdgqn76mo
        - cy3doe0v7z
        - kcixk9z5o9
        - 966r6oto5k
        - z2p9pj7o4t
        - 6t1dxrg1t5
        valid:
        - i9q9x0474n
        - q6bym76vrn
        - 3aykyi1f61
        - trhugpaxb1
      type: string
    - attribute: lastname
      description: Lastname of the Director
      optional: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - 16m3kzvwjg
        - 6lu1e2dllr
        - 2y46cqn5i4
        - 83dp9jnzgz
        - 6zdq9jxuho
        - mtw3o65ojc
        - ld7xgx1ofk
        - 4thclb02n0
        - pbzizzjcnv
        - dks277hddc
        - 1u0ums271d
        - 6uilv2fadj
        - 67ng6g2so8
        - kzq8c7q5l7
        - zqr790m5pr
        valid:
        - h2hk7slyam
        - 1vhc3jk7oq
        - 91s5gm47px
        - orpspigkso
      type: string
    type: resource
  max_items: 1
  optional: true
  type: list
- attribute: rating
  element:
    schema:
    - attribute: rater
      description: Rater that provide rating
      required: true
      subtype: string
      test_params:
        invalid:
        - 10
        - 12.43
        multiple_valids:
        - v9b385o6qr
        - wi1371lix8
        - rom4sfgixh
        - 111a47hwuo
        - 9f2rz7frbv
        - raf3gs4ufz
        - 1urvkwvd3e
        - shb1ue2adn
        - m4xhb0pkrd
        - 2ekirf76tf
        - agvsz31arj
        - 57epz0rn9a
        - lju27ruedu
        - z1owargelr
        - id77gncis8
        valid:
        - 91bs56qalz
        - objx6x9wfp
        - y6nx7ahor4
        - e9wvsixfxr
      type: string
    - attribute: rating
      default: 1
      optional: true
      subtype: range
      test_params:
        invalid:
        - 0
        - 11
        multiple_valids:
        - 1
        - 10
        - 5.5
        - 1.2027848540318726
        - 0.3050486120495358
        - 8.247855008448516
        - 2.4182360306341715
        - 0.18915413643883738
        - 4.388729606962679
        - 5.4314244970199885
        - 5.082857689879004
        - 2.5444105102010495
        - 0.4318683728142736
        - 1.051587031051524
        - 0.22144530099498627
        - 0.7505274142672675
        valid:
        - 1
        - 10
        - 5.5
        - 7.237213359750473
      type: float
      validation:
        func_name: FloatBetween
        params:
        - 1
        - 10
    type: resource
  optional: true
  type: list
- attribute: casts
  element:
    schema:
      type: string
    type: schema
  optional: true
  subtype: string
  test_params:
    invalid:
    - 10
    - 12.43
    multiple_valids:
    - fkvc673p91
    - e1s6xb7s9s
    - h03sb6yurk
    - v3s5vjbx3e
    - nedzpf0jhv
    - 9lvydulhpe
    - det9s0keke
    - hnk1gkvzzn
    - ylzgro5tqa
    - ulvmgb316f
    - d3smyamufk
    - ripfhcji8s
    - jhuaw8zyod
    - pwsh892i9u
    - cpvs6s2aqp
    valid:
    - 0dw5f5m5oe
    - g56zr2lauy
    - u8qlmvofgk
    - u184pvwef5
  type: set
types:
  base64:
    invalid:
    - a3+J1b%mFs//
    multiple_valids:
    - N3g0cWxmbHIyag==
    - Y295ZG9iZDY1dA==
    - MWJyOTlpazQyZA==
    - cDJoYnJqdDkyeg==
    - cmJiZG9oeW9ncA==
    - MXBwaDR1YXczOQ==
    - b3d5NWwwbDkwcA==
    - NG9jazZmb2Z6Yw==
    - dzJibnJpYjhiYw==
    - eGc5azN5anduMA==
    - ajVtOGx3Y285Yg==
    - eHFrd3JrNWp2ZA==
    - OWI3aW13ZWUwOQ==
    - ZGJ3OGZ3MnNtcw==
    - ajQ1YXd1MTNnNg==
    valid:
    - dHJ6MmZ0czVrdw==
    - NXgxaWt1bHdrZg==
    - aGpwajY0aXZoOQ==
    - dHNmcXR4end3cw==
  cidr:
    invalid:
    - 270.270.290.265/13
    multiple_valids:
    - 8.33.144.0/20
    - 8.33.224.0/20
    - 8.33.32.0/20
    - 8.33.80.0/20
    - 8.33.192.0/20
    - 8.33.16.0/20
    - 8.33.96.0/20
    - 8.33.112.0/20
    - 8.33.208.0/20
    - 8.33.176.0/20
    - 8.33.128.0/20
    - 8.33.48.0/20
    - 8.33.0.0/20
    - 8.33.160.0/20
    - 8.33.64.0/20
    valid:
    - 8.33.144.0/20
    - 8.33.224.0/20
    - 8.33.32.0/20
    - 8.33.80.0/20
  ipv4:
    invalid:
    - 277.259.291.274
    multiple_valids:
    - 8.33.154.35
    - 8.33.57.198
    - 8.33.246.187
    - 8.33.48.112
    - 8.33.237.135
    - 8.33.180.35
    - 8.33.158.30
    - 8.33.182.13
    - 8.33.2.159
    - 8.33.181.20
    - 8.33.224.57
    - 8.33.54.25
    - 8.33.20.183
    - 8.33.36.19
    - 8.33.61.179
    valid:
    - 8.33.154.35
    - 8.33.57.198
    - 8.33.246.187
    - 8.33.48.112
  ipv6:
    invalid:
    - invalidIPv6
    multiple_valids:
    - 2001:db8::34f4:0:0:f34c
    - 2001:db8::34f4:0:0:f393
    - 2001:db8::34f4:0:0:f337
    - 2001:db8::34f4:0:0:f363
    - 2001:db8::34f4:0:0:f387
    - 2001:db8::34f4:0:0:f39c
    - 2001:db8::34f4:0:0:f318
    - 2001:db8::34f4:0:0:f359
    - 2001:db8::34f4:0:0:f302
    - 2001:db8::34f4:0:0:f3e0
    - 2001:db8::34f4:0:0:f3d6
    - 2001:db8::34f4:0:0:f3ba
    - 2001:db8::34f4:0:0:f34b
    - 2001:db8::34f4:0:0:f3e5
    - 2001:db8::34f4:0:0:f333
    valid:
    - 2001:db8::34f4:0:0:f34c
    - 2001:db8::34f4:0:0:f393
    - 2001:db8::34f4:0:0:f337
    - 2001:db8::34f4:0:0:f363
  json:
    invalid:
    - 'json({ name : val)'
    multiple_valids:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
    - 'json({ "attribute" : "value4" })'
    - 'json({ "attribute" : "value5" })'
    - 'json({ "attribute" : "value6" })'
    - 'json({ "attribute" : "value7" })'
    - 'json({ "attribute" : "value8" })'
    - 'json({ "attribute" : "value9" })'
    - 'json({ "attribute" : "value10" })'
    - 'json({ "attribute" : "value11" })'
    - 'json({ "attribute" : "value12" })'
    - 'json({ "attribute" : "value13" })'
    - 'json({ "attribute" : "value14" })'
    valid:
    - 'json({ "attribute" : "value0" })'
    - 'json({ "attribute" : "value1" })'
    - 'json({ "attribute" : "value2" })'
    - 'json({ "attribute" : "value3" })'
  mac:
    invalid:
    - invalidMAC
    multiple_valids:
    - 3a:36:0c:77:bb:79
    - c7:19:8f:10:5a:39
    - d5:08:70:2e:34:1f
    - ef:37:96:df:ac:7f
    - ef:71:93:22:36:40
    - 16:e7:09:43:55:20
    - ed:e1:f4:42:97:e1
    - c7:85:40:b6:77:35
    - ca:4e:41:fe:17:2f
    - 66:44:b1:a1:82:50
    - 13:52:4e:49:4e:2a
    - 0f:e7:6c:74:14:8c
    - f5:58:ee:b8:ce:ab
    - ec:47:5d:b4:e5:d9
    - 1d:53:db:b2:00:55
    valid:
    - 7e:ba:bb:db:b0:d9
    - 8e:c1:53:18:71:1c
    - 8f:c8:98:7f:96:43
    - 0e:a0:03:d1:03:77
  regex:
    invalid:
    - '[0-9)++'
    multiple_valids:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
    valid:
    - (?m)^[0-9]{2}$
    - ^(\$)(\d)+
  string:
    invalid:
    - 12345
    multiple_valids:
    - v937770370
    - z1fnrqjz3n
    - 7cgasu7xix
    - z6bja75q0e
    - xruq28h4cc
    - 7z4s680t4u
    - 9oq3917f85
    - 9kmzowv3me
    - zcgd5h7x1c
    - bx5ny0m32a
    - en27rs0mu1
    - u7u5pbf2zy
    - s8ih2zbipb
    - vghekzsn8z
    - 9day0tyn7j
    valid:
    - nds6lqnkk6
    - 27tti85yin
    - u482xbyr83
    - zi8idjmyq2
  time:
    invalid:
    - '2022-07-01 18:30:28.424539'
    multiple_valids:
    - '2022-07-01T13:00:28.424539+00:00'
    - '2022-07-24T13:00:28.424539+00:00'
    - '2022-08-16T13:00:28.424539+00:00'
    - '2022-09-08T13:00:28.424539+00:00'
    - '2022-10-01T13:00:28.424539+00:00'
    - '2022-10-24T13:00:28.424539+00:00'
    - '2022-11-16T13:00:28.424539+00:00'
    - '2022-12-09T13:00:28.424539+00:00'
    - '2023-01-01T13:00:28.424539+00:00'
    - '2023-01-24T13:00:28.424539+00:00'
    - '2023-02-16T13:00:28.424539+00:00'
    - '2023-03-11T13:00:28.424539+00:00'
    - '2023-04-03T13:00:28.424539+00:00'
    - '2023-04-26T13:00:28.424539+00:00'
    - '2023-05-19T13:00:28.424539+00:00'
    valid:
    - '2022-07-01T13:00:28.424539+00:00'
    - '2022-07-24T13:00:28.424539+00:00'
    - '2022-08-16T13:00:28.424539+00:00'
    - '2022-09-08T13:00:28.424539+00:00'
  url-http:
    invalid:
    - ht:/enaeo1foj3to2ma.com
    multiple_valids:
    - http://eqdnm47ooj9vbjg.com
    - http://yxkbbfw1u2stb34.com
    - http://c3vetjusdma2lb6.com
    - http://3wh98chmxng897x.com
    - http://gro9usr1hc4gurt.com
    - http://w9fqwkcro6lhhgn.com
    - http://56vxcge921xsf7l.com
    - http://eyveyp8t26ov19c.com
    - http://tvwo8h11wt1fdpl.com
    - http://cgw2w9npbzvbm9e.com
    - http://m91t7q3jv99xc9w.com
    - http://m2u2bgbs1gikqep.com
    - http://avqoz8gwg31jx9y.com
    - http://9bkasabkgruertu.com
    - http://769cp3j7bmj19au.com
    valid:
    - http://o1p75ig0fes9dlt.com
    - http://rl18lzz9dlvla07.com
    - http://qxl6ad08kkikqfc.com
    - http://rqv6k2kj9sbd3pi.com
  url-https:
    invalid:
    - hts:/52by5n7x57wisbz.com
    multiple_valids:
    - https://9p86hbrcihysiyf.com
    - https://480v9g59cmihjz7.com
    - https://bhqx3duzfx9oys9.com
    - https://f3zo5df8lxcaua3.com
    - https://67gv66mjo77nk5g.com
    - https://9ra98yqqgig02rk.com
    - https://br2fcbucmhdk8m7.com
    - https://wkyb0bvhfpmg09i.com
    - https://lkfd5hhw0u37oqm.com
    - https://x1i9qd1smz5wuqw.com
    - https://axunc4whhmxtb0a.com
    - https://o3m4w9ktrt3wmnl.com
    - https://5g5tzxjkp52m7y7.com
    - https://jrnbuxqwafthqtm.com
    - https://q22h0fv8m7hbg7i.com
    valid:
    - https://s9i6zxo0l337mde.com
    - https://k3szo8r0xhlvbzb.com
    - https://a8ijrmnnxqsov1j.com
    - https://7i3owtrl509hcod.com
  uuid:
    invalid:
    - invalid323Uuid12
    multiple_valids:
    - c7ee459a-f93d-11ec-94d0-7c8ae1979a87
    - c7ee459b-f93d-11ec-9d80-7c8ae1979a87
    - c7ee459c-f93d-11ec-b502-7c8ae1979a87
    - c7ee459d-f93d-11ec-a986-7c8ae1979a87
    - c7ee459e-f93d-11ec-a498-7c8ae1979a87
    - c7ee459f-f93d-11ec-a00a-7c8ae1979a87
    - c7ee45a0-f93d-11ec-8779-7c8ae1979a87
    - c7ee45a1-f93d-11ec-a4cb-7c8ae1979a87
    - c7ee45a2-f93d-11ec-bef8-7c8ae1979a87
    - c7ee45a3-f93d-11ec-a279-7c8ae1979a87
    - c7ee45a4-f93d-11ec-94d4-7c8ae1979a87
    - c7ee45a5-f93d-11ec-82d1-7c8ae1979a87
    - c7ee45a6-f93d-11ec-b164-7c8ae1979a87
    - c7ee45a7-f93d-11ec-94a3-7c8ae1979a87
    - c7ee45a8-f93d-11ec-91fb-7c8ae1979a87
    valid:
    - c7ee4596-f93d-11ec-80fb-7c8ae1979a87
    - c7ee4597-f93d-11ec-9ad2-7c8ae1979a87
    - c7ee4598-f93d-11ec-aa89-7c8ae1979a87
    - c7ee4599-f93d-11ec-ac11-7c8ae1979a87
