# yaml-language-server: $schema=../../json_schema/resource_validate.json
name: Tenant
provider_name: "Aci"
imports:
  - "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
unique_attribute:
  - "name"
schemas:
- attribute: name
  type: string
  description: Name of Tenant
  forcenew: true
  required: true
- attribute: name_alias
  type: string
  description: annotation for Tenant
  optional: true
  computed: true
- attribute: description
  type: string
  description: description for Tenant
  optional: true
  computed: true
- attribute: annotation
  type: string
  description: Annotation for Tenant
  optional: true
  computed: true
  default: "orchestrator:terraform"