# yaml-language-server: $schema=../../json_schema/datasource_validate.json

provider_name: Aci
name: application_profile
imports:
  - "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
  - "github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

unique_attribute:
  - "name"
schemas:
- attribute: tenant_dn
  type: string
  description: Dn of Tenant
  forcenew: true
  required: true
  depends_on:
    resource_name: "tenant"
    attribute_name:
      - id
- attribute: name
  type: string
  computed: true
  description: Name of Application Profile
    
- attribute: name_alias
  type: string
  description: Name Alias for Application Profile
  computed: true
- attribute: description
  type: string
  description: description for Tenant
  computed: true
- attribute: annotation
  type: string
  description: Annotation for Tenant
  computed: true
  default: "orchestrator:terraform"
- attribute: prio
  type: string
  computed: true